vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>StewardshipDisbursementDonorGUID__c</fullName>
        <label>Stewardship Disbursement DonorGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StewardshipPaymentDonorGUID__c</fullName>
        <label>Stewardship Payment DonorGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Bill__c.object
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Bill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatementData__c</fullName>
        <label>Statement Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AuthSystemUserID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The ID string identifying this user in the authentication system (currently Auth0).</inlineHelpText>
        <label>Auth System User ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DriversLicenseOrStateID__c</fullName>
        <label>Drivers License or State ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimarySchoolEmail__c</fullName>
        <label>(DEPRECATE)School Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SSNTaxID__c</fullName>
        <inlineHelpText>Used by Credit Check process to verify identity.</inlineHelpText>
        <label>SSN / Tax ID</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ConsentIPAddress__c</fullName>
        <inlineHelpText>The IP Address from which the student consented to have their credit checked.</inlineHelpText>
        <label>Consent IP Address</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReasonText__c</fullName>
        <inlineHelpText>If Status is Denied, this indicates one or more reason categories for the denial (formatted so it can be included in email communications).</inlineHelpText>
        <label>Credit Check Denied Reason Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>JSONPayload__c</fullName>
        <inlineHelpText>The raw results of the credit check module in JSON format.</inlineHelpText>
        <label>JSON Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Notification__c.object
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Notifications Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/OutboundEmail__c.object
<CustomObject>
    <label>Outbound Email</label>
    <nameField>
        <displayFormat>Email-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Outbound Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BankAccountNumber__c</fullName>
        <label>Bank Account Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>BankName__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankRoutingNumber__c</fullName>
        <label>Bank Routing Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CreditCardNumber__c</fullName>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Optional description - helpful in case Customer has multiple accounts at one bank.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StewardshipDisbursementAccountGUID__c</fullName>
        <label>Stewardship Disbursement AccountGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StewardshipPaymentAccountGUID__c</fullName>
        <label>Stewardship Payment AccountGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StewardshipACHBatch__c.object
<CustomObject>
    <label>Stewardship ACH Batch</label>
    <nameField>
        <displayFormat>STACHBAT-{0000000000}</displayFormat>
        <label>Stewardshp ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StewardshipACHBatchDetail__c.object
<CustomObject>
    <label>Stewardship ACH Batch Detail</label>
    <nameField>
        <displayFormat>SACHBD-{000000000}</displayFormat>
        <label>Stewardship ACH Batch Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipName>Stewardship_ACH_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StewardshipACHBatch__c</fullName>
        <label>Stewardship ACH Batch</label>
        <referenceTo>StewardshipACHBatch__c</referenceTo>
        <relationshipLabel>Stewardship ACH Batch Details</relationshipLabel>
        <relationshipName>Stewardship_ACH_Batch_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BirthdateCertification__c</fullName>
        <inlineHelpText>(Certification) fields are only used for student initiated flow, and store temporary values entered by the School Admin during certification.</inlineHelpText>
        <label>Birthdate (Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdatePostCertification__c</fullName>
        <inlineHelpText>(Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Birthdate (Post-Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdatePreCertification__c</fullName>
        <inlineHelpText>(Pre-Certification) fields are only used for school initiated flow, and store temporary values entered by the School Admin during certification.</inlineHelpText>
        <label>Birthdate (Pre-Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdateStudent__c</fullName>
        <inlineHelpText>(Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Birthdate (Student)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CertificationComments__c</fullName>
        <inlineHelpText>Used by the Certification App. Displays comments added by School Admin during Certification.</inlineHelpText>
        <label>Certification Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReasonText__c</fullName>
        <inlineHelpText>From the Credit Check object. Formatted to be used in communications to student.</inlineHelpText>
        <label>Credit Check Denied Reason Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentEmail__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAudit__c.object
<CustomObject>
    <label>Student Program Audit</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Student Program Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>BirthdateCertification__c</fullName>
        <label>Birthdate (Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdatePostCertification__c</fullName>
        <label>Birthdate (Post-Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdatePreCertification__c</fullName>
        <label>Birthdate (Pre-Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdateStudent__c</fullName>
        <label>Birthdate (Student)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CertificationComments__c</fullName>
        <label>Certification Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReasonText__c</fullName>
        <label>Credit Check Denied Reason Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentEmail__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>StudentProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Audit</relationshipLabel>
        <relationshipName>Student_Program_History</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>NotificationEmail__c</fullName>
        <inlineHelpText>The address to send disbursement notification email.</inlineHelpText>
        <label>Notification Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/SandboxSetupMaskData.cls
public class SandboxSetupMaskData implements Database.Batchable<sObject>, Database.Stateful {
    
    public String query;
    public String sObj = 'Contact';
    public Integer contactCount = 0;

    public SandboxSetupMaskData() {
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        if(sObj == 'Contact'){
            query = 'SELECT id, FirstName, LastName, AuthSystemUserID__c, SSNTaxID__c, Birthdate, PrimarySchoolEmail__c, DriversLicenseOrStateID__c, Email, Phone, HomePhone, MobilePhone, OtherPhone,  MailingStreet, MailingCity, MailingState, MailingPostalCode, OtherStreet, OtherCity, OtherState, OtherPostalCode from Contact';

        } else if(sObj == 'StudentProgram__c'){
            query = 'SELECT id, Birthdate__c, BirthdateCertification__c, BirthdatePostCertification__c, BirthdatePreCertification__c, BirthdateStudent__c, StudentEmail__c, CertificationComments__c from StudentProgram__c';

        } else if(sObj == 'Case'){
            query = 'SELECT id from Case';

        } else if(sObj == 'StudentProgramAudit__c'){
            query = 'SELECT id from StudentProgramAudit__c';

        } else if(sObj == 'Task'){
            query = 'SELECT id from Task';

        } else if(sObj == 'CreditCheck__c'){
            query = 'SELECT id, ConsentIPAddress__c, JSONPayload__c, CreditCheckDeniedReasonText__c from CreditCheck__c';

        } else if(sObj == 'Notification__c'){
            query = 'SELECT id from Notification__c';

        } else if(sObj == 'Bill__c'){
            query = 'SELECT id, Name__c, StatementData__c, Email__c from Bill__c';

        } else if(sObj == 'Transaction__c'){
            query = 'SELECT id, NotificationEmail__c from Transaction__c';

        } else if(sObj == 'Attachment'){
            query = 'SELECT id from Attachment';

        } else if(sObj == 'StewardshipACHBatchDetail__c'){
            query = 'SELECT id from StewardshipACHBatchDetail__c';

        } else if(sObj == 'StewardshipACHBatch__c'){
            query = 'SELECT id from StewardshipACHBatch__c';

        } else if(sObj == 'OutboundEmail__c'){
            query = 'SELECT id from OutboundEmail__c';

        }  else if(sObj == 'Account'){
            query = 'SELECT id, StewardshipDisbursementDonorGUID__c, StewardshipPaymentDonorGUID__c from Account';

        }   else if(sObj == 'PaymentMethod__c'){
            query = 'SELECT id, BankRoutingNumber__c, BankAccountNumber__c, BankName__c, CreditCardNumber__c, Description__c, StewardshipDisbursementAccountGUID__c, StewardshipPaymentAccountGUID__c from PaymentMethod__c';

        } 
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        if(sObj == 'Contact'){
            contactCount++;
            for(Contact cont : (List<Contact>)(scope)){
                System.debug('cont:'+cont);
                cont.FirstName = 'Masked';
                cont.LastName = 'Contact'+contactCount;
                if(String.isNotEmpty(cont.SSNTaxID__c)) cont.SSNTaxID__c = '123-45-6789';
                if(String.isNotEmpty(cont.MailingStreet)) cont.MailingStreet = '123 Main Street';
                if(String.isNotEmpty(cont.MailingPostalCode)) cont.MailingPostalCode = '98765-4321';
                if(String.isNotEmpty(cont.OtherStreet)) cont.OtherStreet = '12345 Secondary Street';
                if(String.isNotEmpty(cont.OtherPostalCode)) cont.OtherPostalCode = '11223';
                if(String.isNotEmpty(cont.Phone)) cont.Phone = '(555) 123-4567';
                if(String.isNotEmpty(cont.MobilePhone)) cont.MobilePhone = '(555) 123-4567';
                if(String.isNotEmpty(cont.OtherPhone)) cont.OtherPhone = '(555) 123-4567';
                if(String.isNotEmpty(cont.HomePhone)) cont.HomePhone = '(555) 123-4567';            
                if(String.isNotEmpty(cont.Email)) cont.Email = 'masked.email@vemo.com';
                if(String.isNotEmpty(cont.AuthSystemUserID__c)) cont.AuthSystemUserID__c = 'auth|'+cont.id;
                if(cont.Birthdate != null) cont.Birthdate = Date.newInstance(2000, 1, 1);

            }               

            update scope;

        } else if(sObj == 'StudentProgram__c'){
            for(StudentProgram__c agreement : (List<StudentProgram__c>) (scope)){
                System.debug('agreement:'+agreement);
                if(String.isNotEmpty(agreement.StudentEmail__c)) agreement.StudentEmail__c = 'masked.email@vemo.com';
                if(agreement.Birthdate__c != null) agreement.Birthdate__c = Date.newInstance(2000, 1, 1);
                if(agreement.BirthdateCertification__c != null) agreement.BirthdateCertification__c = Date.newInstance(2000, 1, 1);
                if(agreement.BirthdatePostCertification__c != null) agreement.BirthdatePostCertification__c = Date.newInstance(2000, 1, 1);
                if(agreement.BirthdatePreCertification__c != null) agreement.BirthdatePreCertification__c = Date.newInstance(2000, 1, 1);
                if(agreement.BirthdateStudent__c != null) agreement.BirthdateStudent__c = Date.newInstance(2000, 1, 1);
                agreement.CertificationComments__c = '';
            }               
 
            update scope;
        } else if(sObj == 'Case'){
            delete scope;        
        } else if(sObj == 'StudentProgramAudit__c'){
            delete scope;        
        } else if(sObj == 'Task'){
            delete scope;        
        } else if(sObj == 'CreditCheck__c'){
            for(CreditCheck__c cc : (List<CreditCheck__c>) (scope)){
                cc.ConsentIPAddress__c = '';
                cc.JSONPayload__c = '';
                cc.CreditCheckDeniedReasonText__c = '';  
            }     
            update scope;
        } else if(sObj == 'Notification__c'){
            delete scope;        
        } else if(sObj == 'Bill__c'){
            for(Bill__c bill : (List<Bill__c>) (scope)){
                bill.Email__c = 'maked.email@vemo.com';
                bill.StatementData__c = '';
                bill.Name__c = 'maked name';
            }     
            update scope;
        } else if(sObj == 'Transaction__c'){
            for(Transaction__c tx : (List<Transaction__c>) (scope)){
                tx.NotificationEmail__c = 'maked.email@vemo.com';
            }     
            update scope;       
        } else if(sObj == 'Attachment'){  
            delete scope;       
        } else if(sObj == 'StewardshipACHBatchDetail__c'){  
            delete scope;       
        } else if(sObj == 'StewardshipACHBatch__c'){  
            delete scope;       
        } else if(sObj == 'Note'){  
            delete scope;       
        } else if(sObj == 'OutboundEmail__c'){  
            delete scope;       
        } else if(sObj == 'Account'){
            for(Account acct : (List<Account>) (scope)){
                acct.StewardshipDisbursementDonorGUID__c = '';
                acct.StewardshipPaymentDonorGUID__c = '';
            }     
            update scope;
        } else if(sObj == 'PaymentMethod__c'){
            for(PaymentMethod__c pay : (List<PaymentMethod__c>) (scope)){
                pay.BankAccountNumber__c = '123456789';
                pay.BankName__c = 'Bank Name';
                pay.BankRoutingNumber__c = '123456789';
                pay.CreditCardNumber__c = '';
                pay.Description__c = '';
                pay.StewardshipDisbursementAccountGUID__c = '';
                pay.StewardshipPaymentAccountGUID__c = '';
            }     
            update scope;
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        if(sObj == 'Contact'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'StudentProgram__c';
            //Database.executeBatch(job);
        } else if(sObj == 'StudentProgram__c'){
             SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Case';
            Database.executeBatch(job);
        } else if(sObj == 'Case'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'StudentProgramAudit__c';
            Database.executeBatch(job);
        } else if(sObj == 'StudentProgramAudit__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Task';
            Database.executeBatch(job);
        } else if(sObj == 'Task'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'CreditCheck__c';
            Database.executeBatch(job);
        } else if(sObj == 'CreditCheck__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Notification__c';
            Database.executeBatch(job);
        } else if(sObj == 'Notification__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Bill__c';
            Database.executeBatch(job);
        } else if(sObj == 'Bill__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Transaction__c';
            Database.executeBatch(job);
        } else if(sObj == 'Transaction__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Attachment';
            Database.executeBatch(job);
        } else if(sObj == 'Attachment'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'StewardshipACHBatchDetail__c';
            Database.executeBatch(job);
        } else if(sObj == 'StewardshipACHBatchDetail__c'){
             SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'StewardshipACHBatch__c';
            Database.executeBatch(job);
        } else if(sObj == 'StewardshipACHBatch__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'OutboundEmail__c';
            Database.executeBatch(job);
        } else if(sObj == 'OutboundEmail__c'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'Account';
            Database.executeBatch(job);
        } else if(sObj == 'Account'){
            SandboxSetupMaskData job = new SandboxSetupMaskData();
            job.sObj = 'PaymentMethod__c';
            Database.executeBatch(job);
        }  
        
    }
    
}