vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BeginDate__c</fullName>
        <inlineHelpText>The date this Income began.</inlineHelpText>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentAllocation__c.object
<CustomObject>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <inlineHelpText>The Payment Instruction related to this Payment Allocation.</inlineHelpText>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CertificationDate__c</fullName>
        <inlineHelpText>The date the Student Program was certified by a School Admin.</inlineHelpText>
        <label>Certification Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ClosedDate__c</fullName>
        <inlineHelpText>The Date when the Status of Agreement was set to Closed</inlineHelpText>
        <label>Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ClosedReason__c</fullName>
        <inlineHelpText>Specifies the closed reason, if the Status of Agreement is Closed</inlineHelpText>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementClosedReason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DaysDelinquent__c</fullName>
        <formula>if(NextPaymentDue__c &gt; 0,if(TODAY() - NextPaymentDueDate__c &gt;0,Today() - NextPaymentDueDate__c, 0),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Delinquent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpectedGraduationDate__c</fullName>
        <inlineHelpText>The date student is expected to graduate.</inlineHelpText>
        <label>Expected Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Servicing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag that indicates that an agreement is in servicing. This is set automatically when current date hits Servicing Start Date or can be set manually. Flag used for other jobs, reports, and the portal to determine if an agreement is in servicing status.</inlineHelpText>
        <label>Servicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAudit__c.object
<CustomObject>
    <label>Student Program Audit</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Student Program Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AuditDateTime__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Audit DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CertificationDate__c</fullName>
        <label>Certification Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DaysDelinquent__c</fullName>
        <label>Days Delinquent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpectedGraduationDate__c</fullName>
        <label>Expected Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MonthEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month End</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Servicing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Servicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StudentProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Audit</relationshipLabel>
        <relationshipName>Student_Program_History</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementClosedReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contract satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Write off</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Transferred servicer</fullName>
    </customValue>
    <masterLabel>Agreement Closed Reason</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/IncomeVerificationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/PaymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/ReportMnthlyInvstrPeriodicControllerTEST.cls
@isTest
public class ReportMnthlyInvstrPeriodicControllerTEST{
    @TestSetup static void setupData(){
        Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, StudentProgram__C> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);    
        Map<ID, PaymentMethod__c> paymentMethods = TestDataFactory.createAndInsertPaymentMethod(1, students);
        Map<ID, PaymentInstruction__c> PIs = TestDataFactory.createAndInsertPaymentInstruction(1, students, paymentMethods);
        Map<ID, PaymentAllocation__c> allocations = TestDataFactory.createAndInsertPaymentAllocation(3,PIs,agreements);
        Map<ID, StudentProgramMonthlyStatus__c> monthlyStatus = TestDataFactory.createAndInsertStudentProgramMonthlyStatus(3, agreements);
        Map<ID, EmploymentHistory__c> employmentHistory = TestDataFactory.createAndInsertEmploymentHistory(20,students);
        Map<ID, IncomeVerification__c> incomes = TestDataFactory.createAndInsertIncomeVerification(1, employmentHistory);
        
        Datetime dt = Datetime.now().addyears(-2);
        integer cnt=0;
        for(Id agreementID:agreements.keySet()){
            agreements.get(agreementID).certificationDate__c = dt.addMonths(cnt);
            if(cnt<4){
                agreements.get(agreementID).expectedGraduationDate__c = dt.addMonths(cnt+6).date();
                agreements.get(agreementID).status__c = 'Closed';
                agreements.get(agreementID).ClosedDate__c = Date.today();
                if(cnt<2) agreements.get(agreementID).ClosedReason__c = 'Default';
                else agreements.get(agreementID).ClosedReason__c = 'Contract Satisfied';  
                        
            }
            if(cnt>=4 && cnt <6){
                agreements.get(agreementID).status__c = 'Cancelled';
                
            }
            if(cnt>=6 && cnt <7){
                agreements.get(agreementID).status__c = 'Pending Reconciliation';
            }
            cnt++;
        }
        update agreements.values();
        
        for(IncomeVerification__c iv:incomes.values()){
            iv.BeginDate__c =Date.today().addDays(-120);
            iv.status__c = 'Verified'; 
        }
        update incomes.values();
        Integer currentMonth = Date.today().month();
        Integer currentYear = Date.today().year();
        
        List<StudentProgramAudit__c> spaList = new List<StudentProgramAudit__c>();
        for(StudentProgram__c sp:agreements.values()){
            Integer month = Date.today().addDays(-120).month();
            Integer year = Date.today().addDays(-120).year();
            Integer count = 1;
            while((month<=currentMonth && year == currentYear) || (year<currentYear)){
                if(count < 3){
                    spaList.add(new StudentProgramAudit__c(studentprogram__c = sp.id,
                                                           auditdatetime__c = Date.newInstance(year,month,28),
                                                           daysdelinquent__c = 0,
                                                           monthend__c = true));
                }
                else{
                    spaList.add(new StudentProgramAudit__c(studentprogram__c = sp.id,
                                                       auditdatetime__c = Date.newInstance(year,month,28),
                                                       daysdelinquent__c = 30,
                                                       servicing__c = true,
                                                       monthend__c = true));
                }
                count++;
                if(month == 12){
                    month = 1;
                    year++;
                }
                else month++;
            }
        }
        insert spaList;    
    }
    
    @isTest public static void validateGetProgram(){
        Test.StartTest(); 
        ReportMnthlyInvstrPeriodicController cntrl = new ReportMnthlyInvstrPeriodicController();
        List<SelectOption> programs = cntrl.getPrograms();
        System.assertEquals(1,programs.size(),'Should be 1');
        Test.StopTest(); 
    }
    
    @isTest public static void testmode1(){
        PageReference pageRef = Page.ReportMonthlyInvestorPeriodic;
        pageRef.getParameters().put('currentvfpage','ReportMonthlyInvestorPeriodic');
        Test.setCurrentPage(pageRef);
        Test.StartTest(); 
        ReportMnthlyInvstrPeriodicController cntrl = new ReportMnthlyInvstrPeriodicController();
        List<SelectOption> programs = cntrl.getPrograms();
        cntrl.selectedProgram = programs[0].getValue();
        cntrl.runReport();
        Test.StopTest(); 
    }
    
    @isTest public static void testExportmode1(){
        PageReference pageRef = Page.ReportMonthlyInvestorPeriodic;
        pageRef.getParameters().put('currentvfpage','ReportMonthlyInvestorPeriodic');
        Test.setCurrentPage(pageRef);
        Test.StartTest(); 
        ReportMnthlyInvstrPeriodicController cntrl = new ReportMnthlyInvstrPeriodicController();
        List<SelectOption> programs = cntrl.getPrograms();
        cntrl.selectedProgram = programs[0].getValue();
        cntrl.exportToCSV();
        cntrl.buildCsvString(); 
        Test.StopTest();   
    }  
    
    @isTest public static void testmode2(){
        PageReference pageRef = Page.ReportSalesForecast;
        pageRef.getParameters().put('currentvfpage','ReportSalesForecast');
        Test.setCurrentPage(pageRef);
        Test.StartTest(); 
        ReportMnthlyInvstrPeriodicController cntrl = new ReportMnthlyInvstrPeriodicController();
        List<SelectOption> programs = cntrl.getPrograms();
        cntrl.selectedProgram = programs[0].getValue();
        cntrl.runReport();
        Test.StopTest(); 
    }
    
    @isTest public static void testExportmode2(){
        PageReference pageRef = Page.ReportSalesForecast;
        pageRef.getParameters().put('currentvfpage','ReportSalesForecast');
        Test.setCurrentPage(pageRef);
        Test.StartTest(); 
        ReportMnthlyInvstrPeriodicController cntrl = new ReportMnthlyInvstrPeriodicController();
        List<SelectOption> programs = cntrl.getPrograms();
        cntrl.selectedProgram = programs[0].getValue();
        cntrl.exportToCSV();
        cntrl.buildCsvString(); 
        Test.StopTest();   
    }  
        
                    
}