vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>FundingAmountPostCertification__c</fullName>
        <inlineHelpText>(Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Funding Amount (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/CumulativeProgramFundingBatch.cls
public class CumulativeProgramFundingBatch implements Database.Batchable<sObject> {
	
	public String query {get;set;}
	public Boolean debugScope {get;set;}
	
	public CumulativeProgramFundingBatch() {
		query = 'SELECT id from Account where RecordTypeID = \''+String.valueOf(GlobalUtil.getRecordTypeIdByLabelName('Account', 'Student')+'\'');
		debugScope = true;
		System.debug(this);
	}
	public CumulativeProgramFundingBatch(String query, Boolean debugScope){
		this.query = query;
		this.debugScope = debugScope;
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug(query);
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
   		Map<ID, sObject> scopeMap = new Map<ID, sObject>(scope);
   		List<Account> acctsToUpdate = new List<Account>();
		//Get All Students as the main loop
		Boolean debug = debugScope;
		//Boolean debug = true;
		//Boolean debug = false;
		for(List<Account> students : [SELECT id,
											 SchoolProgramOfStudy__pc,
											 PrimarySchoolGradeLevel__pc
									  FROM Account
									  where ID = :scopeMap.keySet()
									  and RecordTypeID = :GlobalUtil.getRecordTypeIdByLabelName('Account', 'Student')]){
			Map<ID, Account> studentMap = new Map<ID, Account>(students);
			if(debug) System.debug(studentMap);
			//Get All Student Programs and Sort them By Programs
			Map<ID, StudentProgram__c> agreementMap = new Map<ID, StudentProgram__c>([SELECT id,
																							 Student__c,
																							 Program__c,
																							 Status__c,
																							 FundingAmountPostCertification__c
																					  FROM StudentProgram__c
																					  Where Student__c in : studentMap.keySet()]);
			if(debug) System.debug(agreementMap);

			Map<ID, Map<ID, List<StudentProgram__c>>> studentProgramsByProgramByStudent = new Map<ID, Map<ID,List<StudentProgram__c>>>();

			for(StudentProgram__c agreement : agreementMap.values()){
				if(!StudentProgramTriggerHandler.cumulativeIncomeStatusExclusions.contains(agreement.Status__c)){


					if(!studentProgramsByProgramByStudent.containsKey(agreement.Student__c)){
						studentProgramsByProgramByStudent.put(agreement.Student__c, new Map<ID, List<StudentProgram__c>>());
					}
					if(!studentProgramsByProgramByStudent.get(agreement.Student__c).containsKey(agreement.Program__c)){
						studentProgramsByProgramByStudent.get(agreement.Student__c).put(agreement.Program__c, new List<StudentProgram__c>());
					}
					studentProgramsByProgramByStudent.get(agreement.Student__c).get(agreement.Program__c).add(agreement);
				}
			}
			if(debug) System.debug(studentProgramsByProgramByStudent);


			for(Account student : students){
				if(debug) System.debug(student);
				if(studentProgramsByProgramByStudent.containsKey(student.id)){
					for(ID programID : studentProgramsByProgramByStudent.get(student.id).keySet()){
						//Get the program terms for this student and this program
						if(debug) System.debug(programID);
						if(debug) System.debug(student.SchoolProgramOfStudy__pc);
						if(debug) System.debug(student.PrimarySchoolGradeLevel__pc);
						if(student.SchoolProgramOfStudy__pc != null && student.PrimarySchoolGradeLevel__pc != null){
							ContractTermsService.ContractTerm ct = ContractTermsService.getContractTermsWithCriteria(programId, student.SchoolProgramOfStudy__pc, student.PrimarySchoolGradeLevel__pc);
							if(debug) System.debug(ct);
							if(debug) System.debug('Maximum Funding Amount:'+ct.maximumFundingAmount);

							Decimal cumulativeFunding = 0;
							for(StudentProgram__c agreement : studentProgramsByProgramByStudent.get(student.id).get(programID)){
								if(debug) System.debug(agreement);
								cumulativeFunding += (agreement.FundingAmountPostCertification__c == null ? 0 : agreement.FundingAmountPostCertification__c);

							}
							if(debug) System.debug('Cumulative Funding:'+cumulativeFunding);
							if(cumulativeFunding > ct.maximumFundingAmount){
								String error = '***Overfunded Account:'+student.id+ ' with Program:'+programID+' (maximumFundingAmount='+ct.maximumFundingAmount+') and Cumulative Funding of '+cumulativeFunding;
								System.debug(error);
								acctsToUpdate.add(new Account(id = student.id,
															  Error__c = error));

							}
						}
					}
				}
			}
		}
		if (acctsToUpdate.size()>0) {
			if(debug) System.debug('acctsToUpdate:'+acctsToUpdate);
			update acctsToUpdate;			
		}


	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
	
}