vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CampusServiceAvailability__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Availability</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampusServiceEmail__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CampusServiceMobile__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampusServiceName__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AgeOfMajorityCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age of Majority Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AgeOfMajorityRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age of Majority Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AgreementTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement Template</label>
        <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
        <relationshipLabel>Programs (Agreement Template)</relationshipLabel>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AllowedSpecialDisbursementTypes__c</fullName>
        <label>Allowed Special Disbursement Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASDAttachmentCleanURL__c</fullName>
        <formula>IF(!ISBLANK( ASDAttachmentID__c  ), $Setup.GlobalSettings__c.AttachmentDownloadPrefix__c &amp;  ASDAttachmentID__c  , &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASD Attachment Clean URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASDAttachmentID__c</fullName>
        <label>ASD Attachment ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttendanceDateRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, Attendance Dates will be available during the origination process</description>
        <inlineHelpText>If checked, Attendance Dates will be available during the origination process</inlineHelpText>
        <label>Attendance Date Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AutomaticallyConfirmTransactions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatically Confirm Transactions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreditApprovalScore__c</fullName>
        <label>Credit Approval Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreditCheckRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this box is checked, a credit check is required during the registration for this program</description>
        <inlineHelpText>If this box is checked, a credit check is required during the registration for this program</inlineHelpText>
        <label>Credit Check Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreditModel__c</fullName>
        <label>Credit Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Configured in Program</fullName>
                </value>
                <value>
                    <fullName>Detailed Evaluation</fullName>
                    <isActive>false</isActive>
                    <label>Detailed Evaluation</label>
                </value>
                <value>
                    <fullName>Score Based</fullName>
                    <isActive>false</isActive>
                    <label>Score Based</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CumulativeIncomeShareCap__c</fullName>
        <label>Cumulative Income Share Cap</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DefaultRules__c</fullName>
        <description>How many months of what kind of (in)activity are required to define an account as being in default?</description>
        <inlineHelpText>How many months of what kind of (in)activity are required to define an account as being in default?</inlineHelpText>
        <label>Default Rules</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DefermentTypeRules__c</fullName>
        <description>For each deferment type: is payment term extended? is there a duration limit?</description>
        <inlineHelpText>For each deferment type: is payment term extended? is there a duration limit?</inlineHelpText>
        <label>Deferment Type Rules</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisbursementConfRequiredNotification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is checked, the SchoolEmailNotification2__c will be sent a notification email when there is one or more disbursement confirmations awaiting the program.</description>
        <inlineHelpText>If this field is checked, the SchoolEmailNotification2__c will be sent a notification email when there is one or more disbursement confirmations awaiting the program.</inlineHelpText>
        <label>Disbursement Conf Required Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DisclosureTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Disclosure Template</label>
        <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
        <relationshipLabel>Programs (Disclosure Template)</relationshipLabel>
        <relationshipName>Programs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentBeginDate__c</fullName>
        <label>Enrollment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentEndDate__c</fullName>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentType__c</fullName>
        <description>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</description>
        <inlineHelpText>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</inlineHelpText>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Invite Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FeeRules__c</fullName>
        <description>list of fee types and amounts that agreement is subject to</description>
        <inlineHelpText>list of fee types and amounts that agreement is subject to</inlineHelpText>
        <label>Fee Rules</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GracePeriodMonths__c</fullName>
        <label>Grace Period (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GradeLevelCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GradeLevelDescription__c</fullName>
        <label>Grade Level Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GradeLevelRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImmediatePayment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, Income and Payment Information is mandatory as part of origination process</description>
        <inlineHelpText>If checked, Income and Payment Information is mandatory as part of origination process</inlineHelpText>
        <label>Immediate Payment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncomeThreshold__c</fullName>
        <description>minimum income required to make payment</description>
        <inlineHelpText>minimum income required to make payment</inlineHelpText>
        <label>Income Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InstructionText__c</fullName>
        <label>Instruction Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/DisbursementSpecialTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/ProgramStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/ProgramQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: ProgramQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION----------------------------- 
// 2016-12-23   Greg Cook       Changed all functions to return maps
/////////////////////////////////////////////////////////////////////////
public class ProgramQueries {
    public static Map<ID, Program__c> getProgramMapWithProgramID(Set<ID> programIds){
        Map<ID, Program__c> prgMap = new Map<ID, Program__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(programIds);
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        prgMap = new Map<ID, Program__c>((List<Program__c>)db.query(query));
        return prgMap;  
    }   

    public static Map<ID, Program__c> getProgramMapWithSchoolID(Set<ID> schoolIDs){
        Map<ID, Program__c> prgMap = new Map<ID, Program__c>();
        String query = generateSOQLSelect();
        query += ' WHERE School__c IN ' + DatabaseUtil.inSetStringBuilder(schoolIDs);
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        prgMap = new Map<ID, Program__c>((List<Program__c>)db.query(query));
        return prgMap;  
    }
    public static Map<ID, Program__c> getOpenProgramMapWithSchoolID(Set<ID> schoolIDs){
        Map<ID, Program__c> prgMap = new Map<ID, Program__c>();
        String query = generateSOQLSelect();
        query += ' WHERE School__c IN ' + DatabaseUtil.inSetStringBuilder(schoolIDs);
        query += ' and EnrollmentType__c = \'Open\' ';
        query += ' and ProgramStatus__c = \'Open\' ';
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        prgMap = new Map<ID, Program__c>((List<Program__c>)db.query(query));
        return prgMap;  
    }
    public static Map<ID, Program__c> getInviteOnlyProgramMapWithSchoolID(Set<ID> schoolIDs){
        Map<ID, Program__c> prgMap = new Map<ID, Program__c>();
        String query = generateSOQLSelect();
        query += ' WHERE School__c IN ' + DatabaseUtil.inSetStringBuilder(schoolIDs);
        query += ' and EnrollmentType__c = \'Invite Only\' ';
        query += ' and ProgramStatus__c = \'Open\' ';
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        prgMap = new Map<ID, Program__c>((List<Program__c>)db.query(query));
        return prgMap;  
    }

    public static Map<ID, Program__c> getProgramMap(){
        Map<ID, Program__c> prgMap = new Map<ID, Program__c>();
        String query = generateSOQLSelect();
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' WHERE School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        prgMap = new Map<ID, Program__c>((List<Program__c>)db.query(query));
        return prgMap;  
    }

    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getFieldNames() + ' FROM Program__c';
        return soql;
    }

    private static String getFieldNames(){
        String fieldNames;
        fieldNames = 'Id, ';
        fieldNames += 'Name, ';

        fieldNames += 'School__r.CampusServiceName__c, ';
        fieldNames += 'School__r.CampusServiceEmail__c, ';
        fieldNames += 'School__r.CampusServiceMobile__c, ';
        fieldNames += 'School__r.CampusServiceAvailability__c, ';

//      fieldNames += 'GUID__c, ';
        fieldNames += 'AgeOfMajorityCollected__c, ';
        fieldNames += 'AgeOfMajorityRequired__c, ';
        fieldNames += 'AgreementTemplate__c, ';
        fieldNames += 'AllowedSpecialDisbursementTypes__c, ';
        fieldNames += 'ASDAttachmentCleanURL__c, ';
        fieldNames += 'ASDAttachmentID__c, ';
        fieldNames += 'AttendanceDateRequired__c, ';
        fieldNames += 'AutomaticallyConfirmTransactions__c, ';
        fieldNames += 'CreditCheckRequired__c, ';
        fieldNames += 'CreditModel__c, ';
        fieldNames += 'CreditApprovalScore__c, ';
        fieldNames += 'CumulativeIncomeShareCap__c, ';
        fieldNames += 'DefaultRules__c, ';
        fieldNames += 'DefermentTypeRules__c, ';
        fieldNames += 'DisbursementConfRequiredNotification__c, ';
        fieldNames += 'DisclosureTemplate__c, ';
        fieldNames += 'EnrollmentBeginDate__c, ';
        fieldNames += 'EnrollmentEndDate__c, ';
        fieldNames += 'EnrollmentStatusCollected__c, ';
        fieldNames += 'EnrollmentStatusRequired__c, ';
        fieldNames += 'EnrollmentType__c, ';
        fieldNames += 'FeeRules__c, ';
        fieldNames += 'GracePeriodMonths__c, ';
        fieldNames += 'GradeLevelCollected__c, ';
        fieldNames += 'GradeLevelDescription__c, ';
        fieldNames += 'GradeLevelRequired__c, ';
        fieldNames += 'ImmediatePayment__c, ';
        fieldNames += 'IncomeThreshold__c, ';
        fieldNames += 'InstructionText__c, ';
        fieldNames += 'MinimumIncomePerYear__c, ';
        fieldNames += 'MinimumIncomePerMonth__c, ';
//      fieldNames += 'PostAgreementFlow__c, ';
        fieldNames += 'ProgramName__c, ';
        fieldNames += 'ProgramNotes__c, ';
        fieldNames += 'ProgramStatus__c, ';
        fieldNames += 'QuizLinkURL__c, ';
        fieldNames += 'QuizLinkID__c, ';
        fieldNames += 'QuizAttemptsBeforeLock__c,';
        fieldNames += 'QuizPostID__c, ';
        fieldNames += 'QuizResultID__c, ';
        fieldNames += 'RecordLabel__c, ';
        fieldNames += 'RecordLink__c, ';
        fieldNames += 'RegistrationBeginDate__c, ';
        fieldNames += 'RegistrationEndDate__c, ';
        fieldNames += 'ResidencyCollected__c, ';
        fieldNames += 'ResidencyRequired__c, ';
        fieldNames += 'RightToCancelDays__c, ';
        fieldNames += 'School__c, ';
        fieldNames += 'SchoolEmailNotification1__c, ';
        fieldNames += 'SchoolEmailNotification2__c, ';
        fieldNames += 'SchoolProgramOfStudyCollected__c, ';
        fieldNames += 'SchoolProgramOfStudyRequired__c, ';
//      fieldNames += 'StepText__c, ';
        fieldNames += 'StudentSignedISANotification__c, ';

        fieldNames += 'TotalDefermentMonths__c, ';

        fieldNames += 'CreatedDate, ';
        fieldNames += 'CreatedByID, ';
//      fieldNames += 'OwnerID, ';
        fieldNames += 'LastModifiedById, ';
        fieldNames += 'LastModifiedDate, ';
        fieldNames += 'LastReferencedDate, ';
        fieldNames += 'LastViewedDate, ';
        fieldNames += 'SystemModstamp ';

        return fieldNames;
    }

    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }
}