vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>VemoAccountNumber__c</fullName>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Automatially generated number identifying the Student/Account. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>SchoolCustomer</fullName>
        <active>true</active>
        <label>School - Customer</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/objects/ClrHouseStudentEnrollment__c.object
<CustomObject>
    <label>ClearingHouse Enrollment</label>
    <nameField>
        <displayFormat>CHS-{00000000}</displayFormat>
        <label>ClrHouseStudentEnrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClearingHouse Enrollment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ClrHouseStudentEnrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>College_Name__c</fullName>
        <label>College Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_begin__c</fullName>
        <label>Enrollment begin</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_end__c</fullName>
        <label>Enrollment end</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_status__c</fullName>
        <label>Enrollment status</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduated__c</fullName>
        <label>Graduated?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduation_date__c</fullName>
        <label>Graduation date</label>
        <length>8</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CertificationDate__c</fullName>
        <inlineHelpText>The date the Student Program was certified by a School Admin.</inlineHelpText>
        <label>Certification Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExpectedGraduationDate__c</fullName>
        <inlineHelpText>The date student is expected to graduate.</inlineHelpText>
        <label>Expected Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastDateOfAttendance__c</fullName>
        <label>Last Date of Attendance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ServicingStartDate__c</fullName>
        <inlineHelpText>Date that agreement starts servicing. Set by servicing team. Automated jobs look at this date to automatically check the servicing checkbox.</inlineHelpText>
        <label>Servicing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Servicing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag that indicates that an agreement is in servicing. This is set automatically when current date hits Servicing Start Date or can be set manually. Flag used for other jobs, reports, and the portal to determine if an agreement is in servicing status.</inlineHelpText>
        <label>Servicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/ReportClearinghouseController.cls
public with sharing class ReportClearinghouseController{
    public String selectedSchool {get;set;}
    transient public List<reportDataWrapper> reportData {get;set;}   
    transient public String csv {get;set;}
    
    private static Set<String> exclusionStatus = new Set<String>{'Draft','Invited','Application Incomplete','Application Complete','Application Under Review','Cancelled','Closed'};  
     
    public ReportClearinghouseController(){
        selectedSchool = '';
        reportData = new List<reportDataWrapper>();    
        
    }
    
    public List<SelectOption> getSchools(){
        List<Account> schools = [Select id,name From Account Where RecordType.developerName = 'SchoolCustomer' Order By name ASC];
        List<SelectOption> options = new List<SelectOption>();
        for(Account sch:schools){
            options.add(new SelectOption(sch.id,sch.name));    
        }
        return options;
    }
    
    public void runReport(){
        ///////////////////////////////////////////////////////////////////////////////////
        Map<ID,List<StudentProgram__c>> agreementsByStudent = new Map<ID,List<StudentProgram__c>>();
        
        Map<ID,List<ClrHouseStudentEnrollment__c>> clrHouseEnrollmentsByStudent = new Map<ID,List<ClrHouseStudentEnrollment__c>>(); 
        ///////////////////////////////////////////////////////////////////////////////////    
        getAgreements(agreementsByStudent);
        getClrHouseEnrollments(clrHouseEnrollmentsByStudent,agreementsByStudent.keySet());
        
        reportData = buildReportData(agreementsByStudent,clrHouseEnrollmentsByStudent);
    }
    
    ///////////////////////////////////////////////
    ///Get Student Programs for the selected School
    ///////////////////////////////////////////////
    public void getAgreements(Map<ID,List<StudentProgram__c>> agreementsByStudent){
        List<StudentProgram__c> agreementList = [SELECT id,name,student__c,student__r.name,student__r.vemoAccountNumber__c,certificationDate__c,
                                                  expectedGraduationDate__c,lastDateOfAttendance__c,Servicing__c,ServicingStartDate__c,status__c 
                                                  FROM StudentProgram__c
                                                  WHERE Status__c NOT IN :exclusionStatus AND Program__r.school__c =: selectedSchool
                                                  ORDER BY CertificationDate__c DESC];            
        
        for(StudentProgram__c agreement:agreementList){
            if(!agreementsByStudent.containsKey(agreement.student__c)){
                agreementsByStudent.put(agreement.student__c,new List<StudentProgram__c>());
            }
            agreementsByStudent.get(agreement.student__c).add(agreement);
        }
    }
    
    ////////////////////////////////////////////////////
    ///Get Clearinghouse Data for the given students school
    ////////////////////////////////////////////////////
    public void getClrHouseEnrollments(Map<ID,List<ClrHouseStudentEnrollment__c>> clrHouseEnrollmentsByStudent,Set<ID> studentIDs){
        List<ClrHouseStudentEnrollment__c> clrHouseEnrollmentList = [SELECT id,name,Enrollment_status__c,Graduated__c,Graduation_date__c,
                                                                     Enrollment_begin__c,Enrollment_end__c,College_Name__c,account__c
                                                                     FROM ClrHouseStudentEnrollment__c
                                                                     WHERE Account__c IN :studentIDs
                                                                     ORDER BY Enrollment_begin__c DESC];
        for(ClrHouseStudentEnrollment__c clrHouseEnrollment:clrHouseEnrollmentList){
            if(!clrHouseEnrollmentsByStudent.containsKey(clrHouseEnrollment.account__c)){
                clrHouseEnrollmentsByStudent.put(clrHouseEnrollment.account__c,new List<ClrHouseStudentEnrollment__c>());    
            }
            clrHouseEnrollmentsByStudent.get(clrHouseEnrollment.account__c).add(clrHouseEnrollment);
        }
    }
    
    ////////////////////////////////////////////////////////
    ///Build final report data
    ////////////////////////////////////////////////////////
    public List<ReportDataWrapper> buildReportData(Map<ID,List<StudentProgram__c>> agreementsByStudent,Map<ID,List<ClrHouseStudentEnrollment__c>> clrHouseEnrollmentsByStudent){
        List<ReportDataWrapper> output = new List<ReportDataWrapper>();
        
        for(ID studentID:clrHouseEnrollmentsByStudent.keySet()){
            Date earliestCertDate = null;
            //get the earliest cert date across all agreements
            for(StudentProgram__c agreement:agreementsByStudent.get(studentID)){
                if(agreement.certificationDate__c <> null){
                    if(earliestCertDate == null || earliestCertDate > agreement.certificationDate__c.date()) earliestCertDate = agreement.certificationDate__c.date();            
                }
            }
            
            if(earliestCertDate == null) continue;
            
            //iterate on ClrHouse enrollement records to check if the student needs to appear on the report OR not
            Boolean showOnReport = false;
            for(ClrHouseStudentEnrollment__c clrHouse:clrHouseEnrollmentsByStudent.get(studentID)){
                Date enrollmentEndDate;
                if(clrHouse.Graduated__c == 'N') enrollmentEndDate = convertTextToDate(clrHouse.Enrollment_end__c);
                if(clrHouse.Graduated__c == 'Y') enrollmentEndDate = convertTextToDate(clrHouse.Graduation_date__c);
                
                if(enrollmentEndDate == null) continue; 
                if(enrollmentEndDate < earliestCertDate) continue;
                if(clrHouse.Graduated__c == 'Y'){
                     showOnReport = true;
                     break;   
                }
                if(clrHouse.Enrollment_status__c == 'L' || clrHouse.Enrollment_status__c == 'W' ){
                     showOnReport = true;
                     break;
                }
            }
            
            //if showOnReport is true format the output 
            if(showOnReport){
                ReportDataWrapper wrapper = new ReportDataWrapper();        
                Integer sizeOfAgreements = agreementsByStudent.get(studentID).size();
                Integer sizeOfClrHouseEnrollments = clrHouseEnrollmentsByStudent.get(studentID).size();
                Integer interationCount = (sizeOfAgreements > sizeOfClrHouseEnrollments)? sizeOfAgreements:sizeOfClrHouseEnrollments; 
                List<StudentProgram__c> agreementList = agreementsByStudent.get(studentID);
                List<ClrHouseStudentEnrollment__c> clrHouseList = clrHouseEnrollmentsByStudent.get(studentID);
                
                for(integer index=0;index<interationCount;index++){
                    if(index == 0){
                        wrapper.vemoAccountNumber = agreementList[index].student__r.vemoAccountNumber__c;
                        wrapper.studentName = agreementList[index].student__r.name;
                        wrapper.studentId = agreementList[index].student__c;
                    }
                    
                    ReportRowWrapper row = new ReportRowWrapper();
                    if(index < sizeOfClrHouseEnrollments){
                        row.CHId = clrHouseList[index].id;
                        row.CHRecNumber = clrHouseList[index].name; 
                        row.collegeName = clrHouseList[index].college_Name__c;
                        row.enrollmentStatus = clrHouseList[index].enrollment_status__c;
                        row.enrollmentBegin = convertTextToDate(clrHouseList[index].Enrollment_begin__c);
                        row.enrollmentEnd = convertTextToDate(clrHouseList[index].Enrollment_end__c);
                        row.graduated = clrHouseList[index].Graduated__c;
                        row.graduationDate = convertTextToDate(clrHouseList[index].Graduation_date__c);              
                    }
                    if(index<sizeOfAgreements){
                        row.SPId = agreementList[index].id;
                        row.SPNumber = agreementList[index].name; 
                        row.status = agreementList[index].status__c;
                        row.expectedGradDate = agreementList[index].expectedGraduationDate__c;
                        row.lastDateOfAttendance = agreementList[index].lastDateOfAttendance__c;
                        row.servicing = agreementList[index].servicing__c;
                        row.servicingStartDate = agreementList[index].servicingStartDate__c;
                    }
                    wrapper.rowData.add(row);                
                }
                
                output.add(wrapper);
            }        
        } 
        return output;       
    } 
    
    ////////////////////////////////////////////////////////
    ///Convert text field to date
    ///////////////////////////////////////////////////////
    public Date convertTextToDate(String dateStr){
        Integer year,month,day;
        Date outputDate;
        try{
            year = Integer.valueOf(dateStr.subString(0,4));
            month = Integer.valueOf(dateStr.subString(4,6)); 
            day = Integer.valueOf(dateStr.subString(6,8));
            outputDate = date.newinstance(year, month, day);
        }
        catch(Exception e){
        } 
        return outputDate; 

    }
    
    ////////////////////////////////////////////////
    ///Wrapper to hold complete report data
    //////////////////////////////////////////////// 
    public class ReportDataWrapper{
        public String vemoAccountNumber {get;set;}
        public String studentName {get;set;}
        public String studentId {get;set;}
        public List<reportRowWrapper> rowData {get;set;}
        
        public reportDataWrapper(){
            this.rowData = new List<reportRowWrapper>();    
        }
    }
    
    ////////////////////////////////////////////////
    ///Wrapper to hold row level Data
    ////////////////////////////////////////////////
    public class ReportRowWrapper{
        public String CHId {get;set;}
        public String CHRecNumber {get;set;}
        public String collegeName {get;set;}
        public String enrollmentStatus {get;set;}
        public Date enrollmentBegin {get;set;}
        public Date enrollmentEnd {get;set;}
        public string graduated {get;set;}
        public Date graduationDate {get;set;}
        public String SPId {get;set;}
        public string SPNumber {get;set;}
        public String status {get;set;}
        public Date expectedGradDate {get;set;}
        public Date lastDateOfAttendance {get;set;}
        public Boolean servicing {get;set;}
        public Date servicingStartDate {get;set;}
    }
}