vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <inlineHelpText>This field is used to share this student with the School Account with a matching School Security Field. For example a Student with a School Security of Purdue will be shared with the School Account that has a value of &quot;Purdue&quot; in its School Security field</inlineHelpText>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AllowedSpecialDisbursementTypes__c</fullName>
        <label>Allowed Special Disbursement Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DayPriorToFirstDisbursement__c</fullName>
        <label>Day Prior to First Disbursement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Disbursement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if Disbursement has been confirmed.</inlineHelpText>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NotificationEmail__c</fullName>
        <inlineHelpText>The address to send disbursement notification email.</inlineHelpText>
        <label>Notification Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <formula>Agreement__r.Program__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProgramID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecialDisbursementType__c</fullName>
        <label>Special Disbursement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionDate__c</fullName>
        <inlineHelpText>The date the funds were disbursed.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Represents a funding event in a contract. This is typically a transaction from an investor or school to the school (for tuition) or directly to the student (ex. stipend)</description>
        <label>Disbursement</label>
    </recordTypes>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/DisbursementSpecialTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/School.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Purdue</fullName>
    </customValue>
    <customValue>
        <fullName>Test School</fullName>
    </customValue>
    <customValue>
        <fullName>Coalition for Queens</fullName>
    </customValue>
    <customValue>
        <fullName>Education Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Hack Reactor</fullName>
    </customValue>
    <customValue>
        <fullName>Holberton</fullName>
    </customValue>
    <customValue>
        <fullName>ISDE</fullName>
    </customValue>
    <customValue>
        <fullName>Learners Guild</fullName>
    </customValue>
    <customValue>
        <fullName>Make School</fullName>
    </customValue>
    <customValue>
        <fullName>MissionU</fullName>
    </customValue>
    <customValue>
        <fullName>Thinkful</fullName>
    </customValue>
    <customValue>
        <fullName>UnCollege</fullName>
    </customValue>
    <customValue>
        <fullName>General Assembly</fullName>
    </customValue>
    <customValue>
        <fullName>Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Coder Camps</fullName>
    </customValue>
    <customValue>
        <fullName>NYCDA</fullName>
    </customValue>
    <customValue>
        <fullName>Point Loma</fullName>
    </customValue>
    <customValue>
        <fullName>Sales2Job</fullName>
    </customValue>
    <customValue>
        <fullName>Powderhouse Studios</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Careers Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Lackawanna College</fullName>
    </customValue>
    <customValue>
        <fullName>Studio Institute Global</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Sollers</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Dojo</fullName>
    </customValue>
    <customValue>
        <fullName>Clarkson University</fullName>
    </customValue>
    <customValue>
        <fullName>Messiah College</fullName>
    </customValue>
    <customValue>
        <fullName>Berkeley College</fullName>
    </customValue>
    <customValue>
        <fullName>Haverton</fullName>
    </customValue>
    <masterLabel>School</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/TransactionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/TransactionTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: TransactionTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-29   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class TransactionTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State Control Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    public static Boolean manageTransactionsHasRun = false;

    /**************************Constructors**********************************************/
    
    /**************************Execution Control - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.TriggerContext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'TransactionTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.TriggerContext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'TransactionTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'TransactionTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'TransactionTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onBeforeInsert()');
       //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> newTransactionList = (List<Transaction__c>)tc.newList;
        //This is where you should call your business logic
        setDefaultsOnInsert(newTransactionList);
        validateProgramRules(newTransactionList);
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onBeforeUpdate()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> newTransactionList = (List<Transaction__c>)tc.newList;
        List<Transaction__c> oldTransactionList = (List<Transaction__c>)tc.oldList;
        Map<ID, Transaction__c> newTransactionMap = (Map<ID, Transaction__c>)tc.newMap;
        Map<ID, Transaction__c> oldTransactionMap = (Map<ID, Transaction__c>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldTransactionMap, newTransactionMap); 
        validateProgramRules(newTransactionList);
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onBeforeDelete()');
       //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> oldTransactionList = (List<Transaction__c>)tc.oldList;
        Map<ID, Transaction__c> oldTransactionMap = (Map<ID, Transaction__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onAfterInsert()');
         //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> newTransactionList = (List<Transaction__c>)tc.newList;
        Map<ID, Transaction__c> newTransactionMap = (Map<ID, Transaction__c>)tc.newMap;
        //This is where you should call your business logic
 		manageAgreements(null, newTransactionMap);
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onAfterUpdate()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> newTransactionList = (List<Transaction__c>)tc.newList;
        List<Transaction__c> oldTransactionList = (List<Transaction__c>)tc.oldList;
        Map<ID, Transaction__c> newTransactionMap = (Map<ID, Transaction__c>)tc.newMap;
        Map<ID, Transaction__c> oldTransactionMap = (Map<ID, Transaction__c>)tc.oldMap;
        //This is where you should call your business logic
 		manageAgreements(oldTransactionMap, newTransactionMap);
   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onAfterDelete()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> oldTransactionList = (List<Transaction__c>)tc.oldList;
        Map<ID, Transaction__c> oldTransactionMap = (Map<ID, Transaction__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.TriggerContext tc){
		System.debug('TransactionTriggerHandler.onAfterUndelete()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Transaction__c> newTransactionList = (List<Transaction__c>)tc.newList;
        Map<ID, Transaction__c> newTransactionMap = (Map<ID, Transaction__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<Transaction__c> newTransactionList){
		System.debug('TransactionTriggerHandler.setDefaultsOnInsert()');
        Set<ID> studentIDs = new Set<ID>();
        Set<ID> agreementIDs = new Set<ID>();
        for(Transaction__c tx: newTransactionList){
            agreementIDs.add(tx.Agreement__c);
            studentIDs.add(tx.Student__c);

        }
        Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
        Map<ID, StudentProgram__c> studentProgramMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreementIDs);
        for(Transaction__c tx: newTransactionList){
            if(tx.RecordTypeID == GlobalUtil.getRecordTypeIdByLabelName('Transaction__c', TransactionService.disbursementRecType)){
                if(String.isBlank(tx.NotificationEmail__c)) tx.NotificationEmail__c = studentMap.get(tx.Student__c).PersonEmail;
                if(String.isBlank(tx.SchoolSecurity__c)) tx.SchoolSecurity__c = studentProgramMap.get(tx.Agreement__c).Program__r.School__r.SchoolSecurity__c;
            }
            studentIDs.add(tx.Student__c);
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, Transaction__c> oldTransactionMap, Map<ID, Transaction__c> newTransactionMap){
		System.debug('TransactionTriggerHandler.setDefaultsOnUpdate()'); 
        Set<ID> studentIDs = new Set<ID>();
        Set<ID> agreementIDs = new Set<ID>();        
        for(Transaction__c tx: newTransactionMap.values()){
            agreementIDs.add(tx.Agreement__c);
            studentIDs.add(tx.Student__c);

        }
        Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
        Map<ID, StudentProgram__c> studentProgramMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreementIDs);
        for(Transaction__c tx: newTransactionMap.values()){
            if(tx.RecordTypeID == GlobalUtil.getRecordTypeIdByLabelName('Transaction__c', TransactionService.disbursementRecType)){
                if(String.isBlank(tx.NotificationEmail__c)) tx.NotificationEmail__c = studentMap.get(tx.Student__c).PersonEmail;
                if(String.isBlank(tx.SchoolSecurity__c)) tx.SchoolSecurity__c = studentProgramMap.get(tx.Agreement__c).Program__r.School__r.SchoolSecurity__c;
            }
            studentIDs.add(tx.Student__c);
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: validateProgramRules
    /////////////////////////////////////////////////////////////////////////
    private void validateProgramRules(List<Transaction__c> newTransactionList){
        Set<ID> programIDs = new Set<ID>();
        for(Transaction__c disb : newTransactionList){
            programIDs.add(disb.ProgramID__c);
        }
        Map<ID, Program__c> programMap = ProgramQueries.getProgramMapWithProgramID(programIds);

        for(Transaction__c disb : newTransactionList){
            //Validate Program Rules for this Disbursement Record
            if(programMap.containsKey(disb.ProgramID__c)){
                if(String.isNotEmpty(disb.SpecialDisbursementType__c)){
                    try{
                        if(!programMap.get(disb.ProgramID__c).AllowedSpecialDisbursementTypes__c.contains(disb.SpecialDisbursementType__c)){
                            disb.addError('This Special Disbursement Type is not allowed by this program');
                        }
                    } catch (Exception e) {
                        disb.addError('This Special Disbursement Type is not allowed by this program');                        
                    }

                }
            }
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: manageAgreements
    /////////////////////////////////////////////////////////////////////////
    private void manageAgreements(Map<ID, Transaction__c> oldTransactionMap, Map<ID, Transaction__c> newTransactionMap){
        System.debug('TransactionTriggerHandler.manageAgreements()'); 
        Map<ID, StudentProgram__c> agreementsToUpdate = new Map<ID, StudentProgram__c>();
        Set<ID> agreementIDs = new Set<ID>();
        for(Transaction__c tx:newTransactionMap.values()){
            if(String.isNotEmpty(tx.Agreement__c)) agreementIDs.add(tx.Agreement__c);
        }
        //Get Disbursements by Agreement
        Map<ID, List<Transaction__c>> disbursementsByAgreement = TransactionQueries.getTransactionMapByAgreementWithAgreementID(agreementIDs, TransactionService.disbursementRecType);
/*        for(Transaction__c tx : newTransactionMap.values()){
            if(tx.RecordTypeID == GlobalUtil.getRecordTypeIdByLabelName('Transaction__c', TransactionService.disbursementRecType)){
                if(String.isNotEmpty(tx.Agreement__c)){
                    if(!disbursementsByAgreement.containsKey(tx.Agreement__c)){
                        disbursementsByAgreement.put(tx.Agreement__c, new List<Transaction__c>());
                    }
                    disbursementsByAgreement.get(tx.Agreement__c).add(tx);
                }
            }
        }*/
//        System.debug(disbursementsByAgreement);
        for(ID studProgID : disbursementsByAgreement.keySet()){
//            System.debug(disbursementsByAgreement.get(studProgID));
//            Boolean partiallyFunded = false;
//            Boolean notFullyFunded = false;

/*            for(Transaction__c tx : disbursementsByAgreement.get(studProgID)){
                System.debug('tx:'+tx);
                if(tx.Status__c == 'Complete' && tx.Confirmed__c){
                    partiallyFunded = true;
                } else {
                    notFullyFunded = true;
                }
                ifDay
            }
            if(!notFullyFunded){
                agreementsToUpdate.put(studProgID, new StudentProgram__c(id = studProgID,
                                                                         Status__c = 'Fully Funded'));
            } else if(partiallyFunded){   
                agreementsToUpdate.put(studProgID, new StudentProgram__c(id = studProgID,
                                                                         Status__c = 'Partially Funded'));
            }
            System.debug('partiallyFunded:'+partiallyFunded);
            System.debug('notFullyFunded:'+notFullyFunded);*/

            if(disbursementsByAgreement.containsKey(studProgID)){
                //Find the earliest disbursement date in the list of disgbursements
                Date earliestDate;
                for(Transaction__c disb : disbursementsByAgreement.get(studProgID)){
                    if(disb.TransactionDate__c < earliestDate || earliestDate == null) earliestDate = disb.TransactionDate__c;
                }
                //Set the Day Prior to First Disbursement
                agreementsToUpdate.put(studProgID, new StudentProgram__c(id= studProgID,
                                                                          DayPriorToFirstDisbursement__c = earliestDate.addDays(-1)));
            }    
        } 
             
        if(agreementsToUpdate.size()>0){
            update agreementsToUpdate.values();
        }
    }

    public class TransactionTriggerHandlerException extends Exception {}
}