vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <inlineHelpText>This field is used to share this student with the School Account with a matching School Security Field. For example a Student with a School Security of Purdue will be shared with the School Account that has a value of &quot;Purdue&quot; in its School Security field</inlineHelpText>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DEPRECATEAgreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The result of the credit check (Under Review, Denied, Approved).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditCheckStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Credit Check.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CancellationReason__c</fullName>
        <inlineHelpText>If Status is set to Cancelled, this will show the reason for the cancellation (Credit Denied, etc).</inlineHelpText>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Certified</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Customer Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EligibleToReapply__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Eligible To Reapply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/CreditCheckStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <masterLabel>Credit Check Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/School.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Purdue</fullName>
    </customValue>
    <customValue>
        <fullName>Test School</fullName>
    </customValue>
    <customValue>
        <fullName>Coalition for Queens</fullName>
    </customValue>
    <customValue>
        <fullName>Education Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Hack Reactor</fullName>
    </customValue>
    <customValue>
        <fullName>Holberton</fullName>
    </customValue>
    <customValue>
        <fullName>ISDE</fullName>
    </customValue>
    <customValue>
        <fullName>Learners Guild</fullName>
    </customValue>
    <customValue>
        <fullName>Make School</fullName>
    </customValue>
    <customValue>
        <fullName>MissionU</fullName>
    </customValue>
    <customValue>
        <fullName>Thinkful</fullName>
    </customValue>
    <customValue>
        <fullName>UnCollege</fullName>
    </customValue>
    <customValue>
        <fullName>General Assembly</fullName>
    </customValue>
    <customValue>
        <fullName>Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Coder Camps</fullName>
    </customValue>
    <customValue>
        <fullName>NYCDA</fullName>
    </customValue>
    <customValue>
        <fullName>Point Loma</fullName>
    </customValue>
    <customValue>
        <fullName>Sales2Job</fullName>
    </customValue>
    <customValue>
        <fullName>Powderhouse Studios</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Careers Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Lackawanna College</fullName>
    </customValue>
    <customValue>
        <fullName>Studio Institute Global</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Sollers</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Dojo</fullName>
    </customValue>
    <customValue>
        <fullName>Clarkson University</fullName>
    </customValue>
    <customValue>
        <fullName>Messiah College</fullName>
    </customValue>
    <customValue>
        <fullName>Berkeley College</fullName>
    </customValue>
    <customValue>
        <fullName>Haverton</fullName>
    </customValue>
    <masterLabel>School</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/CreditCheckTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: CreditCheckTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-02-06   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class CreditCheckTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State acctrol Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    public static Boolean manageSchoolSecurityHasRun = false;

    /**************************Constructors**********************************************/
    
    /**************************Execution acctrol - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.Triggercontext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'CreditCheckTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.Triggercontext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'CreditCheckTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'CreditCheckTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'CreditCheckTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onBeforeInsert()');
       //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> newCreditCheckList = (List<CreditCheck__c>)tc.newList;
        //This is where you should call your business logic
		setDefaultsOnInsert(newCreditCheckList);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onBeforeUpdate()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> newCreditCheckList = (List<CreditCheck__c>)tc.newList;
        List<CreditCheck__c> oldCreditCheckList = (List<CreditCheck__c>)tc.oldList;
        Map<ID, CreditCheck__c> newCreditCheckMap = (Map<ID, CreditCheck__c>)tc.newMap;
        Map<ID, CreditCheck__c> oldCreditCheckMap = (Map<ID, CreditCheck__c>)tc.oldMap;
        //This is where you should call your business logic
		setDefaultsOnUpdate(oldCreditCheckMap, newCreditCheckMap); 

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onBeforeDelete()');
       //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> oldCreditCheckList = (List<CreditCheck__c>)tc.oldList;
        Map<ID, CreditCheck__c> oldCreditCheckMap = (Map<ID, CreditCheck__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onAfterInsert()');
         //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> newCreditCheckList = (List<CreditCheck__c>)tc.newList;
        Map<ID, CreditCheck__c> newCreditCheckMap = (Map<ID, CreditCheck__c>)tc.newMap;
        //This is where you should call your business logic

        setAgreementFields(null, newCreditCheckMap);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onAfterUpdate()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> newCreditCheckList = (List<CreditCheck__c>)tc.newList;
        List<CreditCheck__c> oldCreditCheckList = (List<CreditCheck__c>)tc.oldList;
        Map<ID, CreditCheck__c> newCreditCheckMap = (Map<ID, CreditCheck__c>)tc.newMap;
        Map<ID, CreditCheck__c> oldCreditCheckMap = (Map<ID, CreditCheck__c>)tc.oldMap;
        //This is where you should call your business logic

        setAgreementFields(oldCreditCheckMap, newCreditCheckMap);

   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onAfterDelete()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> oldCreditCheckList = (List<CreditCheck__c>)tc.oldList;
        Map<ID, CreditCheck__c> oldCreditCheckMap = (Map<ID, CreditCheck__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.Triggercontext tc){
system.debug('CreditCheckTriggerHandler.onAfterUndelete()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<CreditCheck__c> newCreditCheckList = (List<CreditCheck__c>)tc.newList;
        Map<ID, CreditCheck__c> newCreditCheckMap = (Map<ID, CreditCheck__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<CreditCheck__c> newCreditCheckList){
system.debug('CreditCheckTriggerHandler.setDefaultsOnInsert()');
        Set<ID> studentIDs = new Set<ID>();
        for(CreditCheck__c cc : newCreditCheckList){
            studentIDs.add(cc.Student__c);
        }
        Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
        for(CreditCheck__c cc : newCreditCheckList){  //before trigger
            cc.SchoolSecurity__c = studentMap.get(cc.Student__c).SchoolSecurity__c;
        }   
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, CreditCheck__c> oldCreditCheckMap, Map<ID, CreditCheck__c> newCreditCheckMap){
system.debug('CreditCheckTriggerHandler.setDefaultsOnUpdate()'); 
        Set<ID> studentIDs = new Set<ID>();
        for(CreditCheck__c cc : newCreditCheckMap.values()){
            studentIDs.add(cc.Student__c);
        }
        Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);        
        for(CreditCheck__c cc : newCreditCheckMap.values()){  //before trigger
            cc.SchoolSecurity__c = studentMap.get(cc.Student__c).SchoolSecurity__c;
        }   
    }

    //private void manageSchoolSecurity(Map<ID, CreditCheck__c> oldCreditCheckMap, Map<ID, CreditCheck__c> newCreditCheckMap){
    //    //if(!manageSchoolSecurityHasRun){
    //      //  manageSchoolSecurityHasRun = true;
    //        Set<ID> studentIDs = new Set<ID>();
    //        //List<CreditCheck__c> ccToUpdate = new List<CreditCheck__c>();
    //        for(CreditCheck__c cc : newCreditCheckMap.values()){
    //            studentIDsByCreditCheckID.put(cc.id, cc.Student__c);
    //        }
    //        Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDsByCreditCheckID.values());
    //        for(CreditCheck__c cc : newCreditCheckMap.values()){  //before trigger
    //            cc.SchoolSecurity__c = studentMap.get(studentIDsByCreditCheckID.get(cc.id).SchoolSecurity__c)));
    //        }
    //        //if(ccToUpdate.size()>0){

    //        //}

    //   // } else {
    //     //   System.debug('manageSchoolSecurityHasRun is true');
    //    //}
    //}

    private void setAgreementFields(Map<ID, CreditCheck__c> oldCreditCheckMap, Map<ID, CreditCheck__c> newCreditCheckMap){
/*		System.debug('CreditCheckTriggerHandler.setAgreementFields()'); 
    	Set<ID> agreementIDs = new Set<ID>();
    	Map<ID, StudentProgram__c> agreementsToUpdate = new Map<ID, StudentProgram__c>();
    	for(CreditCheck__c cc: newCreditCheckMap.values()){
    		System.debug(cc);
    		if(oldCreditCheckMap == null){ //insert
    			if(cc.Status__c == 'Denied'){
    				agreementsToUpdate.put(cc.Agreement__c, new StudentProgram__c(id = cc.Agreement__c,
    																			  Status__c = 'Cancelled',
    																			  CancellationReason__c = 'Credit Denied',
    																			  EligibleToReapply__c = false));
				} else if(cc.Status__c == 'Under Review'){
    				agreementsToUpdate.put(cc.Agreement__c, new StudentProgram__c(id = cc.Agreement__c,
    																			  Status__c = 'Application Under Review'));    				
    			}
    		} else { //update
				if(cc.Status__c != oldCreditCheckMap.get(cc.id).Status__c){

					if(cc.Status__c == 'Denied'){
	    				agreementsToUpdate.put(cc.Agreement__c, new StudentProgram__c(id = cc.Agreement__c,
	    																			  Status__c = 'Cancelled',
	    																			  CancellationReason__c = 'Credit Denied',
	    																			  EligibleToReapply__c = false));
					} else if(cc.Status__c == 'Under Review'){
	    				agreementsToUpdate.put(cc.Agreement__c, new StudentProgram__c(id = cc.Agreement__c,
	    																			  Status__c = 'Application Under Review'));   					
					}
				}

    		}
    	}
    	System.debug(agreementsToUpdate);
    	if(agreementsToUpdate.size()>0){
    		update agreementsToUpdate.values();
    	}

*/
    }

    public class CreditCheckTriggerHandlerException extends Exception {}
}