vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <defaultValue>16</defaultValue>
        <inlineHelpText>The default day of the month to perform this student&#39;s assessment.  This value copies to the Student Program level</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DueDayOfTheMonth__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>The day of the month on which this student&#39;s payments are due.</inlineHelpText>
        <label>Due Day of the Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentAllocation__c.object
<CustomObject>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Payment Allocation.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AllocationType__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Allocation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>The amount of this Payment Allocation.</inlineHelpText>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <inlineHelpText>Details of this Payment Allocation (free-text field).</inlineHelpText>
        <label>Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <inlineHelpText>The Payment Instruction related to this Payment Allocation.</inlineHelpText>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>Sum of the Payment Allocations for this Payment Instruction.</inlineHelpText>
        <label>Amount Allocated</label>
        <summarizedField>PaymentAllocation__c.AmountAllocated__c</summarizedField>
        <summaryForeignKey>PaymentAllocation__c.PaymentInstruction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DATA__c</fullName>
        <label>DATA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date of the Payment Instruction.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Scheduled_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <inlineHelpText>The default day of the month to perform this contract assessment.</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BirthdateStudent__c</fullName>
        <inlineHelpText>(Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Birthdate (Student)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusStudent__c</fullName>
        <inlineHelpText>Full Time, Half Time, etc. (Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Enrollment Status (Student)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FundingAmountStudent__c</fullName>
        <inlineHelpText>(Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Funding Amount (Student)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GradeLevelStudent__c</fullName>
        <inlineHelpText>Senior, Junior, etc. (Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Grade Level (Student)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IncomeShareStudent__c</fullName>
        <inlineHelpText>The percent of student&#39;s total earned income that they will share each month. (Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Income Share (Student)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IncomeShare__c</fullName>
        <label>Income Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MajorStudent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The student&#39;s Major, also known as &#39;School Program of Study&#39;. (Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Major (Student)</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Major (Student)</relationshipLabel>
        <relationshipName>Student_Programs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentCapStudent__c</fullName>
        <inlineHelpText>The maximum amount student will pay over the payment term. (Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Payment Cap (Student)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RequestedAmount__c</fullName>
        <label>Requested Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Disbursement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount to be disbursed or refunded.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DATA__c</fullName>
        <label>DATA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionDate__c</fullName>
        <inlineHelpText>The date the funds were disbursed.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>false</active>
        <description>Represents a transaction covering the student&#39;s income-based obligation in the ISA contract. This type of transaction does not occur until the student leaves school.</description>
        <label>Payment</label>
    </recordTypes>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/DebitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/EnrollmentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Three Quarter Time</fullName>
    </customValue>
    <customValue>
        <fullName>Half Time</fullName>
    </customValue>
    <customValue>
        <fullName>Less than Half Time</fullName>
    </customValue>
    <masterLabel>Enrollment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/GradeLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/PaymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/TransactionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/Atom21Migration.cls
public with sharing class Atom21Migration {
	// public static void migratePayments() {
	// 	List<PaymentInstruction__c> paymentInstructionsToAdd = new List<PaymentInstruction__c>();
	// 	for(List<Transaction__c> trans : [SELECT id, RecordTypeID, Student__c, Agreement__c, Status__c, TransactionDate__c, Amount__c
	// 									  FROM Transaction__c
	// 									  WHERE RecordTypeID = :GlobalUtil.getRecordTypeIdByLabelName('Transaction__c', 'Payment')
	// 									  AND DATA__c != 'DELETE']){
	// 		for(Transaction__c tx : trans){
	// 			PaymentInstruction__c payment = new PaymentInstruction__c();
	// 			payment.Amount__c = tx.Amount__c;
	// 			payment.Date__c = tx.TransactionDate__c;
	// 			payment.DATA__c = String.valueOf(tx.Agreement__c);
	// 			payment.Student__c = tx.Student__c;
	// 			paymentInstructionsToAdd.add(payment);
	// 			tx.DATA__c = 'DELETE';
	// 		}
	// 		update trans;

	// 	}
	// 	if(paymentInstructionsToAdd.size()>0){
	// 		insert paymentInstructionsToAdd;
	// 	}
	// 	List<PaymentAllocation__c> allocations = new List<PaymentAllocation__c>();
	// 	for(PaymentInstruction__c payment : paymentInstructionsToAdd){
	// 		allocations.add(new PaymentAllocation__c(PaymentInstruction__c = payment.id, 
	// 													Agreement__c = payment.DATA__c, Detail__c = 'Data Conversion',
	// 													AmountAllocated__c = payment.Amount__c,
	// 													AllocationType__c = 'Monthly Amount'));
	// 	}
	// 	if(allocations.size()>0){
	// 		insert allocations;
	// 	}
	// }

	// public static void deleteMigratedPayments(){
	// 	delete [SELECT id from Transaction__c where DATA__c = 'DELETE'];
	// }

	// public static void setAssessmentNumbers(){
	// 	for(List<Account> accts : [SELECT id
	// 									from Account where
	// 	 								RecordTypeID = :GlobalUtil.getRecordTypeIdByLabelName('Account', 'Student')]){
	// 		for(Account acct : accts){
	// 			acct.AssessmentDayOfMonth__c = 16;
	// 			acct.DueDayOfTheMonth__c = 1;
	// 		}
	// 		update accts;

	// 	}
	// }

	// public static void approvePendingAccounts(){
	// 	for(List<Account> accts : [SELECT id,
	// 	 								RecordStatus__pc,
	// 									PendingFirstName__pc,
	// 									PendingMiddleName__pc,
	// 									PendingLastName__pc,
	// 									PendingBirthdate__pc,
	// 									PendingDriversLicenseOrStateID__pc,
	// 									PendingEmail__pc,
	// 									PendingResidency__pc,
	// 									PendingMailingStreet__pc,
	// 									PendingMailingCity__pc,
	// 									PendingMailingStateCode__pc,
	// 									PendingMailingState__pc,
	// 									PendingMailingCountryCode__pc,
	// 									PendingMailingCountry__pc,
	// 									PendingMailingPostalCode__pc
	// 									from Account where RecordStatus__pc != 'Approved' and 
	// 	 								RecordTypeID = :GlobalUtil.getRecordTypeIdByLabelName('Account', 'Student')]){
	// 		for(Account acct : accts){
	// 			acct.RecordStatus__pc = 'Approved';
	// 			if(String.isNotEmpty(acct.PendingFirstName__pc)) acct.FirstName = acct.PendingFirstName__pc;
	// 			if(String.isNotEmpty(acct.PendingMiddleName__pc)) acct.MiddleName = acct.PendingMiddleName__pc;
	// 			if(acct.PendingBirthdate__pc != null) acct.PersonBirthdate = acct.PendingBirthDate__pc;
	// 			if(String.isNotEmpty(acct.PendingLastName__pc)) acct.LastName = acct.PendingLastName__pc;
	// 			if(String.isNotEmpty(acct.PendingDriversLicenseOrStateID__pc)) acct.DriversLicenseOrStateID__pc = acct.PendingDriversLicenseOrStateID__pc;
	// 			if(String.isNotEmpty(acct.PendingEmail__pc)) acct.PersonEmail = acct.PendingEmail__pc;
	// 			if(String.isNotEmpty(acct.PendingResidency__pc)) acct.Residency__pc = acct.PendingResidency__pc;

	// 			if(String.isNotEmpty(acct.PendingMailingStreet__pc)) acct.PersonMailingStreet = acct.PendingMailingStreet__pc;
	// 			if(String.isNotEmpty(acct.PendingMailingCity__pc)) acct.PersonMailingCity = acct.PendingMailingCity__pc;				
	// 			if(String.isNotEmpty(acct.PendingMailingStateCode__pc)) acct.PersonMailingStateCode = acct.PendingMailingStateCode__pc;
	// 			if(String.isNotEmpty(acct.PendingMailingState__pc)) acct.PersonMailingState = acct.PendingMailingState__pc;
	// 			if(String.isNotEmpty(acct.PendingMailingCountryCode__pc)) acct.PersonMailingCountryCode = acct.PendingMailingCountryCode__pc;
	// 			if(String.isNotEmpty(acct.PendingMailingCountry__pc)) acct.PersonMailingCountry = acct.PendingMailingCountry__pc;
	// 			if(String.isNotEmpty(acct.PendingMailingPostalCode__pc)) acct.PersonMailingPostalCode = acct.PendingMailingPostalCode__pc;

	// 			acct.PendingFirstName__pc = '';
	// 			acct.PendingMiddleName__pc = '';
	// 			acct.PendingLastName__pc = '';
	// 			acct.PendingBirthdate__pc = null;
	// 			acct.PendingDriversLicenseOrStateID__pc = '';
	// 			acct.PendingEmail__pc = '';
	// 			acct.PendingResidency__pc = '';
	// 			acct.PendingMailingStreet__pc = '';
	// 			acct.PendingMailingCity__pc = '';
	// 			acct.PendingMailingStateCode__pc = '';
	// 			acct.PendingMailingState__pc = '';
	// 			acct.PendingMailingCountryCode__pc = '';
	// 			acct.PendingMailingCountry__pc = '';
	// 			acct.PendingMailingPostalCode__pc = '';


	// 			system.debug(acct);
	// 		}
	// 		system.debug(accts);
	// 		update accts;
	// 	}
	// }

	// public static void migrateAgreementData() {
	// 	Map<ID, StudentProgram__c> agreements1 = new Map<ID, StudentProgram__c>([SELECT id from StudentProgram__c]);
	// 	Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreements1.keySet());
	// 	Set<ID> studentIDs = new Set<ID>();
	// 	for(StudentProgram__c agreement : agreementMap.values()){
	// 		studentIDs.add(agreement.Student__c);
	// 	}
	// 	Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);

	// 	for(StudentProgram__c a : agreementMap.values()){
	// 		Account acct = studentMap.get(a.Student__c);
	// 		if(a.Status__c == 'Application Incomplete' || a.Status__c == 'Application Under Review' || a.Status__c == 'Cancelled' || a.Status__c == 'Application Complete'){
	// 			//Copy from legacy to Student Fields
	// 			a.BirthdateStudent__c = acct.PersonBirthdate;
	// 			a.EnrollmentStatusStudent__c = (String.isNotEmpty(a.EnrollmentStatus__c) ? a.EnrollmentStatus__c : acct.PrimarySchoolEnrollmentStatus__pc);
	// 			a.FundingAmountStudent__c = a.RequestedAmount__c;
	// 			a.GradeLevelStudent__c = (String.isNotEmpty(a.GradeLevel__c) ? a.GradeLevel__c : acct.PrimarySchoolGradeLevel__pc);
	// 			a.IncomeShareStudent__c = a.IncomeShare__c;
	// 			a.MajorStudent__c = (String.isNotEmpty(a.SchoolProgramOfStudy__c) ? a.SchoolProgramOfStudy__c : acct.SchoolProgramOfStudy__pc);
	// 			a.PaymentCapStudent__c = a.PaymentCap__c;
	// 			a.PaymentTermStudent__c = a.PaymentTerm__c;
	// 			a.ResidencyStudent__c = (String.isNotEmpty(a.Residency__c) ? a.Residency__c : acct.Residency__pc);
	// 			a.StateOfResidenceStudent__c = acct.PersonMailingStateCode;

	// 		}
	// 		if(a.Status__c == 'Certified' ||
	// 		   a.Status__c == 'Partially Funded' ||
	// 		   a.Status__c == 'Fully Funded' ||
	// 		   a.Status__c == 'Grace' ||
	// 		   a.Status__c == 'Deferment' || 
	// 		   a.Status__c == 'Payment'){
	// 			a.BirthdateStudent__c = acct.PersonBirthdate;
	// 			a.BirthdateCertification__c = acct.PersonBirthdate;
	// 			a.BirthdatePostCertification__c = acct.PersonBirthdate;	

	// 			a.EnrollmentStatusStudent__c = (String.isNotEmpty(a.EnrollmentStatus__c) ? a.EnrollmentStatus__c : acct.PrimarySchoolEnrollmentStatus__pc);
	// 			a.EnrollmentStatusCertification__c = (String.isNotEmpty(a.EnrollmentStatus__c) ? a.EnrollmentStatus__c : acct.PrimarySchoolEnrollmentStatus__pc);
	// 			a.EnrollmentStatusPostCertification__c = (String.isNotEmpty(a.EnrollmentStatus__c) ? a.EnrollmentStatus__c : acct.PrimarySchoolEnrollmentStatus__pc);
				
	// 			a.FundingAmountStudent__c = a.RequestedAmount__c;
	// 			a.FundingAmountCertification__c = a.AllocatedAmount__c;
	// 			a.FundingAmountPostCertification__c = a.AllocatedAmount__c;								

	// 			a.GradeLevelStudent__c = (String.isNotEmpty(a.GradeLevel__c) ? a.GradeLevel__c : acct.PrimarySchoolGradeLevel__pc);
	// 			a.GradeLevelCertification__c = (String.isNotEmpty(a.GradeLevel__c) ? a.GradeLevel__c : acct.PrimarySchoolGradeLevel__pc);				
	// 			a.GradeLevelPostCertification__c = (String.isNotEmpty(a.GradeLevel__c) ? a.GradeLevel__c : acct.PrimarySchoolGradeLevel__pc);

	// 			a.IncomeShareStudent__c = a.IncomeShare__c;
	// 			a.IncomeShareCertification__c = a.IncomeShare__c;				
	// 			a.IncomeSharePostCertification__c = a.IncomeShare__c;

	// 			a.MajorStudent__c = (String.isNotEmpty(a.SchoolProgramOfStudy__c) ? a.SchoolProgramOfStudy__c : acct.SchoolProgramOfStudy__pc);
	// 			a.MajorCertification__c = (String.isNotEmpty(a.SchoolProgramOfStudy__c) ? a.SchoolProgramOfStudy__c : acct.SchoolProgramOfStudy__pc);
	// 			a.MajorPostCertification__c = (String.isNotEmpty(a.SchoolProgramOfStudy__c) ? a.SchoolProgramOfStudy__c : acct.SchoolProgramOfStudy__pc);
				
	// 			a.PaymentCapStudent__c = a.PaymentCap__c;
	// 			a.PaymentCapCertification__c = a.PaymentCap__c;				
	// 			a.PaymentCapPostCertification__c = a.PaymentCap__c;

	// 			a.PaymentTermStudent__c = a.PaymentTerm__c;
	// 			a.PaymentTermCertification__c = a.PaymentTerm__c;				
	// 			a.PaymentTermPostCertification__c = a.PaymentTerm__c;

	// 			a.ResidencyStudent__c = (String.isNotEmpty(a.Residency__c) ? a.Residency__c : acct.Residency__pc);
	// 			a.ResidencyCertification__c = (String.isNotEmpty(a.Residency__c) ? a.Residency__c : acct.Residency__pc);				
	// 			a.ResidencyPostCertification__c = (String.isNotEmpty(a.Residency__c) ? a.Residency__c : acct.Residency__pc);

	// 			a.StateOfResidenceStudent__c = acct.PersonMailingStateCode;
	// 			a.StateOfResidenceCertification__c = acct.PersonMailingStateCode;
	// 			a.StateOfResidencePostCertification__c = acct.PersonMailingStateCode;
	// 			a.CertificationDraftStatus__c = 'Certified';
	// 		}
	// 		if(a.Status__c == 'Fully Funded' || a.Status__c == 'Grace' || a.Status__c == 'Deferment' || a.Status__c == 'Payment'){

	// 		}
	// 	}
	// 	system.debug(agreementMap.values());
	// 	update agreementMap.values();
	// }
}