vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DEPRECATEAgreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ConsentDateTimeStamp__c</fullName>
        <defaultValue>Now()</defaultValue>
        <inlineHelpText>The date at which the student consented to have their credit checked.</inlineHelpText>
        <label>Consent Date Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ConsentIPAddress__c</fullName>
        <inlineHelpText>The IP Address from which the student consented to have their credit checked.</inlineHelpText>
        <label>Consent IP Address</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReasonText__c</fullName>
        <inlineHelpText>If Status is Denied, this indicates one or more reason categories for the denial (formatted so it can be included in email communications).</inlineHelpText>
        <label>Credit Check Denied Reason Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReason__c</fullName>
        <inlineHelpText>If Status is Denied, this indicates one or more reason categories for the denial.</inlineHelpText>
        <label>Credit Check Denied Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditCheckDeniedReason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>JSONPayload__c</fullName>
        <inlineHelpText>The raw results of the credit check module in JSON format.</inlineHelpText>
        <label>JSON Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The result of the credit check (Under Review, Denied, Approved).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditCheckStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Credit Check.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CreditCheckDeniedReasonText__c</fullName>
        <inlineHelpText>From the Credit Check object. Formatted to be used in communications to student.</inlineHelpText>
        <label>Credit Check Denied Reason Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/CreditCheckDeniedReason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Educational Loan Default</fullName>
    </customValue>
    <customValue>
        <fullName>Bankruptcy</fullName>
    </customValue>
    <customValue>
        <fullName>Collection</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfied Suit or Judgement</fullName>
    </customValue>
    <customValue>
        <fullName>Major Derogatory Public Record</fullName>
    </customValue>
    <customValue>
        <fullName>Unpaid Tax Liens</fullName>
    </customValue>
    <customValue>
        <fullName>Business or Administrative Error</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Error</fullName>
    </customValue>
    <customValue>
        <fullName>Insufficient FICO score</fullName>
    </customValue>
    <masterLabel>Credit Check Denied Reason</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/CreditCheckStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <masterLabel>Credit Check Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/CreditCheckQueries.cls
public class CreditCheckQueries {
	public static Map<ID, CreditCheck__c> getCreditCheckMap(){
		Map<ID, CreditCheck__c> ccMap = new Map<ID, CreditCheck__c>();
		String query = generateSOQLSelect();
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' WHERE Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		ccMap = new Map<ID, CreditCheck__c>((List<CreditCheck__c>)db.query(query));
		return ccMap;		
	}

	public static Map<ID, CreditCheck__c> getCreditCheckMapWithCreditCheckID(Set<ID> creditCheckIDs){
		Map<ID, CreditCheck__c> ccMap = new Map<ID, CreditCheck__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(creditCheckIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		ccMap = new Map<ID, CreditCheck__c>((List<CreditCheck__c>)db.query(query));
		return ccMap;
	}

	public static Map<ID, CreditCheck__c> getCreditCheckMapWithStudentID(Set<ID> studentIDs){
		Map<ID, CreditCheck__c> ccMap = new Map<ID, CreditCheck__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Student__c IN ' + DatabaseUtil.inSetStringBuilder(studentIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		ccMap = new Map<ID, CreditCheck__c>((List<CreditCheck__c>)db.query(query));
		return ccMap;
	}

	public static Map<ID, CreditCheck__c> getCreditCheckMapWithAgreementID(Set<ID> agreementIDs){
		Map<ID, CreditCheck__c> ccMap = new Map<ID, CreditCheck__c>();
		Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreementIDs);
		Set<ID> ccIDs = new Set<ID>();
		for(StudentProgram__c agreement : agreementMap.values()){
			if(String.isNotEmpty(agreement.CreditCheck__c))	ccIDs.add(agreement.CreditCheck__c);
		}
		ccMap = getCreditCheckMapWithCreditCheckID(ccIDs);
		/*
		String query = generateSOQLSelect();
		query += ' WHERE Agreement__c IN ' + DatabaseUtil.inSetStringBuilder(agreementIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		ccMap = new Map<ID, CreditCheck__c>((List<CreditCheck__c>)db.query(query));*/
		return ccMap;
	}

	public static Map<ID, CreditCheck__c> getCreditCheckMapByAgreementIDWithAgreementID(Set<ID> agreementIDs){
		Map<ID, CreditCheck__c> ccMap = new Map<ID, CreditCheck__c>();
		Map<ID, CreditCheck__c> ccByAgreementID = new Map<ID, CreditCheck__c>();
		Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreementIDs);
		Set<ID> ccIDs = new Set<ID>();
		for(StudentProgram__c agreement : agreementMap.values()){
			if(String.isNotEmpty(agreement.CreditCheck__c))	ccIDs.add(agreement.CreditCheck__c);
		}
		System.debug('ccIDs:'+ccIDs);
		ccMap = getCreditCheckMapWithCreditCheckID(ccIDs);
		for(StudentProgram__c agree : agreementMap.values()){
			System.debug('ccMap:'+ccMap);
			System.debug('agreementMap:'+agreementMap);
			if(ccMap.containsKey(agreementMap.get(agree.id).CreditCheck__c)){
				ccByAgreementID.put(agree.id, ccMap.get(agreementMap.get(agree.id).CreditCheck__c));				
			}
		}

		/*
		String query = generateSOQLSelect();
		query += ' WHERE Agreement__c IN ' + DatabaseUtil.inSetStringBuilder(agreementIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		ccMap = new Map<ID, CreditCheck__c>((List<CreditCheck__c>)db.query(query));*/
		return ccByAgreementID;
	}


	private static String generateSOQLSelect(){
		String soql;		
		soql = 'SELECT ' + getFieldNames() + ' FROM CreditCheck__c';
		return soql;
	}

	private static String getFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Student__c, ';
		fieldNames += 'Student__r.GUID__c, ';
//		fieldNames += 'Agreement__c, ';
//		fieldNames += 'Agreement__r.GUID__c, ';
		fieldNames += 'ConsentIPAddress__c, ';
		fieldNames += 'ConsentDateTimeStamp__c, ';
		fieldNames += 'JSONPayload__c, ';
		fieldNames += 'Status__c, ';
		fieldNames += 'CreditCheckDeniedReason__c, ';
		fieldNames += 'CreditCheckDeniedReasonText__c, ';
		fieldNames += 'GUID__c';

		return fieldNames;
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
}