vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessmentDate__c</fullName>
        <description>The date when this account will next be assessed.  The assessment process will run on any account where the assessment is today or in the past.</description>
        <inlineHelpText>The date when this account will next be assessed.  The assessment process will run on any account where the assessment is today or in the past.</inlineHelpText>
        <label>(Deprecate)Assessment Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/KeyValuePair__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Key Value Pair</label>
    <fields>
        <fullName>ValueText__c</fullName>
        <label>ValueText</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/OutboundEmail__c.object
<CustomObject>
    <label>Outbound Email</label>
    <nameField>
        <displayFormat>Email-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Outbound Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SendviaSES__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send via SES</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TargetObjectId__c</fullName>
        <description>Required if using a template, optional otherwise. The ID of the contact, lead, or user to which the email will be sent. The ID you specify sets the context and ensures that merge fields in the template contain the correct data.</description>
        <inlineHelpText>Required if using a template, optional otherwise. The ID of the contact, lead, or user to which the email will be sent. The ID you specify sets the context and ensures that merge fields in the template contain the correct data.</inlineHelpText>
        <label>TargetObjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TemplateID__c</fullName>
        <description>Required if using a template, optional otherwise. The ID of the template used to create the email.</description>
        <inlineHelpText>Required if using a template, optional otherwise. The ID of the template used to create the email.</inlineHelpText>
        <label>TemplateID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <description>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</description>
        <inlineHelpText>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</inlineHelpText>
        <label>ToAddresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WhatID__c</fullName>
        <description>If you specify a contact for the targetObjectId field, you can specify an optional whatId as well. This helps to further ensure that merge fields in the template contain the correct data.</description>
        <inlineHelpText>If you specify a contact for the targetObjectId field, you can specify an optional whatId as well. This helps to further ensure that merge fields in the template contain the correct data.</inlineHelpText>
        <label>WhatID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AssessContract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is checked, Assessment will run for this Student Program record regardless of Assessment Date</description>
        <inlineHelpText>If this field is checked, Assessment will run for this Student Program record regardless of Assessment Date</inlineHelpText>
        <label>Assess Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AssessmentDate__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DaysDelinquent__c</fullName>
        <formula>if(NextPaymentDue__c &gt; 0,if(TODAY() - NextPaymentDueDate__c &gt;0,Today() - NextPaymentDueDate__c, 0),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Delinquent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAudit__c.object
<CustomObject>
    <label>Student Program Audit</label>
    <nameField>
        <displayFormat>SPA-{000000}</displayFormat>
        <label>Student Program Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AuditDateTime__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Audit DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DaysDelinquent__c</fullName>
        <label>Days Delinquent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MonthEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month End</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StudentProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Audit</relationshipLabel>
        <relationshipName>Student_Program_History</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this disbursement is deleted and will be purged by an hourly job.  Necessary for school admins to be able to delete records</description>
        <inlineHelpText>If this flag is checked, this disbursement is deleted and will be purged by an hourly job</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/StudentProgramBatch.cls
public with sharing class StudentProgramBatch implements Database.Batchable<sObject>, Database.ALlowsCallouts{
    public enum JobType {DELINQUENCY, PURGE_DELETED, MONTH_END_AUDIT, CONTRACT_ASSESSMENT} 
    
    public String query {get;set;}
    public JobType job {get;set;}
    
    public StudentProgramBatch() {

    }
    public StudentProgramBatch(String query) {
        this.query = query;
    }   
    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('StudentProgramBatch.start()');
        if(job == JobType.DELINQUENCY){
            if(String.isEmpty(this.query)){
                query = 'SELECT id, DaysDelinquent__c, Student__c, Student__r.PersonContactID, Student__r.PersonEmail from StudentProgram__c WHERE DaysDelinquent__c > 0 ORDER BY DaysDelinquent__c DESC';
            }
        } else if(job == JobType.PURGE_DELETED){
            if(String.isEmpty(this.query)){
                Set<String> deletableStatuses= new Set<String>{'Draft', 'Invited', 'Cancelled'};
                query = 'SELECT id from StudentProgram__c WHERE Deleted__c = true and Status__c IN :deletableStatuses';
            }
        } else if(job == JobType.MONTH_END_AUDIT){
            if(String.isEmpty(this.query)){
                query = 'SELECT id From StudentProgram__c Where Deleted__c = false';
            }
        } else if(job == JobType.CONTRACT_ASSESSMENT){
            if(String.isEmpty(this.query)){
				String dateToday = String.valueOf(Date.today());			
				query = 'SELECT id from StudentProgram__c WHERE (AssessmentDate__c <= '+dateToday + ' OR AssessContract__c = true)';
            }
        }
        System.debug('job:'+job);
        System.debug('query:'+query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('StudentProgramBatch.execute()');
        System.debug('scope:'+scope);   
        if(job == JobType.DELINQUENCY){
            handleDelinquency((List<StudentProgram__c>)scope);
        }else if(job == JobType.PURGE_DELETED){
            handlePurgeDeleted((List<StudentProgram__c>)scope);
        }else if(job == JobType.MONTH_END_AUDIT){
            handleAudit((List<StudentProgram__c>)scope);
        }else if(job == JobType.CONTRACT_ASSESSMENT){
            Set<ID> agreementIDs = new Set<ID>();
            for(SObject obj : scope){
                agreementIDs.add(obj.id);
            }
            AssessmentService.assessContracts(agreementIDs);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('StudentProgramBatch.finish()');

    }
    
    private static void handlePurgeDeleted(List<StudentProgram__c> agreements){
        System.debug('StudentProgramBatch.handlePurgeDeleted()');   
        Set<ID> agreementIDs = new Set<ID>();
        for(StudentProgram__c agreement : agreements){
            agreementIDs.add(agreement.id);
        }
        Map<ID, Transaction__c> disbMap = TransactionQueries.getTransactionMapWithAgreementID(agreementIDs, TransactionService.disbursementRecType);
        Database.delete(disbMap.values(), false);
        Database.delete(agreements, false);
    }

       private static void handleDelinquency(List<StudentProgram__c> agreements){

        System.debug('StudentProgramBatch.handleDelinquency()');    
        List<Task> tasksToBeCreated = new List<Task>();
        List<OutboundEmail__c> emailToBeCreated = new List<OutboundEmail__c>();
        for(StudentProgram__c agreement : agreements){
            if(agreement.DaysDelinquent__c == 12 ||
               agreement.DaysDelinquent__c == 42 ||
               agreement.DaysDelinquent__c == 72 || 
               agreement.DaysDelinquent__c == 102 ||    
               agreement.DaysDelinquent__c == 132 ||    
               agreement.DaysDelinquent__c == 162 ){    
                 tasksToBeCreated.add(delinquencyCall(agreement));
                 
                 OutboundEmail__c delEmail = delinquencyEmail(agreement);
                 if(delEmail != null)
                     emailToBeCreated.add(delEmail);
            }
            
            else if(agreement.DaysDelinquent__c == 27 ||
               agreement.DaysDelinquent__c == 57 ||
               agreement.DaysDelinquent__c == 87 || 
               agreement.DaysDelinquent__c == 117 ||    
               agreement.DaysDelinquent__c == 147 ||
               agreement.DaysDelinquent__c == 177 ||
               agreement.DaysDelinquent__c == 192 ||
               agreement.DaysDelinquent__c == 207 ||
               agreement.DaysDelinquent__c == 222 ||
               agreement.DaysDelinquent__c == 237 ||
               agreement.DaysDelinquent__c == 252){
                 //emailToBeCreated.add(delinquencyEmail(agreement));
                 
                 OutboundEmail__c delEmail = delinquencyEmail(agreement);
                 if(delEmail != null)
                     emailToBeCreated.add(delEmail);
            }
            //if(agreement.DaysDelinquent__c == 12 ||
            //   agreement.DaysDelinquent__c == 27 ||
            //   agreement.DaysDelinquent__c == 42 ||   
            //   agreement.DaysDelinquent__c == 57 ||   
            //   agreement.DaysDelinquent__c == 72 ||   
            //   agreement.DaysDelinquent__c == 87 ||   
            //   agreement.DaysDelinquent__c == 102 ||  
            //   agreement.DaysDelinquent__c == 117 ||
            //   agreement.DaysDelinquent__c == 132 ||  
            //   agreement.DaysDelinquent__c == 147 ||  
            //   agreement.DaysDelinquent__c == 162 ||
            //   agreement.DaysDelinquent__c == 177){
            //  emailToBeCreated.add(delinquencyEmail(agreement));
            //}
            //if(agreement.DaysDelinquent__c == 27 ||
            //   agreement.DaysDelinquent__c == 57 ||
            //   agreement.DaysDelinquent__c == 87 ||   
            //   agreement.DaysDelinquent__c == 117 ||  
            //   agreement.DaysDelinquent__c == 147 ||      
            //   agreement.DaysDelinquent__c == 177 ){
            //  tasksToBeCreated.add(delinquencyText(agreement));
            //}
        }
        if(tasksToBeCreated != null && tasksToBeCreated.size()>0){
            insert tasksToBeCreated;
        }
        if(emailToBeCreated != null && emailToBeCreated.size()>0){
          insert emailToBeCreated;
        }
    }

    private static Task delinquencyCall(StudentProgram__c agreement){
        String owner;
        try{
            owner = String.isNotBlank(KeyValuePair__c.getValues('DelinquencyTaskOwnerID').ValueText__c) ?
                                        KeyValuePair__c.getValues('DelinquencyTaskOwnerID').ValueText__c :
                                        UserInfo.getUserId();
        } catch (Exception e) {
            owner =  UserInfo.getUserId();
        }
        Task newTask = new Task(Type = 'Call',
                          ActivityDate = Date.today(),
                          Subject = 'Delinquency Notification: (' + String.valueOf((Integer)agreement.DaysDelinquent__c) + ' Days)', 
                          WhatID = agreement.Student__c,
                          WhoID = agreement.Student__r.PersonContactID,
                          OwnerID = owner,
                          Description = 'This student is overdue. Please reach out to the student by telephone.');
        System.debug(newTask);
        return newTask;
    }
    private static OutboundEmail__c delinquencyEmail(StudentProgram__c agreement){
        
        EmailTemplate template;
        
        if(agreement.DaysDelinquent__c == 12 || agreement.DaysDelinquent__c == 27)
            template = selectTemplate('Delinquency_Letter_11_Days');
        else if(agreement.DaysDelinquent__c == 42 || agreement.DaysDelinquent__c == 57)
            template = selectTemplate('Delinquency_Letter_30_Days');
        else if(agreement.DaysDelinquent__c == 72 || agreement.DaysDelinquent__c == 87)
            template = selectTemplate('Delinquency_Letter_60_Days');
        else if(agreement.DaysDelinquent__c == 102 || agreement.DaysDelinquent__c == 117)
            template = selectTemplate('Delinquency_Letter_90_Days');
        else if(agreement.DaysDelinquent__c == 132 || agreement.DaysDelinquent__c == 147)
            template = selectTemplate('Delinquency_Letter_120_Days');
        else if(agreement.DaysDelinquent__c == 162 || agreement.DaysDelinquent__c == 177)
            template = selectTemplate('Delinquency_Letter_150_Days');
        else if(agreement.DaysDelinquent__c == 192 || agreement.DaysDelinquent__c == 207)
            template = selectTemplate('Delinquency_Letter_180_Days');
        else if(agreement.DaysDelinquent__c == 222 || agreement.DaysDelinquent__c == 237)
            template = selectTemplate('Delinquency_Letter_210_Days');
        else if(agreement.DaysDelinquent__c == 252)
            template = selectTemplate('Delinquency_Letter_240_Days');
        
        if(template != null){
            return new OutboundEmail__c(ToAddresses__c = agreement.Student__r.PersonEmail,
                                      TemplateID__c = template.id,
                                      WhatID__c = agreement.id,
                                      TargetObjectId__c = agreement.Student__r.PersonContactID,
                                      SendviaSES__c = true);
        }
        else
            return null;
    }
    
    private static EmailTemplate selectTemplate(string templateName){
        try{
            return [Select id from EmailTemplate where developerName =: templateName];            
        } catch (Exception e){
            return null;
        }
    }
    
    //private static Task delinquencyText(StudentProgram__c agreement){
    //  return new Task(Type = 'Other',
    //                        ActivityDate = Date.today(),
    //                        Subject = 'Delinquency Notification: (' + String.valueOf((Integer)agreement.DaysDelinquent__c) + ' Days)', 
    //                    WhatID = agreement.Student__c,
    //                    WhoID = agreement.Student__r.PersonContactID,
    //                    Description = 'This student is overdue. Please reach out to the student by text message.');
    //}
    
    private static void handleAudit(List<StudentProgram__c> agreements){
        List<StudentProgramAudit__c> auditToCreate = new List<StudentProgramAudit__c>();
        List<StudentProgram__c> spList = new List<StudentProgram__c>();
        Set<ID> agreementIDs = new Set<ID>();
        String queryString = 'Select Id,'; 
        
        for(StudentProgram__c agreement:agreements){
            agreementIDs.add(agreement.id);
        }
        
        SObjectType studentProgramAuditDescribe = Schema.getGlobalDescribe().get('StudentProgramAudit__c');
        Map<String,Schema.SObjectField> studProgAudFields = studentProgramAuditDescribe.getDescribe().fields.getMap();
        
        ////generate a dynamic query string to query studentProgram records
        for(String fld : studProgAudFields.keySet()){
            if(fld.endsWith('__c') && fld != 'StudentProgram__c' && fld != 'auditdatetime__c' && fld != 'MonthEnd__c'){
                queryString += fld;
                queryString += ',';    
            }
        }
        queryString = queryString.removeEnd(',');
        queryString += ' From StudentProgram__c Where ID IN ' + DatabaseUtil.inSetStringBuilder(agreementIDs);
        
        spList = Database.query(queryString);
        
        for(StudentProgram__c agreement:spList){
            StudentProgramAudit__c audit = new StudentProgramAudit__c();
            audit.StudentProgram__c = agreement.Id;
            audit.monthEnd__c = true;
            for(String fld : studProgAudFields.keySet()){
                if(fld.endsWith('__c') && fld != 'StudentProgram__c' && fld != 'auditdatetime__c' && fld != 'MonthEnd__c'){
                    audit.put(fld, agreement.get(fld));
                }
            }
            auditToCreate.add(audit);    
        }
        
        if(auditToCreate.size()>0){
            insert auditToCreate;
        } 
        
                       
    }    
}