vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <inlineHelpText>This field is used to share this student with the School Account with a matching School Security Field. For example a Student with a School Security of Purdue will be shared with the School Account that has a value of &quot;Purdue&quot; in its School Security field</inlineHelpText>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of Program related to this Student Program.</inlineHelpText>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>VemoContractNumber__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <inlineHelpText>Automatically generated number identifying the Contract/Student Program. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Contract Number</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Disbursement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount to be disbursed or refunded.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if Disbursement has been confirmed.</inlineHelpText>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this disbursement is deleted and will be purged by an hourly job.  Necessary for school admins to be able to delete records</description>
        <inlineHelpText>If this flag is checked, this disbursement is deleted and will be purged by an hourly job</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DisbursementPercentage__c</fullName>
        <label>Disbursement Percentage</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Agreement__r.Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Field used in email communications.</inlineHelpText>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Disbursement was created by a Disbursement Schedule, indicates the related Disbursement Schedule.</inlineHelpText>
        <label>Related Schedule</label>
        <referenceTo>TransactionSchedule__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>RelatedTransactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScheduledAmount__c</fullName>
        <formula>Agreement__r.FundingAmountCertification__c  * DisbursementPercentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DEPRECATEScheduled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecialDisbursementType__c</fullName>
        <label>Special Disbursement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionDate__c</fullName>
        <inlineHelpText>The date the funds were disbursed.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/DisbursementSpecialTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/School.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Purdue</fullName>
    </customValue>
    <customValue>
        <fullName>Test School</fullName>
    </customValue>
    <customValue>
        <fullName>Coalition for Queens</fullName>
    </customValue>
    <customValue>
        <fullName>Education Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Hack Reactor</fullName>
    </customValue>
    <customValue>
        <fullName>Holberton</fullName>
    </customValue>
    <customValue>
        <fullName>ISDE</fullName>
    </customValue>
    <customValue>
        <fullName>Learners Guild</fullName>
    </customValue>
    <customValue>
        <fullName>Make School</fullName>
    </customValue>
    <customValue>
        <fullName>MissionU</fullName>
    </customValue>
    <customValue>
        <fullName>Thinkful</fullName>
    </customValue>
    <customValue>
        <fullName>UnCollege</fullName>
    </customValue>
    <customValue>
        <fullName>General Assembly</fullName>
    </customValue>
    <customValue>
        <fullName>Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Coder Camps</fullName>
    </customValue>
    <customValue>
        <fullName>NYCDA</fullName>
    </customValue>
    <customValue>
        <fullName>Point Loma</fullName>
    </customValue>
    <customValue>
        <fullName>Sales2Job</fullName>
    </customValue>
    <customValue>
        <fullName>Powderhouse Studios</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Careers Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Lackawanna College</fullName>
    </customValue>
    <customValue>
        <fullName>Studio Institute Global</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Sollers</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Dojo</fullName>
    </customValue>
    <customValue>
        <fullName>Clarkson University</fullName>
    </customValue>
    <customValue>
        <fullName>Messiah College</fullName>
    </customValue>
    <customValue>
        <fullName>Berkeley College</fullName>
    </customValue>
    <customValue>
        <fullName>Haverton</fullName>
    </customValue>
    <masterLabel>School</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/TransactionQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: TransactionQueries
// 
// Description: 
//  All queries on the Transaction__c object
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-28   Greg Cook       Created                         
// 
/////////////////////////////////////////////////////////////////////////
public class TransactionQueries {
    
    public static Map<ID, Transaction__c> getTransactionMap(String recordTypeLabel){
        Map<ID, Transaction__c> tranMap = new Map<ID, Transaction__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ' + generateRecordTypeStatement(recordTypeLabel);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and School__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += ' and Deleted__c = false ';
        query += ' Order By TransactionDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        tranMap = new Map<ID, Transaction__c>((List<Transaction__c>)db.query(query));
        return tranMap; 
    }

    public static Map<ID, Transaction__c> getTransactionMapWithTransactionID(Set<ID> transactionIDs, String recordTypeLabel){
        Map<ID, Transaction__c> tranMap = new Map<ID, Transaction__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ' + generateRecordTypeStatement(recordTypeLabel);
        query += ' and ID IN ' + DatabaseUtil.inSetStringBuilder(transactionIDs);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += ' and Deleted__c = false ';
        query += ' Order By TransactionDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        tranMap = new Map<ID, Transaction__c>((List<Transaction__c>)db.query(query));
        return tranMap; 
    }

    public static Map<ID, Transaction__c> getTransactionMapWithStudentID(Set<ID> accountIDs, String recordTypeLabel){
        Map<ID, Transaction__c> tranMap = new Map<ID, Transaction__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ' + generateRecordTypeStatement(recordTypeLabel);
        query += ' and Student__c IN ' + DatabaseUtil.inSetStringBuilder(accountIDs);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += ' and Deleted__c = false ';
        query += ' Order By TransactionDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        tranMap = new Map<ID, Transaction__c>((List<Transaction__c>)db.query(query));
        return tranMap; 
    }

    public static Map<ID, Transaction__c> getTransactionMapWithAgreementID(Set<ID> studentProgramIDs, String recordTypeLabel){
        Map<ID, Transaction__c> tranMap = new Map<ID, Transaction__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ' + generateRecordTypeStatement(recordTypeLabel);
        query += ' and Agreement__c IN ' + DatabaseUtil.inSetStringBuilder(studentProgramIDs);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += ' and Deleted__c = false ';
        query += ' Order By TransactionDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        tranMap = new Map<ID, Transaction__c>((List<Transaction__c>)db.query(query));
        return tranMap; 
    }

    public static Map<ID, List<Transaction__c>> getTransactionMapByAgreementWithAgreementID(Set<ID> studentProgramIDs, String recordTypeLabel){
        Map<ID, List<Transaction__c>> transByAgreement = new Map<ID, List<Transaction__c>>();
        Map<ID, Transaction__c> transMap = getTransactionMapWithAgreementID(studentProgramIDs, recordTypeLabel);

        for(Transaction__c tx : transMap.values()){
            if(!transByAgreement.containsKey(tx.Agreement__c)){
                transByAgreement.put(tx.Agreement__c, new List<Transaction__c>());
            }
            transByAgreement.get(tx.Agreement__c).add(tx);
        }
        return transByAgreement;    
    }
    
    public static Map<ID,Transaction__c> getTransactionMapWithSchoolID(Set<ID> schoolIDs, String recordTypeLabel){
        Map<ID, Transaction__c> tranMap = new Map<ID, Transaction__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ' + generateRecordTypeStatement(recordTypeLabel);
        query += ' and Agreement__r.Program__r.School__c IN ' + DatabaseUtil.inSetStringBuilder(schoolIDs);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        if(DatabaseUtil.filterByDate){
            Date fromDate = DatabaseUtil.fromDate;
            Date toDate = DatabaseUtil.toDate;    
            if(fromDate != null){
                query += ' and TransactionDate__c >= :fromDate ';
            }
            if(toDate != null){
                query += ' and TransactionDate__c <= :toDate ';
            }
        }
        if(DatabaseUtil.filterByConfirmFlag){
            if(DatabaseUtil.confirmFlag != null){
                query += ' and Confirmed__c = ' + DatabaseUtil.confirmFlag + ' ';
            }
        }
        query += ' and Deleted__c = false ';
        query += ' Order By TransactionDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        tranMap = new Map<ID, Transaction__c>((List<Transaction__c>)db.query(query));
        return tranMap; 
    }

    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getFieldNames() + ' FROM Transaction__c';
        return soql;
    }

    private static String getFieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'RecordTypeID, ';
        fieldNames += 'Amount__c, ';
        fieldNames += 'Student__c, ';
        fieldNames += 'Agreement__c, ';
        fieldNames += 'RelatedSchedule__c, ';
        fieldNames += 'TransactionDate__c, ';
        fieldNames += 'DisbursementPercentage__c, ';
        fieldNames += 'ScheduledAmount__c, ';
        fieldNames += 'Status__c, ';
        fieldNames += 'SpecialDisbursementType__c, ';
        fieldNames += 'SchoolSecurity__c, ';
        fieldNames += 'Confirmed__c, ';
        fieldNames += 'Student__r.name, ';
        fieldNames += 'Agreement__r.Program__c, ';
        fieldNames += 'Agreement__r.Program__r.ProgramName__c, ';
        fieldNames += 'Agreement__r.Status__c, ';
        fieldNames += 'Agreement__r.VemoContractNumber__c ';
        return fieldNames;
    }

    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }

    private static String generateRecordTypeStatement(String recordTypeLabel){
        ID recordTypeID = (String)GlobalUtil.getRecordTypeIDByLabelName('Transaction__c', recordTypeLabel);
        return 'RecordTypeID = \''+ String.valueOf(recordTypeID) + '\'';
    }
    
}