vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <defaultValue>16</defaultValue>
        <inlineHelpText>The default day of the month to perform this student&#39;s assessment.  This value copies to the Student Program level</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BeginDate__c</fullName>
        <inlineHelpText>The date this Income began.</inlineHelpText>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>The date this Income ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IncomePerMonth__c</fullName>
        <inlineHelpText>The student&#39;s monthly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>(DEPRECATED)Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Income Verification.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of Income Verification (Reported vs Estimated).</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has the student&#39;s Income been verified?</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>MinimumIncomePerMonth__c</fullName>
        <label>Minimum Income per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <inlineHelpText>The default day of the month to perform this contract assessment.</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinimumIncomePerMonth__c</fullName>
        <inlineHelpText>The monthly Earned Income threshold below which the student may qualify for a Deferment.</inlineHelpText>
        <label>Minimum Income per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ServicingStartDate__c</fullName>
        <inlineHelpText>Date that agreement starts servicing. Set by servicing team. Automated jobs look at this date to automatically check the servicing checkbox.</inlineHelpText>
        <label>Servicing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Servicing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag that indicates that an agreement is in servicing. This is set automatically when current date hits Servicing Start Date or can be set manually. Flag used for other jobs, reports, and the portal to determine if an agreement is in servicing status.</inlineHelpText>
        <label>Servicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExcludeFromBalance__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates that an amount due should not be included in the account statement summaries. Used primarily for reconciliation amounts that are pre-assessed for future months, but which should not actually show up on the statement/bill until that month arrives</inlineHelpText>
        <label>Exclude from Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncomeVerification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Income Verification Object used to derive Monthly Income during Assessment</description>
        <inlineHelpText>Income Verification Object used to derive Monthly Income during Assessment</inlineHelpText>
        <label>Income Verification</label>
        <referenceTo>IncomeVerification__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Amount_Due</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>For this month, is the Student Program in Grace, Deferment, or Payment?</inlineHelpText>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MonthlyStatusActivity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Monthly Status.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Monthly Status</relationshipLabel>
        <relationshipName>Student_Program_Monthly_Status</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonthlyStatusGUID__c</fullName>
        <externalId>true</externalId>
        <label>MonthlyStatusGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <formula>VALUE(
TEXT(Year__c) +
(CASE( TEXT(Month__c) ,
&quot;January&quot;, &quot;01&quot;,
&quot;February&quot;, &quot;02&quot;,
&quot;March&quot;, &quot;03&quot;,
&quot;April&quot;, &quot;04&quot;,
&quot;May&quot;, &quot;05&quot;,
&quot;June&quot;, &quot;06&quot;,
&quot;July&quot;, &quot;07&quot;,
&quot;August&quot;, &quot;08&quot;,
&quot;September&quot;, &quot;09&quot;,
&quot;October&quot;, &quot;10&quot;,
&quot;November&quot;, &quot;11&quot;,
&quot;December&quot;, &quot;12&quot;,
&quot;99&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/DebitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/IncomeVerificationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/IncomeVerificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Estimated</fullName>
    </customValue>
    <masterLabel>Income Verification Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Month.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Month</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/MonthlyStatusActivity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <masterLabel>Monthly Status Activity</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/AssessmentService.cls
public with sharing class AssessmentService {
    public static void assessContracts(Set<ID> agreementIDs) {
		System.debug('AssessmentService.accountAssessment()');
		Date systemDate = Date.today();//for testing
		//systemDate = Date.newInstance(2018, 4, 16);//for testing

		String systemYear = String.valueOf(systemDate.year());
		String systemMonth = monthToMonthStr(systemDate.month());
		System.debug('systemDate:'+systemDate);

		///////////////////////////////////////////Get Agreement Data///////////////////////////////////////////////
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreementIDs);
        System.debug('agreementMap:'+agreementMap);


		///////////////////////////////////////////Get Student & Program Data///////////////////////////////////////////////
        Set<ID> studentIDs = new Set<ID>();
		Set<ID> programIDs = new Set<ID>();
        for(StudentProgram__c agreement : agreementMap.values()){
            studentIDs.add(agreement.Student__c);
			programIDs.add(agreement.Program__c);
        }
        Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
        System.debug('studentMap:'+studentMap);
		Map<ID, Program__c> programMap = ProgramQueries.getProgramMapWithProgramID(programIDs);
		System.debug('programMap:'+programMap);


		///////////////////////////////////////////Get Income Data///////////////////////////////////////////////
        Map<ID, IncomeVerification__c> incVerMap = new Map<ID, IncomeVerification__c>([SELECT Id, MonthlyIncome__c, Student__c, BeginDate__c, EndDate__c, Verified__c, IncomePerMonth__c, Type__c
																						FROM IncomeVerification__c
																						WHERE BeginDate__c < :systemDate
																						AND Student__c IN :studentMap.keySet()
																						AND Status__c = 'Verified'
																						ORDER BY BeginDate__c asc]);

		Map<ID, List<IncomeVerification__c>> incomeByStudent = new Map<ID, List<IncomeVerification__c>>();
		for(IncomeVerification__c income : incVerMap.values()){
			if(!incomeByStudent.containsKey(income.Student__c)){
				incomeByStudent.put(income.Student__c, new List<IncomeVerification__c>());
			}
			incomeByStudent.get(income.Student__c).add(income);
		}
		System.debug('incomeByStudent:'+incomeByStudent);


		////////////////////////////////////////Monthly Tracker Data Structures//////////////////////////////////////
		List<StudentProgramMonthlyStatus__c> monthlyTrackerToAdd = new List<StudentProgramMonthlyStatus__c>();
		Map<Id,StudentProgramMonthlyStatus__c> existingMonthlyTrackers = new Map<ID, StudentProgramMonthlyStatus__c>([SELECT id, Agreement__c, Year__c, Month__c, Activity__c, MonthlyStatusGUID__c, Sequence__c
																													  FROM StudentProgramMonthlyStatus__c
																													  WHERE Agreement__c IN :agreementMap.keySet()
																													  ORDER BY Sequence__c ASC]);
		System.debug('existingMonthlyTrackers:'+existingMonthlyTrackers);

		Map<ID, List<StudentProgramMonthlyStatus__c>> monthlyTrackersByAgreement = new Map<ID, List<StudentProgramMonthlyStatus__c>>();
		for(StudentProgramMonthlyStatus__c tracker : existingMonthlyTrackers.values()){
			if(!monthlyTrackersByAgreement.containsKey(tracker.Agreement__c)){
				monthlyTrackersByAgreement.put(tracker.Agreement__c, new List<StudentProgramMonthlyStatus__c>());
			}
			monthlyTrackersByAgreement.get(tracker.Agreement__c).add(tracker);
		}
		System.debug('monthlyTrackersByAgreement:'+monthlyTrackersByAgreement);


		////////////////////////////////////////Amount Due Data Structures//////////////////////////////////////
		List<StudentProgramAmountDue__c> amountDueToAdd = new List<StudentProgramAmountDue__c>();
		Map<ID, StudentProgramAmountDue__c> existingAmountDue = new Map<ID, StudentProgramAmountDue__c>([SELECT id, Agreement__c, AMount__c, AssessmentDateTime__c, ExcludeFromBalance__c, Type__c, StudentProgramMonthlyStatus__c
																										 FROM StudentProgramAmountDue__c
																										 WHERE Agreement__c IN : agreementMap.keySet()
																										 AND Type__c = 'Monthly Amount'
																										 AND ExcludeFromBalance__c = false]);
		System.debug('existingAmountDue:'+existingAmountDue);
		Map<ID, List<StudentProgramAmountDue__c>> amountDueByAgreement = new Map<ID, List<StudentProgramAmountDue__c>>();
		for(StudentProgramAmountDue__c amountDue : existingAmountDue.values()){
			if(!amountDueByAgreement.containsKey(amountDue.Agreement__c)){
				amountDueByAgreement.put(amountDue.Agreement__c, new List<StudentProgramAmountDue__c>());
			}
			amountDueByAgreement.get(amountDue.Agreement__c).add(amountDue);
		}	

        //////////////////////////////Main Loop////////////////////////////////////////
        Map<ID, List<StudentProgramMonthlyStatus__c>> trackersMissingByAgreement = new Map<ID, List<StudentProgramMonthlyStatus__c>>();
		Integer assessUntilSeq = Integer.valueOf(String.valueOf(systemDate.year()) + monthIntToMonthSeq(systemDate.month()));
		List<Case> casesToAdd = new List<Case>();


		System.debug('....assessUntilSeq'+assessUntilSeq);
		for(StudentProgram__c agreement : agreementMap.values()){
			System.debug('....Main Loop on Agreement:'+agreement);
			Integer ssYear = agreement.ServicingStartDate__c.year();
			String ssYearStr = String.valueOf(ssYear);
			Integer ssMonth = agreement.ServicingStartDate__c.month();
			String ssMonthStr = monthIntToMonthSeq(ssMonth);
			System.debug('....ssMonthStr:'+ssMonthStr);
			Integer ssSequence = Integer.valueOf(ssYearStr + ssMonthStr);
			System.debug('....ssSequence:'+ssSequence);

			if(!trackersMissingByAgreement.containsKey(agreement.id)){
				trackersMissingByAgreement.put(agreement.id, new List<StudentProgramMonthlyStatus__c>());
			}
            Set<String> validStatus = new Set<String>{'Payment', 'Internship'};
            if((agreement.Servicing__c = true) && validStatus.contains(agreement.Status__c)){

                //Loop Through The Monthly Tracker for this agreement.  Assess any months that do not have Monthly Trackers from the date of servicing through the current month
				Integer i = 0;
				Integer expectedTracker = 0;
				Set<Integer> dontAssess = new Set<Integer>();
				if(monthlyTrackersByAgreement.containsKey(agreement.id)){
					for(StudentProgramMonthlyStatus__c monthlyTracker : monthlyTrackersByAgreement.get(agreement.id)){
						System.debug('....monthlyTracker:'+monthlyTracker);
						dontAssess.add((Integer)monthlyTracker.Sequence__c);
						if(i == 0){
							//monthly tracker should equal start of servicing
							System.debug('....servicingStartDate:'+agreement.ServicingStartDate__c);
							if(ssSequence == monthlyTracker.Sequence__c ){
								system.debug('....expected first tracker');
							} else if(ssSequence > monthlyTracker.Sequence__c ){
								system.debug('....first tracker is earlier than expected');
							} else if(ssSequence < monthlyTracker.Sequence__c ){
								system.debug('....first tracker is later than expected');
							}
						}
						i++;
					}					
				} else {
					//first tracker does not exist
					System.debug('....no monthly trackers exist for this agreement being assessed');
				}
				//Loop from servicing start to assessmentThrough					
				Integer assessingSeq = ssSequence;
				while(assessingSeq <= assessUntilSeq){
					System.debug('....assessingSeqBefore:'+assessingSeq);
			 		String guid = agreement.id + ':' + assessingSeq;					
					if(!dontAssess.contains(assessingSeq)){
						System.debug('....Assess this sequence:'+assessingSeq);

						DateTime assessmentDateTime;
						if(assessingSeq == assessUntilSeq){
							//current month
							assessmentDateTime = systemDate;
						} else {
							assessmentDateTime = Datetime.newInstance(Integer.valueOf(sequenceToYearStr(assessingSeq)),
																	  sequenceToMonthInt(assessingSeq), 
																	  (Integer)agreement.AssessmentDayOfMonth__c);
						}
						System.debug('....assessmentDateTime:'+assessmentDateTime);


						StudentProgramMonthlyStatus__c monthlyStatus = new StudentProgramMonthlyStatus__c(Agreement__c = agreement.id,
																											Activity__c = 'Payment',
																											Month__c = sequenceToMonthStr(assessingSeq),
																											Year__c = sequenceToYearStr(assessingSeq),
																											MonthlyStatusGUID__c = guid);

						//insert the monthly status upon successful income calculation



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
						IncomeVerification__c incomeToUse;
						//Loop through the income objects for the student based upon the following criteria
						//Begin Date <= first day of the month being assessed
						
						//If the assessor job is calculating amount due for May 2018, Income Verification objects with Begin Date of May 1, 2018 or earlier can be considered.
						//Any Income Verification object with a Begin Date of May 2, 2018 or later should not be considered.
						
						//There will often be more than one Income Verification object with a Begin Date earlier than the month in question. 
						//In these scenarios, the Income Verification object with a Begin Date closest to the assessment month should be used.
						Boolean incomeClear = true;
						try{
							for(IncomeVerification__c income : incomeByStudent.get(agreement.Student__c)){
								System.debug('....income:'+income);
								Date incomeConsiderationDate = Date.newInstance(assessmentDateTime.year(), assessmentDateTime.month(), 1);
								System.debug('....incomeConsiderationDate:'+incomeConsiderationDate);
								if(income.BeginDate__c <= incomeConsiderationDate){
									//can be considered
									System.debug('....can be considered based on date');
									if(incomeToUse == null){
										incomeToUse = income;	
										incomeClear = true;								
									} else {
										if(incomeToUse.BeginDate__c == income.BeginDate__c){
											System.debug('....both incomes have same date');
											if(incomeToUse.Type__c == 'Estimated' && income.Type__c == 'Reported'){
												System.debug('....use the reported');
												incomeToUse = income;
												incomeClear = true;
											} else if (incomeToUse.Type__c == income.Type__c){
												System.debug('....unclear based on same begin date/same type');
												incomeToUse = null;
												incomeClear = false;
											} else {
												System.debug('....do not change to the new income');
											}
										} else if(incomeToUse.BeginDate__c <= income.BeginDate__c){
											System.debug('....use the new income');
											incomeToUse = income;
											incomeClear = true;
										} else {
											System.debug('....do not change to this income');
										}
									}

								} else {
									//cannot be considered
									System.debug('....cannot be considered based on date');
								}
							}
							if(incomeToUse == null){
								System.debug('....unclear based on not finding anything valid for the assessment month');
								incomeClear = false;
							} else {
								System.debug('....clear income selected:'+incomeToUse);
								incomeClear = true;
							}

					
						} catch (Exception e){
							incomeToUse = null;
							incomeClear = false;

						}
						if(incomeClear){
							trackersMissingByAgreement.get(agreement.id).add(monthlyStatus);
							Decimal incomeAmount = incomeToUse.IncomePerMonth__c;

							if(incomeAmount>=programMap.get(agreement.Program__c).MinimumIncomePerMonth__c){

								//Assuming they are over the income threshold, add the monthly amount due
								Decimal amount = 0;
								try{
									amount = (incomeAmount * (agreement.IncomeSharePostCertification__c == null ? 0 :agreement.IncomeSharePostCertification__c)/100);							
								} catch (Exception e){
									System.debug('error calculating amount');
								}
								StudentProgramMonthlyStatus__c relatedMonthlyStatus= new StudentProgramMonthlyStatus__c(MonthlyStatusGUID__c = guid);

								amountDueToAdd.add(new StudentProgramAmountDue__c(Agreement__c = agreement.id,
																				Type__c = 'Monthly Amount',
																				AssessmentDateTime__c = assessmentDateTime,
																				Amount__c = amount,
																				ExcludeFromBalance__c = false,
																				StudentProgramMonthlyStatus__r = relatedMonthlyStatus,
																				IncomeShare__c = agreement.IncomeSharePostCertification__c,
																				IncomeVerification__c = incomeToUse.id));

							} else {
								//Open a case for servicing - not over minimum threshold
								casesToAdd.add(new Case(AccountID=agreement.Student__c,
														ContactID=studentMap.get(agreement.Student__c).PersonContactID,
														Status = 'New',
														Subject = 'Assessment Determined Income Under Minimum Threshold:'+assessingSeq,
														Type = 'Problem',
														Priority = 'Medium',
														Origin= 'System',
														Agreement__c = agreement.id));
							}
				
						} else {
							//enter a case - income not clear
							System.debug('....enter a case for servicing');		
							casesToAdd.add(new Case(AccountID=agreement.Student__c,
													ContactID=studentMap.get(agreement.Student__c).PersonContactID,
													Status = 'New',
													Subject = 'Assessment Determined Unclear Income for Assessment Month:'+assessingSeq,
													Type = 'Problem',
													Priority = 'Medium',
													Origin= 'System',
													Agreement__c = agreement.id));													
						}

					} else {
						System.debug('....Dont assess:'+assessingSeq);
					}	
					assessingSeq = determineNextSequence(assessingSeq);		
					System.debug('....assessingSeqAfter:'+assessingSeq);
				}         
            
                //////////////////////////////Update Assessment Date////////////////////////////////////////

                System.debug('agreement.AssessmentDate__c:'+agreement.AssessmentDate__c);
                System.debug('agreement.AssessmentDayOfMonth__c:'+agreement.AssessmentDayOfMonth__c);
                Boolean advanceAssessmentDate = false; 
                if(agreement.AssessmentDate__c <= systemDate || agreement.AssessmentDate__c == null) advanceAssessmentDate = true;
                if(advanceAssessmentDate){
                    System.debug('advanceAssessmentDate');
                    Integer nextAssessmentYear = systemDate.year();
                    Integer nextAssessmentMonth = systemDate.month();
                    if(agreement.AssessmentDayOfMonth__c < systemDate.day()){
                        //Advance the month
                        nextAssessmentYear = (systemDate.month() == 12) ? systemDate.year() + 1 : systemDate.year();
                        nextAssessmentMonth = (systemDate.month() == 12) ? 1 : systemDate.month() + 1;					
                    }

                    Integer nextAssessmentDay = Integer.valueOf(agreement.AssessmentDayOfMonth__c);
                    agreement.AssessmentDate__c = Date.newInstance(nextAssessmentYear, nextAssessmentMonth, nextAssessmentDay);		

                    System.debug('Set agreement.AssessmentDate__c:'+agreement.AssessmentDate__c);		
                }
                //////////////////////////////Update Due Date if the date is in the past AND the balance is zero////////////////////////////////////////
                Boolean advanceDueDate = false; 
                if((agreement.NextPaymentDueDate__c <= systemDate || agreement.NextPaymentDueDate__c == null) && 
                (agreement.NextPaymentDue__c <= 0)){
                    advanceDueDate = false; //for now
                }
                if(advanceDueDate){
                    Integer nextDueDateYear = systemDate.year();
                    Integer nextDueDateMonth = systemDate.month();
                    if(studentMap.get(agreement.Student__c).DueDayOfTheMonth__c < systemDate.day()){
                        //Advance the month
                        nextDueDateYear = (systemDate.month() == 12) ? systemDate.year() + 1 : systemDate.year();
                        nextDueDateMonth = (systemDate.month() == 12) ? 1 : systemDate.month() + 1;
                    }
                    Integer nextDueDateDay = Integer.valueOf(studentMap.get(agreement.Student__c).DueDayOfTheMonth__c);
                    agreement.NextPaymentDueDate__c = Date.newInstance(nextDueDateYear, nextDueDateMonth, nextDueDateDay);				
                }
                agreement.AssessContract__c = false;

            }


			//Add All Trackers
			monthlyTrackerToAdd.addAll(trackersMissingByAgreement.get(agreement.id));
        }



        if(monthlyTrackerToAdd.size()>0){
			System.debug('insert monthlyTrackers:'+monthlyTrackerToAdd);
            Database.insert(monthlyTrackerToAdd);
        }
        if(amountDueToAdd.size()>0){
			System.debug('insert amountDue:'+amountDueToAdd);
            Database.insert(amountDueToAdd);
        }
        if(casesToAdd.size()>0){
			System.debug('insert cases:'+casesToAdd);
            Database.insert(casesToAdd);
        }
		System.debug('update agreementMap');
        Database.update(agreementMap.values());
        LogService.writeLogs();        

    }

	private static String monthToMonthStr(Integer month){
		System.debug('....month:'+month);
		if(month == 1) return 'January';
		if(month == 2) return 'February';
		if(month == 3) return 'March';
		if(month == 4) return 'April';
		if(month == 5) return 'May';
		if(month == 6) return 'June';
		if(month == 7) return 'July';
		if(month == 8) return 'August';
		if(month == 9) return 'September';
		if(month == 10) return 'October';
		if(month == 11) return 'November';
		if(month == 12) return 'December';
		return '99';
	}
	private static String monthIntToMonthSeq(Integer monthSeq){
		System.debug('....monthSeq:'+monthSeq);
		return (monthSeq < 10 ? (String.valueOf('0' + String.valueOf(monthSeq))) : String.valueOf(monthSeq));
	}
	private static String sequenceToYearStr(Integer seq){
		System.debug('....seq:'+seq);
		String returnVal = String.valueOf(seq).subString(0,4);
		System.debug(returnVal);
		return returnVal;
	}
	private static String sequenceToMonthStr(Integer seq){
		System.debug('....seq:'+seq);
		System.debug(String.valueOf(seq).substring(4,6));
		String returnVal = monthToMonthStr(Integer.valueOf((String.valueOf(seq)).substring(4,6)));
		System.debug(returnVal);
		return returnVal;
	}
	private static Integer sequenceToMonthInt(Integer seq){
		System.debug('....seq:'+seq);
		System.debug(String.valueOf(seq).substring(4,6));
		Integer returnVal = (Integer.valueOf((String.valueOf(seq)).substring(4,6)));
		System.debug(returnVal);
		return returnVal;
	}
	private static Integer determineNextSequence(Integer currentSequence){
		String nextMonthStr;
		String nextYearStr;
		String currentSequenceStr = String.valueOf(currentSequence);
		String currentYearStr = currentSequenceStr.substring(0,4); 
		System.debug('....currentYearStr:'+currentYearStr);
		String currentMonthStr = currentSequenceStr.substring(4, 6);
		System.debug('....currentMonthStr:'+currentMonthStr);
		if(currentMonthStr == '12'){
			nextMonthStr = '01';
			nextYearStr = monthIntToMonthSeq(Integer.valueOf(currentYearStr)+1);
		}else{
			nextMonthStr = monthIntToMonthSeq(Integer.valueOf(currentMonthStr)+1);
			nextYearStr = currentYearStr;
		}
		System.debug('....nextMonthStr:'+nextMonthStr);
		System.debug('....nextYearStr:'+nextYearStr);
		return Integer.valueOf(nextYearStr + nextMonthStr);
	}
}