vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ConsentDateTimeStamp__c</fullName>
        <defaultValue>Now()</defaultValue>
        <inlineHelpText>The date at which the student consented to have their credit checked.</inlineHelpText>
        <label>Consent Date Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ConsentIPAddress__c</fullName>
        <inlineHelpText>The IP Address from which the student consented to have their credit checked.</inlineHelpText>
        <label>Consent IP Address</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReasonText__c</fullName>
        <inlineHelpText>If Status is Denied, this indicates one or more reason categories for the denial (formatted so it can be included in email communications).</inlineHelpText>
        <label>Credit Check Denied Reason Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CreditCheckDeniedReason__c</fullName>
        <inlineHelpText>If Status is Denied, this indicates one or more reason categories for the denial.</inlineHelpText>
        <label>Credit Check Denied Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditCheckDeniedReason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>JSONPayload__c</fullName>
        <inlineHelpText>The raw results of the credit check module in JSON format.</inlineHelpText>
        <label>JSON Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The result of the credit check (Under Review, Denied, Approved).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditCheckStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Credit Check.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/CreditCheckDeniedReason.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Educational Loan Default</fullName>
    </customValue>
    <customValue>
        <fullName>Bankruptcy</fullName>
    </customValue>
    <customValue>
        <fullName>Collection</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfied Suit or Judgement</fullName>
    </customValue>
    <customValue>
        <fullName>Major Derogatory Public Record</fullName>
    </customValue>
    <customValue>
        <fullName>Unpaid Tax Liens</fullName>
    </customValue>
    <customValue>
        <fullName>Business or Administrative Error</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Error</fullName>
    </customValue>
    <customValue>
        <fullName>Insufficient FICO score</fullName>
    </customValue>
    <masterLabel>Credit Check Denied Reason</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/CreditCheckStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <masterLabel>Credit Check Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/CreditCheckService.cls
/////////////////////////////////////////////////////////////////////////
// Class: CreditCheckService
// 
// Description: 
// 	Handles all CreditCheck DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-01-08   Greg Cook       Created                          
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class CreditCheckService {
	public static List<CreditCheck> getCreditCheckWithCreditCheckID(Set<ID> creditCheckIDs){
		System.debug('CreditCheckService.getCreditCheckWithCreditCheckID()');
		Map<ID, CreditCheck__c> ccMap = CreditCheckQueries.getCreditCheckMapWithCreditCheckID(creditCheckIDs);
		List<CreditCheck> ccList = new List<CreditCheck>();
		for(CreditCheck__c cc : ccMap.values()){
			CreditCheck ccCls = new CreditCheck(cc);
			ccList.add(ccCls);
		}
		return ccList;
	}

	public static List<CreditCheck> getCreditCheckWithStudentID(Set<ID> studentIDs){
		System.debug('CreditCheckService.getCreditCheckWithStudentID()');
		Map<ID, CreditCheck__c> ccMap = CreditCheckQueries.getCreditCheckMapWithStudentID(studentIDs);
		List<CreditCheck> ccList = new List<CreditCheck>();
		for(CreditCheck__c cc : ccMap.values()){
			CreditCheck ccCls = new CreditCheck(cc);
			ccList.add(ccCls);
		}
		return ccList;
	}

	public static List<CreditCheck> getCreditCheckWithAgreementID(Set<ID> agreementIDs){
		System.debug('CreditCheckService.getCreditCheckWithAgreementID()');
		Map<ID, CreditCheck__c> ccMap = CreditCheckQueries.getCreditCheckMapWithAgreementID(agreementIDs);
		List<CreditCheck> ccList = new List<CreditCheck>();
		for(CreditCheck__c cc : ccMap.values()){
			CreditCheck ccCls = new CreditCheck(cc);
			ccList.add(ccCls);
		}
		return ccList;
	}

	public static Set<ID> createCreditChecks(List<CreditCheck> ccs){
		System.debug('CreditCheckService.createCreditChecks()');
		List<CreditCheck__c> newCCs = new List<CreditCheck__c>();
		for(CreditCheck cc : ccs){
			CreditCheck__c newCC = ccToCC(cc);
			newCCs.add(newCC);
		}
		insert newCCs;
		Set<ID> ccIDs = new Set<ID>();
		for(CreditCheck__c cc : newCCs){
			ccIDs.add(cc.ID);
		}
		return ccIDs;
	}

	public static Set<ID> updateCreditChecks(List<CreditCheck> ccs){
		System.debug('CreditCheckService.updateCreditChecks()');
		List<CreditCheck__c> newCCs = new List<CreditCheck__c>();
		for(CreditCheck cc : ccs){
			CreditCheck__c newCC = ccToCC(cc);
			newCCs.add(newCC);
		}
		update newCCs;
		Set<ID> ccIDs = new Set<ID>();
		for(CreditCheck__c cc : newCCs){
			ccIDs.add(cc.ID);
		}
		return ccIDs;
	}

	public static Integer deleteCreditChecks(Set<ID> creditCheckIDs){
		System.debug('CreditCheckService.deleteCreditChecks()');
		Map<ID, CreditCheck__c> ccMap = CreditCheckQueries.getCreditCheckMapWithCreditCheckID(creditCheckIDs);
		Integer numToDelete = ccMap.size();
		delete ccMap.values();
		return numToDelete;
	}

	public static CreditCheck__c ccToCC(CreditCheck cc){
		CreditCheck__c ccObj = new CreditCheck__c();
		if(cc.studentID != null) ccObj.Student__c = cc.studentID;
		if(cc.consentDateTimeStamp != null) ccObj.ConsentDateTimeStamp__c = cc.consentDateTimeStamp;
		if(cc.consentIPAddress != null) ccObj.ConsentIPAddress__c = cc.consentIPAddress;
		if(cc.creditCheckID != null) ccObj.ID = cc.creditCheckID;
		if(cc.jsonPayload != null) ccObj.JSONPayload__c = cc.jsonPayload;
		if(cc.status != null) ccObj.Status__c = cc.status;		
		if(cc.creditCheckDeniedReasonText != null) ccObj.CreditCheckDeniedReasonText__c = cc.creditCheckDeniedReasonText;
		if(cc.creditCheckDeniedReason != null) ccObj.CreditCheckDeniedReason__c = cc.creditCheckDeniedReason;
		return ccObj;
	}

	public class CreditCheck{
		public String studentID {get;set;}
		public DateTime consentDateTimeStamp {get;set;}
		public String consentIPAddress {get;set;}
		public String creditCheckID {get;set;}
		public String jsonPayload {get;set;}
		public String status {get;set;}
		public String creditCheckDeniedReasonText {get;set;}
		public String creditCheckDeniedReason {get;set;}

		public CreditCheck(){}

		public CreditCheck(boolean testValues){
			if(testValues){
				this.studentID = 'testStudentID';
				this.consentDateTimeStamp = DateTime.Now();
				this.consentIPAddress = '1.1.1.1';
				this.jsonPayload = 'test';

			}
		}

		public CreditCheck(CreditCheck__c cc){
			this.studentID = cc.Student__r.GUID__c;
			this.consentIPAddress = cc.ConsentIPAddress__c;
			this.consentDateTimeStamp = cc.ConsentDateTimeStamp__c;
			this.creditCheckID = cc.ID;
			this.jsonPayload = cc.JSONPayload__c;
			this.status = cc.Status__c;
			this.creditCheckDeniedReasonText = cc.CreditCheckDeniedReasonText__c;
			this.creditCheckDeniedReason = cc.CreditCheckDeniedReason__c;
		}
	}
}