vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>UnpaidFees__c</fullName>
        <label>Unpaid Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>Sum of the Payment Allocations for this Payment Instruction.</inlineHelpText>
        <label>Amount Allocated</label>
        <summarizedField>PaymentAllocation__c.AmountAllocated__c</summarizedField>
        <summaryForeignKey>PaymentAllocation__c.PaymentInstruction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AmountPosted__c</fullName>
        <inlineHelpText>The Posted amount of the Payment Instruction.</inlineHelpText>
        <label>Amount Posted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DatePosted__c</fullName>
        <inlineHelpText>The date the Payment Instruction posted.</inlineHelpText>
        <label>Date Posted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date of the Payment Instruction.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FullyAllocated__c</fullName>
        <formula>IF( AmountAllocated__c =  Amount__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Checked if Amount Allocated is equal to Amount.</inlineHelpText>
        <label>Fully Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RemainingAllocation__c</fullName>
        <formula>Amount__c -  AmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount minus Amount Allocated.</inlineHelpText>
        <label>Remaining Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Scheduled_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransactionDirection__c</fullName>
        <inlineHelpText>Inbound (from Student to Vemo) or Outbound (from Vemo to Student).</inlineHelpText>
        <label>Transaction Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionDirection</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Optional description - helpful in case Customer has multiple accounts at one bank.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/PaymentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionDirection.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <masterLabel>Transaction Direction</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/PaymentInstructionQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentInstructionQueries
// 
// Description: 
// 	
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-18   Jared Hagemann  Created      
// 2017-05-18	Greg Cook 		Changed Student__c to Customer__c                           
/////////////////////////////////////////////////////////////////////////
public class PaymentInstructionQueries {
	public static Map<String, Object> filterCriteria = new Map<String, Object>();
	public static void clearFilterCriteria(){
		filterCriteria.clear();
	}

	public static Map<ID, PaymentInstruction__c> getPaymentInstructionMap(){
		Map<ID, PaymentInstruction__c> paymentInstructionMap = new Map<ID, PaymentInstruction__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Id != null';
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' order by CreatedDate asc';
		query += ' '+ generateLIMITStatement();

		DatabaseUtil db = new DatabaseUtil();
		paymentInstructionMap = new Map<ID, PaymentInstruction__c>((List<PaymentInstruction__c>)db.query(query));
		return paymentInstructionMap;		
	}

	public static Map<ID, PaymentInstruction__c> getPaymentInstructionMapWithPaymentInstructionID(Set<Id> paymentInstructionIds){
		Map<ID, PaymentInstruction__c> paymentInstructionMap = new Map<ID, PaymentInstruction__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(paymentInstructionIds);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' order by CreatedDate asc';
		query += ' '+ generateLIMITStatement();

		DatabaseUtil db = new DatabaseUtil();
		paymentInstructionMap = new Map<ID, PaymentInstruction__c>((List<PaymentInstruction__c>)db.query(query));
		return paymentInstructionMap;		
	}

	public static Map<ID, PaymentInstruction__c> getPaymentInstructionMapWithPaymentStudentID(Set<Id> studentIds){
		Map<ID, PaymentInstruction__c> paymentInstructionMap = new Map<ID, PaymentInstruction__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Student__c IN ' + DatabaseUtil.inSetStringBuilder(studentIds);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' order by CreatedDate asc';
		query += ' '+ generateLIMITStatement();

		DatabaseUtil db = new DatabaseUtil();
		paymentInstructionMap = new Map<ID, PaymentInstruction__c>((List<PaymentInstruction__c>)db.query(query));
		return paymentInstructionMap;		
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
	
	private static String buildFilterString(){
		String filterStr = '';
		if(filterCriteria.size()>0){
			for(String filter : filterCriteria.keyset()){
				filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) + 	'\' ');
			}			
		}
		return filterStr;
	}

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getFieldNames() + ' FROM PaymentInstruction__c';
		return soql;
	}

	private static String getFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Name, ';
		fieldNames += 'CreatedDate, ';
		fieldNames += 'Amount__c, ';
		fieldNames += 'AmountAllocated__c, ';
		fieldNames += 'FullyAllocated__c, ';
		fieldNames += 'RemainingAllocation__c, ';
		fieldNames += 'Date__c, ';
		fieldNames += 'Description__c, ';
		fieldNames += 'PaymentMethod__c, ';
		fieldNames += 'Student__c, ';
		fieldNames += 'Student__r.UnpaidFees__c, ';
		fieldNames += 'DatePosted__c, ';
		fieldNames += 'AmountPosted__c, ';
		fieldNames += 'TransactionDirection__c, ';
		fieldNames += 'Status__c ';
		return fieldNames;
	}
}