vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AgeOfMajorityCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age of Majority Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AgeOfMajorityRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age of Majority Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AgreementTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement Template</label>
        <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
        <relationshipLabel>Programs (Agreement Template)</relationshipLabel>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AllowedSpecialDisbursementTypes__c</fullName>
        <label>Allowed Special Disbursement Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASDAttachmentCleanURL__c</fullName>
        <formula>IF(!ISBLANK( ASDAttachmentID__c  ), $Setup.GlobalSettings__c.AttachmentDownloadPrefix__c &amp;  ASDAttachmentID__c  , &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASD Attachment Clean URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASDAttachmentID__c</fullName>
        <label>ASD Attachment ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttendanceDateRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, Attendance Dates will be available during the origination process</description>
        <inlineHelpText>If checked, Attendance Dates will be available during the origination process</inlineHelpText>
        <label>Attendance Date Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AutomaticallyConfirmTransactions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatically Confirm Transactions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreditApprovalScore__c</fullName>
        <label>Credit Approval Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreditCheckRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this box is checked, a credit check is required during the registration for this program</description>
        <inlineHelpText>If this box is checked, a credit check is required during the registration for this program</inlineHelpText>
        <label>Credit Check Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreditModel__c</fullName>
        <label>Credit Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Configured in Program</fullName>
                </value>
                <value>
                    <fullName>Detailed Evaluation</fullName>
                    <isActive>false</isActive>
                    <label>Detailed Evaluation</label>
                </value>
                <value>
                    <fullName>Score Based</fullName>
                    <isActive>false</isActive>
                    <label>Score Based</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CumulativeIncomeShareCap__c</fullName>
        <label>Cumulative Income Share Cap</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DefaultRules__c</fullName>
        <description>How many months of what kind of (in)activity are required to define an account as being in default?</description>
        <inlineHelpText>How many months of what kind of (in)activity are required to define an account as being in default?</inlineHelpText>
        <label>Default Rules</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DefermentTypeRules__c</fullName>
        <description>For each deferment type: is payment term extended? is there a duration limit?</description>
        <inlineHelpText>For each deferment type: is payment term extended? is there a duration limit?</inlineHelpText>
        <label>Deferment Type Rules</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisclosureTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Disclosure Template</label>
        <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
        <relationshipLabel>Programs (Disclosure Template)</relationshipLabel>
        <relationshipName>Programs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnrollmentBeginDate__c</fullName>
        <label>Enrollment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentEndDate__c</fullName>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentType__c</fullName>
        <description>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</description>
        <inlineHelpText>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</inlineHelpText>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Invite Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FeeRules__c</fullName>
        <description>list of fee types and amounts that agreement is subject to</description>
        <inlineHelpText>list of fee types and amounts that agreement is subject to</inlineHelpText>
        <label>Fee Rules</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GracePeriodMonths__c</fullName>
        <label>Grace Period (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GradeLevelCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GradeLevelDescription__c</fullName>
        <label>Grade Level Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GradeLevelRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IncomeThreshold__c</fullName>
        <description>minimum income required to make payment</description>
        <inlineHelpText>minimum income required to make payment</inlineHelpText>
        <label>Income Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InstructionText__c</fullName>
        <label>Instruction Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>QuizAttemptsBeforeLock__c</fullName>
        <label>Quiz Attempts Before Lock</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuizLinkID__c</fullName>
        <description>The ID used for this program&#39;s financial fitness quiz</description>
        <inlineHelpText>The ID used for this program&#39;s financial fitness quiz</inlineHelpText>
        <label>Quiz Link ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuizLinkURL__c</fullName>
        <description>The link used by this program for its financial fitness quiz</description>
        <inlineHelpText>The link used by this program for its financial fitness quiz</inlineHelpText>
        <label>Quiz Link URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>QuizPostID__c</fullName>
        <label>Quiz Post ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuizResultID__c</fullName>
        <label>Quiz Result ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegistrationBeginDate__c</fullName>
        <label>Registration Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegistrationEndDate__c</fullName>
        <label>Registration End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ResidencyCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residency Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResidencyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residency Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudyCollected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>School Program of Study Collected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>School Program of Study Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/DisbursementSpecialTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/ProgramStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/ProgramService.cls
/////////////////////////////////////////////////////////////////////////
// Class: ProgramService
// 
// Description: 
//  Handles all Program DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-17   Greg Cook       Created                          
// 2016-12-18   Greg Cook       Added Input/Output classes, skeleton methods, implemented getProgramV1
// 2016-12-23   Greg Cook       Removed ProgramInput/Ouput inner classes and replaced with Program inner class, made service layer independent
// 2016-12-24   Greg Cook       getProgramsWithSchoolID
/////////////////////////////////////////////////////////////////////////
public with sharing class ProgramService {
    
    public static List<Program> getProgramsWithProgramID(Set<ID> programIDs){
        System.debug('ProgramService.getProgramsWithProgramID');
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMapWithProgramID(programIDs);
        List<Program> programs = new List<Program>();
        for(Program__c prg : programMap.values()){
            programs.add(new Program(prg));
        }
        return programs;
    }

    public static List<Program> getProgramsWithSchoolID(Set<ID> schoolIDs){
        System.debug('ProgramService.getProgramsWithProgramID');
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMapWithSchoolID(schoolIDs);
        List<Program> programs = new List<Program>();
        for(Program__c prg : programMap.values()){
            programs.add(new Program(prg));
        }
        return programs;
    }

    
    public static Set<Id> createProgramV1(List<Program> programs){
        System.debug('ProgramService.createProgramV1');
        List<Program__c> newPrograms = new List<Program__c>();
        For(Program prg : programs){
            Program__c newPrg = programToProgram(prg);
            newPrograms.add(newPrg);
        }
        insert newPrograms;
        Set<Id> prgIDs = new Set<Id>();
        for(Program__c prg : newPrograms){
            prgIDs.add(prg.ID);
        }
        return prgIDs;
    }
    
    
    public static Set<Id> updateProgramV1(List<Program> programs){
        System.debug('ProgramService.updateProgramV1');
        List<Program__c> newPrograms = new List<Program__c>();
        For(Program prg : programs){
            prg.schoolID = null;
            Program__c newPrg = programToProgram(prg);
            newPrograms.add(newPrg);
        }
        update newPrograms;
        Set<Id> prgIDs = new Set<Id>();
        for(Program__c prg : newPrograms){
            prgIDs.add(prg.ID);
        }
        return prgIDs;
    }   
    
    public static Integer deleteProgramV1(Set<ID> programIDs){
        System.debug('ProgramService.deleteProgramV1');
        Map<ID, Program__c> prgMap = ProgramQueries.getProgramMapWithProgramID(programIDs);
        Integer numToDelete = programIDs.size();
        delete prgMap.values();
        return numToDelete;
    }
    
    public static Map<ID, Boolean> evaluateProgramEligibilityForStudents(ID programID, Set<ID> studentIDs){
        System.debug('ProgramService.evaluateProgramEligibilityForStudents');
        Map<ID, Boolean> returnMap = ProgramEligibilityQueries.evaluateEligibility(programID, studentIDs);
        return returnMap;
    }

    public static Boolean evaluateProgramEligibilityWithCriteria(ID programID, String residency,
                                                 String enrollmentStatus, String gradeLevel,
                                                 ID schoolProgramOfStudyID, String state, Integer studentAge){
        System.debug('ProgramService.evaluateProgramEligibilityWithCriteria');
        Boolean returnVal = ProgramEligibilityQueries.evaluateEligibilityWithCriteria(programID,
                                                                                      residency,
                                                                                      enrollmentStatus,
                                                                                      gradeLevel,
                                                                                      schoolProgramOfStudyID,
                                                                                      state,
                                                                                      studentAge);
        return returnVal;
    }

    public static Program__c programToProgram(Program prg){
        Program__c newPrg = new Program__c();

//      if(prg.guid != null) newPrg.GUID__c = prg.guid;





        if(prg.programID != null) newPrg.ID = prg.programID;

        if(String.isNotEmpty(prg.ageOfMajorityCollected)){
            newPrg.AgeOfMajorityCollected__c = prg.ageOfMajorityCollected == 'true' ?  true : false;
        }
        if(String.isNotEmpty(prg.ageOfMajorityRequired)){
            newPrg.AgeOfMajorityRequired__c = prg.ageOfMajorityRequired == 'true' ?  true : false;
        }
        if(prg.agreementTemplateID != null) newPrg.AgreementTemplate__c = prg.agreementTemplateID;
        if(prg.asdAttachmentID != null) newPrg.ASDAttachmentID__c = prg.asdAttachmentID;
        if(String.isNotEmpty(prg.automaticallyConfirmTransactions)){
            newPrg.AutomaticallyConfirmTransactions__c = prg.automaticallyConfirmTransactions == 'true' ?  true : false;
        }
        if(prg.cumulativeIncomeShareCap != null) newPrg.CumulativeIncomeShareCap__c = prg.cumulativeIncomeShareCap;     
        if(prg.defaultRules != null) newPrg.DefaultRules__C = prg.defaultRules;
        if(prg.defermentTypeRules != null) newPrg.DefermentTypeRules__c = prg.defermentTypeRules;
        if(prg.disclosureTemplateID != null) newPrg.DisclosureTemplate__c = prg.disclosureTemplateID;       
        if(prg.enrollmentBeginDate != null) newPrg.EnrollmentBeginDate__c = prg.enrollmentBeginDate;
        if(prg.enrollmentEndDate != null) newPrg.EnrollmentEndDate__c = prg.enrollmentEndDate;
        if(String.isNotEmpty(prg.enrollmentStatusCollected)){
            newPrg.EnrollmentStatusCollected__c = prg.enrollmentStatusCollected == 'true' ?  true : false;
        }
        if(String.isNotEmpty(prg.enrollmentStatusRequired)){
            newPrg.EnrollmentStatusRequired__c = prg.enrollmentStatusRequired == 'true' ?  true : false;
        }
        if(prg.enrollmentType != null) newPrg.EnrollmentType__c = prg.enrollmentType;
        if(prg.feeRules != null) newPrg.FeeRules__c = prg.feeRules;
        if(prg.gracePeriodMonths != null) newPrg.GracePeriodMonths__c = prg.gracePeriodMonths;

        if(String.isNotEmpty(prg.gradeLevelCollected)){
            newPrg.GradeLevelCollected__c = prg.gradeLevelCollected == 'true' ?  true : false;
        }
        if(prg.gradeLevelDescription != null) newPrg.GradeLevelDescription__c = prg.gradeLevelDescription;
        if(String.isNotEmpty(prg.gradeLevelRequired)){
            newPrg.GradeLevelRequired__c = prg.gradeLevelRequired == 'true' ?  true : false;
        }
        if(prg.incomeThreshold != null) newPrg.IncomeThreshold__c = prg.incomeThreshold;
        if(prg.instructionText != null) newPrg.InstructionText__c = prg.instructionText;
        if(prg.quizLinkURL != null) newPrg.QuizLinkURL__c = prg.quizLinkURL;
        if(prg.quizLinkID != null) newPrg.QuizLinkID__c = prg.quizLinkID;
        if(prg.quizAttemptsBeforeLock != null) newPrg.QuizAttemptsBeforeLock__c = prg.quizAttemptsBeforeLock;
        if(prg.quizPostID != null) newPrg.QuizPostID__c = prg.quizPostID;
        if(prg.quizResultID != null) newPrg.QuizResultID__c = prg.quizResultID;
        if(prg.programName != null) newPrg.ProgramName__c = prg.programName;
        if(prg.programStatus != null) newPrg.ProgramStatus__c = prg.programStatus;
        if(prg.registrationBeginDate != null) newPrg.RegistrationBeginDate__c = prg.registrationBeginDate;
        if(prg.registrationEndDate != null) newPrg.RegistrationEndDate__c = prg.registrationEndDate;
        if(String.isNotEmpty(prg.residencyCollected)){
            newPrg.ResidencyCollected__c = prg.residencyCollected == 'true' ?  true : false;
        }
        if(String.isNotEmpty(prg.residencyRequired)){
            newPrg.ResidencyRequired__c = prg.residencyRequired == 'true' ?  true : false;
        }
        if(prg.schoolID != null) newPrg.School__c = prg.schoolID;
        if(String.isNotEmpty(prg.schoolProgramOfStudyCollected)){
            newPrg.SchoolProgramOfStudyCollected__c = prg.schoolProgramOfStudyCollected == 'true' ?  true : false;
        }
        if(String.isNotEmpty(prg.schoolProgramOfStudyRequired)){
            newPrg.SchoolProgramOfStudyRequired__c = prg.schoolProgramOfStudyRequired == 'true' ?  true : false;
        }
        return newPrg;
    }

    public class Program{
        public String programID {get;set;}
//      public String guid {get;set;}

        public String ageOfMajorityCollected {get;set;}
        public String ageOfMajorityRequired {get;set;}
        public String agreementTemplateID {get;set;}
        public String allowedSpecialDisbursementTypes {get;set;}
        public String asdAttachmentCleanURL {get;set;}
        public String asdAttachmentID {get;set;}
        public String attendanceDateRequired {get;set;}
        public String automaticallyConfirmTransactions {get;set;}
        public String creditCheckRequired {get;set;}
        public String creditModel {get;set;}
        public Decimal creditApprovalScore {get;set;}
        public Decimal cumulativeIncomeShareCap {get;set;}
        public String defaultRules {get;set;}
        public String defermentTypeRules {get;set;}
        public String disclosureTemplateID {get;set;}
        public Date enrollmentBeginDate {get;set;}
        public Date enrollmentEndDate {get;set;}
        public String enrollmentStatusCollected {get;set;}
        public String enrollmentStatusRequired {get;set;}
        public String enrollmentType {get;set;}
        public String feeRules {get;set;}
        public Decimal gracePeriodMonths {get;set;}
        public String gradeLevelCollected {get;set;}
        public String gradeLevelDescription {get;set;}
        public String gradeLevelRequired {get;set;}
        public String immediatePayment {get;set;}
        public Decimal incomeThreshold {get;set;}
        public String instructionText {get;set;}
//      public String postAgreementFlow {get;set;}
        public Decimal minimumIncomePerMonth {get;set;}
        public String quizLinkURL {get;set;}
        public String quizLinkID {get;set;}
        public Integer quizAttemptsBeforeLock {get;set;}
        public String quizPostID {get;set;}
        public String quizResultID {get;set;}
        public String programName {get;set;}
        public String programNotes {get;set;}
        public String programStatus {get;set;}
        public String recordLabel {get;set;}
        public String recordLink {get;set;}
        public Date registrationBeginDate {get;set;}
        public Date registrationEndDate {get;set;}
        public String residencyCollected {get;set;}
        public String residencyRequired {get;set;}
        public Integer rightToCancelDays {get;set;}
        public String schoolID {get;set;}
        public String schoolProgramOfStudyCollected {get;set;}
        public String schoolProgramOfStudyRequired {get;set;}
//      public String stepText {get;set;}
        
        public String schoolCampusServiceName {get;set;}
        public String schoolCampusServiceEmail {get;set;}
        public String schoolCampusServiceMobile {get;set;}
        public String schoolCampusServiceAvailability {get;set;}
        public Decimal totalDefermentMonths {get;set;}

        public Program(){

        }

        public Program(Boolean testValues){
            if(testValues){
                this.programName = 'testProgramName';
                this.programStatus = 'Open'; //Planned, Closed, Cancelled
                DateTime dT = System.Now();
                this.enrollmentEndDate = Date.newinstance(dT.year(), dT.month(), dT.day());
            }
        }

        public Program(Program__c prog){
//          this.guid = prog.GUID__c;

            this.programID = prog.Id;   
            this.ageOfMajorityCollected = String.valueOf(prog.AgeOfMajorityCollected__c);
            this.ageOfMajorityRequired = String.valueOf(prog.AgeOfMajorityRequired__c);
            this.agreementTemplateID = prog.AgreementTemplate__c;
            this.allowedSpecialDisbursementTypes = prog.AllowedSpecialDisbursementTypes__c;
            this.asdAttachmentCleanURL = prog.ASDAttachmentCleanURL__c;
            this.asdAttachmentID = prog.ASDAttachmentID__c;
            this.attendanceDateRequired = String.valueOf(prog.AttendanceDateRequired__c);
            this.automaticallyConfirmTransactions = String.valueOf(prog.AutomaticallyConfirmTransactions__c);
            this.creditCheckRequired = String.valueOf(prog.CreditCheckRequired__c);
            this.creditModel = prog.creditModel__c;
            this.creditApprovalScore = prog.creditApprovalScore__c;
            this.cumulativeIncomeShareCap = prog.CumulativeIncomeShareCap__c;
            this.defaultRules = prog.DefaultRules__c;
            this.defermentTypeRules = prog.DefermentTypeRules__c;
            this.disclosureTemplateID = prog.DisclosureTemplate__c;
            this.enrollmentBeginDate = prog.EnrollmentBeginDate__c;
            this.enrollmentEndDate = prog.EnrollmentEndDate__c;
            this.enrollmentStatusCollected = String.valueOf(prog.EnrollmentStatusCollected__c);
            this.enrollmentStatusRequired = String.valueOf(prog.EnrollmentStatusRequired__c);
            this.enrollmentType = prog.EnrollmentType__c;
            this.feeRules = prog.FeeRules__c;
            this.gracePeriodMonths = prog.GracePeriodMonths__c;
            this.gradeLevelCollected = String.valueOf(prog.GradeLevelCollected__c);
            this.gradeLevelDescription = prog.GradeLevelDescription__c;
            this.gradeLevelRequired = String.valueOf(prog.GradeLevelRequired__c);
            this.immediatePayment = String.valueOf(prog.ImmediatePayment__c);
            this.incomeThreshold = prog.IncomeThreshold__c;
            this.instructionText = prog.InstructionText__c;
            this.minimumIncomePerMonth = prog.minimumIncomePerMonth__c; 
            this.quizAttemptsBeforeLock = (Integer) prog.QuizAttemptsBeforeLock__c;
            this.quizLinkID = prog.QuizLinkID__c;
            this.quizLinkURL = prog.QuizLinkURL__c;
            this.quizPostID = prog.QuizPostID__c;
            this.quizResultID = prog.QuizResultID__c;
            this.programName = prog.ProgramName__c; 
            this.programNotes = prog.ProgramNotes__c;    
            this.programStatus = prog.ProgramStatus__c;
//          this.postAgreementFlow = prog.PostAgreementFlow__c;
            this.recordLabel = prog.RecordLabel__c;
            this.recordLink = prog.RecordLink__c;
            this.registrationBeginDate = prog.RegistrationBeginDate__c;
            this.registrationEndDate = prog.RegistrationEndDate__c;
            this.residencyCollected = String.valueOf(prog.ResidencyCollected__c);
            this.residencyRequired = String.valueOf(prog.ResidencyRequired__c);
            this.rightToCancelDays = (Integer) prog.RightToCancelDays__c;
            this.schoolID = prog.School__c;
            this.schoolProgramOfStudyCollected = String.valueOf(prog.SchoolProgramOfStudyCollected__c);
            this.schoolProgramOfStudyRequired = String.valueOf(prog.SchoolProgramOfStudyRequired__c);
            
//          this.stepText = prog.StepText__c;
            
            this.schoolCampusServiceName = prog.School__r.CampusServiceName__c;
            this.schoolCampusServiceEmail = prog.School__r.CampusServiceEmail__c;
            this.schoolCampusServiceMobile = prog.School__r.CampusServiceMobile__c;
            this.schoolCampusServiceAvailability = prog.School__r.CampusServiceAvailability__c;
            this.totalDefermentMonths = prog.totalDefermentMonths__c;  
            
            
        
        }
    }
}