vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>VemoAccountNumber__c</fullName>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Automatially generated number identifying the Student/Account. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Account Number</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DefermentMonthsAllowed__c</fullName>
        <inlineHelpText>The number of months the Payment Term may be extended while student is in Deferment. Not all Deferments qualify for the extention of the Payment Term (see Qualifying Circumstance table in Agreement PDF).</inlineHelpText>
        <label>Deferment Months Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DefermentMonthsRemaining__c</fullName>
        <inlineHelpText>The number of Deferment Months Allowed that remain.</inlineHelpText>
        <label>(Deprecate) Deferment Months Remaining</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DefermentMonthsUsed__c</fullName>
        <inlineHelpText>The number of months the Payment Term has already been extended because of one or more Deferments that qualify for the extention of the Payment Term.</inlineHelpText>
        <label>Deferment Months Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FundingAmountPostCertification__c</fullName>
        <inlineHelpText>(Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Funding Amount (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GraceMonthsAllowed__c</fullName>
        <inlineHelpText>The number of months given to student as a Grace Period during which they will not owe any payments.</inlineHelpText>
        <label>Grace Months Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GraceMonthsRemaining__c</fullName>
        <inlineHelpText>The number of months of Grace Period that remain. Student will not owe any payments during the Grace Period.</inlineHelpText>
        <label>(Deprecate) Grace Months Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GraceMonthsUsed__c</fullName>
        <inlineHelpText>The number of months of Grace Period that has already been used. Student will not owe any payments during the Grace Period.</inlineHelpText>
        <label>Grace Months Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IncomeSharePostCertification__c</fullName>
        <inlineHelpText>The percent of student&#39;s total earned income that they will share each month. (Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Income Share (Post-Certification)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MinimumIncomePerMonth__c</fullName>
        <inlineHelpText>The monthly Earned Income threshold below which the student may qualify for a Deferment.</inlineHelpText>
        <label>Minimum Income per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentCapPostCertification__c</fullName>
        <inlineHelpText>The maximum amount student will pay over the payment term. (Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Payment Cap (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentTermPostCertification__c</fullName>
        <inlineHelpText>The maximum number of months during which student will share their income. (Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Payment Term (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of Program related to this Student Program.</inlineHelpText>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RemainingTerm__c</fullName>
        <inlineHelpText>The number of months remaining in the Payment Term.  The Payment Term is the period of time during which student will share their income.</inlineHelpText>
        <label>(Deprecate) Remaining Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SchoolName__c</fullName>
        <formula>Program__r.School__r.InstitutionShortName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of School (Institution Short Name) related to this Student Program.</inlineHelpText>
        <label>School Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServicingStartDate__c</fullName>
        <inlineHelpText>Date that agreement starts servicing. Set by servicing team. Automated jobs look at this date to automatically check the servicing checkbox.</inlineHelpText>
        <label>Servicing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>VemoContractNumber__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <inlineHelpText>Automatically generated number identifying the Contract/Student Program. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Contract Number</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RemainingAllocation__c</fullName>
        <formula>Amount__c - AmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/AnnualStatementCTRL.cls
public with sharing class AnnualStatementCTRL{

    public Id studentId {get;set;}
    
    public account getAccount()
    {
        //Map<ID, Account> acctMap = AccountQueries.getStudentMapWithStudentID(new set<id>{studentId});
        return [select name, VemoAccountNumber__c,personMailingStreet, personMailingCity, personMailingCountry, personMailingPostalCode, personMailingState from account where id =: studentId limit 1];
    }
    public List<StudentProgram__c> getstudentprograms()
    {
        List<StudentProgram__c> stProgramList;
        stProgramList = [select ProgramName__c,VemoContractNumber__c, SchoolName__c, FundingAmountPostCertification__c, 
                        IncomeSharePostCertification__c, PaymentTermPostCertification__c, PaymentCapPostCertification__c, 
                        ServicingStartDate__c,RemainingTerm__c,MinimumIncomePerMonth__c, GraceMonthsAllowed__c, 
                        GraceMonthsRemaining__c, GraceMonthsUsed__c,DefermentMonthsAllowed__c,DefermentMonthsRemaining__c,
                        DefermentMonthsUsed__c, (select Amount__c,AssessmentDateTime__c,RemainingAllocation__c from Student_Program_Debits__r order by AssessmentDateTime__c desc) from StudentProgram__c 
                        where status__c !='Cancelled' and student__c =: studentId];
        return stProgramList;
    }
}