vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <inlineHelpText>This field is used to share this student with the School Account with a matching School Security Field. For example a Student with a School Security of Purdue will be shared with the School Account that has a value of &quot;Purdue&quot; in its School Security field</inlineHelpText>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of Program related to this Student Program.</inlineHelpText>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>VemoContractNumber__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <inlineHelpText>Automatically generated number identifying the Contract/Student Program. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Contract Number</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Disbursement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount to be disbursed or refunded.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if Disbursement has been confirmed.</inlineHelpText>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this disbursement is deleted and will be purged by an hourly job.  Necessary for school admins to be able to delete records</description>
        <inlineHelpText>If this flag is checked, this disbursement is deleted and will be purged by an hourly job</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DisbursementPercentage__c</fullName>
        <label>Disbursement Percentage</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Agreement__r.Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Field used in email communications.</inlineHelpText>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Disbursement was created by a Disbursement Schedule, indicates the related Disbursement Schedule.</inlineHelpText>
        <label>Related Schedule</label>
        <referenceTo>TransactionSchedule__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>RelatedTransactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecialDisbursementType__c</fullName>
        <label>Special Disbursement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionDate__c</fullName>
        <inlineHelpText>The date the funds were disbursed.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Represents a funding event in a contract. This is typically a transaction from an investor or school to the school (for tuition) or directly to the student (ex. stipend)</description>
        <label>Disbursement</label>
    </recordTypes>
    <recordTypes>
        <fullName>DisbursementRefund</fullName>
        <active>true</active>
        <description>An exception that represents a reversal of a normal transaction</description>
        <label>Disbursement Refund</label>
    </recordTypes>
    <recordTypes>
        <fullName>Fee</fullName>
        <active>false</active>
        <description>Represents a payment from school or investor to Vemo</description>
        <label>Fee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>false</active>
        <description>Represents a transaction covering the student&#39;s income-based obligation in the ISA contract. This type of transaction does not occur until the student leaves school.</description>
        <label>Payment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Remittance</fullName>
        <active>false</active>
        <description>Represents the portion of collected payments that are aggregated and sent back to the program investor. This is typically from Vemo to the school or investor</description>
        <label>Remittance</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/DisbursementSpecialTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/School.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Purdue</fullName>
    </customValue>
    <customValue>
        <fullName>Test School</fullName>
    </customValue>
    <customValue>
        <fullName>Coalition for Queens</fullName>
    </customValue>
    <customValue>
        <fullName>Education Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Hack Reactor</fullName>
    </customValue>
    <customValue>
        <fullName>Holberton</fullName>
    </customValue>
    <customValue>
        <fullName>ISDE</fullName>
    </customValue>
    <customValue>
        <fullName>Learners Guild</fullName>
    </customValue>
    <customValue>
        <fullName>Make School</fullName>
    </customValue>
    <customValue>
        <fullName>MissionU</fullName>
    </customValue>
    <customValue>
        <fullName>Thinkful</fullName>
    </customValue>
    <customValue>
        <fullName>UnCollege</fullName>
    </customValue>
    <customValue>
        <fullName>General Assembly</fullName>
    </customValue>
    <customValue>
        <fullName>Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Coder Camps</fullName>
    </customValue>
    <customValue>
        <fullName>NYCDA</fullName>
    </customValue>
    <customValue>
        <fullName>Point Loma</fullName>
    </customValue>
    <customValue>
        <fullName>Sales2Job</fullName>
    </customValue>
    <customValue>
        <fullName>Powderhouse Studios</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Careers Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Lackawanna College</fullName>
    </customValue>
    <customValue>
        <fullName>Studio Institute Global</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Sollers</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Dojo</fullName>
    </customValue>
    <customValue>
        <fullName>Clarkson University</fullName>
    </customValue>
    <customValue>
        <fullName>Messiah College</fullName>
    </customValue>
    <customValue>
        <fullName>Berkeley College</fullName>
    </customValue>
    <customValue>
        <fullName>Haverton</fullName>
    </customValue>
    <masterLabel>School</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/TransactionService.cls
/////////////////////////////////////////////////////////////////////////
// Class: TransactionService
// 
// Description: 
//  Handles all Transaction DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-28   Greg Cook       Created
// 2017-01-24   Greg Cook       Renamed and Converted to generic transaction service                         
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class TransactionService {

    /////////////////////////////////////////////////////////////////////
    //Record Type Constants
    /////////////////////////////////////////////////////////////////////
    public static final String disbursementRecType = 'Disbursement';
    public static final String disbursementRefundRecType = 'Disbursement Refund';
    public static final String paymentRecType = 'Payment';
    public static final String paymentRefundRecType = 'Payment Refund';
    public static final String feeRecType = 'Fee';
    public static final String feeRefundRecType = 'Fee Refund';
    public static final String remittanceRecType = 'Remittance';        


    /////////////////////////////////////////////////////////////////////
    //Disbursement Functions
    /////////////////////////////////////////////////////////////////////
    public static List<Disbursement> getDisbursementWithDisbursementID(Set<ID> distributionIDs){
        System.debug('TransactionService.getDisbursementWithDisbursementID');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithTransactionID(distributionIDs, TransactionService.disbursementRecType);
        List<Disbursement> dists = new List<Disbursement>();
        for(Transaction__c tran : trans.values()){
            Disbursement dist = new Disbursement(tran);
            dists.add(dist);
        }
        return dists;
    }

    public static List<Disbursement> getDisbursementWithAgreementID(Set<ID> studentProgramIDs){
        System.debug('TransactionService.getDisbursementWithAgreementID');
        system.debug(studentProgramIDs);
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithAgreementID(studentProgramIDs, TransactionService.disbursementRecType);
        List<Disbursement> dists = new List<Disbursement>();
        for(Transaction__c tran : trans.values()){
            Disbursement dist = new Disbursement(tran);
            dists.add(dist);
        }
        return dists;
    }

    public static List<Disbursement> getDisbursementWithStudentID(Set<ID> accountIDs){
        System.debug('TransactionService.getDisbursementWithStudentID');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithStudentID(accountIDs, TransactionService.disbursementRecType);
        List<Disbursement> dists = new List<Disbursement>();
        for(Transaction__c tran : trans.values()){
            Disbursement dist = new Disbursement(tran);
            dists.add(dist);
        }
        return dists;
    }
    
    public static List<Disbursement> getDisbursementWithSchoolID(Set<ID> schoolIDs){
        System.debug('TransactionService.getUnconfirmedDisbursementsWithSchoolID');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithSchoolID(schoolIDs, TransactionService.disbursementRecType);
        List<Disbursement> dists = new List<Disbursement>();
        for(Transaction__c tran : trans.values()){
            Disbursement dist = new Disbursement(tran);
            dists.add(dist);
        }
        return dists;
    }

    public static Set<Id> createDisbursements(List<Disbursement> disbursement){
        System.debug('TransactionService.createDisbursement');
        List<Transaction__c> trans = new List<Transaction__c>();
        for(Disbursement dis : disbursement){
            Transaction__c tran = disbursementToTransaction(dis);
            trans.add(tran);
        }
        insert trans;
        Set<ID> disIDs = new Set<ID>();
        for(Transaction__c tran : trans){
            disIDs.add(tran.ID);
        }
        return disIDs;
    }

    public static Set<Id> updateDisbursements(List<Disbursement> disbursements){
        System.debug('TransactionService.updateDisbursement');
        List<Transaction__c> trans = new List<Transaction__c>();
        for(Disbursement dis : disbursements){
            Transaction__c tran = disbursementToTransaction(dis);
            trans.add(tran);
        }
        update trans;
        Set<ID> disIDs = new Set<ID>();
        for(Transaction__c tran : trans){
            disIDs.add(tran.ID);
        }
        return disIDs;
    }

    public static Integer deleteDisbursements(Set<ID> disbursementIDs){
        System.debug('TransactionService.deleteDisbursements');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithTransactionID(disbursementIDs, TransactionService.disbursementRecType);
        Integer numToDelete = trans.size();
        //School admins can't delete due to role hierarchy so they will be flagged and filtered
        for(Transaction__c disb : trans.values()){
            disb.Deleted__c = true;
        }
        update trans.values();
        return numToDelete;
    }
    /////////////////////////////////////////////////////////////////////
    //Disbursement Refund Functions
    /////////////////////////////////////////////////////////////////////
    public static List<DisbursementRefund> getDisbursementRefundWithDisbursementRefundID(Set<ID> distRefundIDs){
        System.debug('TransactionService.getDisbursementRefundWithDisbursementRefundID');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithTransactionID(distRefundIDs, TransactionService.disbursementRefundRecType);
        List<DisbursementRefund> dists = new List<DisbursementRefund>();
        for(Transaction__c tran : trans.values()){
            DisbursementRefund dist = new DisbursementRefund(tran);
            dists.add(dist);
        }
        return dists;
    }

    public static List<DisbursementRefund> getDisbursementRefundWithAgreementID(Set<ID> studentProgramIDs){
        System.debug('TransactionService.getDisbursementRefundWithAgreementID');
        system.debug(studentProgramIDs);
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithAgreementID(studentProgramIDs, TransactionService.disbursementRefundRecType);
        List<DisbursementRefund> dists = new List<DisbursementRefund>();
        for(Transaction__c tran : trans.values()){
            DisbursementRefund dist = new DisbursementRefund(tran);
            dists.add(dist);
        }
        return dists;
    }

    public static List<DisbursementRefund> getDisbursementRefundWithStudentID(Set<ID> accountIDs){
        System.debug('TransactionService.getDisbursementRefundWithStudentID');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithStudentID(accountIDs, TransactionService.disbursementRefundRecType);
        List<DisbursementRefund> dists = new List<DisbursementRefund>();
        for(Transaction__c tran : trans.values()){
            DisbursementRefund dist = new DisbursementRefund(tran);
            dists.add(dist);
        }
        return dists;
    }

    public static Set<Id> createDisbursementRefunds(List<DisbursementRefund> disbursementRefunds){
        System.debug('TransactionService.createDisbursementRefunds');
        List<Transaction__c> trans = new List<Transaction__c>();
        for(DisbursementRefund dis : disbursementRefunds){
            Transaction__c tran = disbursementRefundToTransaction(dis);
            trans.add(tran);
        }
        insert trans;
        Set<ID> disIDs = new Set<ID>();
        for(Transaction__c tran : trans){
            disIDs.add(tran.ID);
        }
        return disIDs;
    }

    public static Set<Id> updateDisbursementRefunds(List<DisbursementRefund> disbursementRefunds){
        System.debug('TransactionService.updateDisbursementRefunds');
        List<Transaction__c> trans = new List<Transaction__c>();
        for(DisbursementRefund dis : disbursementRefunds){
            Transaction__c tran = disbursementRefundToTransaction(dis);
            trans.add(tran);
        }
        update trans;
        Set<ID> disIDs = new Set<ID>();
        for(Transaction__c tran : trans){
            disIDs.add(tran.ID);
        }
        return disIDs;
    }

    public static Integer deleteDisbursementRefunds(Set<ID> distRefundIDs){
        System.debug('TransactionService.deleteDisbursementRefunds');
        Map<ID, Transaction__c> trans = TransactionQueries.getTransactionMapWithTransactionID(distRefundIDs, TransactionService.disbursementRefundRecType);
        Integer numToDelete = trans.size();
        delete trans.values();
        return numToDelete;
    }
    
    /////////////////////////////////////////////////////////////////////
    //Mapper Functions
    /////////////////////////////////////////////////////////////////////
    public static Transaction__c disbursementToTransaction(Disbursement dist){
        System.debug('TransactionService.disbursementToTransaction');
        Transaction__c trans = new Transaction__c();
        
        if(dist.disbursementID != null) trans.ID = dist.disbursementID;
        if(dist.studentID != null) trans.Student__c = dist.studentID;
        if(dist.agreementID != null) trans.Agreement__c = dist.agreementID;
        if(dist.relatedScheduleID != null) trans.RelatedSchedule__c = dist.relatedScheduleID;
        if(dist.amount != null) trans.Amount__c = dist.amount;
        if(dist.disbursementPercentage != null) trans.DisbursementPercentage__c = dist.disbursementPercentage;
        if(dist.transactionDate != null) trans.TransactionDate__c = dist.transactionDate;
        if(dist.status != null) trans.Status__C = dist.status;
        if(dist.specialDisbursementType != null) trans.SpecialDisbursementType__c = dist.specialDisbursementType;
        trans.RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Transaction__c', TransactionService.disbursementRecType);
        
        if(String.isNotEmpty(dist.confirmed)){
            trans.Confirmed__c = dist.confirmed == 'true' ?  true : false;
        } 
        if(dist.schoolSecurity != null) trans.SchoolSecurity__c = dist.schoolSecurity;
        
        return trans;
    }
    public static Transaction__c disbursementRefundToTransaction(DisbursementRefund distRefund){
        System.debug('TransactionService.disbursementRefundToTransaction');
        Transaction__c trans = new Transaction__c();
        
        if(distRefund.disbursementRefundID != null) trans.ID = distRefund.disbursementRefundID;
        if(distRefund.studentID != null) trans.Student__c = distRefund.studentID;
        if(distRefund.agreementID != null) trans.Agreement__c = distRefund.agreementID;
        if(distRefund.amount != null) trans.Amount__c = distRefund.amount;
        if(distRefund.transactionDate != null) trans.TransactionDate__c = distRefund.transactionDate;
        if(distRefund.status != null) trans.Status__C = distRefund.status;
        trans.RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Transaction__c', TransactionService.disbursementRefundRecType);
        if(distRefund.schoolSecurity != null) trans.SchoolSecurity__c = distRefund.schoolSecurity;

        return trans;
    }

    /////////////////////////////////////////////////////////////////////
    //Record Type Classes
    /////////////////////////////////////////////////////////////////////
    public class Disbursement{
        public String disbursementID {get;set;}
        public String studentID {get;set;}
        public String agreementID {get;set;}
        public String relatedScheduleID {get;set;}
        public Decimal amount {get;set;}
        public Date transactionDate {get;set;}
        public String status {get;set;}
        public Decimal disbursementPercentage {get;set;}
        public String confirmed {get;set;}
        public String schoolSecurity {get;set;}
        public String specialDisbursementType {get;set;}
        public String studentName {get;set;}
        public String programID {get;set;}
        public String programName {get;set;}
        public String agreementStatus {get;set;}
        public String vemoContractNumber {get;set;}
        public Disbursement(){

        }

        public Disbursement(Boolean testValues){
            if(testValues){
                this.transactionDate = Date.today();
                this.amount = 1000; 
                this.status = 'Complete'; //Pending, Scheduled      
            }
        }

        public Disbursement(Transaction__c trans){
            this.disbursementID = trans.ID;
            this.studentID = trans.Student__c;
            this.agreementID = trans.Agreement__c;
            this.relatedScheduleID = trans.RelatedSchedule__c;
            this.amount = trans.Amount__c;
            this.transactionDate = trans.TransactionDate__c;
            this.status = trans.Status__c;
            this.disbursementPercentage = trans.DisbursementPercentage__c;
            this.confirmed = String.valueOf(trans.Confirmed__c);
            this.schoolSecurity = trans.SchoolSecurity__c;
            this.specialDisbursementType = trans.SpecialDisbursementType__c;
            this.studentName = trans.Student__r.name;
            this.programID = trans.Agreement__r.Program__c;
            this.programName = trans.Agreement__r.Program__r.ProgramName__c;
            this.agreementStatus = trans.Agreement__r.Status__c;
            this.vemoContractNumber = trans.Agreement__r.VemoContractNumber__c;
        }
    }

    public class DisbursementRefund{
        public String disbursementRefundID {get;set;}
        public String studentID {get;set;}
        public String agreementID {get;set;}
        public Decimal amount {get;set;}
        public Date transactionDate {get;set;}
        public String status {get;set;}
        public String schoolSecurity {get;set;}

        public DisbursementRefund(){

        }

        public DisbursementRefund(Boolean testValues){
            if(testValues){
                this.transactionDate = Date.today();
                this.amount = 1000; 
                this.status = 'Complete'; //Pending, Scheduled      
            }
        }

        public DisbursementRefund(Transaction__c trans){
            this.disbursementRefundID = trans.ID;
            this.studentID = trans.Student__c;
            this.agreementID = trans.Agreement__c;
            this.amount = trans.Amount__c;
            this.transactionDate = trans.TransactionDate__c;
            this.status = trans.Status__c;
            this.schoolSecurity = trans.SchoolSecurity__c;

        }
    }

}