vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <inlineHelpText>This field is used to share this student with the School Account with a matching School Security Field. For example a Student with a School Security of Purdue will be shared with the School Account that has a value of &quot;Purdue&quot; in its School Security field</inlineHelpText>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/AttendancePeriod__c.object
<CustomObject>
    <label>Attendance Period</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Attendance Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AttendanceBeginDate__c</fullName>
        <label>Attendance Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AttendanceEndDate__c</fullName>
        <label>Attendance End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Attendance Periods</relationshipLabel>
        <relationshipName>Attendance_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentType__c</fullName>
        <description>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</description>
        <inlineHelpText>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</inlineHelpText>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Invite Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/ProgramStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/School.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Purdue</fullName>
    </customValue>
    <customValue>
        <fullName>Test School</fullName>
    </customValue>
    <customValue>
        <fullName>Coalition for Queens</fullName>
    </customValue>
    <customValue>
        <fullName>Education Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Hack Reactor</fullName>
    </customValue>
    <customValue>
        <fullName>Holberton</fullName>
    </customValue>
    <customValue>
        <fullName>ISDE</fullName>
    </customValue>
    <customValue>
        <fullName>Learners Guild</fullName>
    </customValue>
    <customValue>
        <fullName>Make School</fullName>
    </customValue>
    <customValue>
        <fullName>MissionU</fullName>
    </customValue>
    <customValue>
        <fullName>Thinkful</fullName>
    </customValue>
    <customValue>
        <fullName>UnCollege</fullName>
    </customValue>
    <customValue>
        <fullName>General Assembly</fullName>
    </customValue>
    <customValue>
        <fullName>Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Coder Camps</fullName>
    </customValue>
    <customValue>
        <fullName>NYCDA</fullName>
    </customValue>
    <customValue>
        <fullName>Point Loma</fullName>
    </customValue>
    <customValue>
        <fullName>Sales2Job</fullName>
    </customValue>
    <customValue>
        <fullName>Powderhouse Studios</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Careers Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Lackawanna College</fullName>
    </customValue>
    <customValue>
        <fullName>Studio Institute Global</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Sollers</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Dojo</fullName>
    </customValue>
    <customValue>
        <fullName>Clarkson University</fullName>
    </customValue>
    <customValue>
        <fullName>Messiah College</fullName>
    </customValue>
    <customValue>
        <fullName>Berkeley College</fullName>
    </customValue>
    <customValue>
        <fullName>Haverton</fullName>
    </customValue>
    <masterLabel>School</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/AttendancePeriodQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: AttendancePeriodQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION----------------------------- 
// 2018-03-06  Rini Gupta    Created
/////////////////////////////////////////////////////////////////////////

public class AttendancePeriodQueries {
    
    public static Map<ID, AttendancePeriod__c> getAttendancePeriodMapWithProgramID(set<ID> programIDs){
        Map<ID, AttendancePeriod__c> AttendancePeriodMap = new Map<ID, AttendancePeriod__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Program__c IN ' + DatabaseUtil.inSetStringBuilder(programIDs);
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' Order By AttendanceBeginDate__c asc';
        query += ' '+ generateLIMITStatement();
        system.debug('no of queries-');
        DatabaseUtil db = new DatabaseUtil();
        AttendancePeriodMap = new Map<ID, AttendancePeriod__c>((List<AttendancePeriod__c>)db.query(query));
        return AttendancePeriodMap;
    }
    
    
    public static Map<ID, AttendancePeriod__c> getAttendancePeriodMap(){
        Map<ID, AttendancePeriod__c> AtdprdMap = new Map<ID, AttendancePeriod__c>();
        String query = generateSOQLSelect();
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' WHERE Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        AtdprdMap = new Map<ID, AttendancePeriod__c>((List<AttendancePeriod__c>)db.query(query));
        return AtdprdMap;  
    }
    
    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getfieldNames() + ' FROM AttendancePeriod__c';
        system.debug(soql);
        return soql;
   }
   
    private static String getfieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'Name, ';
        fieldNames += 'AttendanceBeginDate__c, ';
        fieldNames += 'AttendanceEndDate__c, ';
        
        fieldNames += 'Program__c, ';
        fieldNames += 'Program__r.ProgramName__c, ';
        fieldNames += 'Program__r.ProgramStatus__c, ';
        fieldNames += 'Program__r.School__c, ';
        fieldNames += 'Program__r.School__r.SchoolSecurity__c, ';
        fieldNames += 'Program__r.EnrollmentType__c ';
        
        return fieldNames;
   }
   
   private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
   }
}