vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>BypassApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CertificationProcess__c</fullName>
        <label>Certification Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vemo</fullName>
                </value>
                <value>
                    <fullName>CL4</fullName>
                </value>
                <value>
                    <fullName>CSV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CertificationChanges__c</fullName>
        <formula>if( ApplicationRequestedAmount__c != CertifiedAllocatedAmount__c, true, false) || 
if( Text(ApplicationEnrollmentStatus__c) != Text(CertifiedEnrollmentStatus__c) , true, false) || 
if( ApplicationExpectedGraduationDate__c != CertifiedExpectedGraduationDate__c , true, false) || 
if( ApplicationSchoolProgramOfStudy__c != CertifiedSchoolProgramOfStudy__c , true, false) || 
if( Text(ApplicationResidency__c) != Text(CertifiedResidency__c) , true, false) || 
if( Text(ApplicationGradeLevel__c) != Text(CertifiedGradeLevel__c) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(DEPRECATE)Certification Changes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CertificationProcess__c</fullName>
        <label>(DEPRECATE)Certification Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Certified</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CertifiedAllocatedAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>(DEPRECATE)Certified Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CertifiedEligibleToReapply__c</fullName>
        <defaultValue>true</defaultValue>
        <label>(DEPRECATE)Student Eligible to Reapply?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CertifiedEnrollmentStatus__c</fullName>
        <label>(DEPRECATE)Certified Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CertifiedExpectedGraduationDate__c</fullName>
        <label>((DEPRECATE)Expected Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CertifiedGradeLevel__c</fullName>
        <label>(DEPRECATE)Certified Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CertifiedIncomeShare__c</fullName>
        <label>(DEPRECATE)Certified Income Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CertifiedPaymentCap__c</fullName>
        <label>(DEPRECATE)Certified Payment Cap</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CertifiedPaymentTerm__c</fullName>
        <label>(DEPRECATE)Certified Payment Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CertifiedResidency__c</fullName>
        <label>(DEPRECATE)Certified Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CertifiedSchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(DEPRECATE)(Major (SchoolProgramOfStudy)</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Certification</fullName>
        <active>true</active>
        <businessProcess>Certification</businessProcess>
        <description>Certification Cases</description>
        <label>Certification</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationReason__c</fullName>
        <inlineHelpText>If Status is set to Cancelled, this will show the reason for the cancellation (Credit Denied, etc).</inlineHelpText>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Certified</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Customer Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EligibleToReapply__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Eligible To Reapply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExpectedGraduationDate__c</fullName>
        <inlineHelpText>The date student is expected to graduate.</inlineHelpText>
        <label>Expected Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IncomeShare__c</fullName>
        <label>Income Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PaymentCap__c</fullName>
        <label>Payment Cap</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/EnrollmentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Three Quarter Time</fullName>
    </customValue>
    <customValue>
        <fullName>Half Time</fullName>
    </customValue>
    <customValue>
        <fullName>Less than Half Time</fullName>
    </customValue>
    <masterLabel>Enrollment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/GradeLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Residency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US Citizen/Non-Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Naturalized Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Work Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Student Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Refugee/Asylee</fullName>
    </customValue>
    <masterLabel>Residency</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/CaseTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: CaseTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-02-14   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class CaseTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State cserol Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution cserol - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.Triggercontext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'CaseTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.Triggercontext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'CaseTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'CaseTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'CaseTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onBeforeInsert()');
       //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> newCaseList = (List<Case>)tc.newList;
        //This is where you should call your business logic
        setDefaultsOnInsert(newCaseList);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onBeforeUpdate()');
        //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> newCaseList = (List<Case>)tc.newList;
        List<Case> oldCaseList = (List<Case>)tc.oldList;
        Map<ID, Case> newCaseMap = (Map<ID, Case>)tc.newMap;
        Map<ID, Case> oldCaseMap = (Map<ID, Case>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldCaseMap, newCaseMap); 
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onBeforeDelete()');
       //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> oldCaseList = (List<Case>)tc.oldList;
        Map<ID, Case> oldCaseMap = (Map<ID, Case>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onAfterInsert()');
         //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> newCaseList = (List<Case>)tc.newList;
        Map<ID, Case> newCaseMap = (Map<ID, Case>)tc.newMap;
        //This is where you should call your business logic

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onAfterUpdate()');
        //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> newCaseList = (List<Case>)tc.newList;
        List<Case> oldCaseList = (List<Case>)tc.oldList;
        Map<ID, Case> newCaseMap = (Map<ID, Case>)tc.newMap;
        Map<ID, Case> oldCaseMap = (Map<ID, Case>)tc.oldMap;
        //This is where you should call your business logic

		manageAgreements(oldCaseMap, newCaseMap);
   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onAfterDelete()');
        //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> oldCaseList = (List<Case>)tc.oldList;
        Map<ID, Case> oldCaseMap = (Map<ID, Case>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.Triggercontext tc){
		System.debug('CaseTriggerHandler.onAfterUndelete()');
        //Recast the trigger cseext variables into the appropriate shandlerect types
        List<Case> newCaseList = (List<Case>)tc.newList;
        Map<ID, Case> newCaseMap = (Map<ID, Case>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<Case> newCaseList){
		System.debug('CaseTriggerHandler.setDefaultsOnInsert()');
        for(Case cse : newCaseList){

        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, Case> oldCaseMap, Map<ID, Case> newCaseMap){
		System.debug('CaseTriggerHandler.setDefaultsOnUpdate()'); 
        for(Case cse : newCaseMap.values()){
            if(cse.CertificationProcess__c == 'Certified' && oldCaseMap.get(cse.id).CertificationProcess__c != 'Certified'){
                cse.Status = 'School Certified';
            }
            if(cse.CertificationProcess__c == 'Cancelled' && oldCaseMap.get(cse.id).CertificationProcess__c != 'Cancelled'){
                cse.Status = 'School Cancelled';
            }
            if(cse.Status == 'School Certified' && !cse.CertificationChanges__c){
                cse.Status = 'Certified';
            }
            if(cse.Status == 'School Cancelled'){
                cse.Status = 'Cancelled';
            }
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: manageAgreements
    /////////////////////////////////////////////////////////////////////////
    private void manageAgreements(Map<ID, Case> oldCaseMap, Map<ID, Case> newCaseMap){
        System.debug('CaseTriggerHandler.setPendingFields()'); 
        Map<ID, StudentProgram__c> agreementMap = new Map<ID, StudentProgram__c>();
        Map<ID, Account> studentMap = new Map<ID, Account>();
        for(Case cse : newCaseMap.values()){
            if(cse.Status == 'Certified' && oldCaseMap.get(cse.id).Status != 'Certified'){
                agreementMap.put(cse.Agreement__c, new StudentProgram__c(id = cse.Agreement__c,
                                                                         Status__c = 'Certified',
                                                                         GradeLevel__c = cse.CertifiedGradeLevel__c,
                                                                         SchoolProgramOfStudy__c = cse.CertifiedSchoolProgramOfStudy__c,
                                                                         EnrollmentStatus__c = cse.CertifiedEnrollmentStatus__c,
                                                                         ExpectedGraduationDate__c = cse.CertifiedExpectedGraduationDate__c,
                                                                         Residency__c = cse.CertifiedResidency__c,
                                                                         AllocatedAmount__c = cse.CertifiedAllocatedAmount__c,
                                                                         IncomeShare__c = cse.CertifiedIncomeShare__c,
                                                                         PaymentTerm__c = cse.CertifiedPaymentTerm__c,
                                                                         PaymentCap__c = cse.CertifiedPaymentCap__c));
                studentMap.put(cse.AccountId, new Account(id = cse.AccountId,
                                                          PrimarySchoolGradeLevel__pc = cse.CertifiedGradeLevel__c,
                                                          PrimarySchoolEnrollmentStatus__pc = cse.CertifiedEnrollmentStatus__c,
                                                          PrimarySchoolGraduationDate__pc = cse.CertifiedExpectedGraduationDate__c,
                                                          SchoolProgramOfStudy__pc = cse.CertifiedSchoolProgramOfStudy__c,
                                                          Residency__pc = cse.CertifiedResidency__c,
                                                          BypassApproval__c = true));
            }
            if(cse.Status == 'Cancelled' && oldCaseMap.get(cse.id).Status != 'Cancelled'){
                agreementMap.put(cse.Agreement__c, new StudentProgram__c(id = cse.Agreement__c,
                                                                         Status__c = 'Cancelled',
                                                                         CancellationReason__c = 'Ineligible',
                                                                         EligibleToReapply__c = cse.CertifiedEligibleToReapply__c));
            }
        }

        if(agreementMap.size()>0){
            Database.SaveResult[] srList = Database.update(agreementMap.values(), false);

            // Iterate through each returned result
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully updated agreement. StudentProgram__c ID: ' + sr.getId());
                }
                else {
                    for(Case cse : newCaseMap.values()){
                        cse.addError(sr.getErrors()[0].getMessage());
                    }
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {

                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Account fields that affected this error: ' + err.getFields());
                        //throw new CaseTriggerHandlerException('error'+sr);
                    }
                }
            }
        }
        if(studentMap.size()>0){
            update studentMap.values();
        }
    }
 /*   /////////////////////////////////////////////////////////////////////////
    //Method: manageShares
    /////////////////////////////////////////////////////////////////////////
    private void manageShares(Map<ID, Case> newCaseMap){
        System.debug('CaseTriggerHandler.manageShares()');
        List<AccountShare> acctShares = new List<AccountShare>();
        List<ID> schoolIDs = new List<ID>();
        for(Case cse : newCaseMap.values()){
            if(cse.RecordTypeID == GlobalUtil.getRecordTypeIdByLabelName('Case', 'Certification')){
                //share the school account with the portal users
                //not bulk safe!!
                List<User> schoolPortalUsers = [SELECT id from User where accountID = :cse.School__c];
                for (User usr : schoolPortalUsers){
                    acctShares.add(new AccountShare(AccountAccessLevel = 'Edit',
                                                      AccountID = cse.AccountID,
                                                      CaseAccessLevel = 'Edit',
            //                                        ContactAccessLevel = 'None',
                                                      OpportunityAccessLevel = 'None',
            //                                        RowCause = 'Apex',
                                                      UserOrGroupID = usr.id));

                }
            }
        }
        if(acctShares.size()>0){
            insert acctShares;
        }
    }
*/

    public class CaseTriggerHandlerException extends Exception {}
}