vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>VemoAccountNumber__c</fullName>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Automatially generated number identifying the Student/Account. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Account Number</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ClrHouseStudentEnrollment__c.object
<CustomObject>
    <label>ClearingHouse Enrollment</label>
    <nameField>
        <displayFormat>CHS-{00000000}</displayFormat>
        <label>ClrHouseStudentEnrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClearingHouse Enrollment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ClrHouseStudentEnrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequestorReturnFieldId__c</fullName>
        <formula>IF( AND(RequestorReturnField__c != null,RIGHT(RequestorReturnField__c, 1) == &#39;_&#39;) , LEFT(RequestorReturnField__c,LEN(RequestorReturnField__c)-1),  RequestorReturnField__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RequestorReturnFieldId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestorReturnField__c</fullName>
        <label>Requestor Return Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/ClrHouseStudentEnrolBatch.cls
global class ClrHouseStudentEnrolBatch implements Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful {
    String query;
  
    global ClrHouseStudentEnrolBatch () {
        query = 'SELECT id,RequestorReturnField__c,RequestorReturnFieldId__c from ClrHouseStudentEnrollment__c where Processed__c = false';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        set<string> accountVemoNumberSet = new set<string>();
        List<ClrHouseStudentEnrollment__c> ClrHouseStudentEnrollmentList = new List<ClrHouseStudentEnrollment__c>();
        
        for(ClrHouseStudentEnrollment__c c: (List<ClrHouseStudentEnrollment__c>) scope){
            if(c.RequestorReturnFieldId__c != null){
                accountVemoNumberSet.add(c.RequestorReturnFieldId__c);    
            }
        }
        
        if(accountVemoNumberSet != null && accountVemoNumberSet.size()>0){
            Map<id,account> accountMap = AccountQueries.getStudentMapWithVemoAccountNumber(accountVemoNumberSet);
            
            Map<string,account> vemoAccountNumberNAccountMap = new Map<string,account>();
            if(accountMap != null && accountMap.size()>0){
                for(Id i : accountMap.keyset()){
                    if(accountMap.get(i).VemoAccountNumber__c != null)
                        vemoAccountNumberNAccountMap.put(accountMap.get(i).VemoAccountNumber__c,accountMap.get(i));        
                }
            }
            for(ClrHouseStudentEnrollment__c c: (List<ClrHouseStudentEnrollment__c>) scope){
                if(c.RequestorReturnFieldId__c != null && vemoAccountNumberNAccountMap.get(c.RequestorReturnFieldId__c) != null){
                    c.account__c = vemoAccountNumberNAccountMap.get(c.RequestorReturnFieldId__c).id;
                    c.Processed__c = true;
                    ClrHouseStudentEnrollmentList.add(c);
                }
            }
            
            if(ClrHouseStudentEnrollmentList != null && ClrHouseStudentEnrollmentList.size()>0)
                upsert ClrHouseStudentEnrollmentList;
        }
    }
  
    global void finish(Database.BatchableContext BC) {
    }
}