vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is checked, the assessment process will run, regardless of the assessment date.</description>
        <inlineHelpText>If this box is checked, the assessment process will run, regardless of the assessment date.</inlineHelpText>
        <label>(Deprecate)Assess Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AssessmentDate__c</fullName>
        <description>The date when this account will next be assessed.  The assessment process will run on any account where the assessment is today or in the past.</description>
        <inlineHelpText>The date when this account will next be assessed.  The assessment process will run on any account where the assessment is today or in the past.</inlineHelpText>
        <label>(Deprecate)Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <defaultValue>16</defaultValue>
        <inlineHelpText>The default day of the month to perform this student&#39;s assessment.  This value copies to the Student Program level</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <description>The date when this account is due for payment</description>
        <inlineHelpText>The date when this account is due for payment</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DueDayOfTheMonth__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>The day of the month on which this student&#39;s payments are due.</inlineHelpText>
        <label>Due Day of the Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NextAutoPaymentDate__c</fullName>
        <description>The next date of the auto payment</description>
        <inlineHelpText>The next date of the auto payment</inlineHelpText>
        <label>Next Auto Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receive_Annual_Statement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Receive Annual Statement</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Default Record Type</description>
        <label>Default</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BeginDate__c</fullName>
        <inlineHelpText>The date this Income began.</inlineHelpText>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>(DEPRECATED)Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Income Verification.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has the student&#39;s Income been verified?</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date of the Payment Instruction.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Scheduled_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransactionDirection__c</fullName>
        <inlineHelpText>Inbound (from Student to Vemo) or Outbound (from Vemo to Student).</inlineHelpText>
        <label>Transaction Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionDirection</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Optional description - helpful in case Customer has multiple accounts at one bank.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseForRecurring__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Can this payment method be used for recurring payments?</inlineHelpText>
        <label>Use For Recurring</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AssessmentDate__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <inlineHelpText>The default day of the month to perform this contract assessment.</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IncomeVerification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Income Verification Object used to derive Monthly Income during Assessment</description>
        <inlineHelpText>Income Verification Object used to derive Monthly Income during Assessment</inlineHelpText>
        <label>Income Verification</label>
        <referenceTo>IncomeVerification__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Amount_Due</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>For this month, is the Student Program in Grace, Deferment, or Payment?</inlineHelpText>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MonthlyStatusActivity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Monthly Status.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Monthly Status</relationshipLabel>
        <relationshipName>Student_Program_Monthly_Status</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/IncomeVerificationStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Month.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Month</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/MonthlyStatusActivity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <masterLabel>Monthly Status Activity</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/PaymentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionDirection.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <masterLabel>Transaction Direction</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/StudentAccountBatch.cls
public with sharing class StudentAccountBatch implements Database.Batchable<sObject>, Database.ALlowsCallouts{
    public enum JobType {RECURRING_PAYMENT_GENERATION, ACCOUNT_ASSESSMENT,ANNUAL_STATEMENT_GENERATION} 
    
    public String query {get;set;}
    public JobType job {get;set;}
    
    public StudentAccountBatch() {
        job = JobType.RECURRING_PAYMENT_GENERATION;
    }
    public StudentAccountBatch(String query) {
        this.query = query;
        job = JobType.RECURRING_PAYMENT_GENERATION;
    }   
    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('StudentAccountBatch.start()');
        if(job == JobType.RECURRING_PAYMENT_GENERATION){
            if(String.isEmpty(this.query)){
                query = 'SELECT id from Account WHERE RecordTypeID = \'' + GlobalUtil.getRecordTypeIDByLabelName('Account', 'Student') + '\'';
            }
        } else if (job == JobType.ACCOUNT_ASSESSMENT){
            if(String.isEmpty(this.query)){
                String dateToday = String.valueOf(Date.today());            
                query = 'SELECT id from Account WHERE RecordTypeID = \'' + GlobalUtil.getRecordTypeIDByLabelName('Account', 'Student') + '\'';
                query += ' and (AssessmentDate__c <= '+dateToday + ' OR AssessAccount__c = true)';
            }
        }
        else if(job == JobType.ANNUAL_STATEMENT_GENERATION){
            if(String.isEmpty(this.query)){
                query = 'SELECT id,PersonContactID,PersonEmail from Account WHERE Receive_Annual_Statement__c = true AND RecordTypeID = \'' + GlobalUtil.getRecordTypeIDByLabelName('Account', 'Student') + '\'';
            }
        }
        System.debug('job:'+job);
        System.debug('query:'+query);
        LogService.writeLogs();
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('StudentAccountBatch.execute()');
        Set<ID> scopeIDs = new Set<ID>();
        for(sObject sobj : scope){
            scopeIDs.add(sobj.id);
        }

        Set<String> preservicingAgreementStatus = new Set<String>{'Invited',
                                                                  'Application Incomplete',
                                                                  'Application Under Review',
                                                                  'Under Review',
                                                                  'Cancelled'};
        Set<String> closedStatus = new Set<String>{'Contract Satisfied',
                                                                  'Default',
                                                                  'Forgiven'};
        if(job == JobType.RECURRING_PAYMENT_GENERATION){
            Map<ID, Account> studentMap = new Map<ID, Account>([SELECT id,
                                                                       RecordTypeID,
                                                                       AutoPayment__pc,
                                                                       AutoPaymentDateActivated__pc,
                                                                       AutoPaymentDayOfMonth1__pc,
                                                                       AutoPaymentDayOfMonth2__pc,
                                                                       AutoPaymentFrequency__pc,
                                                                       NextAutoPaymentDate__c,
                                                                       PersonContactID,
                                                                              (SELECT Student__c, Status__c
                                                                               FROM Student_Programs__r
                                                                               WHERE Status__c NOT IN :preservicingAgreementStatus
                                                                               and Status__c NOT IN :closedStatus)

                                                                    FROM Account
                                                                    WHERE RecordTypeID = :GlobalUtil.getRecordTypeIDByLabelName('Account', 'Student')
                                                                    and id = :scopeIDs
                                                                    and AutoPayment__pc = true
                                                                    and (AutoPaymentFrequency__pc = '1 Time Per Month' OR AutoPaymentFrequency__pc = 'On Due Date')
                                                                    and AutoPaymentDayOfMonth1__pc != null
                                                                    and ID IN (SELECT Student__c 
                                                                               FROM StudentProgram__c
                                                                               WHERE Status__c NOT IN :preservicingAgreementStatus
                                                                               and Status__c NOT IN :closedStatus)]);
            System.debug('studentMap:'+studentMap);
            recurringPaymentGeneration(studentMap);
            LogService.writeLogs();
        } else if (job == JobType.ACCOUNT_ASSESSMENT){
            Map<ID, Account> studentMap = new Map<ID, Account>([SELECT id,
                                                                       AssessAccount__c,
                                                                       AssessmentDate__c,
                                                                       AssessmentDayOfMonth__c,
                                                                       DueDayOfTheMonth__c,
                                                                       DueDate__c

                                                                    FROM Account
                                                                    WHERE RecordTypeID = :GlobalUtil.getRecordTypeIDByLabelName('Account', 'Student')
                                                                    and id = :scopeIDs
                                                                    FOR UPDATE]);
            System.debug('studentMap:'+studentMap);
            accountAssessment(studentMap);
            LogService.writeLogs();
        } 
        else if(job == JobType.ANNUAL_STATEMENT_GENERATION){
            Set<ID> studentIDs = new Set<ID>();
            for(SObject obj : scope){
                studentIDs.add(obj.id);
            }
            StudentService.sendAnnualStatements(studentIDs);
        }
        
        LogService.writeLogs(); 
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('StudentAccountBatch.finish()');
        if(job == StudentAccountBatch.JobType.ACCOUNT_ASSESSMENT){
            StudentAccountBatch batchJob = new StudentAccountBatch();
            batchJob.job = StudentAccountBatch.JobType.RECURRING_PAYMENT_GENERATION;
            Database.executeBatch(batchJob);
        }

        LogService.writeLogs();
    }
    
    private static void recurringPaymentGeneration(Map<ID, Account> studentMap){
        System.debug('StudentAccountBatch.recurringPaymentGenration()');
        List<PaymentInstruction__c> paymentsToCreate = new List<PaymentInstruction__c>();
        List<Case> casesToCreate = new List<Case>();
        Map<ID, Account> accountsToUpdate = new Map<ID, Account>();
        Map<ID, PaymentMethod__c> paymentMethodMap = PaymentMethodQueries.getPaymentMethodMapWithCustomerID(studentMap.keySet());
        Map<ID, Integer> studentDelinquencyMap = StudentService.getStudentDelinquencyMap(studentMap.keyset());
        Map<ID, List<PaymentMethod__c>> paymentMethodsByStudentID = new Map<ID, List<PaymentMethod__c>>();
        for(PaymentMethod__c paymentMethod : paymentMethodMap.values()){
            if(paymentMethod.UseForRecurring__c){
                if(!paymentMethodsByStudentID.containsKey(paymentMethod.Customer__c)){
                    paymentMethodsByStudentID.put(paymentMethod.Customer__c, new List<PaymentMethod__c>());
                }
                paymentMethodsByStudentID.get(paymentMethod.Customer__c).add(paymentMethod);
            }
        }

        Set<ID> acctsToCreatePayment = new Set<ID>();
        for(Account acct : studentMap.values()){
            System.debug('Account:'+acct);
            System.debug('Open Agreements:'+acct.Student_Programs__r);
            if(paymentMethodsByStudentID.containsKey(acct.id)){
                System.debug('Recurring Payment:'+paymentMethodsByStudentID.get(acct.id)[0]);
                acctsToCreatePayment.add(acct.id);          
            } else {
                casesToCreate.add(new Case(Type = 'Problem',
                                           Origin = 'Other',
                                           Priority = 'High',
                                           ContactID = studentMap.get(acct.id).PersonContactID,
                                           Subject = 'No Recurring Payment Method Found for Account '+acct.id));
                //throw new StudentAccountBatchException('No Payment Method found for '+acct.id);
            }
        }
        Map<ID, PaymentInstruction__c> paymentMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentStudentID(acctsToCreatePayment);
        Map<ID, List<PaymentInstruction__c>> paymentsByStudent = new Map<ID, List<PaymentInstruction__c>>();
        for(PaymentInstruction__c payment : paymentMap.values()){
            if(payment.Status__c == 'Created By Student' || payment.Status__c == 'Automatically Created'){
                if(!paymentsByStudent.containsKey(payment.Student__c)){
                    paymentsByStudent.put(payment.Student__c, new List<PaymentInstruction__c>());
                }
                paymentsByStudent.get(payment.Student__c).add(payment);             
            }

        }

        Map<ID, StatementService.StatementV1> statements = StatementService.getCurrentStatementV1ByStudentWithStudentID(acctsToCreatePayment);
        Map<ID, Decimal> amountDueByStudentID = new Map<ID, Decimal>();
        

        Date systemDate = Date.today();//for testing
        //systemDate = Date.newInstance(2018, 4, 16);//for testing
        
        for(ID theID : acctsToCreatePayment){
            if(statements.containsKey(theID) && statements.get(theID).totalAmountDue > 0){
                System.debug('Statement '+statements.get(theID));
                amountDueByStudentID.put(theID, statements.get(theID).totalAmountDue);
            }
            if(paymentsByStudent.containsKey(theID)){
                System.debug('Student '+theID + ' has an existing Payment Instruction.  Skipping');
            } else if(!amountDueByStudentID.containsKey(theID)){
                System.debug('Student '+theID + ' has no total amount due.  Skipping');
            } else if((studentMap.get(theID).NextAutoPaymentDate__c <= Date.today()) ||
                      (studentMap.get(theID).NextAutoPaymentDate__c == null) ||
                      (studentDelinquencyMap.containsKey(theID) && studentDelinquencyMap.get(theID)>30)){

                System.debug('Create');
                System.debug('studentMap.get(theID).NextAutoPaymentDate__c'+studentMap.get(theID).NextAutoPaymentDate__c);
                try{
                    System.debug('delinquency:'+studentDelinquencyMap.get(theID));                  
                } catch (Exception e){
                    System.debug('no delinquency');
                }

                paymentsToCreate.add(new PaymentInstruction__c(Student__c = theID,
                                                               PaymentMethod__c = paymentMethodsByStudentID.get(theID)[0].id,
                                                               Status__c = 'Automatically Created',
                                                               TransactionDirection__c = 'Inbound',
                                                               Description__c = 'Auto Payment',
                                                               Date__c = systemDate,
                                                               Amount__c = amountDueByStudentID.get(theID)));

                Boolean advanceAutoPaymentDate = false; 
                if(studentMap.get(theID).NextAutoPaymentDate__c <= systemDate || studentMap.get(theID).NextAutoPaymentDate__c == null) advanceAutoPaymentDate = true;
                if(advanceAutoPaymentDate){
                    Integer nextPaymentYear = (systemDate.month() == 12) ? systemDate.year() + 1 : systemDate.year();
                    Integer nextPaymentMonth = (systemDate.month() == 12) ? 1 : systemDate.month() + 1;
                    Integer nextPaymentDay = Integer.valueOf(studentMap.get(theID).AutoPaymentDayOfMonth1__pc);
                    accountsToUpdate.put(theID, new Account(id = theID, 
                                                     NextAutoPaymentDate__c = Date.newInstance(nextPaymentYear, nextPaymentMonth, nextPaymentDay)));                
                }               
            } else {
                System.debug(theID + ' does Not meet the criteria to create payment instructions');
            }
        }
        if(paymentsToCreate.size()>0){
            insert paymentsToCreate;
        }
        if(casesToCreate.size()>0){
            Database.insert(casesToCreate, false);
        }
        if(accountsToUpdate.size()>0){
            Database.update(accountsToUpdate.values(), false);          
        }

        LogService.writeLogs();
    }

    private static void accountAssessment(Map<ID, Account> studentMap){
        System.debug('StudentAccountBatch.accountAssessment()');
        Date systemDate = Date.today();//for testing
        //systemDate = Date.newInstance(2018, 4, 16);//for testing

        String systemYear = String.valueOf(systemDate.year());
        String systemMonth = '';
        if(systemDate.month() ==1){
            systemMonth = 'Janurary';
        } else if(systemDate.month() ==2){
            systemMonth = 'February';
        } else if(systemDate.month() ==3){
            systemMonth = 'March';
        } else if(systemDate.month() ==4){
            systemMonth = 'April';
        } else if(systemDate.month() ==5){
            systemMonth = 'May';
        } else if(systemDate.month() ==6){
            systemMonth = 'June';
        } else if(systemDate.month() ==7){
            systemMonth = 'July';
        } else if(systemDate.month() ==8){
            systemMonth = 'August';
        } else if(systemDate.month() ==9){
            systemMonth = 'September';
        } else if(systemDate.month() ==10){
            systemMonth = 'October';
        } else if(systemDate.month() ==11){
            systemMonth = 'November';
        } else if(systemDate.month() ==12){
            systemMonth = 'December';
        }
        System.debug('systemDate:'+systemDate);
        DateTime monthBeginDate = Date.newInstance(systemDate.year(), systemDate.month(), 1);
        DateTime monthEndDate;
        if(systemMonth == 'December'){
            monthEndDate = Date.newInstance(systemDate.year()+1, 1, 1);
        } else {
            monthEndDate = Date.newInstance(systemDate.year(), systemDate.month()+1, 1);            
        }


        ///////////////////////////////////////////Get Income Data///////////////////////////////////////////////
        Map<ID, IncomeVerification__c> incVerMap = new Map<ID, IncomeVerification__c>([SELECT Id, MonthlyIncome__c, Student__c, Verified__c
                                                                                        FROM IncomeVerification__c
                                                                                        WHERE Verified__c = true
                                                                                        AND BeginDate__c < :Date.today()
                                                                                        AND Student__c IN :studentMap.keySet()
                                                                                        ORDER BY BeginDate__c desc]);

        Map<ID, List<IncomeVerification__c>> incomeByStudent = new Map<ID, List<IncomeVerification__c>>();
        for(IncomeVerification__c income : incVerMap.values()){
            if(!incomeByStudent.containsKey(income.Student__c)){
                incomeByStudent.put(income.Student__c, new List<IncomeVerification__c>());
            }
            incomeByStudent.get(income.Student__c).add(income);
        }
        System.debug('incomeByStudent:'+incomeByStudent);


        ///////////////////////////////////////////Get Agreement Data///////////////////////////////////////////////
        Map<ID, StudentProgram__c> studProgramMap = StudentProgramQueries.getStudentProgramMapWithStudentID(studentMap.keySet());
        System.debug('studProgramMap:'+studProgramMap);
        Map<ID, List<StudentProgram__c>> agreementsByStudent = new Map<ID, List<StudentProgram__c>>();
        for(StudentProgram__c agreement : studProgramMap.values()){
            if(!agreementsByStudent.containsKey(agreement.Student__c)){
                agreementsByStudent.put(agreement.Student__c, new List<StudentProgram__c>());
            }
            agreementsByStudent.get(agreement.Student__c).add(agreement);
        }
        System.debug('agreementsByStudent:'+agreementsByStudent);


        ////////////////////////////////////////Monthly Tracker Data Structures//////////////////////////////////////
        List<StudentProgramMonthlyStatus__c> monthlyTrackerToAdd = new List<StudentProgramMonthlyStatus__c>();
        Map<Id,StudentProgramMonthlyStatus__c> existingMonthlyTrackers = new Map<ID, StudentProgramMonthlyStatus__c>([SELECT id, Agreement__c, Year__c, Month__c, Activity__c, MonthlyStatusGUID__c
                                                                                                                      FROM StudentProgramMonthlyStatus__c
                                                                                                                      WHERE Agreement__c IN :studProgramMap.keySet()
                                                                                                                      AND Year__c = :systemYear
                                                                                                                      AND Month__c = :systemMonth]);
        System.debug('existingMonthlyTrackers:'+existingMonthlyTrackers);

        Map<ID, List<StudentProgramMonthlyStatus__c>> monthlyTrackersByAgreement = new Map<ID, List<StudentProgramMonthlyStatus__c>>();
        for(StudentProgramMonthlyStatus__c tracker : existingMonthlyTrackers.values()){
            if(!monthlyTrackersByAgreement.containsKey(tracker.Agreement__c)){
                monthlyTrackersByAgreement.put(tracker.Agreement__c, new List<StudentProgramMonthlyStatus__c>());
            }
            monthlyTrackersByAgreement.get(tracker.Agreement__c).add(tracker);
        }
        System.debug('monthlyTrackersByAgreement:'+monthlyTrackersByAgreement);


        ////////////////////////////////////////Amount Due Data Structures//////////////////////////////////////
        List<StudentProgramAmountDue__c> amountDueToAdd = new List<StudentProgramAmountDue__c>();
        Map<ID, StudentProgramAmountDue__c> existingAmountDue = new Map<ID, StudentProgramAmountDue__c>([SELECT id, Agreement__c, AMount__c, AssessmentDateTime__c, ExcludeFromBalance__c, Type__c, StudentProgramMonthlyStatus__c
                                                                                                         FROM StudentProgramAmountDue__c
                                                                                                         WHERE Agreement__c IN : studProgramMap.keySet()
                                                                                                         AND AssessmentDateTime__c > :monthBeginDate
                                                                                                         AND AssessmentDateTime__c < :monthEndDate
                                                                                                         AND Type__c = 'Monthly Amount'
                                                                                                         AND ExcludeFromBalance__c = false]);
        System.debug('existingAmountDue:'+existingAmountDue);
        Map<ID, List<StudentProgramAmountDue__c>> amountDueByAgreement = new Map<ID, List<StudentProgramAmountDue__c>>();
        for(StudentProgramAmountDue__c amountDue : existingAmountDue.values()){
            if(!amountDueByAgreement.containsKey(amountDue.Agreement__c)){
                amountDueByAgreement.put(amountDue.Agreement__c, new List<StudentProgramAmountDue__c>());
            }
            amountDueByAgreement.get(amountDue.Agreement__c).add(amountDue);
        }   


        for(Account acct : studentMap.values()){
            System.debug('On acct:'+acct);

            //////////////////////////////Loop Through Agreements////////////////////////////////////////
            for(StudentProgram__c agreement : agreementsByStudent.get(acct.id)){
                System.debug('On agreement:'+agreement);
                String guid = agreement.id + ':' + systemYear + ':' + systemMonth;
                StudentProgramMonthlyStatus__c monthlyStatus;
                //////////////////////////////Update Monthly Tracker////////////////////////////////////////
                //Check to see if a monthly tracker exists.  If it DOES exist, skip this section
                if(!monthlyTrackersByAgreement.containsKey(agreement.id)){
                    String status = studProgramMap.get(agreement.id).Status__c;
                    Set<String> servicingStatus = new Set<String>{'Grace',
                                                                  'Deferment',
                                                                  'Payment',
                                                                  'Internship',
                                                                  'School',
                                                                  'Leave of Absence'};
                    if(servicingStatus.contains(status)){
                            monthlyStatus = new StudentProgramMonthlyStatus__c(Agreement__c = agreement.id,
                                                                                        Year__c = systemYear,
                                                                                        Month__c = systemMonth,
                                                                                        Activity__c = status,
                                                                                        MonthlyStatusGUID__c = guid);
                            monthlyTrackerToAdd.add(monthlyStatus);                                 
                    }
                } else {
                    monthlyStatus = monthlyTrackersByAgreement.get(agreement.id)[0];
                }

                //////////////////////////////Update Amount Due////////////////////////////////////////
                //Check to see if a monthly amount exists.  If it DOES exist, skip this section
                if(!amountDueByAgreement.containsKey(agreement.id)){
                    StudentProgramMonthlyStatus__c existingMonthlyStatus = new StudentProgramMonthlyStatus__c(MonthlyStatusGUID__c = guid);
                    Decimal amount = 0;
                    Set<String> paymentStatus = new Set<String>{'Payment','Internship'};
                    try{
                        if(paymentStatus.contains(monthlyStatus.Activity__c)){
                            Decimal latestVerifiedMonthlyIncome = incomeByStudent.get(acct.id)[0].MonthlyIncome__c;
                            amount = (latestVerifiedMonthlyIncome * (agreement.IncomeSharePostCertification__c == null ? 0 :agreement.IncomeSharePostCertification__c)/100);
                        } else {
                            amount = 0;
                        }                       
                    } catch (Exception e){
                        System.debug('error calculating amount');
                        amount = 0;
                    }

                    amountDueToAdd.add(new StudentProgramAmountDue__c(Agreement__c = agreement.id,
                                                                      Type__c = 'Monthly Amount',
                                                                      AssessmentDateTime__c = DateTime.now(),
                                                                      Amount__c = amount,
                                                                      ExcludeFromBalance__c = false,
                                                                      StudentProgramMonthlyStatus__r = existingMonthlyStatus));
                }

            }






            //////////////////////////////Update Assessment Date////////////////////////////////////////

            System.debug('acct.AssessmentDate__c:'+acct.AssessmentDate__c);
            System.debug('acct.AssessmentDayOfMonth__c:'+acct.AssessmentDayOfMonth__c);
            Boolean advanceAssessmentDate = false; 
            if(acct.AssessmentDate__c <= systemDate || acct.AssessmentDate__c == null) advanceAssessmentDate = true;
            if(advanceAssessmentDate){
                System.debug('advanceAssessmentDate');
                Integer nextAssessmentYear = systemDate.year();
                Integer nextAssessmentMonth = systemDate.month();
                if(acct.AssessmentDayOfMonth__c < systemDate.day()){
                    //Advance the month
                    nextAssessmentYear = (systemDate.month() == 12) ? systemDate.year() + 1 : systemDate.year();
                    nextAssessmentMonth = (systemDate.month() == 12) ? 1 : systemDate.month() + 1;                  
                }

                Integer nextAssessmentDay = Integer.valueOf(acct.AssessmentDayOfMonth__c);
                acct.AssessmentDate__c = Date.newInstance(nextAssessmentYear, nextAssessmentMonth, nextAssessmentDay);      

                System.debug('Set acct.AssessmentDate__c:'+acct.AssessmentDate__c);     
            }
            //////////////////////////////Update Due Date////////////////////////////////////////
            Boolean advanceDueDate = false; 
            if(acct.DueDate__c <= systemDate || acct.DueDate__c == null) advanceDueDate = true;
            if(advanceDueDate){
                Integer nextDueDateYear = systemDate.year();
                Integer nextDueDateMonth = systemDate.month();
                if(acct.DueDayOfTheMonth__c < systemDate.day()){
                    //Advance the month
                    nextDueDateYear = (systemDate.month() == 12) ? systemDate.year() + 1 : systemDate.year();
                    nextDueDateMonth = (systemDate.month() == 12) ? 1 : systemDate.month() + 1;
                }
                Integer nextDueDateDay = Integer.valueOf(acct.DueDayOfTheMonth__c);
                acct.DueDate__c = Date.newInstance(nextDueDateYear, nextDueDateMonth, nextDueDateDay);              
            }
            acct.AssessAccount__c = false;
        }

        if(monthlyTrackerToAdd.size()>0){
            Database.insert(monthlyTrackerToAdd);
        }
        if(amountDueToAdd.size()>0){
            Database.insert(amountDueToAdd);
        }

        Database.update(studentMap.values());
        LogService.writeLogs();

    }

    public class StudentAccountBatchException extends Exception {}
}