vemo-mdapi-qa/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessmentDayOfMonth__c</fullName>
        <defaultValue>16</defaultValue>
        <inlineHelpText>The default day of the month to perform this student&#39;s assessment.  This value copies to the Student Program level</inlineHelpText>
        <label>Assessment Day of Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CampusServiceAvailability__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Availability</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampusServiceEmail__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CampusServiceMobile__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampusServiceName__c</fullName>
        <description>This field will be presented to the students for customer service contact information</description>
        <inlineHelpText>This field will be presented to the students for customer service contact information</inlineHelpText>
        <label>Campus Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DescriptionBlock__c</fullName>
        <label>Description Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DetailBlock__c</fullName>
        <label>Detail Block</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisplayName__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DueDayOfTheMonth__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>The day of the month on which this student&#39;s payments are due.</inlineHelpText>
        <label>Due Day of the Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EntryPoint__c</fullName>
        <label>Entry Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SchoolLogoURL__c</fullName>
        <formula>$Setup.GlobalSettings__c.DocumentDownloadPrefix__c + SchoolLogoDocumentID__c +&quot;&amp;oid=&quot; +  $Organization.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Logo URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SchoolSecurity__c</fullName>
        <inlineHelpText>This field is used to share this student with the School Account with a matching School Security Field. For example a Student with a School Security of Purdue will be shared with the School Account that has a value of &quot;Purdue&quot; in its School Security field</inlineHelpText>
        <label>School Security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StewardshipDisbursementDonorGUID__c</fullName>
        <label>Stewardship Disbursement DonorGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StewardshipPaymentDonorGUID__c</fullName>
        <label>Stewardship Payment DonorGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentCampusServiceAvailability__c</fullName>
        <label>Student Campus Service Availability</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentCampusServiceEmail__c</fullName>
        <label>Student Campus Service Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>StudentCampusServiceMobile__c</fullName>
        <label>Student Campus Service Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentCampusServiceName__c</fullName>
        <label>Student Campus Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TitleBlock__c</fullName>
        <label>Title Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UnpaidFees__c</fullName>
        <label>Unpaid Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VemoAccountNumber__c</fullName>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Automatially generated number identifying the Student/Account. It is independent of any particular system (Salesforce, Auth0, CampusDoor, ATOM1, etc) and can be given to customers.</inlineHelpText>
        <label>Vemo Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>WebsiteStatus__c</fullName>
        <label>Website Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProvisioningStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>WebStyle__c</fullName>
        <label>Web Style</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/ProvisioningStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Provisioning</fullName>
    </customValue>
    <customValue>
        <fullName>Provisioned</fullName>
    </customValue>
    <masterLabel>Provisioning Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/School.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Purdue</fullName>
    </customValue>
    <customValue>
        <fullName>Test School</fullName>
    </customValue>
    <customValue>
        <fullName>Coalition for Queens</fullName>
    </customValue>
    <customValue>
        <fullName>Education Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Hack Reactor</fullName>
    </customValue>
    <customValue>
        <fullName>Holberton</fullName>
    </customValue>
    <customValue>
        <fullName>ISDE</fullName>
    </customValue>
    <customValue>
        <fullName>Learners Guild</fullName>
    </customValue>
    <customValue>
        <fullName>Make School</fullName>
    </customValue>
    <customValue>
        <fullName>MissionU</fullName>
    </customValue>
    <customValue>
        <fullName>Thinkful</fullName>
    </customValue>
    <customValue>
        <fullName>UnCollege</fullName>
    </customValue>
    <customValue>
        <fullName>General Assembly</fullName>
    </customValue>
    <customValue>
        <fullName>Watson</fullName>
    </customValue>
    <customValue>
        <fullName>Coder Camps</fullName>
    </customValue>
    <customValue>
        <fullName>NYCDA</fullName>
    </customValue>
    <customValue>
        <fullName>Point Loma</fullName>
    </customValue>
    <customValue>
        <fullName>Sales2Job</fullName>
    </customValue>
    <customValue>
        <fullName>Powderhouse Studios</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Careers Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Lackawanna College</fullName>
    </customValue>
    <customValue>
        <fullName>Studio Institute Global</fullName>
    </customValue>
    <customValue>
        <fullName>Kenzie</fullName>
    </customValue>
    <customValue>
        <fullName>Sollers</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Dojo</fullName>
    </customValue>
    <customValue>
        <fullName>Clarkson University</fullName>
    </customValue>
    <customValue>
        <fullName>Messiah College</fullName>
    </customValue>
    <customValue>
        <fullName>Berkeley College</fullName>
    </customValue>
    <customValue>
        <fullName>Haverton</fullName>
    </customValue>
    <masterLabel>School</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/AccountQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: AccountQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-07-13   Greg Cook       Created                                 
// 2016-12-17   Greg Cook       Added getStudent(), added fields to getStudentMapByID
// 2016-12-20   Greg Cook       Changed all functions to maps, changed function names to overloaded functions
// 2016-12-24   Greg Cook       Added StudentMayByAuthIDWithAuthID, changed function names
// 2017-02-09   Greg Cook       Added filterCriteria
/////////////////////////////////////////////////////////////////////////
public class AccountQueries {
    public static Map<String, Object> filterCriteria = new Map<String, Object>();
    public static void clearFilterCriteria(){
        filterCriteria.clear();
    }

    public static Map<String, Account> getStudentMapByAuthIDWithAuthID(Set<String> authIDs){
        Map<String, Account> acctMapByAuthID = new Map<String, Account>();
        String query = generateSOQLSelect('student');
        query += ' WHERE AuthSystemUserID__pc IN ' + DatabaseUtil.inSetStringBuilder(authIDs);
        query += ' and ' + generateRecordTypeStatement('Student');

        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        Map<ID, Account> retMap = new Map<ID, Account>((List<Account>)db.query(query));

        for(Account acct : retMap.values()){
            acctMapByAuthID.put(acct.AuthSystemUserID__pc, acct);
        }
        system.debug('acctMapByAuthID:'+acctMapByAuthID);
        return acctMapByAuthID;
    }

    public static Map<ID, Account> getStudentMap(){
        Map<ID, Account> acctMap = new Map<ID, Account>();
        String query = generateSOQLSelect('student');
        query += ' WHERE ' + generateRecordTypeStatement('Student');
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        acctMap = new Map<ID, Account>((List<Account>)db.query(query));
        return acctMap;     
    }
    
    public static Map<ID, Account> getStudentMapWithPersonEmails(Set<String> personEmails){
        Map<ID, Account> acctMap = new Map<ID, Account>();
        String query = generateSOQLSelect('student');
        query += ' WHERE ' + generateRecordTypeStatement('Student');
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += ' and PersonEmail IN ' + DatabaseUtil.inSetStringBuilder(personEmails)+ ' ';
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        acctMap = new Map<ID, Account>((List<Account>)db.query(query));
        return acctMap;     
    }

    public static Map<ID, Account> getStudentMapWithStudentID(Set<ID> studentIDs){
        Map<ID, Account> acctMap = new Map<ID, Account>();
        String query = generateSOQLSelect('student');       
        query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(studentIDs);
        query += ' and ' + generateRecordTypeStatement('Student');
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        acctMap = new Map<ID, Account>((List<Account>)db.query(query));
        return acctMap;     
        
    }   
    
    public static Map<ID, Account> getStudentMapWithVemoAccountNumber(Set<string> vemoAccountNos){
        Map<ID, Account> acctMap = new Map<ID, Account>();
        String query = generateSOQLSelect('student');
        query += ' WHERE ' + generateRecordTypeStatement('Student');
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += ' and VemoAccountNumber__c IN ' + DatabaseUtil.inSetStringBuilder(vemoAccountNos)+ ' ';
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        acctMap = new Map<ID, Account>((List<Account>)db.query(query));
        return acctMap;     
        
    }  

    ///////////////////////////////////////////////////////////////////////////////////////////
    // School Queries
    ///////////////////////////////////////////////////////////////////////////////////////////
    public static Map<ID, Account> getSchoolMap(){
        Map<ID, Account> schlMap = new Map<ID, Account>();
        String query = generateSOQLSelect('school');        
        query += ' WHERE ' + generateRecordTypeStatement('School - Available Prospect');
        query += 'or ' + generateRecordTypeStatement('School - Customer');
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        schlMap = new Map<ID, Account>((List<Account>)db.query(query));
        return schlMap;     
    }
    
    public static Map<ID, Account> getSchoolCustomerMap(){
        Map<ID, Account> schlMap = new Map<ID, Account>();
        String query = generateSOQLSelect('school');        
        query += ' WHERE ' + generateRecordTypeStatement('School - Customer');
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        schlMap = new Map<ID, Account>((List<Account>)db.query(query));
        return schlMap;     
    }
    public static Map<ID, Account> getSchoolMapWithSchoolID(Set<ID> schoolIDs){
        Map<ID, Account> schlMap = new Map<ID, Account>();
        String query = generateSOQLSelect('school');    
        query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(schoolIDs);          
        query += ' and ';
        query += '(' + generateRecordTypeStatement('School - Available Prospect');

        query += ' or ' + generateRecordTypeStatement('School - Customer') + ') ';
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        schlMap = new Map<ID, Account>((List<Account>)db.query(query));
        return schlMap;         
    }   

    public static Map<ID, Account> getSchoolMapWithSchoolName(Set<String> schoolNames){
        Map<ID, Account> schlMap = new Map<ID, Account>();
        String query = generateSOQLSelect('school');    
        query += ' WHERE Name IN ' + DatabaseUtil.inSetStringBuilder(schoolNames);  
        query += ' and ';
        query += '(' + generateRecordTypeStatement('School - Available Prospect');

        query += ' or ' + generateRecordTypeStatement('School - Customer') + ') ';
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        schlMap = new Map<ID, Account>((List<Account>)db.query(query));
        return schlMap;     
    }

    public static Map<ID, Account> getSchoolMapWithEntryPoint(Set<String> entryPoints){
        Map<ID, Account> schlMap = new Map<ID, Account>();
        String query = generateSOQLSelect('school');    
        query += ' WHERE EntryPoint__c IN ' + DatabaseUtil.inSetStringBuilder(entryPoints); 
        query += ' and ';
        query += '(' + generateRecordTypeStatement('School - Available Prospect');

        query += ' or ' + generateRecordTypeStatement('School - Customer') + ') ';
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and ID = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        schlMap = new Map<ID, Account>((List<Account>)db.query(query));
        return schlMap;     
    }

    private static String generateSOQLSelect(String type){
        String soql;
        if(type == 'student'){
            soql = 'SELECT ' + getStudentFieldNames() + ' FROM Account';
        }
        else if(type == 'school'){
            soql = 'SELECT ' + getSchoolFieldNames() + ' FROM Account';
        }
        return soql;
    }

    private static String getStudentFieldNames(){
        String fieldNames;
        //Account Fields

        fieldNames = 'id, ';
//      fieldNames += 'GUID__c, ';
        fieldNames += 'DueDayOfTheMonth__c, ';
        fieldNames += 'AssessmentDayOfMonth__c, ';
        fieldNames += 'RecordTypeID, ';
        fieldNames += 'Salutation, ';
        fieldNames += 'FirstName, ';
        fieldNames += 'MiddleName, ';
        fieldNames += 'LastName, ';
        fieldNames += 'Suffix, ';
        fieldNames += 'SchoolSecurity__c, ';
        fieldNames += 'PersonBirthDate, ';
        fieldNames += 'PersonEmail, ';
        fieldNames += 'PersonDoNotCall, ';
        fieldNames += 'PersonHasOptedOutOfEmail, ';
        fieldNames += 'PersonHomePhone, ';
        fieldNames += 'PersonMailingCity, ';
        fieldNames += 'PersonMailingCountry, ';
        fieldNames += 'PersonMailingCountryCode, ';     
        fieldNames += 'PersonMailingPostalCode, ';
        fieldNames += 'PersonMailingState, ';
        fieldNames += 'PersonMailingStateCode, ';
        fieldNames += 'PersonMailingStreet, ';
        fieldNames += 'PersonOtherCity, ';
        fieldNames += 'PersonOtherCountry, ';
        fieldNames += 'PersonOtherCountryCode, ';       
        fieldNames += 'PersonOtherPostalCode, ';
        fieldNames += 'PersonOtherState, ';
        fieldNames += 'PersonOtherStateCode, ';
        fieldNames += 'PersonOtherStreet, ';
        fieldNames += 'PersonMobilePhone, ';
        fieldNames += 'PersonContactID, ';

        //Contact fields
        fieldNames += 'AuthSystemUserID__pc, ';
        fieldNames += 'DriversLicenseOrStateID__pc, ';
        fieldNames += 'Residency__pc, ';
        fieldNames += 'PreferredMethodOfCommunication__pc, ';
        fieldNames += 'SSNTaxID__pc, ';
        fieldNames += 'HasOptedOutOfText__pc, ';
        fieldNames += 'TimeZone__pc, ';
        fieldNames += 'PrimarySchool__pc, ';
//      fieldNames += 'PrimarySchool__pr.GUID__c, ';
        fieldNames += 'PrimarySchoolStudentID__pc, ';
        fieldNames += 'PrimarySchoolEmail__pc, ';
        fieldNames += 'PrimarySchoolGraduationDate__pc, ';
        fieldNames += 'PrimarySchoolEnrollmentStatus__pc, ';
        fieldNames += 'PrimarySchoolGradeLevel__pc, ';
        fieldNames += 'SchoolProgramOfStudy__pc, '; 
        fieldNames += 'CommonLineID__pc, '; 
//      fieldNames += 'PendingFirstName__pc, '; 
//      fieldNames += 'PendingMiddleName__pc, ';    
//      fieldNames += 'PendingLastName__pc, ';  
//      fieldNames += 'PendingBirthdate__pc, '; 
//      fieldNames += 'PendingDriversLicenseOrStateID__pc, ';   
//      fieldNames += 'PendingEmail__pc, '; 
//      fieldNames += 'RecordStatus__pc, '; 
//      fieldNames += 'PendingMailingStreet__pc, '; 
//      fieldNames += 'PendingMailingCity__pc, ';   
//      fieldNames += 'PendingMailingState__pc, ';
//      fieldNames += 'PendingMailingStateCode__pc, ';
//      fieldNames += 'PendingMailingCountry__pc, ';
//      fieldNames += 'PendingMailingCountryCode__pc, ';
//      fieldNames += 'PendingMailingPostalCode__pc, ';
        fieldNames += 'VemoAccountNumber__c, ';
        fieldNames += 'VerifiedAnnualIncome__pc, ';

//      fieldNames += 'PendingResidency__pc, ';
        fieldNames += 'Credit__pc, ';
        fieldNames += 'AutoPayment__pc, ';
        fieldNames += 'AutoPaymentFrequency__pc, ';
        fieldNames += 'AutoPaymentDayOfMonth1__pc, ';
        fieldNames += 'AutoPaymentDayOfMonth2__pc, ';
        fieldNames += 'AutoPaymentDateActivated__pc, ';
        fieldNames += 'Age__pc, ';  
        fieldNames += 'DateIncomeVerified__pc, ';
        fieldNames += 'StewardshipPaymentDonorGUID__c, ';
        fieldNames += 'StewardshipDisbursementDonorGUID__c, ';
        fieldNames += 'UnpaidFees__c, ';
        fieldNames += 'CumulativeIncomeShare__pc, ';
        fieldNames += 'CumulativeIncomeShareCap__pc ';

        return fieldNames;
    }

    private static String getSchoolFieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'GUID__c, ';
        fieldNames += 'Name, ';
        fieldNames += 'BillingStreet, ';
        fieldNames += 'BillingCity, ';
        fieldNames += 'BillingCountry, ';
        fieldNames += 'BillingCountryCode, ';
        fieldNames += 'BillingPostalCode, ';
        fieldNames += 'BillingState, ';
        fieldNames += 'BillingStateCode, ';
        fieldNames += 'CampusServiceName__c, ';
        fieldNames += 'CampusServiceEmail__c, ';
        fieldNames += 'CampusServiceMobile__c, ';
        fieldNames += 'CampusServiceAvailability__c, ';
        fieldNames += 'VemoAccountNumber__c, ';
        fieldNames += 'EntryPoint__c, ';
        fieldNames += 'WebsiteStatus__c, ';
        fieldNames += 'WebStyle__c, ';
        fieldNames += 'DisplayName__c, ';
        fieldNames += 'SchoolLogoURL__c, ';
        fieldNames += 'TitleBlock__c, ';
        fieldNames += 'DescriptionBlock__c, ';
        fieldNames += 'DetailBlock__c, ';
        fieldNames += 'SchoolSecurity__c, ';
        fieldNames += 'StudentCampusServiceAvailability__c, ';
        fieldNames += 'StudentCampusServiceEmail__c, ';
        fieldNames += 'StudentCampusServiceMobile__c, ';
        fieldNames += 'StudentCampusServiceName__c ';
        return fieldNames;
    }
    
    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }

    private static String generateRecordTypeStatement(String recordTypeLabel){
        ID recordTypeID = (String)GlobalUtil.getRecordTypeIDByLabelName('Account', recordTypeLabel);
        return 'RecordTypeID = \''+ String.valueOf(recordTypeID) + '\'';
    }

    private static String buildFilterString(){
        String filterStr = '';
        if(filterCriteria.size()>0){
            for(String filter : filterCriteria.keyset()){
                filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) +  '\' ');
            }           
        }
        return filterStr;
    }
}