vemo-mdapi-qa/objects/ApprovalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ApprovalSettings</label>
    <fields>
        <fullName>AccountNameChangeAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AccountNameChangeAllowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassTransactionFreeze__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BypassTransactionFreeze</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/ApprovalSettings.cls
public with sharing class ApprovalSettings {
    public static void createApprovalSettings(){

        List<ApprovalSettings__c> settings = new List<ApprovalSettings__c>();
        
        //Organizational Settings
        settings.add(new ApprovalSettings__c(SetupOwnerID = UserInfo.getOrganizationID(),
                                             AccountNameChangeAllowed__c = false,
                                             BypassTransactionFreeze__c = false));
        //User Settings
        settings.add(new ApprovalSettings__c(SetupOwnerID = UserInfo.getUserID(),
                                              AccountNameChangeAllowed__c = true,
                                              BypassTransactionFreeze__c = true));       
        
        insert settings;
    }
}