vemo-mdapi-qa/objects/AttendancePeriod__c.object
<CustomObject>
    <label>Attendance Period</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Attendance Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AttendanceBeginDate__c</fullName>
        <label>Attendance Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AttendanceEndDate__c</fullName>
        <label>Attendance End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Attendance Periods</relationshipLabel>
        <relationshipName>Attendance_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/classes/AttendancePeriodService.cls
/////////////////////////////////////////////////////////////////////////
// Class: AttendancePeriodService
// 
// Description: 
//  Handles all AttendancePeriod DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2018-03-06   Rini Gupta      Created                          
/////////////////////////////////////////////////////////////////////////
public with sharing class AttendancePeriodService{
    
     public static List<AttendancePeriod> getAttendancePeriodsWithProgramID(Set<ID> programIDs){
        System.debug('AttendancePeriodService.getAttendancePeriodsWithProgramID');
        Map<Id, AttendancePeriod__c> AttendancePeriodMap = AttendancePeriodQueries.getAttendancePeriodMapWithProgramID(programIDs);
        List<AttendancePeriod> AttendancePeriods = new List<AttendancePeriod>();
        for(AttendancePeriod__c attprd : AttendancePeriodMap.values()){
            AttendancePeriods.add(new AttendancePeriod(attprd));
        }
        return AttendancePeriods;
     }
     
     public static Map<ID,List<AttendancePeriod>> getAttendancePeriodsByProgramIDWithProgramID(Set<ID> programIDs){
        System.debug('AttendancePeriodService.getAttendancePeriodsByProgramIDWithProgramID');
        List<AttendancePeriod> AttendancePeriods = AttendancePeriodService.getAttendancePeriodsWithProgramID(programIDs); 
        Map<Id, List<AttendancePeriod>> AttendancePeriodMap = new Map<Id, List<AttendancePeriod>>();
        for(AttendancePeriod attprd : AttendancePeriods){
             if(!AttendancePeriodMap.containsKey(attprd.ProgramId)){
                AttendancePeriodMap.put(attprd.ProgramId, new List<AttendancePeriod>());  
             } 
             AttendancePeriodMap.get(attprd.ProgramId).add(attprd);  
        }
        return AttendancePeriodMap;
     }
     
    public class AttendancePeriod{
        public String attendancePeriodID {get;set;}
        public String programID {get;set;}
        public Date AttendanceBeginDate {get;set;}
        public Date AttendanceEndDate {get;set;}
        
        public AttendancePeriod(){

        }
        
        public AttendancePeriod(AttendancePeriod__c attprd){
            this.attendancePeriodID = attprd.Id;
            this.ProgramId = attprd.program__c;
            this.AttendanceBeginDate = attprd.AttendanceBeginDate__c;
            this.AttendanceEndDate = attprd.AttendanceEndDate__c;
        }
    }
    public class AttendancePeriodServiceException extends Exception {}
}