vemo-mdapi-qa/objects/Bill__c.object
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Bill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>NextPaymentDue__c</fullName>
        <inlineHelpText>The amount of the next payment (due on the above date).</inlineHelpText>
        <label>Next Payment Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/StatementService_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: StatementService_TEST
// 
// Description: 
// 		Test class for StatementService
//
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-10   Jared Hagemann  Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class StatementService_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

	static testMethod void testGetCurrentStatementV1ByStudentWithStudentID(){
		Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<Id, StudentProgram__c> studProgramMap = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	for(StudentProgram__c sp : studProgramMap.values()){
    		sp.NextPaymentDue__c = 1000;
    	}
    	update studProgramMap.values();
    	
    	Test.startTest();
    	Map<ID, StatementService.StatementV1> statements =  StatementService.getCurrentStatementV1ByStudentWithStudentID(students.keySet());
    	Test.stopTest();
    	System.assertEquals(students.size(), statements.size());
    	for(StatementService.StatementV1 statement : statements.values()){
    		System.assertEquals(TestUtil.TEST_THROTTLE, statement.agreements.size());
    	}
	}

	static testMethod void testStatementV1(){
		Test.startTest();
		StatementService.StatementV1 statements = new StatementService.StatementV1(true);
		Test.stopTest();
		System.assert(true);

	}

	static testMethod void testCreateBillsFromStatements(){
		Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<Id, StudentProgram__c> studProgramMap = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, StatementService.StatementV1> statements =  StatementService.getCurrentStatementV1ByStudentWithStudentID(students.keySet());
    	Test.startTest();
    		StatementService.createBillsFromStatements(statements.values());
    	Test.stopTest();
    	List<Bill__c> bills = [select Id from Bill__c];
    	System.assertEquals(statements.size(), bills.size());
	}
}