vemo-mdapi-qa/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ContractTerm__c.object
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Contract Terms Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeBand__c.object
<CustomObject>
    <label>Income Band</label>
    <nameField>
        <displayFormat>IB-{0000000}</displayFormat>
        <label>Income Band Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Income Bands</relationshipLabel>
        <relationshipName>Income_Bands</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AgeOfMajorityRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age of Majority Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentBeginDate__c</fullName>
        <label>Enrollment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentEndDate__c</fullName>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentType__c</fullName>
        <description>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</description>
        <inlineHelpText>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</inlineHelpText>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Invite Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevelRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegistrationBeginDate__c</fullName>
        <label>Registration Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegistrationEndDate__c</fullName>
        <label>Registration End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ResidencyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residency Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>School Program of Study Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramEligibility__c.object
<CustomObject>
    <label>Program Eligibility</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Program Eligibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Eligibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>School_Programs_of_Study</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/TransactionSchedule__c.object
<CustomObject>
    <label>Disbursement Schedule</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Transaction_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/EnrollmentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Three Quarter Time</fullName>
    </customValue>
    <customValue>
        <fullName>Half Time</fullName>
    </customValue>
    <customValue>
        <fullName>Less than Half Time</fullName>
    </customValue>
    <masterLabel>Enrollment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/GradeLevel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/ProgramStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/Residency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US Citizen/Non-Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Naturalized Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Work Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Student Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Refugee/Asylee</fullName>
    </customValue>
    <masterLabel>Residency</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/OfferService_TEST.cls
@isTest
public with sharing class OfferService_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        for(Account stud : studentMap.values()){
            stud.PrimarySchool__pc = schoolMap.values()[0].id;
        }
        update studentMap.values();
        Map<ID, ProgramEligibility__c> eligibilityMap = TestDataFactory.createAndInsertProgramEligibility(2,programMap);
        Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(2);
        Map<ID, SchoolProgramsOfStudy__c> sposMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schoolMap, posMap);
        
        //Map<ID, ContractTerm__c> termMap = TestDataFactory.createAndInsertContractTerms(2,programMap);
        //Map<ID, TransactionSchedule__c> txSchMap = TestDataFactory.createAndInsertTransactionSchedule(2, programMap);
        //Map<ID, IncomeBand__c> bandMap = TestDataFactory.createAndInsertIncomeBands(1, sposMap);

    }
    @isTest public static void testOpenOffers() {
        //Test Case 1 - Any program with an enrollment type of open should appear in the list
        System.assertEquals(ProgramQueries.getProgramMap().size(), TestUtil.TEST_THROTTLE);
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMap();
        for(Program__c prog : programMap.values()){
            prog.EnrollmentType__c = 'Invite Only';
        }
        update programMap.values();
        Test.startTest();
        Map<ID, List<OfferService.Offer>> offersBefore = OfferService.getOffersByStudentIDWithStudentMap(studentMap);
        System.assertEquals(offersBefore.size(), 0, 'No Offers should exist');

        for(Program__c prog : programMap.values()){
            prog.EnrollmentType__c = 'Open';
        }
        update programMap.values();
        Map<ID, List<OfferService.Offer>> offersAfter = OfferService.getOffersByStudentIDWithStudentMap(studentMap);
        Test.stopTest();
        //todo System.assertEquals(offersAfter.size(), TestUtil.TEST_THROTTLE, 'Offers should exist');      
        
    }

    @isTest public static void testInvitedAgreements(){
        //Test Case - Any StudentProgram__c with a Status of Invited should appear in the list
        System.assertEquals(ProgramQueries.getProgramMap().size(), TestUtil.TEST_THROTTLE);
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMap();
        Map<ID, StudentProgram__c> agreementMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, 
                                                                                                studentMap, 
                                                                                                programMap);
        for(StudentProgram__c agreement : agreementMap.values()){
            agreement.Status__c = 'Application Complete';
        }                                   
        update agreementMap.values();

        Test.startTest();
        Map<ID, List<OfferService.Offer>> offersBefore = OfferService.getOffersByStudentIDWithStudentMap(studentMap);
        System.assertEquals(offersBefore.size(), 0, 'No Offers should exist');

        for(StudentProgram__c agreement : agreementMap.values()){
            agreement.Status__c = 'Invited';
        }
        update agreementMap.values();
        Map<ID, List<OfferService.Offer>> offersAfter = OfferService.getOffersByStudentIDWithStudentMap(studentMap);
        Test.stopTest();
        //todo System.assertEquals(offersAfter.size(), TestUtil.TEST_THROTTLE, 'Offers should exist');      
        

    }
    
    @isTest public static void testEligibleOffersWithCriteria(){
        //Test Case - All 'Invite Only' Offers for a particular school should be returned after chechking the Eligibilty against the given criteria 
        //Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMapWithSchoolID(schoolMap.keySet());
        Map<ID, ProgramEligibility__c> eligibilityMap = ProgramEligibilityQueries.getProgramEligibilityMap();
        Map<Id, SchoolProgramsOfStudy__c> sposMap = SchoolProgramsOfStudyQueries.getSchoolProgramOfStudyMapWithSchoolID(schoolMap.keySet());
        
        //Account student = studentMap.values()[0];
        Program__c prg = programMap.values()[0];
        SchoolProgramsOfStudy__c spos = sposMap.values()[0];
        ProgramEligibility__c eligibility = null;
        //find 1 eligibilty record for the selected program 
        for(ProgramEligibility__c elig:eligibilityMap.values()){
            if(elig.program__c == prg.id){
                eligibility = elig;
                break;
            }
        }
        
        //set required eligibity field on program
        prg.EnrollmentType__c = 'Invite Only';
        prg.ProgramStatus__c = 'Open';
        prg.EnrollmentBeginDate__c = Date.Today().addDays(-1);
        prg.EnrollmentEndDate__c = Date.Today().addDays(1);
        prg.RegistrationBeginDate__c = Date.Today().addDays(-1);
        prg.RegistrationEndDate__c = Date.Today().addDays(1);
        prg.GradeLevelRequired__c = true;
        prg.SchoolProgramOfStudyRequired__c = true;
        prg.ResidencyRequired__c = true;
        prg.EnrollmentStatusRequired__c = true;
        prg.AgeOfMajorityRequired__c = true;
        update prg;
        
        //set eligility record
        eligibility.EnrollmentStatus__c = 'Full Time';
        eligibility.GradeLevel__c = 'Senior';
        eligibility.Residency__c = 'US Citizen';
        eligibility.SchoolProgramOfStudy__c = spos.id;
        update eligibility;
        
        Test.startTest();        
        Map<ID,OfferService.Offer> resultMap = OfferService.getEligibleOffersByProgramIDWithCriteria(prg.School__c,'US Citizen',
                                                    'Full Time','Senior',spos.id,'CO',Date.newInstance(1991,1,1));
        System.assertEquals(1,resultMap.size());
        Test.stopTest();
    }
}