vemo-mdapi-qa/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Fee__c.object
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>FEE-{0000000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount of the fee.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Allocate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to allocate the payment manually</inlineHelpText>
        <label>Allocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-app/main/default/classes/PaymentInstructionTriggerHandler_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentInstructionTriggerHandler_TEST
// 
// Description: 
// 		Test class for PaymentInstructionTriggerHandler
//
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-17   Jared Hagemann  Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public with sharing class PaymentInstructionTriggerHandler_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(1);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInsturctionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);

    	//Add a few fees
    	//5 fees @ $1000 apiece
    	Map<ID, Fee__c> testFeeMap = TestDataFactory.createAndInsertFee(1, testStudentAccountMap);
    	
    	Map<Id, PaymentInstruction__c> paymenetInstructionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    }

	@isTest public static void testManageAllocations(){
    	Map<ID, PaymentInstruction__c> paymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMap();
    	paymentInstructionMap.values().get(0).Allocate__c = true;
    	paymentInstructionMap.values().get(0).Amount__c = 500;
    	Test.startTest();
    	update paymentInstructionMap.values();
    	Test.stopTest();
    	List<Case> cases = [select Id from Case];
    	System.assertEquals(1, cases.size());
	}
}