vemo-mdapi-qa/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Program</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Fee__c.object
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>FEE-{0000000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount of the fee.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>DateAssessed__c</fullName>
        <inlineHelpText>The date the fee was assessed.</inlineHelpText>
        <label>Date Assessed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateCleared__c</fullName>
        <inlineHelpText>The date the fee&#39;s payment cleared.</inlineHelpText>
        <label>Date Cleared</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Unpaid, Paid, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Late Fee or NSF Fee.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentAllocation__c.object
<CustomObject>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Payment Allocation.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AllocationType__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Allocation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>The amount of this Payment Allocation.</inlineHelpText>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <inlineHelpText>Details of this Payment Allocation (free-text field).</inlineHelpText>
        <label>Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Fee related to this Payment Allocation.</inlineHelpText>
        <label>Fee</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <inlineHelpText>The Payment Instruction related to this Payment Allocation.</inlineHelpText>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentAllocationDetail__c.object
<CustomObject>
    <label>Payment Allocation Detail</label>
    <nameField>
        <displayFormat>PADN-{0000000000}</displayFormat>
        <label>PaymentAllocationDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentAllocation__c</fullName>
        <label>Payment Allocation</label>
        <referenceTo>PaymentAllocation__c</referenceTo>
        <relationshipLabel>Payment Allocation Details</relationshipLabel>
        <relationshipName>Payment_Allocation_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>StudentProgramAmountDue__c</fullName>
        <label>Student Program Amount Due</label>
        <referenceTo>StudentProgramAmountDue__c</referenceTo>
        <relationshipLabel>Payment Allocation Details</relationshipLabel>
        <relationshipName>Payment_Allocation_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>Sum of the Payment Allocations for this Payment Instruction.</inlineHelpText>
        <label>Amount Allocated</label>
        <summarizedField>PaymentAllocation__c.AmountAllocated__c</summarizedField>
        <summaryForeignKey>PaymentAllocation__c.PaymentInstruction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FullyAllocated__c</fullName>
        <formula>IF( AmountAllocated__c =  Amount__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Checked if Amount Allocated is equal to Amount.</inlineHelpText>
        <label>Fully Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RemainingAllocation__c</fullName>
        <formula>Amount__c -  AmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount minus Amount Allocated.</inlineHelpText>
        <label>Remaining Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Scheduled_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <label>Amount Allocated</label>
        <summarizedField>PaymentAllocationDetail__c.AmountAllocated__c</summarizedField>
        <summaryForeignKey>PaymentAllocationDetail__c.StudentProgramAmountDue__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExcludeFromBalance__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates that an amount due should not be included in the account statement summaries. Used primarily for reconciliation amounts that are pre-assessed for future months, but which should not actually show up on the statement/bill until that month arrives</inlineHelpText>
        <label>Exclude from Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FullyAllocated__c</fullName>
        <formula>IF( AmountAllocated__c = Amount__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fully Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RemainingAllocation__c</fullName>
        <formula>Amount__c - AmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Monthly Status.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Monthly Status</relationshipLabel>
        <relationshipName>Student_Program_Monthly_Status</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/DebitType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/FeeStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Fee Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/FeeType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Late Fee</fullName>
    </customValue>
    <customValue>
        <fullName>NSF Fee</fullName>
    </customValue>
    <masterLabel>Fee Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/PaymentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/PaymentAllocationService.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentAllocationService
// 
// Description: 
// 	Handles all Agreement Service DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-10   Greg Cook       Created               
/////////////////////////////////////////////////////////////////////////
public with sharing class PaymentAllocationService {
	public class PaymentAllocation{
		AllocatedFee fee {get;set;}
		AllocatedAgreement agreement {get;set;}
	}
	public class PaymentInstruction{
		public ID paymentInstructionID {get;set;}
		public Decimal paymentAmount {get;set;}
		public Decimal remainingAllocation {get;set;}
		public List<PaymentAllocation> allocations {get;set;}

	}
	public class AllocatedFee{
		Decimal amount {get;set;}
	}
	public class AllocatedAgreement{
		String agreementID {get;set;}
		Decimal amount {get;set;}
		String type {get;set;}
	}

	public static List<PaymentInstruction> allocatePayment(ID paymentInstructionID, Boolean proofMode){
		return null;
// 		//THis is only able to operate on one paymentInstruction at a time as it needs to update the database and requery after each allocaiton in complete.
// 		//The best way to run this would be from a batch job set to a scope of 1 record or via a button on a payment instruciton screen
// 		List<PaymentInstruction> returnData = new List<PaymentInstruction>();
// 		String logEntry = 'PaymentAllocationService.allocatePayment()';
// 		////////////////////////////////////////////////////////////////////
// 		//GET ALL REQUIRED DATA STRUCTURES FOR ALLOCATIONS
// 		////////////////////////////////////////////////////////////////////		
// 		Map<ID, PaymentInstruction__c> paymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentInstructionID(new Set<ID>{paymentInstructionID});
// 		Map<ID, PaymentInstruction__c> paymentToAllocateMap = new Map<ID, PaymentInstruction__c>();
// 		Set<ID> studentIDs = new Set<ID>();
// 		Set<ID> studentContactIDs = new Set<ID>();

// 		//Set<ID> agreementIDs = new Set<ID>();


// 		for(PaymentInstruction__c payment : paymentInstructionMap.values()){
// 			if(!payment.fullyAllocated__c){
// 				paymentToAllocateMap.put(payment.id, payment);
// 				studentIDs.add(payment.Student__c);
// 				//agreementIDs.add(payment.Agreement__c);
// 			}
// 		}

// //		List<StudentService.Student> students = StudentService.getStudentsWithStudentID(studentIDs);
// //		Map<ID, StudentService.Student> studentMap = new Map<ID, StudentService.Student>();
// //		for(StudentService.Student student : students){
// //			studentMap.put(student.personAccountID, student);
// //		}

// 		Map<ID, Account> studentAccountMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
// 		for(Account student : studentAccountMap.values()){
// 			studentContactIDs.add(student.PersonContactID);
// 		}

// 		Map<ID, List<PaymentInstruction__c>> paymentsByStudent = new Map<ID, List<PaymentInstruction__c>>();
// 		for(PaymentInstruction__c payment : paymentToAllocateMap.values()){
// 			if(!paymentsByStudent.containsKey(payment.Student__c)){
// 				paymentsByStudent.put(payment.Student__c, new List<PaymentInstruction__c>());
// 			}
// 			paymentsByStudent.get(payment.Student__c).add(payment);
// 		}

// 		//Get all Agreements for these students
// 		List<AgreementService.Agreement> agreements = AgreementService.getAgreementWithStudentID(studentIDs);
// 		agreements.sort();
// 		System.debug('sorted agreements:'+ agreements);
// 		AgreementService.determineAmountsDue(agreements);
// 		Map<ID, List<AgreementService.Agreement>> agreementsByStudent = new Map<ID, List<AgreementService.Agreement>>();
// 		for(AgreementService.Agreement agree : agreements){
// 			if(!agreementsByStudent.containsKey(agree.studentID)){
// 				agreementsByStudent.put(agree.studentID, new List<AgreementService.Agreement>());
// 			}
// 			agreementsByStudent.get(agree.studentID).add(agree);
// 		}

// 		//Get all Open Allocation Cases for these students
// 		Map<ID, Case> openCaseMap = new Map<ID, Case>([SELECT id,
// 															  RecordTypeID,
// 															  ContactID,
// 															  Subject
// 													   FROM Case
// 													   WHERE RecordTypeID = :GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT) and
// 													   		 ContactID IN :studentContactIDs and 
// 													   		 Status != 'Closed' and
// 													   		 PaymentInstruction__c != null]);
// 		System.debug('openCaseMap:'+openCaseMap);
// 		Map<ID, List<Case>> casesByContactID = new Map<ID, List<Case>>();
// 		for(Case cse : openCaseMap.values()){
// 			if(!casesByContactID.containsKey(cse.ContactID)){
// 				casesByContactID.put(cse.ContactID, new List<Case>());
// 			}
// 			casesByContactID.get(cse.ContactID).add(cse);
// 		}



// /*
// 			                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
// 		                            ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
// 		                            Subject = 'Not enough funds on payment instruction to pay all open fees',
// 		                            Status = 'New',
// 		                            Priority = 'Medium',
// 		                            Reason = 'Other',
// 		                            OwnerId=GlobalUtil.getQueueId('Servicing'),
// 		                            Type = 'Problem',                                   
// 		                            Origin = 'Other',
// 		                            PaymentInstruction__c = payment.id));*/



// 		//Get All Fees for these students
// 		Map<ID, Fee__c> feeMap = new Map<ID, Fee__c>([SELECT id, Amount__c, Customer__c, DateAssessed__c, DateCleared__c, Status__c, Type__c
// 													   FROM Fee__c
// 													   WHERE Customer__c IN : studentIDs
// 													   and Status__c = 'Unpaid'
// 													   order by DateAssessed__c asc]);
// 		System.debug(feeMap);
// 		Map<ID, List<Fee__c>> feesByStudent = new Map<ID, List<Fee__c>>();
// 		for(Fee__c fee : feeMap.values()){
// 			if(!feesByStudent.containsKey(fee.Customer__c)){
// 				feesByStudent.put(fee.Customer__c, new List<Fee__c>());
// 			}
// 			feesByStudent.get(fee.Customer__c).add(fee);
// 		}
// 		System.debug(feesByStudent);

// 		List<Case> casesToCreate = new List<Case>();
// 		List<PaymentAllocation__c> paymentAllocationsToCreate = new List<PaymentAllocation__c>();
// 		Map<ID, Fee__c> feesToUpdate = new Map<ID, Fee__c>();


// 		////////////////////////////////////////////////////////////////////
// 		//Main Loop
// 		////////////////////////////////////////////////////////////////////
// 		Boolean continueAllocationProcess = true;	
// 		for(PaymentInstruction__c payment : paymentToAllocateMap.values()){
// 			if(continueAllocationProcess){
// 				//Decimal remainingToAllocate = payment.RemainingAllocation__c;

// 				PaymentInstruction paymentInst = new PaymentInstruction();
// 				paymentInst.paymentAmount = payment.Amount__c;
// 				paymentInst.remainingAllocation = payment.RemainingAllocation__c;
// 				System.debug('remainingToAllocate:'+paymentInst.remainingAllocation);
// 				paymentInst.paymentInstructionID = payment.id;
// 				paymentInst.allocations = new List<PaymentAllocation>();

// 				////////////////////////////////////////////////////////////////////
// 				//Pay all Fees First Starting with the Earliest
// 				////////////////////////////////////////////////////////////////////	
// 				//Look for any unpaid fees on this student that are less than or equal to the payment amount
// 				if(feesByStudent.containsKey(payment.Student__c)){
// 					System.debug('Fees');
// 					for(Fee__c fee : feesByStudent.get(payment.Student__c)){
// 						if(continueAllocationProcess){
// 							if(fee.Status__c == 'Unpaid'){ //don't pick up the unpaid fees a second time
// 								if(fee.Amount__c <= paymentInst.remainingAllocation){
// 									System.debug('pay this fee in full:'+ fee);
// 									paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Fee',
// 																							Fee__c = fee.id,
// 																							AmountAllocated__c = fee.Amount__c,
// 																							PaymentInstruction__c = payment.id));
// 									fee.DateCleared__c = Date.today();
// 									fee.Status__c = 'Paid';
// 									feesToUpdate.put(fee.id, fee);
// 									paymentInst.remainingAllocation -= fee.Amount__c;
// 									AllocatedFee allocFee = new AllocatedFee();
// 									allocFee.amount = fee.Amount__c;
// 									PaymentAllocation paymentAlloc = new PaymentAllocation();
// 									paymentAlloc.fee = allocFee;
// 									paymentInst.allocations.add(paymentAlloc);

// 								} else {
// 									if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
// 										//only create a new case if nothing else exists

// 										//not enough money on payment instruction to pay remaining fee - raise a case for servicing
// 										//this will create a case at each payment instruction - if there are multiple payment instructions for the same student a case would
// 										//still be created - so this would need to be refactored to only add a case if allpayments for the student were done being allocated
// 				                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
// 			                            ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
// 			                            Subject = 'Not enough funds on payment instruction to pay all open fees',
// 			                            Status = 'New',
// 			                            Priority = 'Medium',
// 			                            Reason = 'Other',
// 			                            OwnerId=GlobalUtil.getQueueId('Servicing'),
// 			                            Type = 'Problem',                                   
// 			                            Origin = 'Other',
// 			                            PaymentInstruction__c = payment.id));

// 									}
// 			                       	continueAllocationProcess = false;
// 								}

// 							}

// 						}
// 					}
// 				}


// 				////////////////////////////////////////////////////////////////////
// 				//Next Pay Past Due Reconciliations - Oldest Contract first
// 				////////////////////////////////////////////////////////////////////	
// 				if(continueAllocationProcess){
// 					System.debug('Past Due Reconciliations Amounts');
// 					if(agreementsByStudent.containsKey(payment.Student__c)){
// 						for(AgreementService.Agreement agree : agreementsByStudent.get(payment.Student__c)){
// 							System.debug('agree:'+agree);
// 							if(agree.reconciliationPastDue > 0){
// 								//allocate to this reconciliation
// 								Decimal allocation = 0;
// 								allocation = (paymentInst.remainingAllocation > agree.reconciliationPastDue ? agree.reconciliationPastDue : paymentInst.remainingAllocation);
// 								if(allocation>0){
// 									System.debug('Allocate to Past Due Reconciliation:'+allocation);
// 									paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Reconciliation',
// 																							Agreement__c = agree.agreementID,
// 																							AmountAllocated__c = allocation,
// 																							PaymentInstruction__c = payment.id,
// 																							Detail__c = 'Past Due Reconciliation'));
// 									paymentInst.remainingAllocation -= allocation;
// 									AllocatedAgreement allocAgreement = new AllocatedAgreement();
// 									allocAgreement.amount = allocation;
// 									allocAgreement.type = 'Past Due Reconciliation';
// 									allocAgreement.agreementID = agree.agreementID;
// 									PaymentAllocation paymentAlloc = new PaymentAllocation();
// 									paymentAlloc.agreement = allocAgreement;
// 									paymentInst.allocations.add(paymentAlloc);										
// 								}
// 							}
// 						}
// 					}
// 				}

// 				////////////////////////////////////////////////////////////////////
// 				//Next Pay Current Reconciliations - Oldest Contract first
// 				////////////////////////////////////////////////////////////////////
// 				if(continueAllocationProcess){
// 					System.debug('Current Reconciliations Amounts');
// 					if(agreementsByStudent.containsKey(payment.Student__c)){
// 						for(AgreementService.Agreement agree : agreementsByStudent.get(payment.Student__c)){
// 							System.debug('agree:'+agree);
// 							if(agree.reconciliationCurrentDue > 0){
// 								//allocate to this reconciliation
// 								Decimal allocation = 0;
// 								allocation = (paymentInst.remainingAllocation > agree.reconciliationCurrentDue ? agree.reconciliationCurrentDue : paymentInst.remainingAllocation);
// 								if(allocation>0){
// 									System.debug('Allocate to Current Reconciliation:'+allocation);
// 									paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Reconciliation',
// 																							Agreement__c = agree.agreementID,
// 																							AmountAllocated__c = allocation,
// 																							PaymentInstruction__c = payment.id,
// 																							Detail__c = 'Current Due Reconciliation'));
// 									paymentInst.remainingAllocation -= allocation;
// 									AllocatedAgreement allocAgreement = new AllocatedAgreement();
// 									allocAgreement.amount = allocation;
// 									allocAgreement.type = 'Current Due Reconciliation';
// 									allocAgreement.agreementID = agree.agreementID;								
// 									PaymentAllocation paymentAlloc = new PaymentAllocation();
// 									paymentAlloc.agreement = allocAgreement;
// 									paymentInst.allocations.add(paymentAlloc);											
// 								}								
// 							}
// 						}
// 					}
// 				}
// 				////////////////////////////////////////////////////////////////////
// 				//Next Pay Past Due Monthly Amounts - Oldest Contract first
// 				////////////////////////////////////////////////////////////////////	
// 				if(continueAllocationProcess){
// 					System.debug('Past Due Monthly Amounts');
// 					if(agreementsByStudent.containsKey(payment.Student__c)){
// 						for(AgreementService.Agreement agree : agreementsByStudent.get(payment.Student__c)){
// 							System.debug('agree:'+agree);
// 							if(agree.monthlyAmountPastDue > 0){
// 								//allocate to this reconciliation
// 								Decimal allocation = 0;
// 								allocation = (paymentInst.remainingAllocation > agree.monthlyAmountPastDue ? agree.monthlyAmountPastDue : paymentInst.remainingAllocation);
// 								if(allocation>0){
// 									System.debug('Allocate to Past Due Monthly Amounts:'+allocation);
// 									paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Monthly Amount',
// 																							Agreement__c = agree.agreementID,
// 																							AmountAllocated__c = allocation,
// 																							PaymentInstruction__c = payment.id,
// 																							Detail__c = 'Monthly Amount Past Due'));
// 									paymentInst.remainingAllocation -= allocation;
// 									AllocatedAgreement allocAgreement = new AllocatedAgreement();
// 									allocAgreement.amount = allocation;
// 									allocAgreement.type = 'Monthly Amount Past Due';
// 									allocAgreement.agreementID = agree.agreementID;
// 									PaymentAllocation paymentAlloc = new PaymentAllocation();
// 									paymentAlloc.agreement = allocAgreement;
// 									paymentInst.allocations.add(paymentAlloc);											
// 								}
// 							}
// 						}
// 					}
// 				}
// 				////////////////////////////////////////////////////////////////////
// 				//Next Pay Current Monthly Amounts - Oldest Contract first
// 				////////////////////////////////////////////////////////////////////
// 				if(continueAllocationProcess){
// 					System.debug('Current Monthly Amounts');
// 					if(agreementsByStudent.containsKey(payment.Student__c)){
// 						Boolean remainingCurrentAmount = false;
// 						System.debug('remainingCurrentAmount = false - entering loop');
// 						for(AgreementService.Agreement agree : agreementsByStudent.get(payment.Student__c)){
// 							System.debug('agree:'+agree);
// 							if(agree.monthlyAmountCurrentDue > 0){
// 								remainingCurrentAmount = true;
// 								//allocate to this reconciliation
// 								Decimal allocation = 0;
// 								allocation = (paymentInst.remainingAllocation >= agree.monthlyAmountCurrentDue ? agree.monthlyAmountCurrentDue : paymentInst.remainingAllocation);
// 								if(allocation>0){
// 									System.debug('Allocate to Current Month Due:'+allocation);
// 									paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Monthly Amount',
// 																							Agreement__c = agree.agreementID,
// 																							AmountAllocated__c = allocation,
// 																							PaymentInstruction__c = payment.id,
// 																							Detail__c = 'Monthly Amount Current Due'));
// 									paymentInst.remainingAllocation -= allocation;
// 									AllocatedAgreement allocAgreement = new AllocatedAgreement();
// 									allocAgreement.amount = allocation;
// 									allocAgreement.type = 'Monthly Amount Current Due';
// 									allocAgreement.agreementID = agree.agreementID;
// 									PaymentAllocation paymentAlloc = new PaymentAllocation();
// 									paymentAlloc.agreement = allocAgreement;
// 									paymentInst.allocations.add(paymentAlloc);
// 									System.debug('adding allocation:'+paymentAlloc);										
// 								}
// 								System.debug('allocation:'+allocation);
// 								System.debug('agree.monthlyAmountCurrentDue'+agree.monthlyAmountCurrentDue);
// 								if(agree.monthlyAmountCurrentDue > allocation){
// 									remainingCurrentAmount = true;
// 									System.debug('remainingCurrentAmount = true');
// 								} else {
// 									remainingCurrentAmount = false;
// 									System.debug('remainingCurrentAmount = false');
// 								}
// 							}
// 						}
// 						if(remainingCurrentAmount){
// 							System.debug('Create the case');
// 							if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
// 								//only create a new case if nothing else exists

// 		                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
// 	                            ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
// 	                            Subject = 'Underpayment of current amount due',
// 	                            Status = 'New',
// 	                            Priority = 'Medium',
// 	                            Reason = 'Other',
// 	                            OwnerId=GlobalUtil.getQueueId('Servicing'),
// 	                            Type = 'Problem',                                   
// 	                            Origin = 'Other',
// 	                            PaymentInstruction__c = payment.id));

// 							}	
// 	                       	continueAllocationProcess = false;													
// 						}
// 					}
// 				}

// 				////////////////////////////////////////////////////////////////////
// 				//Any remaining amount to be allocated
// 				////////////////////////////////////////////////////////////////////
// 				if(continueAllocationProcess){
// 					System.debug('Overpayment');
// 					if(paymentInst.remainingAllocation > 0){
// 						if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
// 							//only create a new case if nothing else exists

// 							//not enough money on payment instruction to pay remaining fee - raise a case for servicing
// 							//this will create a case at each payment instruction - if there are multiple payment instructions for the same student a case would
// 							//still be created - so this would need to be refactored to only add a case if allpayments for the student were done being allocated
// 	                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
//                             ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
//                             Subject = 'Overpayment',
//                             Status = 'New',
//                             Priority = 'Medium',
//                             Reason = 'Other',
//                             OwnerId=GlobalUtil.getQueueId('Servicing'),
//                             Type = 'Problem',                                   
//                             Origin = 'Other',
//                             PaymentInstruction__c = payment.id));

// 						}	
// 						continueAllocationProcess = false;					
// 					}
// 				}


// 				////////////////////////////////////////////////////////////////////
// 				//Any Remainder of the Payment Should be credited to account or pre-allocated
// 				//to agreements in the future
// 				////////////////////////////////////////////////////////////////////					

// 				returnData.add(paymentInst);
				
// 				logEntry += '\n PaymentInstructionAmount: '+ paymentInst.paymentAmount;
// 				logEntry += '\n PaymentInstructionID: ' + paymentInst.paymentInstructionID;
// 				logEntry += '\n PaymentInstructionRemainingAllocation: '+ paymentInst.remainingAllocation;
// 				for(PaymentAllocation pa : paymentInst.allocations){
// 					logEntry += '\n PaymentAllocation: '+pa;
// 				}				
// 				LogService.debug(logEntry, payment.id);
// 				logEntry = '';
// 			}

// 		}
// 		LogService.writeLogs();


// 		////////////////////////////////////////////////////////////////////
// 		//Update Tables 
// 		////////////////////////////////////////////////////////////////////	
// 		if(!proofMode){
// 			if(paymentAllocationsToCreate.size()>0){
// 				System.debug(paymentAllocationsToCreate);
// 				insert paymentAllocationsToCreate;
// 			}
// 			if(feesToUpdate.size()>0){
// 				System.debug(feesToUpdate);
// 				update feesToUpdate.values();
// 			}
// 			if(casesToCreate.size()>0){
// 				insert casesToCreate;
// 			}			
// 		}
// 		System.debug(returnData);
// 		return returnData;
	}

	public static List<PaymentInstruction> allocatePaymentV2(ID paymentInstructionID, Boolean proofMode){

		//override v2 until data conversion is ready
//		return allocatePayment(paymentInstructionID, proofMode);
		//THis is only able to operate on one paymentInstruction at a time as it needs to update the database and requery after each allocaiton in complete.
		//The best way to run this would be from a batch job set to a scope of 1 record or via a button on a payment instruciton screen
		List<PaymentInstruction> returnData = new List<PaymentInstruction>();
		String logEntry = 'PaymentAllocationService.allocatePaymentV2()';
		////////////////////////////////////////////////////////////////////
		//GET ALL REQUIRED DATA STRUCTURES FOR ALLOCATIONS
		////////////////////////////////////////////////////////////////////		
		Map<ID, PaymentInstruction__c> paymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentInstructionID(new Set<ID>{paymentInstructionID});
		Map<ID, PaymentInstruction__c> paymentToAllocateMap = new Map<ID, PaymentInstruction__c>();
		Set<ID> studentIDs = new Set<ID>();
		Set<ID> studentContactIDs = new Set<ID>();



		for(PaymentInstruction__c payment : paymentInstructionMap.values()){
			if(!payment.fullyAllocated__c){
				paymentToAllocateMap.put(payment.id, payment);
				studentIDs.add(payment.Student__c);
			}
		}



		Map<ID, Account> studentAccountMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
		for(Account student : studentAccountMap.values()){
			studentContactIDs.add(student.PersonContactID);
		}

		Map<ID, List<PaymentInstruction__c>> paymentsByStudent = new Map<ID, List<PaymentInstruction__c>>();
		for(PaymentInstruction__c payment : paymentToAllocateMap.values()){
			if(!paymentsByStudent.containsKey(payment.Student__c)){
				paymentsByStudent.put(payment.Student__c, new List<PaymentInstruction__c>());
			}
			paymentsByStudent.get(payment.Student__c).add(payment);
		}

		//Get all Agreements for these students
		List<AgreementService.Agreement> agreements = AgreementService.getAgreementWithStudentID(studentIDs);
		agreements.sort();
		System.debug('sorted agreements:'+ agreements);
		AgreementService.determineAmountsDue(agreements);
		Map<ID, List<AgreementService.Agreement>> agreementsByStudent = new Map<ID, List<AgreementService.Agreement>>();

		Set<ID> agreementIDs = new Set<ID>();
		for(AgreementService.Agreement agree : agreements){
			agreementIDs.add(agree.agreementID);
			if(!agreementsByStudent.containsKey(agree.studentID)){
				agreementsByStudent.put(agree.studentID, new List<AgreementService.Agreement>());
			}
			agreementsByStudent.get(agree.studentID).add(agree);
		}

		//Get all Open Allocation Cases for these students
		Map<ID, Case> openCaseMap = new Map<ID, Case>([SELECT id,
															  RecordTypeID,
															  ContactID,
															  Subject
													   FROM Case
													   WHERE RecordTypeID = :GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT) and
													   		 ContactID IN :studentContactIDs and 
													   		 Status != 'Closed' and
													   		 PaymentInstruction__c != null]);
		System.debug('openCaseMap:'+openCaseMap);
		Map<ID, List<Case>> casesByContactID = new Map<ID, List<Case>>();
		for(Case cse : openCaseMap.values()){
			if(!casesByContactID.containsKey(cse.ContactID)){
				casesByContactID.put(cse.ContactID, new List<Case>());
			}
			casesByContactID.get(cse.ContactID).add(cse);
		}

		//Get All Fees for these students
		Map<ID, Fee__c> feeMap = new Map<ID, Fee__c>([SELECT id, Amount__c, Customer__c, DateAssessed__c, DateCleared__c, Status__c, Type__c
													   FROM Fee__c
													   WHERE Customer__c IN : studentIDs
													   and Status__c = 'Unpaid'
													   order by DateAssessed__c asc]);
		System.debug(feeMap);
		Map<ID, List<Fee__c>> feesByStudent = new Map<ID, List<Fee__c>>();
		for(Fee__c fee : feeMap.values()){
			if(!feesByStudent.containsKey(fee.Customer__c)){
				feesByStudent.put(fee.Customer__c, new List<Fee__c>());
			}
			feesByStudent.get(fee.Customer__c).add(fee);
		}
		System.debug(feesByStudent);

		List<Case> casesToCreate = new List<Case>();
		List<PaymentAllocation__c> paymentAllocationsToCreate = new List<PaymentAllocation__c>();
		List<PaymentAllocationDetail__c> paymentAllocationDetailsToCreate = new List<PaymentAllocationDetail__c>();
		Map<ID, Fee__c> feesToUpdate = new Map<ID, Fee__c>();

		//Get all the amount due records for 
		Map<ID, StudentProgramAmountDue__c> amountDueMap = new Map<ID, StudentProgramAmountDue__c>([SELECT id,
																										   Agreement__c,
																										   Amount__c,
																										   AmountAllocated__c,
																										   AssessmentDateTime__c,
																										   ExcludeFromBalance__c,
																										   FullyAllocated__c,
																										   RemainingAllocation__c,
																										   StudentProgramMonthlyStatus__c,
																										   Type__c
																								    FROM StudentProgramAmountDue__c
																								    WHERE Agreement__c in :agreementIDs and
																								    	  FullyAllocated__c = false
																								    Order BY AssessmentDateTime__c ASC,
																											 Agreement__r.CertificationDate__c ASC, 
																											 Agreement__r.SubmittedDate__c ASC]);

		Map<ID, StudentProgramAmountDue__c> pastDueReconciliation = new Map<ID, StudentProgramAmountDue__c>();
		Map<ID, StudentProgramAmountDue__c> currentReconciliation = new Map<ID, StudentProgramAmountDue__c>();
		Map<ID, StudentProgramAmountDue__c> pastDueAmountDue = new Map<ID, StudentProgramAmountDue__c>();
		Map<ID, StudentProgramAmountDue__c> currentAmountDue = new Map<ID, StudentProgramAmountDue__c>();

		System.debug(amountDueMap);
		for(StudentProgramAmountDue__c amountDue : amountDueMap.values()){
			System.debug('Date.today().month():'+Date.today().month());
			System.debug('amountDue.AssessmentDateTime__c:'+amountDue.AssessmentDateTime__c);
			if((amountDue.AssessmentDateTime__c.month() < Date.today().month() &&
				amountDue.AssessmentDateTime__c.year() == Date.today().year()) ||
				amountDue.AssessmentDateTime__c.year() < Date.today().year()){
				//Past Due Amount
				if(amountDue.Type__c == 'Reconciliation'){
					pastDueReconciliation.put(amountDue.id, amountDue);
				} else if(amountDue.Type__c == 'Monthly Amount'){
					pastDueAmountDue.put(amountDue.id, amountDue);
				}
			} else {
				if(amountDue.Type__c == 'Reconciliation'){
					currentReconciliation.put(amountDue.id, amountDue);
				} else if(amountDue.Type__c == 'Monthly Amount'){
					currentAmountDue.put(amountDue.id, amountDue);
				}
			}
			
		}
		System.debug('pastDueReconciliation:'+pastDueReconciliation);
		System.debug('currentReconciliation:'+currentReconciliation);
		System.debug('pastDueAmountDue:'+pastDueAmountDue);
		System.debug('currentAmountDue:'+currentAmountDue);

		////////////////////////////////////////////////////////////////////
		//Main Loop
		////////////////////////////////////////////////////////////////////
		Boolean continueAllocationProcess = true;	
		for(PaymentInstruction__c payment : paymentToAllocateMap.values()){
			if(continueAllocationProcess){
				//Decimal remainingToAllocate = payment.RemainingAllocation__c;

				PaymentInstruction paymentInst = new PaymentInstruction();
				paymentInst.paymentAmount = payment.Amount__c;
				paymentInst.remainingAllocation = payment.RemainingAllocation__c;
				System.debug('remainingToAllocate:'+paymentInst.remainingAllocation);
				paymentInst.paymentInstructionID = payment.id;
				paymentInst.allocations = new List<PaymentAllocation>();

				////////////////////////////////////////////////////////////////////
				//Pay all Fees First Starting with the Earliest
				////////////////////////////////////////////////////////////////////	
				//Look for any unpaid fees on this student that are less than or equal to the payment amount
				if(feesByStudent.containsKey(payment.Student__c)){
					System.debug('Fees');
					for(Fee__c fee : feesByStudent.get(payment.Student__c)){
						if(continueAllocationProcess){
							if(fee.Status__c == 'Unpaid'){ //don't pick up the unpaid fees a second time
								if(fee.Amount__c <= paymentInst.remainingAllocation){
									System.debug('pay this fee in full:'+ fee);
									paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Fee',
																							Fee__c = fee.id,
																							AmountAllocated__c = fee.Amount__c,
																							PaymentInstruction__c = payment.id));
									fee.DateCleared__c = Date.today();
									fee.Status__c = 'Paid';
									feesToUpdate.put(fee.id, fee);
									paymentInst.remainingAllocation -= fee.Amount__c;
									AllocatedFee allocFee = new AllocatedFee();
									allocFee.amount = fee.Amount__c;
									PaymentAllocation paymentAlloc = new PaymentAllocation();
									paymentAlloc.fee = allocFee;
									paymentInst.allocations.add(paymentAlloc);

								} else {
									if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
										//only create a new case if nothing else exists

										//not enough money on payment instruction to pay remaining fee - raise a case for servicing
										//this will create a case at each payment instruction - if there are multiple payment instructions for the same student a case would
										//still be created - so this would need to be refactored to only add a case if allpayments for the student were done being allocated
				                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
			                            ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
			                            Subject = 'Not enough funds on payment instruction to pay all open fees',
			                            Status = 'New',
			                            Priority = 'Medium',
			                            Reason = 'Other',
			                            OwnerId=GlobalUtil.getQueueId('Servicing'),
			                            Type = 'Problem',                                   
			                            Origin = 'Other',
			                            PaymentInstruction__c = payment.id));

									}
			                       	continueAllocationProcess = false;
								}

							}

						}
					}
				}

				////////////////////////////////////////////////////////////////////
				//Next Pay Past Due Reconciliations - Oldest Reconciliation first
				////////////////////////////////////////////////////////////////////	
				if(continueAllocationProcess){
					System.debug('Past Due Reconciliations Amounts');
					for(StudentProgramAmountDue__c amountDue : pastDueReconciliation.values()){
						System.debug('amountDue:'+amountDue);
						//Allocate to this reconciliation
						Decimal allocation = 0;
						allocation = (paymentInst.remainingAllocation > amountDue.RemainingAllocation__c ? amountDue.RemainingAllocation__c : paymentInst.remainingAllocation);
						if(allocation > 0){
							String allocationGUID = GlobalUtil.createGUID();
							paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Reconciliation',
																					Agreement__c = amountDue.Agreement__c,
																					AllocationGUID__c = allocationGUID,
																					AmountAllocated__c = allocation,
																					PaymentInstruction__c = payment.id,
																					Detail__c = 'Past Due Reconciliation: '+ String.valueOf(amountDue.AssessmentDateTime__c)));
							PaymentAllocationDetail__c allocDetail = new PaymentAllocationDetail__c();
							PaymentAllocation__c parentAlloc = new PaymentAllocation__c(AllocationGUID__c = allocationGUID);
							allocDetail.PaymentAllocation__r = parentAlloc;//.AllocationGUID__c = allocationGUID;
							allocDetail.StudentProgramAmountDue__c = amountDue.id;
							allocDetail.AmountAllocated__c = allocation;

							paymentAllocationDetailsToCreate.add(allocDetail);

							paymentInst.remainingAllocation -= allocation;
							AllocatedAgreement allocAgreement = new AllocatedAgreement();
							allocAgreement.amount = allocation;
							allocAgreement.type = 'Past Due Reconciliation';
							allocAgreement.agreementID = amountDue.Agreement__c;
							PaymentAllocation paymentAlloc = new PaymentAllocation();
							paymentAlloc.agreement = allocAgreement;
							paymentInst.allocations.add(paymentAlloc);	

						}

					}
				}

				////////////////////////////////////////////////////////////////////
				//Next Pay Current  Reconciliations - Oldest Current (and oldest Contract) first
				////////////////////////////////////////////////////////////////////	
				if(continueAllocationProcess){
					System.debug('Current Reconciliations Amounts');
					for(StudentProgramAmountDue__c amountDue : currentReconciliation.values()){
						System.debug('amountDue:'+amountDue);
						//Allocate to this reconciliation
						Decimal allocation = 0;
						allocation = (paymentInst.remainingAllocation > amountDue.RemainingAllocation__c ? amountDue.RemainingAllocation__c : paymentInst.remainingAllocation);
						if(allocation > 0){
							String allocationGUID = GlobalUtil.createGUID();
							paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Reconciliation',
																					Agreement__c = amountDue.Agreement__c,
																					AllocationGUID__c = allocationGUID,
																					AmountAllocated__c = allocation,
																					PaymentInstruction__c = payment.id,
																					Detail__c = 'Current Due Reconciliation: '+ String.valueOf(amountDue.AssessmentDateTime__c)));
							PaymentAllocationDetail__c allocDetail = new PaymentAllocationDetail__c();
							PaymentAllocation__c parentAlloc = new PaymentAllocation__c(AllocationGUID__c = allocationGUID);
							allocDetail.PaymentAllocation__r = parentAlloc;//.AllocationGUID__c = allocationGUID;
							allocDetail.StudentProgramAmountDue__c = amountDue.id;
							allocDetail.AmountAllocated__c = allocation;

							paymentAllocationDetailsToCreate.add(allocDetail);

							paymentInst.remainingAllocation -= allocation;
							AllocatedAgreement allocAgreement = new AllocatedAgreement();
							allocAgreement.amount = allocation;
							allocAgreement.type = 'Current Due Reconciliation';
							allocAgreement.agreementID = amountDue.Agreement__c;
							PaymentAllocation paymentAlloc = new PaymentAllocation();
							paymentAlloc.agreement = allocAgreement;
							paymentInst.allocations.add(paymentAlloc);	

						}

					}

				}

				////////////////////////////////////////////////////////////////////
				//Next Pay PMonthly Amount Past Due - Oldest Amount Due first
				////////////////////////////////////////////////////////////////////	
				if(continueAllocationProcess){
					System.debug('Past Due Monthly Amounts');
					for(StudentProgramAmountDue__c amountDue : pastDueAmountDue.values()){
						System.debug('amountDue:'+amountDue);
						//Allocate to this reconciliation
						Decimal allocation = 0;
						allocation = (paymentInst.remainingAllocation > amountDue.RemainingAllocation__c ? amountDue.RemainingAllocation__c : paymentInst.remainingAllocation);
						if(allocation > 0){
							String allocationGUID = GlobalUtil.createGUID();
							paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Monthly Amount',
																					Agreement__c = amountDue.Agreement__c,
																					AllocationGUID__c = allocationGUID,
																					AmountAllocated__c = allocation,
																					PaymentInstruction__c = payment.id,
																					Detail__c = 'Monthly Amount Past Due: '+ String.valueOf(amountDue.AssessmentDateTime__c)));
							PaymentAllocationDetail__c allocDetail = new PaymentAllocationDetail__c();
							PaymentAllocation__c parentAlloc = new PaymentAllocation__c(AllocationGUID__c = allocationGUID);
							allocDetail.PaymentAllocation__r = parentAlloc;//.AllocationGUID__c = allocationGUID;
							allocDetail.StudentProgramAmountDue__c = amountDue.id;
							allocDetail.AmountAllocated__c = allocation;

							paymentAllocationDetailsToCreate.add(allocDetail);

							paymentInst.remainingAllocation -= allocation;
							AllocatedAgreement allocAgreement = new AllocatedAgreement();
							allocAgreement.amount = allocation;
							allocAgreement.type = 'Monthly Amount Past Due';
							allocAgreement.agreementID = amountDue.Agreement__c;
							PaymentAllocation paymentAlloc = new PaymentAllocation();
							paymentAlloc.agreement = allocAgreement;
							paymentInst.allocations.add(paymentAlloc);	

						}

					}
				}

				////////////////////////////////////////////////////////////////////
				//Next Pay Current  Monthly Amount Due - Oldest Current (and oldest Contract) first
				////////////////////////////////////////////////////////////////////	
				if(continueAllocationProcess){
					Boolean remainingCurrentAmount = false;
					System.debug('Monthly Amount Current Due');
					for(StudentProgramAmountDue__c amountDue : currentAmountDue.values()){
						System.debug('amountDue:'+amountDue);
						//Allocate to this reconciliation
						Decimal allocation = 0;
						allocation = (paymentInst.remainingAllocation > amountDue.RemainingAllocation__c ? amountDue.RemainingAllocation__c : paymentInst.remainingAllocation);
						if(allocation > 0){
							String allocationGUID = GlobalUtil.createGUID();
							paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Monthly Amount',
																					Agreement__c = amountDue.Agreement__c,
																					AllocationGUID__c = allocationGUID,
																					AmountAllocated__c = allocation,
																					PaymentInstruction__c = payment.id,
																					Detail__c = 'Monthly Amount Current Due: '+ String.valueOf(amountDue.AssessmentDateTime__c)));
							PaymentAllocationDetail__c allocDetail = new PaymentAllocationDetail__c();
							PaymentAllocation__c parentAlloc = new PaymentAllocation__c(AllocationGUID__c = allocationGUID);
							allocDetail.PaymentAllocation__r = parentAlloc;//.AllocationGUID__c = allocationGUID;
							allocDetail.StudentProgramAmountDue__c = amountDue.id;
							allocDetail.AmountAllocated__c = allocation;

							paymentAllocationDetailsToCreate.add(allocDetail);

							paymentInst.remainingAllocation -= allocation;
							AllocatedAgreement allocAgreement = new AllocatedAgreement();
							allocAgreement.amount = allocation;
							allocAgreement.type = 'Monthly Amount Current Due';
							allocAgreement.agreementID = amountDue.Agreement__c;
							PaymentAllocation paymentAlloc = new PaymentAllocation();
							paymentAlloc.agreement = allocAgreement;
							paymentInst.allocations.add(paymentAlloc);	

						} else {
							remainingCurrentAmount = true;
							System.debug('remainingCurrentAmount = true');
						}

					}
					if(remainingCurrentAmount){
						System.debug('Create the case');
						if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
							//only create a new case if nothing else exists

	                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
                           ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
                           Subject = 'Underpayment of current amount due',
                           Status = 'New',
                           Priority = 'Medium',
                           Reason = 'Other',
                           OwnerId=GlobalUtil.getQueueId('Servicing'),
                           Type = 'Problem',                                   
                           Origin = 'Other',
                           PaymentInstruction__c = payment.id));

						}	
                      	continueAllocationProcess = false;			

                   }										


				}

//here


				//////////////////////////////////////////////////////////////////////
				////Next Pay Current Monthly Amounts - Oldest Contract first
				//////////////////////////////////////////////////////////////////////
				//if(continueAllocationProcess){
				//	System.debug('Current Monthly Amounts');
				//	if(agreementsByStudent.containsKey(payment.Student__c)){
				//		Boolean remainingCurrentAmount = false;
				//		System.debug('remainingCurrentAmount = false - entering loop');
				//		for(AgreementService.Agreement agree : agreementsByStudent.get(payment.Student__c)){
				//			System.debug('agree:'+agree);
				//			if(agree.monthlyAmountCurrentDue > 0){
				//				remainingCurrentAmount = true;
				//				//allocate to this reconciliation
				//				Decimal allocation = 0;
				//				allocation = (paymentInst.remainingAllocation >= agree.monthlyAmountCurrentDue ? agree.monthlyAmountCurrentDue : paymentInst.remainingAllocation);
				//				if(allocation>0){
				//					System.debug('Allocate to Current Month Due:'+allocation);
				//					paymentAllocationsToCreate.add(new PaymentAllocation__c(AllocationType__c = 'Monthly Amount',
				//																			Agreement__c = agree.agreementID,
				//																			AmountAllocated__c = allocation,
				//																			PaymentInstruction__c = payment.id,
				//																			Detail__c = 'Monthly Amount Current Due'));
				//					paymentInst.remainingAllocation -= allocation;
				//					AllocatedAgreement allocAgreement = new AllocatedAgreement();
				//					allocAgreement.amount = allocation;
				//					allocAgreement.type = 'Monthly Amount Current Due';
				//					allocAgreement.agreementID = agree.agreementID;
				//					PaymentAllocation paymentAlloc = new PaymentAllocation();
				//					paymentAlloc.agreement = allocAgreement;
				//					paymentInst.allocations.add(paymentAlloc);
				//					System.debug('adding allocation:'+paymentAlloc);										
				//				}
				//				System.debug('allocation:'+allocation);
				//				System.debug('agree.monthlyAmountCurrentDue'+agree.monthlyAmountCurrentDue);
				//				if(agree.monthlyAmountCurrentDue > allocation){
				//					remainingCurrentAmount = true;
				//					System.debug('remainingCurrentAmount = true');
				//				} else {
				//					remainingCurrentAmount = false;
				//					System.debug('remainingCurrentAmount = false');
				//				}
				//			}
				//		}
				//		if(remainingCurrentAmount){
				//			System.debug('Create the case');
				//			if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
				//				//only create a new case if nothing else exists

		  //                     casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
	   //                         ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
	   //                         Subject = 'Underpayment of current amount due',
	   //                         Status = 'New',
	   //                         Priority = 'Medium',
	   //                         Reason = 'Other',
	   //                         OwnerId=GlobalUtil.getQueueId('Servicing'),
	   //                         Type = 'Problem',                                   
	   //                         Origin = 'Other',
	   //                         PaymentInstruction__c = payment.id));

				//			}	
	   //                    	continueAllocationProcess = false;													
				//		}
				//	}
				//}

				////////////////////////////////////////////////////////////////////
				//Any remaining amount to be allocated
				////////////////////////////////////////////////////////////////////
				if(continueAllocationProcess){
					System.debug('Overpayment');
					if(paymentInst.remainingAllocation > 0){
						if(!casesByContactID.containsKey(studentAccountMap.get(payment.Student__c).PersonContactID)){
							//only create a new case if nothing else exists

							//not enough money on payment instruction to pay remaining fee - raise a case for servicing
							//this will create a case at each payment instruction - if there are multiple payment instructions for the same student a case would
							//still be created - so this would need to be refactored to only add a case if allpayments for the student were done being allocated
	                       casesToCreate.add(new Case(RecordTypeID = GlobalUtil.getRecordTypeIdByLabelName('Case', GlobalUtil.CASE_RECTYPELBL_DEFAULT),
                           ContactID = studentAccountMap.get(payment.Student__c).PersonContactID,
                           Subject = 'Overpayment',
                           Status = 'New',
                           Priority = 'Medium',
                           Reason = 'Other',
                           OwnerId=GlobalUtil.getQueueId('Servicing'),
                           Type = 'Problem',                                   
                           Origin = 'Other',
                           PaymentInstruction__c = payment.id));

						}	
						continueAllocationProcess = false;					
					}
				}


				////////////////////////////////////////////////////////////////////
				//Any Remainder of the Payment Should be credited to account or pre-allocated
				//to agreements in the future
				////////////////////////////////////////////////////////////////////					

				returnData.add(paymentInst);
				
				logEntry += '\n PaymentInstructionAmount: '+ paymentInst.paymentAmount;
				logEntry += '\n PaymentInstructionID: ' + paymentInst.paymentInstructionID;
				logEntry += '\n PaymentInstructionRemainingAllocation: '+ paymentInst.remainingAllocation;
				for(PaymentAllocation pa : paymentInst.allocations){
					logEntry += '\n PaymentAllocation: '+pa;
				}				
				LogService.debug(logEntry, payment.id);
				logEntry = '';
			}

		}
		LogService.writeLogs();


		////////////////////////////////////////////////////////////////////
		//Update Tables 
		////////////////////////////////////////////////////////////////////	
		if(!proofMode){
			if(paymentAllocationsToCreate.size()>0){
				System.debug(paymentAllocationsToCreate);
				insert paymentAllocationsToCreate;
			}
			if(paymentAllocationDetailsToCreate.size()>0){
				System.debug(paymentAllocationDetailsToCreate);
				insert paymentAllocationDetailsToCreate;
			}
			if(feesToUpdate.size()>0){
				System.debug(feesToUpdate);
				update feesToUpdate.values();
			}
			if(casesToCreate.size()>0){
				insert casesToCreate;
			}			
		}
		System.debug(returnData);
		return returnData;
	}



	public class AllocatePaymentQueueable implements Queueable, Database.AllowsCallouts {
		public AllocatePaymentQueueable(){
			
		}
		public AllocatePaymentQueueable(ID paymentInstructionID){
			this.paymentInstructionID = paymentInstructionID;
		}
	    public ID paymentInstructionID {get;set;}
	    public void execute(QueueableContext context) {
	    	system.debug('PaymentAllocationService.AllocatePaymentQueueable.execute()');
	    	PaymentAllocationService.allocatePaymentV2(this.paymentInstructionID, false);
	    }
	}	
}