vemo-mdapi-qa/objects/ClrHouseStudentEnrollment__c.object
<CustomObject>
    <label>ClearingHouse Enrollment</label>
    <nameField>
        <displayFormat>CHS-{00000000}</displayFormat>
        <label>ClrHouseStudentEnrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClearingHouse Enrollment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ClrHouseStudentEnrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>College_Name__c</fullName>
        <label>College Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_begin__c</fullName>
        <label>Enrollment begin</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_end__c</fullName>
        <label>Enrollment end</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_status__c</fullName>
        <label>Enrollment status</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduated__c</fullName>
        <label>Graduated?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduation_date__c</fullName>
        <label>Graduation date</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestorReturnField__c</fullName>
        <label>Requestor Return Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CertificationDate__c</fullName>
        <inlineHelpText>The date the Student Program was certified by a School Admin.</inlineHelpText>
        <label>Certification Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/ReportClearinghouseController_TEST.cls
@isTest
public class ReportClearinghouseController_TEST{
    @TestSetup static void setupData(){
        Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, StudentProgram__C> agreements = TestDataFactory.createAndInsertStudentProgram(1, students , programs);
        
        for(StudentProgram__c sp:agreements.values()){
            sp.certificationDate__c = Date.newInstance(2018,1,1);
            sp.status__c = 'Fully Funded';
        }
        update agreements.values();
        
        
        Map<ID, ClrHouseStudentEnrollment__c> clrHouseStudentEnrollmentMap = TestDataFactory.createAndInsertClrHouseStudentEnrollment(3,students);
        for(ClrHouseStudentEnrollment__c clrHouse:clrHouseStudentEnrollmentMap.values()){
            clrHouse.account__c = clrHouse.RequestorReturnField__c.removeEnd('_');
            clrHouse.Enrollment_status__c = 'F';
            clrHouse.Graduated__c = 'N';
            clrHouse.Enrollment_begin__c = '20180101';
            clrHouse.Enrollment_end__c = '20190101';
        }
        update clrHouseStudentEnrollmentMap.values();
        
    }
    
    //////////////////////////////////////////////////////////////////////
    ///Test Case 1: Only 1 student should appear in the final reportData
    //////////////////////////////////////////////////////////////////////
    @isTest public static void validateRunReport(){
        
        List<ClrHouseStudentEnrollment__c> clrHouseEnrollmentList = [SELECT id,name,Enrollment_status__c,Graduated__c,Graduation_date__c,
                                                                     Enrollment_begin__c,Enrollment_end__c,College_Name__c,account__c
                                                                     FROM ClrHouseStudentEnrollment__c];
        
        Map<ID,List<ClrHouseStudentEnrollment__c>> clrHouseEnrollmentsByStudent = new Map<ID,List<ClrHouseStudentEnrollment__c>>();
        for(ClrHouseStudentEnrollment__c clrHouse:clrHouseEnrollmentList){
                if(!clrHouseEnrollmentsByStudent.containsKey(clrHouse.account__c)){
                    clrHouseEnrollmentsByStudent.put(clrHouse.account__c,new List<ClrHouseStudentEnrollment__c>());
                }
                clrHouseEnrollmentsByStudent.get(clrHouse.account__c).add(clrHouse);
        }
        
        for(ID studentID:clrHouseEnrollmentsByStudent.keySet()){
            for(ClrHouseStudentEnrollment__c clrHouse:clrHouseEnrollmentsByStudent.get(studentID)){
                clrHouse.Enrollment_status__c = 'L';
                break;
            }
            update clrHouseEnrollmentsByStudent.get(studentID);
            break;
        }
        
        Test.StartTest(); 

            ReportClearinghouseController  cntrl = new ReportClearinghouseController();
            List<SelectOption> schools = cntrl.getSchools();
            cntrl.selectedSchool = schools[0].getValue();
            cntrl.runReport();
            System.assertEquals(1,cntrl.reportData.size(),'Number of rows in report should be 1');
        
        Test.StopTest();    
    }
    
}