vemo-mdapi-qa/objects/ContractTerm__c.object
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Contract Terms Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AdjustmentMethod__c</fullName>
        <label>Adjustment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ContractTermsAdjustmentMethod</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EarningsGroup__c</fullName>
        <label>Earnings Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EarningsGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IncomeShare__c</fullName>
        <label>Income Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MaximumFundingAmount__c</fullName>
        <label>Maximum Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimumFundingAmount__c</fullName>
        <label>Minimum Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentCapFactor__c</fullName>
        <label>Payment Cap Factor</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramEligibility__c.object
<CustomObject>
    <label>Program Eligibility</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Program Eligibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Eligibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Campus__c</fullName>
        <label>Campus</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/ContractTermsAdjustmentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Income Share</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Term</fullName>
    </customValue>
    <masterLabel>Contract Terms Adjustment Method</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/EarningsGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Earnings Group</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/EnrollmentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Three Quarter Time</fullName>
    </customValue>
    <customValue>
        <fullName>Half Time</fullName>
    </customValue>
    <customValue>
        <fullName>Less than Half Time</fullName>
    </customValue>
    <masterLabel>Enrollment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/GradeLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Residency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US Citizen/Non-Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Naturalized Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Work Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Student Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Refugee/Asylee</fullName>
    </customValue>
    <masterLabel>Residency</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/ContractTermQueries.cls
public with sharing class ContractTermQueries {
//SELECT ID, Name, AgeOfMajority__c, Residency__c, EnrollmentStatus__c, GradeLevel__c, SchoolProgramOfStudy__c, Campus__c, Program__c, State__c FROM ProgramEligibility__c where AgeOfMajority__c < 19 and Residency__c includes ('US Citizen') and EnrollmentStatus__c includes ('Full Time') and GradeLevel__c includes ('Freshman') and SchoolProgramOfStudy__c = 'a0o7A000000xVuJQAU' and Campus__c Like '%West%' and Program__c = 'a0n7A0000012a6nQAA' and State__c includes ('AL')

	public static Map<String, Object> filterCriteria = new Map<String, Object>();
	public static void clearFilterCriteria(){
		filterCriteria.clear();
	}

	public static Map<ID, ContractTerm__c> getContractTermMap(){
		Map<ID, ContractTerm__c> peMap = new Map<ID, ContractTerm__c>();
		String query = generateSOQLSelect();
		query += ' WHERE MaximumFundingAmount__c >= 0';
//		if(DatabaseUtil.filterBySchoolID){
//			ID schoolID = DatabaseUtil.schoolID;
//			query += ' AND Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
//		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		peMap = new Map<ID, ContractTerm__c>((List<ContractTerm__c>)db.query(query));
		return peMap;		
	}
/*
	public static Map<ID, Boolean> evaluateEligibility(ID programID, Set<ID> studentIDs){
		//Takes a list of students and returns of map of eligibility for those students
		Map<ID, Boolean> returnMap = new Map<ID, Boolean>();

		Map<ID, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIDs);
		List<ProgramEligibility__c> eligibility = new List<ProgramEligibility__c>();
		for(Account stud : studentMap.values()){
			//must query each student - NOT BULK SAFE
			eligibility.clear();
			String query = generateSOQLSelect();
			query += ' WHERE AgeOfMajority__c <= ' + stud.Age__pc;
			query += ' and Residency__c includes (\'' + stud.Residency__pc + '\')';
			query += ' and EnrollmentStatus__c includes (\'' + stud.PrimarySchoolEnrollmentStatus__pc + '\')';
			query += ' and GradeLevel__c includes (\'' + stud.PrimarySchoolGradeLevel__pc + '\')';
			if(stud.SchoolProgramOfStudy__pc != null){
				query += ' and SchoolProgramOfStudy__c = \'' + stud.SchoolProgramOfStudy__pc + '\'';				
			} else {
				query += ' and SchoolProgramOfStudy__c = null';					
			}
			query += ' and Program__c = \''+programID+ '\'';
			query += ' and State__c includes (\'' + stud.PersonMailingStateCode + '\')';
//			query += ' and Campus__c like \'%' + 'West' + '%\'';
			query += ' '+generateLIMITStatement();
			DatabaseUtil db = new DatabaseUtil();
			eligibility = (List<ProgramEligibility__c>)db.query(query);
			if (eligibility.size()>0){
				returnMap.put(stud.id, true);
			} else returnMap.put(stud.id, false);
		}

		return returnMap;
	}*/

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getFieldNames() + ' FROM ContractTerm__c';
		return soql;
	}

	private static String getFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Name, ';
		fieldNames += 'Program__c, ';
		fieldNames += 'EarningsGroup__c, ';
		fieldNames += 'GradeLevel__c, ';
		fieldNames += 'IncomeShare__c, ';
		fieldNames += 'MinimumFundingAmount__c, ';
		fieldNames += 'MaximumFundingAmount__c, ';
		fieldNames += 'PaymentTerm__c, ';
		fieldNames += 'AdjustmentMethod__c, ';
		fieldNames += 'PaymentCapFactor__c ';
		return fieldNames;
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}

	private static String buildFilterString(){
		String filterStr = '';
		if(filterCriteria.size()>0){
			for(String filter : filterCriteria.keyset()){
				filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) + 	'\' ');
			}			
		}
		return filterStr;
	}
}