vemo-mdapi-qa/objects/ContractTerm__c.object
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Contract Terms Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>MinimumFundingAmount__c</fullName>
        <label>Minimum Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DateVerified__c</fullName>
        <inlineHelpText>The date this employment was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Full Time or Part Time</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeBand__c.object
<CustomObject>
    <label>Income Band</label>
    <nameField>
        <displayFormat>IB-{0000000}</displayFormat>
        <label>Income Band Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BeginDate__c</fullName>
        <inlineHelpText>The date this Income began.</inlineHelpText>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateVerified__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>The date the student&#39;s Income was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncomePerMonth__c</fullName>
        <inlineHelpText>The student&#39;s monthly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of Income Verification (Reported vs Estimated).</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/ProgramEligibility__c.object
<CustomObject>
    <label>Program Eligibility</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Program Eligibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Eligibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IncomeVerification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Income Verification Object used to derive Monthly Income during Assessment</description>
        <inlineHelpText>Income Verification Object used to derive Monthly Income during Assessment</inlineHelpText>
        <label>Income Verification</label>
        <referenceTo>IncomeVerification__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Amount_Due</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Represents a funding event in a contract. This is typically a transaction from an investor or school to the school (for tuition) or directly to the student (ex. stipend)</description>
        <label>Disbursement</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/objects/TransactionSchedule__c.object
<CustomObject>
    <label>Disbursement Schedule</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Transaction_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/DebitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/EmploymentType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <masterLabel>Employment Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/IncomeVerificationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/IncomeVerificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Estimated</fullName>
    </customValue>
    <masterLabel>Income Verification Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/TransactionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/accountSummaryCTRL_TEST.cls
@isTest
public class accountSummaryCTRL_TEST{
     @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        //create students
        Map<Id,Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(2);
        //create Programs with school
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(3,TestDataFactory.createAndInsertSchoolCustomerAccounts(2));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        integer cnt = 0;
        for(Account acc:studentMap.values()){
            if(cnt<3){
                acc.PrimarySchool__pc = schoolMap.values()[0].id;
            }
            else{
                acc.PrimarySchool__pc = schoolMap.values()[1].id;
            }    
        }
        update studentMap.values();
               
        Map<ID, ProgramEligibility__c> eligibilityMap = TestDataFactory.createAndInsertProgramEligibility(2,programMap);
        Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(2);
        Map<ID, SchoolProgramsOfStudy__c> sposMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schoolMap, posMap);
        
        Map<ID, ContractTerm__c> termMap = TestDataFactory.createAndInsertContractTerms(1,programMap);
        Map<ID, TransactionSchedule__c> txSchMap = TestDataFactory.createAndInsertTransactionSchedule(2, programMap);
        Map<ID, IncomeBand__c> bandMap = TestDataFactory.createAndInsertIncomeBands(1, sposMap);
        
        Map<ID, StudentProgram__c> agreements = TestDataFactory.createAndInsertStudentProgram(3,studentMap,programMap);
        Map<ID, Transaction__c> transactionMap = TestDataFactory.createAndInsertTransactions(3,agreements, 'Disbursement');
        List<transaction__c> transactionList = new list<transaction__c>();//transactionMap.values();
        transactionList.addAll(transactionMap.values());
        transactionList[0].status__c = 'Pending'; 
        transactionList[1].status__c = 'Scheduled';
        update transactionList;
        Map<ID, EmploymentHistory__c> empHistory =  TestDataFactory.createAndInsertEmploymentHistory(1,studentMap);
        
        /*
        Map<ID, IncomeVerification__c> incomeVerMap = TestDataFactory.createAndInsertIncomeVerification(4,empHistory); 
        List<incomeVerification__c> incList = new list<incomeVerification__c>();
        incList = incomeVerMap.values(); 
        incList[0].begindate__c = Date.today().toStartOfMonth();
        incList[0].status__c = true;
        incList[0].type__c = 'Estimated';
        incList[1].begindate__c = Date.today().toStartOfMonth();
        incList[1].status__c = true; 
        incList[1].type__c = 'Reported';
        
        //incList.add(incomeVerMap[0]);
        //incList.add(incomeVerMap[1]);
        update incList;
        */
        Map<ID, StudentProgramMonthlyStatus__c> monthlystatusMap = TestDataFactory.createAndInsertStudentProgramMonthlyStatus(2,agreements);
        Map<ID, StudentProgramAmountDue__c> amountDueMap = TestDataFactory.createAndInsertStudentProgramAmountDue(agreements , monthlystatusMap );
        for(StudentProgramAmountDue__c amountdue: amountdueMap.values()){
            amountdue.AssessmentDateTime__c = datetime.now().addDays(-30);
        }
        update amountdueMap.values();
       /* for(Account acc:studentMap.values()){
            TestDataFactory.createAndInsertStudentProgram(1,new Map<ID,Account>{acc.id => acc},
                                                          ProgramQueries.getProgramMapWithSchoolID(new Set<ID>{acc.PrimarySchool__pc}));
        }
        
        for(ContractTerm__c ct:termMap.values()){
            ct.MinimumFundingAmount__c = 1000;
        }       
        update termMap.values();   */               
    } 
    
    @isTest
    public static void testgetRecords(){
         Account acc = [Select id,personEmail,PrimarySchool__pc From Account Where recordType.developerName = 'Student' Limit 1];
         Test.startTest();
         //accountSummaryCTRL obj = new accountSummaryCTRL();
         accountSummaryCTRL.getRecords(acc.id);
         Test.stopTest();
    }

    /////////////////////////////////////////////////////////////
    ///Test Case: only 1 income record with a future begin date
    /////////////////////////////////////////////////////////////
    @isTest
    public static void validateIncomeScenario1(){
        Map<ID, EmploymentHistory__c> empHistoryMap = EmploymentHistoryQueries.getEmploymentHistoryMap();
        Map<ID, IncomeVerification__c> incomeVerficationMap = TestDataFactory.createAndInsertIncomeVerification(1,empHistoryMap);
        
        incomeVerficationMap.values()[0].begindate__c = Date.today().addDays(120); 
        incomeVerficationMap.values()[0].incomePerMonth__c = 1000;                                               
        incomeVerficationMap.values()[0].status__c = 'Verified';
        update incomeVerficationMap.values();
        Account acc = [Select id,personEmail,PrimarySchool__pc From Account Where recordType.developerName = 'Student' Limit 1];
        Test.startTest();
        //accountSummaryCTRL obj = new accountSummaryCTRL();
        accountSummaryCTRL.wrapperClass output = accountSummaryCTRL.getRecords(acc.id);
        System.assertEquals(0,output.monthlyIncome,'Income should be 0');
        Test.stopTest();
    }

    /////////////////////////////////////////////////////////////
    ///Test Case: only 1 income record with a past begin date
    /////////////////////////////////////////////////////////////
    @isTest
    public static void validateIncomeScenario2(){
        Map<ID, EmploymentHistory__c> empHistoryMap = EmploymentHistoryQueries.getEmploymentHistoryMap();
        Map<ID, IncomeVerification__c> incomeVerficationMap = TestDataFactory.createAndInsertIncomeVerification(1,empHistoryMap);
        
        incomeVerficationMap.values()[0].begindate__c = Date.today().addDays(-120); 
        incomeVerficationMap.values()[0].incomePerMonth__c = 1000;                                               
        incomeVerficationMap.values()[0].status__c = 'Verified';
        update incomeVerficationMap.values();
        Account acc = [Select id,personEmail,PrimarySchool__pc From Account Where recordType.developerName = 'Student' Limit 1];
        Test.startTest();
        //accountSummaryCTRL obj = new accountSummaryCTRL();
        accountSummaryCTRL.wrapperClass output = accountSummaryCTRL.getRecords(acc.id);
        System.assertEquals(1000,output.monthlyIncome,'Income should be 1000');
        Test.stopTest();
    }

    /////////////////////////////////////////////////////////////
    ///Test Case: 2 income records. one with a future begin date
    ///another with past begin date
    /////////////////////////////////////////////////////////////
    @isTest
    public static void validateIncomeScenario3(){
        Map<ID, EmploymentHistory__c> empHistoryMap = EmploymentHistoryQueries.getEmploymentHistoryMap();
        Map<ID, IncomeVerification__c> incomeVerficationMap = TestDataFactory.createAndInsertIncomeVerification(2,empHistoryMap);
        
        incomeVerficationMap.values()[0].begindate__c = Date.today().addDays(-120); 
        incomeVerficationMap.values()[0].incomePerMonth__c = 1000;  
        incomeVerficationMap.values()[0].status__c = 'Verified';                                             
        incomeVerficationMap.values()[1].begindate__c = Date.today().addDays(120); 
        incomeVerficationMap.values()[1].incomePerMonth__c = 2000;
        incomeVerficationMap.values()[1].status__c = 'Verified';                                               
        
        update incomeVerficationMap.values();
        Account acc = [Select id,personEmail,PrimarySchool__pc From Account Where recordType.developerName = 'Student' Limit 1];
        Test.startTest();
        //accountSummaryCTRL obj = new accountSummaryCTRL();
        accountSummaryCTRL.wrapperClass output = accountSummaryCTRL.getRecords(acc.id);
        System.assertEquals(1000,output.monthlyIncome,'Income should be 1000');
        Test.stopTest();
    }

    /////////////////////////////////////////////////////////////
    ///Test Case: 2 income records with same begin date
    ///one of type Reported another of type estimated
    /////////////////////////////////////////////////////////////
    @isTest
    public static void validateIncomeScenario4(){
        Map<ID, EmploymentHistory__c> empHistoryMap = EmploymentHistoryQueries.getEmploymentHistoryMap();
        Map<ID, IncomeVerification__c> incomeVerficationMap = TestDataFactory.createAndInsertIncomeVerification(2,empHistoryMap);
        
        incomeVerficationMap.values()[0].begindate__c = Date.today().addDays(-120);
        incomeVerficationMap.values()[0].type__c = 'Reported'; 
        incomeVerficationMap.values()[0].incomePerMonth__c = 1000;
        incomeVerficationMap.values()[0].status__c = 'Verified';                                               
        incomeVerficationMap.values()[1].begindate__c = Date.today().addDays(-120); 
        incomeVerficationMap.values()[1].type__c = 'Estimated';
        incomeVerficationMap.values()[1].incomePerMonth__c = 2000; 
        incomeVerficationMap.values()[1].status__c = 'Verified';                                              
        
        update incomeVerficationMap.values();
        Account acc = [Select id,personEmail,PrimarySchool__pc From Account Where recordType.developerName = 'Student' Limit 1];
        Test.startTest();
        //accountSummaryCTRL obj = new accountSummaryCTRL();
        accountSummaryCTRL.wrapperClass output = accountSummaryCTRL.getRecords(acc.id);
        System.assertEquals(1000,output.monthlyIncome,'Income should be 1000');
        Test.stopTest();
    }

    /////////////////////////////////////////////////////////////
    ///Test Case: 2 income records with same begin date
    ///both of same type with different DateVerified
    /////////////////////////////////////////////////////////////
    @isTest
    public static void validateIncomeScenario5(){
        Map<ID, EmploymentHistory__c> empHistoryMap = EmploymentHistoryQueries.getEmploymentHistoryMap();
        Map<ID, IncomeVerification__c> incomeVerficationMap = TestDataFactory.createAndInsertIncomeVerification(2,empHistoryMap);
        
        incomeVerficationMap.values()[0].begindate__c = Date.today().addDays(-120);
        incomeVerficationMap.values()[0].type__c = 'Reported';
        incomeVerficationMap.values()[0].dateVerified__c = Date.today();
        incomeVerficationMap.values()[0].incomePerMonth__c = 1000;
        incomeVerficationMap.values()[0].status__c = 'Verified';                                               
        incomeVerficationMap.values()[1].begindate__c = Date.today().addDays(-120); 
        incomeVerficationMap.values()[1].type__c = 'Reported';
        incomeVerficationMap.values()[1].dateVerified__c = Date.today().addDays(-10);
        incomeVerficationMap.values()[1].incomePerMonth__c = 2000; 
        incomeVerficationMap.values()[1].status__c = 'Verified';                                              
        
        update incomeVerficationMap.values();
        Account acc = [Select id,personEmail,PrimarySchool__pc From Account Where recordType.developerName = 'Student' Limit 1];
        Test.startTest();
        //accountSummaryCTRL obj = new accountSummaryCTRL();
        accountSummaryCTRL.wrapperClass output = accountSummaryCTRL.getRecords(acc.id);
        System.assertEquals(1000,output.monthlyIncome,'Income should be 1000');
        Test.stopTest();
    }
}