vemo-mdapi-qa/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <label>Community Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                </value>
                <value>
                    <fullName>Enroll</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PendingBirthdate__c</fullName>
        <label>Pending Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PendingDriversLicenseOrStateID__c</fullName>
        <label>Pending Drivers License or State ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingEmail__c</fullName>
        <label>Pending Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PendingFirstName__c</fullName>
        <label>Pending First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingLastName__c</fullName>
        <label>Pending Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingCity__c</fullName>
        <label>Pending Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingCountryCode__c</fullName>
        <label>Pending Mailing Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingCountry__c</fullName>
        <label>Pending Mailing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingPostalCode__c</fullName>
        <label>Pending Mailing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingStateCode__c</fullName>
        <label>Pending Mailing State Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingState__c</fullName>
        <label>Pending Mailing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingMailingStreet__c</fullName>
        <label>Pending Mailing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PendingMiddleName__c</fullName>
        <label>Pending Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PendingResidency__c</fullName>
        <label>Pending Residency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordStatus__c</fullName>
        <label>Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RecordStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Other Relative</fullName>
                </value>
                <value>
                    <fullName>Other Non Relative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(Reference For) Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (References)</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/RecordStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pending Approval</fullName>
        <default>true</default>
        <label>Pending Approval</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <masterLabel>Record Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/ContactQueries.cls
///////////////////////////////////////////////////////////////////////// git test 1 3 4
// Class: ContactQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-13   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
public class ContactQueries {
/*	public static Map<ID, Contact> getContactMapByID(){
		return new Map<ID, Contact>([SELECT id,
										   FirstName,
										   MiddleName,
										   LastName,
										   MailingCity,
										   MailingCountry,
										   MailingPostalCode,
										   MailingState,
										   MailingStreet,
										   Phone,
										   Relationship__c,
										   PendingFirstName__c,
										   PendingMiddleName__c,
										   PendingLastName__c,
										   PendingBirthDate__c,
										   PendingDriversLicenseOrStateID__c,
										   PendingEmail__c,
										   RecordStatus__c,
										   PendingMailingStreet__c,
										   PendingMailingCity__c,
										   PendingMailingCountry__c,
										   PendingMailingCountryCode__c,
										   PendingMailingState__c,
										   PendingMailingStateCode__c,
										   PendingMailingPostalCode__c,
										   CommunityStatus__c
									 FROM Contact
									 LIMIT 50000]);
	}
	public static Map<ID, Contact> getStudentReferenceMapWithStudentID(Set<ID> studentIDs){
		return new Map<ID, Contact>([SELECT id,
										   FirstName,
										   MiddleName,
										   LastName,
										   MailingCity,
										   MailingCountry,
										   MailingPostalCode,
										   MailingState,
										   MailingStreet,
										   Phone,
										   Relationship__c,
										   PendingFirstName__c,
										   PendingMiddleName__c,
										   PendingLastName__c,
										   PendingBirthDate__c,
										   PendingDriversLicenseOrStateID__c,
										   PendingEmail__c,
										   RecordStatus__c,
										   PendingMailingStreet__c,
										   PendingMailingCity__c,
										   PendingMailingCountry__c,
										   PendingMailingCountryCode__c,
										   PendingMailingState__c,
										   PendingMailingStateCode__c,
										   PendingMailingPostalCode__c,
										   CommunityStatus__c
									 FROM Contact
									 WHERE Student__c IN :studentIDs
									 LIMIT 50000]);
	}

	public static Map<ID, Contact> getStudentReferenceMapWithReferenceID(Set<ID> referenceIDs){
		return new Map<ID, Contact>([SELECT id,
										   FirstName,
										   MiddleName,
										   LastName,
										   MailingCity,
										   MailingCountry,
										   MailingPostalCode,
										   MailingState,
										   MailingStreet,
										   Phone,
										   Relationship__c,
										   PendingFirstName__c,
										   PendingMiddleName__c,
										   PendingLastName__c,
										   PendingBirthDate__c,
										   PendingDriversLicenseOrStateID__c,
										   PendingEmail__c,
										   RecordStatus__c,
										   PendingMailingStreet__c,
										   PendingMailingCity__c,
										   PendingMailingCountry__c,
										   PendingMailingCountryCode__c,
										   PendingMailingState__c,
										   PendingMailingStateCode__c,
										   PendingMailingPostalCode__c,
										   CommunityStatus__c
									 FROM Contact where ID in :referenceIDs
									 LIMIT 50000]);
	}




	public static Map<String, Account> getStudentMapByAuthIDWithAuthID(Set<String> authIDs){
		Map<String, Account> acctMapByAuthID = new Map<String, Account>();
		String query = generateSOQLSelect('student');
		query += ' WHERE AuthSystemUserID__pc IN ' + DatabaseUtil.inSetStringBuilder(authIDs);
		query += ' and ' + generateRecordTypeStatement('Student');

		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		system.debug('***query'+query);
		DatabaseUtil db = new DatabaseUtil();
		Map<ID, Account> retMap = new Map<ID, Account>((List<Account>)db.query(query));

		for(Account acct : retMap.values()){
			acctMapByAuthID.put(acct.AuthSystemUserID__pc, acct);
		}
		system.debug('acctMapByAuthID:'+acctMapByAuthID);
		return acctMapByAuthID;
	}

	public static Map<ID, Account> getStudentMap(){
		Map<ID, Account> acctMap = new Map<ID, Account>();
		String query = generateSOQLSelect('student');
		query += ' WHERE ' + generateRecordTypeStatement('Student');
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and ID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		acctMap = new Map<ID, Account>((List<Account>)db.query(query));
		return acctMap;		
	}*/
	public static Map<ID, Contact> getContactMapByID(){
		Map<ID, Contact> contMap = new Map<ID, Contact>();
		String query = generateSOQLSelect();		
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' WHERE AccountID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		system.debug('***query'+query);
		DatabaseUtil db = new DatabaseUtil();
		contMap = new Map<ID, Contact>((List<Contact>)db.query(query));
		return contMap;		
		
	}
	public static Map<ID, Contact> getContactMapByIDWithContactID(Set<ID> contactIDs){
		Map<ID, Contact> contMap = new Map<ID, Contact>();
		String query = generateSOQLSelect();	
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(contactIDs);	
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' AND AccountID = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		system.debug('***query'+query);
		DatabaseUtil db = new DatabaseUtil();
		contMap = new Map<ID, Contact>((List<Contact>)db.query(query));
		return contMap;		
		
	}	
	public static Map<ID, Contact> getStudentReferenceMapWithStudentID(Set<ID> studentIDs){
		Map<ID, Contact> contMap = new Map<ID, Contact>();
		String query = generateSOQLSelect();		
		query += ' WHERE Student__c IN ' + DatabaseUtil.inSetStringBuilder(studentIDs);
		query += ' and ' + generateRecordTypeStatement('Student Reference');
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		system.debug('***query'+query);
		DatabaseUtil db = new DatabaseUtil();
		contMap = new Map<ID, Contact>((List<Contact>)db.query(query));
		return contMap;		
		
	}
	public static Map<ID, Contact> getStudentReferenceMapWithReferenceID(Set<ID> referenceIDs){
		Map<ID, Contact> contMap = new Map<ID, Contact>();
		String query = generateSOQLSelect();		
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(referenceIDs);
		query += ' and ' + generateRecordTypeStatement('Student Reference');
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		system.debug('***query'+query);
		DatabaseUtil db = new DatabaseUtil();
		contMap = new Map<ID, Contact>((List<Contact>)db.query(query));
		return contMap;		
		
	}	

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getContactFieldNames() + ' FROM Contact';
		return soql;
	}

	private static String getContactFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'AccountID, ';
		fieldNames += 'Student__c, ';		
		fieldNames += 'FirstName, ';
		fieldNames += 'MiddleName, ';
		fieldNames += 'LastName, ';
		fieldNames += 'MailingCity, ';
		fieldNames += 'MailingCountry, ';
		fieldNames += 'MailingPostalCode, ';
		fieldNames += 'MailingState, ';
		fieldNames += 'MailingStreet, ';
		fieldNames += 'Phone, ';
		fieldNames += 'Relationship__c ';
//		fieldNames += 'PendingFirstName__c, ';
//		fieldNames += 'PendingMiddleName__c, ';
//		fieldNames += 'PendingLastName__c, ';
//		fieldNames += 'PendingBirthDate__c, ';
//		fieldNames += 'PendingDriversLicenseOrStateID__c, ';
//		fieldNames += 'PendingEmail__c, ';
//		fieldNames += 'RecordStatus__c, ';
//		fieldNames += 'PendingMailingStreet__c, ';
//		fieldNames += 'PendingMailingCity__c, ';
//		fieldNames += 'PendingMailingCountry__c, ';
//		fieldNames += 'PendingMailingCountryCode__c, ';
//		fieldNames += 'PendingMailingState__c, ';
//		fieldNames += 'PendingMailingStateCode__c, ';
//		fieldNames += 'PendingMailingPostalCode__c, ';
//		fieldNames += 'CommunityStatus__c, ';
//		fieldNames += 'PendingResidency__c';	

		return fieldNames;
	}


	
	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}

	private static String generateRecordTypeStatement(String recordTypeLabel){
		ID recordTypeID = (String)GlobalUtil.getRecordTypeIDByLabelName('Contact', recordTypeLabel);
		return 'RecordTypeID = \''+ String.valueOf(recordTypeID) + '\'';
	}

}