vemo-mdapi-qa/objects/ContractTerm__c.object
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Contract Terms Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/classes/ContractTermQueries_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: ContractTermQueries_TEST
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-04-25   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public with sharing class ContractTermQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
	@isTest public static void validateGetContractTermMap() {
		Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
		Map<Id, Program__c> testProgMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schools);
		Map<Id, ContractTerm__c> testContractTermMap = TestDataFactory.createAndInsertContractTerms(TestUtil.TEST_THROTTLE, testProgMap);

		Test.startTest();
		Map<Id, ContractTerm__c> resultContractTermMap = ContractTermQueries.getContractTermMap();
		System.assertEquals(testContractTermMap.keySet().size(), resultContractTermMap.keySet().size());
		Test.stopTest();
	}

}