vemo-mdapi-qa/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AuthSystemUserID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The ID string identifying this user in the authentication system (currently Auth0).</inlineHelpText>
        <label>Auth System User ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DriversLicenseOrStateID__c</fullName>
        <label>Drivers License or State ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimarySchoolEmail__c</fullName>
        <label>(DEPRECATE)School Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SSNTaxID__c</fullName>
        <inlineHelpText>Used by Credit Check process to verify identity.</inlineHelpText>
        <label>SSN / Tax ID</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BirthdateCertification__c</fullName>
        <inlineHelpText>(Certification) fields are only used for student initiated flow, and store temporary values entered by the School Admin during certification.</inlineHelpText>
        <label>Birthdate (Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdatePostCertification__c</fullName>
        <inlineHelpText>(Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Birthdate (Post-Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdatePreCertification__c</fullName>
        <inlineHelpText>(Pre-Certification) fields are only used for school initiated flow, and store temporary values entered by the School Admin during certification.</inlineHelpText>
        <label>Birthdate (Pre-Certification)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BirthdateStudent__c</fullName>
        <inlineHelpText>(Student) fields store the values entered by the Student during application/registration.</inlineHelpText>
        <label>Birthdate (Student)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StudentEmail__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/SandboxSetupMaskContacts.cls
public class SandboxSetupMaskContacts implements Database.Batchable<sObject> {
	
	public String query = 'SELECT id, AuthSystemUserID__c, SSNTaxID__c, Birthdate, PrimarySchoolEmail__c, DriversLicenseOrStateID__c, Email, Phone, HomePhone, MobilePhone, OtherPhone,  MailingStreet, MailingCity, MailingState, MailingPostalCode, OtherStreet, OtherCity, OtherState, OtherPostalCode from Contact';
	public String sObj = 'Contact';

	public SandboxSetupMaskContacts() {
		
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		if(sObj == 'Contact'){
			query = 'SELECT id, AuthSystemUserID__c, SSNTaxID__c, Birthdate, PrimarySchoolEmail__c, DriversLicenseOrStateID__c, Email, Phone, HomePhone, MobilePhone, OtherPhone,  MailingStreet, MailingCity, MailingState, MailingPostalCode, OtherStreet, OtherCity, OtherState, OtherPostalCode from Contact';

		} else if(sObj == 'StudentProgram__c'){
			query = 'SELECT id, Birthdate__c, BirthdateCertification__c, BirthdatePostCertification__c, BirthdatePreCertification__c, BirthdateStudent__c, StudentEmail__c from StudentProgram__c';

		}
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
   		if(sObj == 'Contact'){

			for(Contact cont : (List<Contact>)(scope)){
				System.debug('cont:'+cont);
				if(String.isNotEmpty(cont.SSNTaxID__c)) cont.SSNTaxID__c = '123-45-6789';
				if(String.isNotEmpty(cont.MailingStreet)) cont.MailingStreet = '123 Main Street';
				if(String.isNotEmpty(cont.MailingPostalCode)) cont.MailingPostalCode = '98765-4321';
				if(String.isNotEmpty(cont.OtherStreet)) cont.OtherStreet = '12345 Secondary Street';
				if(String.isNotEmpty(cont.OtherPostalCode)) cont.OtherPostalCode = '11223';
				if(String.isNotEmpty(cont.Phone)) cont.Phone = '(555) 123-4567';
				if(String.isNotEmpty(cont.MobilePhone)) cont.MobilePhone = '(555) 123-4567';
				if(String.isNotEmpty(cont.OtherPhone)) cont.OtherPhone = '(555) 123-4567';
				if(String.isNotEmpty(cont.HomePhone)) cont.HomePhone = '(555) 123-4567';			
				if(String.isNotEmpty(cont.Email)) cont.Email = 'masked.email@vemo.com';
				if(String.isNotEmpty(cont.AuthSystemUserID__c)) cont.AuthSystemUserID__c = 'auth|'+cont.id;
				if(cont.Birthdate != null) cont.Birthdate = Date.newInstance(2000, 1, 1);
			}   			
   		} else if(sObj == 'StudentProgram__c'){
			for(StudentProgram__c agreement : (List<StudentProgram__c>) (scope)){
				System.debug('agreement:'+agreement);
				if(String.isNotEmpty(agreement.StudentEmail__c)) agreement.StudentEmail__c = 'masked.email@vemo.com';
				if(agreement.Birthdate__c != null) agreement.Birthdate__c = Date.newInstance(2000, 1, 1);
				if(agreement.BirthdateCertification__c != null) agreement.BirthdateCertification__c = Date.newInstance(2000, 1, 1);
				if(agreement.BirthdatePostCertification__c != null) agreement.BirthdatePostCertification__c = Date.newInstance(2000, 1, 1);
				if(agreement.BirthdatePreCertification__c != null) agreement.BirthdatePreCertification__c = Date.newInstance(2000, 1, 1);
				if(agreement.BirthdateStudent__c != null) agreement.BirthdateStudent__c = Date.newInstance(2000, 1, 1);
			}   			
   		}

		update scope;
	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
	
}