vemo-mdapi-qa/objects/ContractTerm__c.object
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Contract Terms Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AdjustmentMethod__c</fullName>
        <label>Adjustment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ContractTermsAdjustmentMethod</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EarningsGroup__c</fullName>
        <label>Earnings Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EarningsGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IncomeShare__c</fullName>
        <label>Income Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MaximumFundingAmount__c</fullName>
        <label>Maximum Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimumFundingAmount__c</fullName>
        <label>Minimum Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentCapFactor__c</fullName>
        <label>Payment Cap Factor</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeBand__c.object
<CustomObject>
    <label>Income Band</label>
    <nameField>
        <displayFormat>IB-{0000000}</displayFormat>
        <label>Income Band Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EarningsGroup__c</fullName>
        <label>Earnings Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EarningsGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Income Bands</relationshipLabel>
        <relationshipName>Income_Bands</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/globalValueSets/ContractTermsAdjustmentMethod.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Income Share</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Term</fullName>
    </customValue>
    <masterLabel>Contract Terms Adjustment Method</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/EarningsGroup.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Earnings Group</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/GradeLevel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/ContractTermsService.cls
/////////////////////////////////////////////////////////////////////////
// Class: ContractTermsService
// 
// Description: 
// 	Handles all Contract Terms Service Layer functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-04-25   Greg Cook       Created                          
/////////////////////////////////////////////////////////////////////////
public with sharing class ContractTermsService {
	public static Map<ID, List<ContractTermsService.ContractTerm>> getContractTermsByStudentIDWithStudentMap(ID programID, Map<ID, Account> studentMap){
		System.debug('ContractTermsService.getContractTermsByStudentIDWithStudentMap');
		Map<ID, List<ContractTermsService.ContractTerm>> contractTermsByStudentID = new Map<ID, List<ContractTermsService.ContractTerm>>();



		for(Account student : studentMap.values()){
			//This is not bulk safe as it must query the income band for each student
			IncomeBandQueries.clearFilterCriteria();
			IncomeBandQueries.filterCriteria.put('SchoolProgramOfStudy__c', student.SchoolProgramOfStudy__pc);

			Map<ID, IncomeBand__c> studentsIncomeBand = IncomeBandQueries.getIncomeBandMap();
			System.debug('studentsIncomeBand:'+studentsIncomeBand);

			if(studentsIncomeBand.size() == 1){
				ContractTermQueries.clearFilterCriteria();
				ContractTermQueries.filterCriteria.put('GradeLevel__c', student.PrimarySchoolGradeLevel__pc);
				ContractTermQueries.filterCriteria.put('Program__c', programID);
				ContractTermQueries.filterCriteria.put('EarningsGroup__c', studentsIncomeBand.values()[0].EarningsGroup__c);
				Map<ID, ContractTerm__c> contractTermMap = ContractTermQueries.getContractTermMap();
				System.debug('contractTermMap:'+contractTermMap);

				if(contractTermMap.size() == 1) {
					if(!contractTermsByStudentID.containsKey(student.id)){
						contractTermsByStudentID.put(student.id, new List<ContractTermsService.ContractTerm>());
					}
					contractTermsByStudentID.get(student.id).add(new ContractTermsService.ContractTerm(contractTermMap.values()[0]));
				}
			}
		}

		system.debug('contractTermsByStudentID:'+contractTermsByStudentID);

		return contractTermsByStudentID;
	}

	public static ContractTermsService.ContractTerm getContractTermsWithCriteria(ID programID, 
																				ID schoolProgramOfStudyID,
																				String gradeLevel){
		System.debug('ContractTermsService.getContractTermsWithCriteria');
		ContractTermsService.ContractTerm contractTerm = new ContractTermsService.ContractTerm();



		IncomeBandQueries.clearFilterCriteria();
		IncomeBandQueries.filterCriteria.put('SchoolProgramOfStudy__c', schoolProgramOfStudyID);

		Map<ID, IncomeBand__c> incomeBand = IncomeBandQueries.getIncomeBandMap();
		System.debug('studentsIncomeBand:'+incomeBand);

		if(incomeBand.size() == 1){
			ContractTermQueries.clearFilterCriteria();
			ContractTermQueries.filterCriteria.put('GradeLevel__c', gradeLevel);
			ContractTermQueries.filterCriteria.put('Program__c', programID);
			ContractTermQueries.filterCriteria.put('EarningsGroup__c', incomeBand.values()[0].EarningsGroup__c);
			Map<ID, ContractTerm__c> contractTermMap = ContractTermQueries.getContractTermMap();
			System.debug('contractTermMap:'+contractTermMap);

			if(contractTermMap.size() == 1) {
				contractTerm = new ContractTermsService.ContractTerm(contractTermMap.values()[0]);
			}
		}

		system.debug('contractTerm:'+contractTerm);

		return contractTerm;
	}


	public class ContractTerm{
		public String contractTermID {get;set;}
		public String programID {get;set;}
		public Decimal minimumFundingAmount {get;set;}
		public Decimal maximumFundingAmount {get;set;}
		public Decimal incomeShare {get;set;}
		public Decimal paymentTerm {get;set;}
		public String gradeLevel {get;set;}
		public String earningsGroup {get;set;}
		public String adjustmentMethod {get;set;}
		public Decimal paymentCapFactor {get;set;}


		public ContractTerm(){

		}

		public ContractTerm(Boolean testValues){
			if(testValues){
				//to do
				//this.programName = 'testProgramName';
				//this.programStatus = 'Open'; //Planned, Closed, Cancelled
			}
		}

		public ContractTerm(ContractTerm__c term){
			this.contractTermID = term.id;
			this.programID = term.Program__c;
			this.minimumFundingAmount = term.MinimumFundingAmount__c;
			this.maximumFundingAmount = term.MaximumFundingAmount__c;
			this.incomeShare = term.IncomeShare__c;
			this.paymentTerm = term.PaymentTerm__c;
			this.gradeLevel = term.GradeLevel__c;
			this.earningsGroup = term.EarningsGroup__c;
			this.adjustmentMethod = term.AdjustmentMethod__c;
			this.paymentCapFactor = term.PaymentCapFactor__c;
		}
	}
	public class ContractTermsServiceException extends Exception {}
}