vemo-mdapi-qa/objects/ContractTerm__c.object
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Contract Terms Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeBand__c.object
<CustomObject>
    <label>Income Band</label>
    <nameField>
        <displayFormat>IB-{0000000}</displayFormat>
        <label>Income Band Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/GradeLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/VemoAPIContractTermsResource_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: VemoAPIContractTermsResource_TEST
// 
// Description: 
// 	Test class for VemoAPIContractTermsResource
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-09  	Jared Hagemann	Created                          
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class VemoAPIContractTermsResource_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testHandleGetV1(){
    	Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Account> schoolMap = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);    	
    	Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schoolMap);
		Map<ID, ContractTerm__c> contractTermMap = TestDataFactory.createAndInsertContractTerms(1, programMap);
		Map<ID, ProgramOfStudy__c> programsOfStudyMap = TestDataFactory.createAndInsertProgramOfStudy(1);
		Map<ID, SchoolProgramsOfStudy__c> schlProgramsOfStudyMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schoolMap, programsOfStudyMap);
		for(Integer i = 0; i < studentMap.keySet().size(); i++){
			studentMap.values().get(i).SchoolProgramOfStudy__pc = schlProgramsOfStudyMap.values().get(i).Id;
			studentMap.values().get(i).PrimarySchoolGradeLevel__pc = contractTermMap.values().get(0).GradeLevel__c;
		}
		update studentMap.values();
		Map<ID, IncomeBand__c> incomeBandMap = TestDataFactory.createAndInsertIncomeBands(1, schlProgramsOfStudyMap);		

		Map<String, String> params = new Map<String, String>();
		params.put('programID', (String)programMap.values().get(0).Id);
		params.put('VEMO_AUTH', 'testStudent_'+studentMap.values()[0].AuthSystemUserID__pc);
		VemoAPI.APIInfo apiInfo = TestUtil.initializeAPI('v1', 'GET', params, null);
		apiInfo.studentPersonAccountID = studentMap.values()[0].Id;

		Test.startTest();
		VemoAPI.ResultResponse stdResult = (VemoAPI.ResultResponse)VemoAPIContractTermsResource.handleAPI(apiInfo);
		System.assertEquals(1, stdResult.numberOfResults);
		Test.stopTest();

    }
}