vemo-mdapi-qa/objects/CreditCriteria__c.object
<CustomObject>
    <label>Credit Criteria</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Credit Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AmountOperator__c</fullName>
        <label>Amount Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DeclineType__c</fullName>
        <label>Decline Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DeclineType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EvaluationCriteria__c</fullName>
        <label>Evaluation Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditEvaluationCriteria</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FICOScoreOperator__c</fullName>
        <label>FICO Score Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FICOScore__c</fullName>
        <label>FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Criteria</relationshipLabel>
        <relationshipName>Credit_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimePeriodMonths__c</fullName>
        <label>Time Period(Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TimePeriodOperator__c</fullName>
        <label>Time Period Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-app/main/default/globalValueSets/CreditEvaluationCriteria.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FICO Score</fullName>
    </customValue>
    <customValue>
        <fullName>Educational Loan Default</fullName>
    </customValue>
    <customValue>
        <fullName>Bankruptcy</fullName>
    </customValue>
    <customValue>
        <fullName>Major Derogatory Public Record</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfied Suit or Judgement</fullName>
    </customValue>
    <customValue>
        <fullName>Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Tax Liens</fullName>
    </customValue>
    <masterLabel>Credit Evaluation Criteria</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/DeclineType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hard Decline</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Decline</fullName>
    </customValue>
    <masterLabel>Decline Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Operator.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&gt;</fullName>
    </customValue>
    <customValue>
        <fullName>&lt;</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;=</fullName>
    </customValue>
    <customValue>
        <fullName>&lt;=</fullName>
    </customValue>
    <customValue>
        <fullName>=</fullName>
    </customValue>
    <customValue>
        <fullName>!=</fullName>
    </customValue>
    <masterLabel>Operator</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/CreditCriteriaService.cls
public with sharing class CreditCriteriaService{
    
    public static List<CreditCriteria> getCreditCriteriaWithProgramID(Set<ID> programIDs){
        System.debug('CreditCriteriaService.getCreditCriteriaWithProgramID');
        Map<Id, CreditCriteria__c> CreditCriteriaMap = CreditCriteriaQueries.getCreditCriteriaMapWithProgramID(programIDs);
        List<CreditCriteria> CreditCriteria = new List<CreditCriteria>();
        for(CreditCriteria__c cc : CreditCriteriaMap.values()){
            CreditCriteria.add(new CreditCriteria(cc));
        }
        return CreditCriteria;
    }
    
    public static Map<ID,List<CreditCriteria>> getCreditCriteriaByProgramIDWithProgramID(Set<ID> programIDs){
        System.debug('CreditCriteriaService.getCreditCriteriaByProgramIDWithProgramID');
        List<CreditCriteria> CreditCriteria = CreditCriteriaService.getCreditCriteriaWithProgramID(programIDs); 
        Map<Id, List<CreditCriteria>> CreditCriteriaMap = new Map<Id, List<CreditCriteria>>();
        for(CreditCriteria cc : CreditCriteria){
             if(!CreditCriteriaMap.containsKey(cc.ProgramId)){
                CreditCriteriaMap.put(cc.ProgramId, new List<CreditCriteria>());  
             } 
             CreditCriteriaMap.get(cc.ProgramId).add(cc);  
        }
        return CreditCriteriaMap;
     }
    
     public class creditCriteria{
        public String creditCriteriaID {get;set;}
        public String programID {get;set;}
        public String declineType {get;set;}
        public String evaluationCriteria {get;set;}
        public String amount {get;set;}
        public String amountOperator {get;set;}
        public String FICOScore {get;set;}
        public String FICOScoreOperator {get;set;}
        public String timePeriod {get;set;}
        public String timePeriodOperator {get;set;}
        
        public creditCriteria(){

        }
        
        public creditCriteria(CreditCriteria__c creditcriteria){
            this.creditCriteriaID = creditcriteria.Id;
            this.programId = creditcriteria.program__c;
            this.amount = creditcriteria.Amount__c != null ? String.valueOf(creditcriteria.Amount__c) : '';
            this.amountOperator = creditcriteria.AmountOperator__c != null ? creditcriteria.AmountOperator__c : '';
            this.evaluationCriteria = creditcriteria.EvaluationCriteria__c ; 
            this.FICOScore = creditcriteria.FICOScore__c != null ? string.valueOf(creditcriteria.FICOScore__c) : ''; 
            this.FICOScoreOperator = creditcriteria.FICOScoreOperator__c != null ? creditcriteria.FICOScoreOperator__c : '';
            this.timePeriod  = creditcriteria.TimePeriodMonths__c != null ? String.valueOf(creditcriteria.TimePeriodMonths__c) : '';
            this.timePeriodOperator = creditcriteria.TimePeriodOperator__c != null ? creditcriteria.TimePeriodOperator__c : '';
            this.declineType = creditcriteria.DeclineType__c;   
        }
    }
    public class CreditCriteriaServiceException extends Exception {}

}