vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>JSONPayload__c</fullName>
        <inlineHelpText>The raw results of the credit check module in JSON format.</inlineHelpText>
        <label>JSON Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Credit Check.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/classes/CreditCheckService_TEST.cls
@isTest
public class CreditCheckService_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, StudentProgram__c> agreementMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, studentMap, programMap);
    }
    
    @isTest public static void validateGetCreditCheckWithCreditCheckID(){
    	Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);

    	Test.startTest();
    	List<CreditCheckService.CreditCheck> ccs = CreditCheckService.getCreditCheckWithCreditCheckID(ccMap.keySet());
    	System.assertEquals(ccMap.size(), ccs.size());
    	Test.stopTest();
    }
    
    @isTest public static void validateGetCreditCheckWithStudentID(){
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();        
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);
        Set<Id> studentIds = new Set<Id>();
        for(CreditCheck__c cc : ccMap.values()){
            studentIds.add(cc.Student__c);
        }
        Test.startTest();
        List<CreditCheckService.CreditCheck> ccs = CreditCheckService.getCreditCheckWithStudentID(studentIds);
        System.assertEquals(ccMap.size(), ccs.size());
        Test.stopTest();
    }

    @isTest public static void validateGetCreditCheckWithAgreementID(){
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();        
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);



        Integer maxSize = agreementMap.size();
        if(ccMap.size()<maxSize) maxSize = ccMap.size();

        for(Integer i = 0; i<maxSize; i++){
            agreementMap.values()[i].CreditCheck__c = ccMap.values()[i].id;
        }
        update agreementMap.values();
        system.debug('agreementMap:'+agreementMap);
        system.debug('ccMap:'+ccMap);



        Test.startTest();
        List<CreditCheckService.CreditCheck> ccs = CreditCheckService.getCreditCheckWithAgreementID(agreementMap.keySet());
        System.assertEquals(ccMap.size(), ccs.size());
        Test.stopTest();
    }
    
    @isTest public static void validateCreateCreditChecks(){

        Map<ID, Account> studentMap = AccountQueries.getStudentMap();

    	List<CreditCheckService.CreditCheck> ccList = new List<CreditCheckService.CreditCheck>();
    	for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
    		CreditCheckService.CreditCheck cc = new CreditCheckService.CreditCheck(true);
    		cc.studentID = studentMap.values().get(i).id;
    		ccList.add(cc);
    	}
    	Test.startTest();
    	Set<ID> ccIDs = CreditCheckService.createCreditChecks(ccList);
    	System.assertEquals(ccList.size(), CreditCheckQueries.getCreditCheckMap().size());
    	Test.stopTest();
    }

    @isTest public static void  validateUpdateCreditChecks(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();

    	List<CreditCheckService.CreditCheck> ccList = new List<CreditCheckService.CreditCheck>();
    	for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
    		CreditCheckService.CreditCheck cc = new CreditCheckService.CreditCheck(true);
    		cc.studentID = studentMap.values().get(i).ID;
    		ccList.add(cc);
    	}
    	Set<ID> ccIDs = CreditCheckService.createCreditChecks(ccList);
    	List<CreditCheckService.CreditCheck> newCCs = CreditCheckService.getCreditCheckWithCreditCheckID(ccIDs);
    	for(CreditCheckService.CreditCheck cc : newCCs){
    		cc.jsonPayload = 'updated payload';
    	}
    	Test.startTest();
    	Set<ID> updatedCCIDs = CreditCheckService.updateCreditChecks(newCCs);
    	Test.stopTest();
    	Map<ID, CreditCheck__c> ccMap = CreditCheckQueries.getCreditCheckMapWithCreditCheckID(updatedCCIDs);
    	for(CreditCheck__c cc : ccMap.values()){
    		System.assertEquals('updated payload', cc.JSONPayload__c);
    	}
    }

    @isTest public static void validateDeleteCreditChecks(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);

    	Test.startTest();
    	Integer numDeleted = CreditCheckService.deleteCreditChecks(ccMap.keySet());
    	System.assertEquals(ccMap.size(), numDeleted);
    	System.assertEquals(0, CreditCheckQueries.getCreditCheckMap().size());
    	Test.stopTest();
    }
    
}