vemo-mdapi-qa/objects/CreditCriteria__c.object
<CustomObject>
    <label>Credit Criteria</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Credit Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Criteria</relationshipLabel>
        <relationshipName>Credit_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-app/main/default/classes/CreditCriteriaQueries_TEST.cls
@isTest
public with sharing class CreditCriteriaQueries_TEST{
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
    @isTest
    public static void validateGetCreditCriteriaMapWithProgramID(){
        //create students
        Map<Id,Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(2);
        //create Programs with school
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(3,TestDataFactory.createAndInsertSchoolCustomerAccounts(2));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        integer cnt = 0;
        for(Account acc:studentMap.values()){
            if(cnt<3){
                acc.PrimarySchool__pc = schoolMap.values()[0].id;
            }
            else{
                acc.PrimarySchool__pc = schoolMap.values()[1].id;
            }    
        }
        update studentMap.values();
        Map<ID, CreditCriteria__c> CreditCriteriaMap = TestDataFactory.createAndInsertCreditCriteria(1,programMap);
        Test.startTest();
        Set<Id> programIDs = new Set<ID>();
        for(CreditCriteria__c cc : CreditCriteriaMap.values()){
            programIDs.add(cc.Program__c);
        }
        Map<Id,CreditCriteria__c> ccMapResult = CreditCriteriaQueries.getCreditCriteriaMapWithProgramID(programIDs);
        System.assertEquals(CreditCriteriaMap.keySet().size(), ccMapResult.keySet().size());
        Test.stopTest();
    }

}