vemo-mdapi-qa/objects/CreditCriteria__c.object
<CustomObject>
    <label>Credit Criteria</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Credit Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Criteria</relationshipLabel>
        <relationshipName>Credit_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/classes/CreditCriteriaService_TEST.cls
@isTest
public class CreditCriteriaService_TEST {

    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
         
    }
    
    @isTest
    public static void validateGetCreditCriteriaWithProgramID(){
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        for(Account stud : studentMap.values()){
            stud.PrimarySchool__pc = schoolMap.values()[0].id;
        }
        update studentMap.values();
        
        Map<ID, CreditCriteria__c> CreditCriteriaMap = TestDataFactory.createAndInsertCreditCriteria(1,programMap);
        Test.startTest();
        Set<Id> programIDs = new Set<ID>();
        for(CreditCriteria__c cc : CreditCriteriaMap.values()){
            programIDs.add(cc.Program__c);
        }
        List<CreditCriteriaService.CreditCriteria> ccList = CreditCriteriaService.getCreditCriteriaWithProgramID(programIDs);
        System.assertEquals(CreditCriteriaMap.keySet().size(), ccList.size());
        Test.stopTest();
    
    }
     @isTest
    public static void validategetCreditCriteriaByProgramIDWithProgramID(){
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        for(Account stud : studentMap.values()){
            stud.PrimarySchool__pc = schoolMap.values()[0].id;
        }
        update studentMap.values();
        
        Map<ID, CreditCriteria__c> CreditCriteriaMap = TestDataFactory.createAndInsertCreditCriteria(1,programMap);
        Test.startTest();
        Set<Id> programIDs = new Set<ID>();
        for(CreditCriteria__c cc: CreditCriteriaMap.values()){
            programIDs.add(cc.Program__c);
        }
        Map<Id,List<CreditCriteriaService.CreditCriteria>> ccMap = CreditCriteriaService.getCreditCriteriaByProgramIDWithProgramID(programIDs);
        System.assertEquals(programIDs.size(), ccMap.keyset().size());
        Test.stopTest();
    }
}