vemo-mdapi-qa/objects/CreditCriteria__c.object
<CustomObject>
    <label>Credit Criteria</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Credit Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AmountOperator__c</fullName>
        <label>Amount Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DeclineType__c</fullName>
        <label>Decline Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DeclineType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EvaluationCriteria__c</fullName>
        <label>Evaluation Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditEvaluationCriteria</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FICOScoreOperator__c</fullName>
        <label>FICO Score Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FICOScore__c</fullName>
        <label>FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Criteria</relationshipLabel>
        <relationshipName>Credit_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimePeriodMonths__c</fullName>
        <label>Time Period(Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TimePeriodOperator__c</fullName>
        <label>Time Period Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/CreditEvaluationCriteria.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FICO Score</fullName>
    </customValue>
    <customValue>
        <fullName>Educational Loan Default</fullName>
    </customValue>
    <customValue>
        <fullName>Bankruptcy</fullName>
    </customValue>
    <customValue>
        <fullName>Major Derogatory Public Record</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfied Suit or Judgement</fullName>
    </customValue>
    <customValue>
        <fullName>Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Tax Liens</fullName>
    </customValue>
    <masterLabel>Credit Evaluation Criteria</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/DeclineType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hard Decline</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Decline</fullName>
    </customValue>
    <masterLabel>Decline Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/Operator.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&gt;</fullName>
    </customValue>
    <customValue>
        <fullName>&lt;</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;=</fullName>
    </customValue>
    <customValue>
        <fullName>&lt;=</fullName>
    </customValue>
    <customValue>
        <fullName>=</fullName>
    </customValue>
    <customValue>
        <fullName>!=</fullName>
    </customValue>
    <masterLabel>Operator</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/CreditCriteriaQueries.cls
public class CreditCriteriaQueries{
    
    public static Map<ID, CreditCriteria__c> getCreditCriteriaMapWithProgramID(set<ID> programIDs){
        Map<ID, CreditCriteria__c> CreditCriteriaMap = new Map<ID, CreditCriteria__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Program__c IN ' + DatabaseUtil.inSetStringBuilder(programIDs);
        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        //query += ' Order By AttendanceBeginDate__c asc';
        query += ' '+ generateLIMITStatement();
        system.debug('no of queries-');
        DatabaseUtil db = new DatabaseUtil();
        CreditCriteriaMap = new Map<ID, CreditCriteria__c>((List<CreditCriteria__c>)db.query(query));
        return CreditCriteriaMap;
    }
    
    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getfieldNames() + ' FROM CreditCriteria__c';
        system.debug(soql);
        return soql;
    }
   
    private static String getfieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'Name, ';
        fieldNames += 'Amount__c, ';
        fieldNames += 'AmountOperator__c, ';
        fieldNames += 'DeclineType__c, ';
        fieldNames += 'EvaluationCriteria__c, ';
        
        fieldNames += 'FICOScore__c, ';
        fieldNames += 'FICOScoreOperator__c, ';
        fieldNames += 'Program__c, ';
        fieldNames += 'TimePeriodMonths__c, ';
        fieldNames += 'TimePeriodOperator__c ';
        
        
        return fieldNames;
    }
    
    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }

}