vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Credit Check.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Checks</relationshipLabel>
        <relationshipName>CreditChecks</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/VemoAPICreditCheckResource_TEST.cls
@isTest
public class VemoAPICreditCheckResource_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, StudentProgram__c> agreementMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, studentMap, programMap);

    }

    static testMethod void testHandleGetV1(){
    	Map<ID, Account> studentMap = AccountQueries.getStudentMap();
    	Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
    	Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);

    	agreementMap.values()[0].CreditCheck__c = ccMap.values()[0].id;
    	update agreementMap.values();

    	System.assertEquals(CreditCheckQueries.getCreditCheckMap().size(), TestUtil.TEST_THROTTLE, 'Did not create credit checks');

    	Map<String, String> ccParams = new Map<String, String>();
		ccParams.put('creditCheckID', (String)ccMap.values().get(0).Id);
		ccParams.put('VEMO_AUTH', 'ABC');
		VemoAPI.APIInfo ccApiInfo = TestUtil.initializeAPI('v1', 'GET', ccParams, null);

		Map<String, String> studParams = new Map<String, String>();
		studParams.put('studentID', (String)ccMap.values().get(0).Student__c);
		studParams.put('VEMO_AUTH', 'ABC');
		VemoAPI.APIInfo studApiInfo = TestUtil.initializeAPI('v1', 'GET', studParams, null);

		Map<String, String> agreeParams = new Map<String, String>();
		agreeParams.put('agreementID', (String)agreementMap.values().get(0).ID);
		agreeParams.put('VEMO_AUTH', 'ABC');
		VemoAPI.APIInfo agreeApiInfo = TestUtil.initializeAPI('v1', 'GET', agreeParams, null);

		Test.startTest();
		VemoAPI.ResultResponse ccResult = (VemoAPI.ResultResponse)VemoAPICreditCheckResource.handleAPI(ccApiInfo);
		System.assertEquals(1, ccResult.numberOfResults);

		VemoAPI.ResultResponse studResult = (VemoAPI.ResultResponse)VemoAPICreditCheckResource.handleAPI(studApiInfo);
		System.assertEquals(1, studResult.numberOfResults);

		VemoAPI.ResultResponse agreeResult = (VemoAPI.ResultResponse)VemoAPICreditCheckResource.handleAPI(agreeApiInfo);
		System.assertEquals(1, agreeResult.numberOfResults);
		Test.stopTest();		
    }
    
    static testMethod void testHandlePostV1(){
    	Map<String, String> params = new Map<String, String>();
		params.put('VEMO_AUTH', 'ABC');

		Map<ID, Account> students = AccountQueries.getStudentMap();

		List<VemoAPICreditCheckResource.CreditCheckResourceInputV1> ccResMap = new List<VemoAPICreditCheckResource.CreditCheckResourceInputV1>();
		for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
			VemoAPICreditCheckResource.CreditCheckResourceInputV1 ccRes = new VemoAPICreditCheckResource.CreditCheckResourceInputV1(true);
			ccRes.studentID = students.values().get(i).ID;
			ccResMap.add(ccRes);
		}

		String body = JSON.serialize(ccResMap);
		VemoAPI.APIInfo apiInfo = TestUtil.initializeAPI('v1', 'POST', params, body);

		Test.startTest();
		VemoAPI.ResultResponse result = (VemoAPI.ResultResponse)VemoAPICreditCheckResource.handleAPI(apiInfo);
		System.assertEquals(TestUtil.TEST_THROTTLE, result.numberOfResults);
		Test.stopTest();
    }

    static testMethod void testHandlePutV1(){
    	Map<ID, Account> studentMap = AccountQueries.getStudentMap();
    	Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);
    	System.assertEquals(CreditCheckQueries.getCreditCheckMap().size(), TestUtil.TEST_THROTTLE, 'Did not create credit checks');

    	Map<String, String> params = new Map<String, String>();
		params.put('VEMO_AUTH', 'ABC');

    	List<VemoAPICreditCheckResource.CreditCheckResourceInputV1> ccResMap = new List<VemoAPICreditCheckResource.CreditCheckResourceInputV1>();
    	for(CreditCheck__c cc : ccMap.values()){
    		VemoAPICreditCheckResource.CreditCheckResourceInputV1 ccRes = new VemoAPICreditCheckResource.CreditCheckResourceInputV1();
    		ccRes.creditCheckID = cc.ID;
    		ccRes.jsonPayload = 'updated payload';
    		ccResMap.add(ccRes);
    	}
    	String body = JSON.serialize(ccResMap);
		VemoAPI.APIInfo apiInfo = TestUtil.initializeAPI('v1', 'PUT', params, body);

		Test.startTest();
		VemoAPI.ResultResponse result = (VemoAPI.ResultResponse)VemoAPICreditCheckResource.handleAPI(apiInfo);
		System.assertEquals(ccResMap.size(), result.numberOfResults);
		Test.stopTest();
    }

    static testMethod void testHandleDeleteV1(){
    	Map<ID, Account> studentMap = AccountQueries.getStudentMap();
    	Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);
    	System.assertEquals(CreditCheckQueries.getCreditCheckMap().size(), TestUtil.TEST_THROTTLE, 'Did not create credit checks');

    	Map<String, String> params = new Map<String, String>();
		params.put('VEMO_AUTH', 'ABC');
		params.put('creditCheckID', (String)ccMap.values().get(0).Id);

		VemoAPI.APIInfo apiInfo = TestUtil.initializeAPI('v1', 'DELETE', params, null);

		Test.startTest();
		VemoAPI.ResultResponse result = (VemoAPI.ResultResponse)VemoAPICreditCheckResource.handleAPI(apiInfo);
		System.assertEquals(1, result.numberOfResults);
		System.assertEquals(TestUtil.TEST_THROTTLE - 1, CreditCheckQueries.getCreditCheckMap().size(), 'One Credit Check should be deleted');
		Test.stopTest();
    }
    
}