vemo-mdapi-qa/objects/CreditCheck__c.object
<CustomObject>
    <label>Credit Check</label>
    <nameField>
        <displayFormat>CC-{YYYY}{MM}{DD}{000}</displayFormat>
        <label>Credit Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/CreditCheckQueries_TEST.cls
@isTest
public class CreditCheckQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, StudentProgram__c> agreementMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, studentMap, programMap);

    }
    @isTest public static void validateGetCreditCheckMap(){
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
    	Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);
    	Test.startTest();
    	Map<ID, CreditCheck__c> resultCCMap = CreditCheckQueries.getCreditCheckMap();
    	System.assertEquals(ccMap.keySet().size(), resultCCMap.keySet().size());
    	Test.stopTest();
    }
    

    @isTest public static void validateGetCreditCheckMapWithCreditCheckID(){
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);
    	Test.startTest();
    	Map<ID, CreditCheck__c> resultCCMap = CreditCheckQueries.getCreditCheckMapWithCreditCheckID(ccMap.keySet());
    	System.assertEquals(ccMap.keySet().size(), resultCCMap.keySet().size());
    	Test.stopTest();
    }

    @isTest public static void validateGetCreditCheckMapWithStudentID(){
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);    
        Test.startTest();
        Map<ID, CreditCheck__c> resultCCMap = CreditCheckQueries.getCreditCheckMapWithStudentID(studentMap.keyset());
        System.assertEquals(ccMap.keySet().size(), resultCCMap.keySet().size());
        Test.stopTest();
    }
    @isTest public static void validateGetCreditCheckMapWithAgreementID(){
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, CreditCheck__c> ccMap = TestDataFactory.createAndInsertCreditCheck(TestUtil.TEST_THROTTLE, studentMap);    



        Integer maxSize = agreementMap.size();
        if(ccMap.size()<maxSize) maxSize = ccMap.size();

        for(Integer i = 0; i<maxSize; i++){
            agreementMap.values()[i].CreditCheck__c = ccMap.values()[i].id;
        }
        update agreementMap.values();
        system.debug('agreementMap:'+agreementMap);
        system.debug('ccMap:'+ccMap);

        Test.startTest();
        Map<ID, CreditCheck__c> resultCCMap = CreditCheckQueries.getCreditCheckMapWithAgreementID(agreementMap.keySet());
        System.assertEquals(ccMap.keySet().size(), resultCCMap.keySet().size());
        Test.stopTest();
    }
}