vemo-mdapi-qa/objects/CreditCriteria__c.object
<CustomObject>
    <label>Credit Criteria</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Credit Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Criteria</relationshipLabel>
        <relationshipName>Credit_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-app/main/default/classes/VemoAPICreditCriteriaResource_TEST.cls
@isTest
public class VemoAPICreditCriteriaResource_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
    static testMethod void testHandleGetV1(){
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        for(Account stud : studentMap.values()){
            stud.PrimarySchool__pc = schoolMap.values()[0].id;
        }
        update studentMap.values();
        VemoAPI.APIInfo CreditCriteriaApiInfo = TestUtil.initializeAPI('v1', 'GET', null, null);
        Map<ID, CreditCriteria__c> CreditCriteriaMap = TestDataFactory.createAndInsertCreditCriteria(1,programMap);  
        Test.startTest();
        Set<Id> programIDs = new Set<ID>();
        for(CreditCriteria__c cc : CreditCriteriaMap.values()){
            programIDs.add(cc.Program__c);
        }
        List<CreditCriteriaService.CreditCriteria> ccList = CreditCriteriaService.getCreditCriteriaWithProgramID(programIDs);
        List<VemoAPICreditCriteriaResource.CreditCriteriaResourceOutputV1> criteriaList = new List<VemoAPICreditCriteriaResource.CreditCriteriaResourceOutputV1>();
        for(CreditCriteriaService.CreditCriteria cc: ccList){
            VemoAPICreditCriteriaResource.CreditCriteriaResourceOutputV1 criteriaResource = new VemoAPICreditCriteriaResource.CreditCriteriaResourceOutputV1(cc);    
            criteriaList.add(criteriaResource); 
        }
        VemoAPI.ResultResponse CreditCriteriaResult = (VemoAPI.ResultResponse)VemoAPICreditCriteriaResource.handleAPI(CreditCriteriaApiInfo);
        system.assertEquals(ccList.size(), criteriaList.size());
        Test.stopTest();  
    }

}