vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DateReported__c</fullName>
        <inlineHelpText>The date the student reported their employment.</inlineHelpText>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateVerified__c</fullName>
        <inlineHelpText>The date this employment was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>The Student related to this Employment History.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment History</relationshipLabel>
        <relationshipName>Employment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Full Time or Part Time</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The date the student&#39;s employment was verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BeginDate__c</fullName>
        <inlineHelpText>The date this Income began.</inlineHelpText>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateReported__c</fullName>
        <inlineHelpText>The date the student reported their Income.</inlineHelpText>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateVerified__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>The date the student&#39;s Income was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>The date this Income ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IncomePerMonth__c</fullName>
        <inlineHelpText>The student&#39;s monthly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IncomePerYear__c</fullName>
        <formula>Round( IncomePerMonth__c *12,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The student&#39;s yearly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Income Verification.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of Income Verification (Reported vs Estimated).</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has the student&#39;s Income been verified?</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <masterLabel>Employment Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/IncomeVerificationStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/IncomeVerificationType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Estimated</fullName>
    </customValue>
    <masterLabel>Income Verification Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/IncomeVerificationService.cls
/////////////////////////////////////////////////////////////////////////
// Class: IncomeVerificationService
// 
// Description: 
//  Handles all IncomeVerification DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-12   Jared Hagemann  Created              
/////////////////////////////////////////////////////////////////////////
public with sharing class IncomeVerificationService {
    public static List<IncomeVerification> getIncomeVerificationWithIncomeVerificationID(Set<ID> incomeVerificationIDs){
        System.debug('IncomeVerificationService.getIncomeVerificationWithIncomeVerificationID');
        Map<Id, IncomeVerification__c> incVerMap = IncomeVerificationQueries.getIncomeVerificationMapWithIncomeVerificationId(incomeVerificationIDs);
        List<IncomeVerification> incVerList = new List<IncomeVerification>();
        for(IncomeVerification__c incVer : incVerMap.values()){
            incVerList.add(new IncomeVerification(incVer));
        }
        return incVerList;
    }


    public static List<IncomeVerification> getIncomeVerificationWithStudentId(Set<ID> studentIds){
        System.debug('IncomeVerificationService.getIncomeVerificationWithStudentId');
        Map<Id, IncomeVerification__c> incVerMap = IncomeVerificationQueries.getIncomeVerificationMapWithStudentId(studentIds);
        List<IncomeVerification> incVerList = new List<IncomeVerification>();
        for(IncomeVerification__c incVer : incVerMap.values()){
            incVerList.add(new IncomeVerification(incVer));
        }
        return incVerList;
    }

    public static Set<Id> createIncomeVerification(List<IncomeVerification> incomeVerifications){
        System.debug('IncomeVerificationService.createIncomeVerification');
        List<IncomeVerification__c> incVerList = new List<IncomeVerification__c>();
        for(IncomeVerification incVer : incomeVerifications){
            IncomeVerification__c incVerObj = incVerClassToIncVerObject(incVer);
            incVerList.add(incVerObj);
        }
        insert incVerList;
        Set<Id> incVerIDs = new Set<Id>();
        for(IncomeVerification__c incVer : incVerList){
            incVerIDs.add(incVer.ID);
        }
        return incVerIDs;
    }

    public static Set<Id> updateIncomeVerification(List<IncomeVerification> incomeVerifications){
        System.debug('IncomeVerificationService.updateIncomeVerification');
        List<IncomeVerification__c> incVerList = new List<IncomeVerification__c>();
        for(IncomeVerification incVer : incomeVerifications){
            IncomeVerification__c incVerObj = incVerClassToIncVerObject(incVer);
            incVerList.add(incVerObj);
        }
        update incVerList;
        Set<Id> incVerIDs = new Set<Id>();
        for(IncomeVerification__c incVer : incVerList){
            incVerIDs.add(incVer.ID);
        }
        return incVerIDs;
    }

    public static Integer deleteIncomeVerificationy(Set<ID> incomeVerificationIDs){
        System.debug('IncomeVerificationService.deleteIncomeVerificationy');
        Map<ID, IncomeVerification__c> incVerMap = IncomeVerificationQueries.getIncomeVerificationMapWithIncomeVerificationId(incomeVerificationIDs);
        Integer numToDelete = incVerMap.size();
        delete incVerMap.values();
        return numToDelete;
    }


    public static IncomeVerification__c incVerClassToIncVerObject(IncomeVerification incVerClass){
        IncomeVerification__c incVerObj = new IncomeVerification__c();
        if(incVerClass.incomeVerificationID != null) incVerObj.ID = incVerClass.incomeVerificationID;

        if(incVerClass.incomePerMonth != null) incVerObj.IncomePerMonth__c = incVerClass.incomePerMonth;        
        if(incVerClass.employmentHistoryID != null) incVerObj.EmploymentHistory__c = incVerClass.employmentHistoryID;
        if(incVerClass.dateVerified != null) incVerObj.DateVerified__c = incVerClass.dateVerified;
        if(incVerClass.dateReported != null) incVerObj.DateReported__c = incVerClass.dateReported;
        if(incVerClass.beginDate != null) incVerObj.BeginDate__c = incVerClass.beginDate;       
        if(incVerClass.studentID != null) incVerObj.Student__c = incVerClass.studentID;
        if(incVerClass.endDate != null) incVerObj.EndDate__c = incVerClass.endDate;
        if(String.isNotEmpty(incVerClass.verified)){
            incVerObj.Verified__c = incVerClass.verified == 'true' ?  true : false;
        }       
        if(incVerClass.type != null) incVerObj.Type__c = incVerClass.type;
        if(incVerClass.status != null) incVerObj.Status__c = incVerClass.status;
        
        return incVerObj;
    }


    public class IncomeVerification{
        public String incomeVerificationID {get;set;}
        public Decimal incomePerYear {get;set;}
        public Decimal incomePerMonth {get;set;}
        public String employmentHistoryID {get;set;}
        public Date dateVerified {get;set;}
        public Date dateReported {get;set;}
        public Date beginDate {get;set;}
        public Date endDate {get;set;}
        public String studentID {get;set;}
        public String verified {get;set;}
        public String type {get;set;}
        public String status {get;set;}

        public IncomeVerification(){

        }

        public IncomeVerification(Boolean testValues){
            if(testValues){
                this.incomePerMonth = 5000; 
                this.dateVerified = System.today(); 
                this.verified = 'true'; 
            }
        }

        public IncomeVerification(IncomeVerification__c incVer){
            this.incomeVerificationID = incVer.ID;
            this.incomePerYear = incVer.IncomePerYear__c;   
            this.incomePerMonth = incVer.IncomePerMonth__c;
            this.employmentHistoryID = incVer.EmploymentHistory__c;     
            this.dateVerified = incVer.DateVerified__c;
            this.dateReported = incVer.DateReported__c;
            this.beginDate = incVer.BeginDate__c;
            this.type = incVer.Type__c;
            this.studentID = incVer.Student__c;
            this.verified = String.valueOf(incVer.Verified__c);
            this.endDate = incVer.EndDate__c;
            this.status = incVer.Status__c;
        }
    }
}