vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DateVerified__c</fullName>
        <inlineHelpText>The date this employment was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>The Student related to this Employment History.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment History</relationshipLabel>
        <relationshipName>Employment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The date the student&#39;s employment was verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DateVerified__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>The date the student&#39;s Income was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncomePerMonth__c</fullName>
        <inlineHelpText>The student&#39;s monthly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Income Verification.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has the student&#39;s Income been verified?</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/IncomeVerificationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/IncomeVerificationTriggerHandler_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: IncomeVerificationTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-07   Jared Hagemann  Created                              
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class IncomeVerificationTriggerHandler_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testVerify(){
        TestUtil.setStandardConfiguration();
        Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, EmploymentHistory__c> testEmpHisMap = TestDataFactory.createAndInsertEmploymentHistory(1, testStudentAccountMap);
        Map<Id, IncomeVerification__c> testIncVerMap = TestDataFactory.createAndInsertIncomeVerification(1, testEmpHisMap);
        IncomeVerification__c incVer = testIncVerMap.values().get(0);
        //incVer.Verified__c = true;
        incVer.status__c = 'Verified';
        incVer.IncomePerMonth__c = 1000;
        Test.startTest();
        update incVer;
        Account student = [select Id, DateIncomeVerified__pc, VerifiedAnnualIncome__pc from Account where Id =: incVer.Student__c];
        System.assertEquals(12000, student.VerifiedAnnualIncome__pc);
        System.assertEquals(System.today(), student.DateIncomeVerified__pc);

        IncomeVerification__c incVer2 = new IncomeVerification__c(IncomePerMonth__c = 2000,
                                                                        EmploymentHistory__c = incVer.EmploymentHistory__c,
                                                                        Student__c = student.Id,
                                                                        Status__c = 'Verified',
                                                                        DateVerified__c = System.today().addDays(2));


        insert incVer2;
        Account student2 = [select Id, DateIncomeVerified__pc, VerifiedAnnualIncome__pc from Account where Id =: incVer2.Student__c];       
        System.assertEquals(24000, student2.VerifiedAnnualIncome__pc);
        System.assertEquals(incVer2.DateVerified__c, student2.DateIncomeVerified__pc);
        Test.stopTest();
        
    }
}