vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Employee, Contractor, or Internship.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <inlineHelpText>The name of the organization employing the student.</inlineHelpText>
        <label>Employer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmploymentEndDate__c</fullName>
        <inlineHelpText>The date the employment ended.</inlineHelpText>
        <label>Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentStartDate__c</fullName>
        <inlineHelpText>The date the employment started.</inlineHelpText>
        <label>Employment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>The Student related to this Employment History.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment History</relationshipLabel>
        <relationshipName>Employment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Full Time or Part Time</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The date the student&#39;s employment was verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/EmploymentCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <masterLabel>Employment Category</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <masterLabel>Employment Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/EmploymentHistoryService.cls
/////////////////////////////////////////////////////////////////////////
// Class: EmploymentHistoryService
// 
// Description: 
// 	Handles all EmploymentHistory DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-11   Jared Hagemann  Created              
/////////////////////////////////////////////////////////////////////////
public with sharing class EmploymentHistoryService {

	public static List<EmploymentHistory> getEmploymentHistoryWithEmployentHistoryID(Set<ID> programIDs){
		System.debug('EmploymentHistoryService.getEmploymentHistoryWithEmployentHistoryID');
		Map<Id, EmploymentHistory__c> empHisMap = EmploymentHistoryQueries.getEmploymentHistoryMapWithEmploymentHistoryId(programIDs);
		List<EmploymentHistory> empHisList = new List<EmploymentHistory>();
		for(EmploymentHistory__c empHis : empHisMap.values()){
			empHisList.add(new EmploymentHistory(empHis));
		}
		return empHisList;
	}

	public static List<EmploymentHistory> getEmploymentHistoryWithStudentID(Set<ID> studentIds){
		System.debug('EmploymentHistoryService.getEmploymentHistoryWithStudentID');
		Map<Id, EmploymentHistory__c> empHisMap = EmploymentHistoryQueries.getEmploymentHistoryMapWithStudentId(studentIds);
		List<EmploymentHistory> empHisList = new List<EmploymentHistory>();
		for(EmploymentHistory__c empHis : empHisMap.values()){
			empHisList.add(new EmploymentHistory(empHis));
		}
		return empHisList;
	}

	public static Set<Id> createEmploymentHistory(List<EmploymentHistory> employmentHistory){
		System.debug('EmploymentHistoryService.createEmploymentHistory');
		List<EmploymentHistory__c> empHisList = new List<EmploymentHistory__c>();
		for(EmploymentHistory empHis : employmentHistory){
			EmploymentHistory__c empHisObj = empHisClassToEmpHisObject(empHis);
			empHisList.add(empHisObj);
		}
		insert empHisList;
		Set<Id> empHisIDs = new Set<Id>();
		for(EmploymentHistory__c empHis : empHisList){
			empHisIDs.add(empHis.ID);
		}
		return empHisIDs;
	}
	
	
	public static Set<Id> updateEmploymentHistory(List<EmploymentHistory> employmentHistory){
		System.debug('EmploymentHistoryService.updateEmploymentHistory');
		List<EmploymentHistory__c> empHisList = new List<EmploymentHistory__c>();
		for(EmploymentHistory empHis : employmentHistory){
			EmploymentHistory__c empHisObj = empHisClassToEmpHisObject(empHis);
			empHisList.add(empHisObj);
		}
		update empHisList;
		Set<Id> empHisIDs = new Set<Id>();
		for(EmploymentHistory__c empHis : empHisList){
			empHisIDs.add(empHis.ID);
		}
		return empHisIDs;
	}	
	
	public static Integer deleteEmploymentHistory(Set<ID> employmentHistoryIDs){
		System.debug('PaymentMethodService.deleteEmploymentHistory');
		Map<ID, EmploymentHistory__c> empHisMap = EmploymentHistoryQueries.getEmploymentHistoryMapWithEmploymentHistoryId(employmentHistoryIDs);
		Integer numToDelete = empHisMap.size();
		delete empHisMap.values();
		return numToDelete;
	}
	
	public static EmploymentHistory__c empHisClassToEmpHisObject(EmploymentHistory empHisClass){
		EmploymentHistory__c empHisObj = new EmploymentHistory__c();
		if(empHisClass.employmentHistoryID != null) empHisObj.ID = empHisClass.employmentHistoryID;
		if(empHisClass.category != null) empHisObj.Category__c = empHisClass.category;
		if(empHisClass.employer != null) empHisObj.Employer__c = empHisClass.employer;
		if(empHisClass.employmentEndDate != null) empHisObj.EmploymentEndDate__c = empHisClass.employmentEndDate;
		if(empHisClass.employmentStartDate != null) empHisObj.EmploymentStartDate__c = empHisClass.employmentStartDate;
		if(empHisClass.studentID != null) empHisObj.Student__c = empHisClass.studentID;
		if(empHisClass.type != null) empHisObj.Type__c = empHisClass.type;
		if(empHisClass.verified != null) empHisObj.Verified__c = empHisClass.verified;
		return empHisObj;
	}
	
	public class EmploymentHistory{
		public String employmentHistoryID {get;set;}
		public String category {get;set;}
		public String employer {get;set;}
		public Date employmentEndDate {get;set;}
		public Date employmentStartDate {get;set;}
		public String studentID {get;set;}
		public String type {get;set;}
		public Boolean verified {get;set;}

		public EmploymentHistory(){

		}

		public EmploymentHistory(Boolean testValues){
			if(testValues){
				this.category = 'Employee'; //Contractor, Internship
				this.employer = 'Test Employer'; //Planned, Closed, Cancelled
				this.type = 'Full Time'; //Part Time
			}
		}

		public EmploymentHistory(EmploymentHistory__c empHis){
			this.employmentHistoryID = empHis.ID;
			this.category = empHis.Category__c;	
			this.employer = empHis.Employer__c;		
			this.employmentEndDate = empHis.EmploymentEndDate__c;
			this.employmentStartDate = empHis.EmploymentStartDate__c;
			this.studentID = empHis.Student__c;
			this.type = empHis.Type__c;
			this.verified = empHis.Verified__c;
		}
	}
}