vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>DateReported__c</fullName>
        <inlineHelpText>The date the student reported their employment.</inlineHelpText>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateVerified__c</fullName>
        <inlineHelpText>The date this employment was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>The Student related to this Employment History.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment History</relationshipLabel>
        <relationshipName>Employment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Full Time or Part Time</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The date the student&#39;s employment was verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BeginDate__c</fullName>
        <inlineHelpText>The date this Income began.</inlineHelpText>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateReported__c</fullName>
        <inlineHelpText>The date the student reported their Income.</inlineHelpText>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateVerified__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>The date the student&#39;s Income was verified.</inlineHelpText>
        <label>Date Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>The date this Income ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IncomePerMonth__c</fullName>
        <inlineHelpText>The student&#39;s monthly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IncomePerYear__c</fullName>
        <formula>Round( IncomePerMonth__c *12,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The student&#39;s yearly Income at the Date Reported.</inlineHelpText>
        <label>Income Per Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Income Verification.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of Income Verification (Reported vs Estimated).</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IncomeVerificationType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has the student&#39;s Income been verified?</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <masterLabel>Employment Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/IncomeVerificationStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Income Verification Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/IncomeVerificationType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Estimated</fullName>
    </customValue>
    <masterLabel>Income Verification Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/IncomeVerificationQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: IncomeVerificationQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-11   Jared Hagemann  Created 
/////////////////////////////////////////////////////////////////////////
public class IncomeVerificationQueries {
    public static Map<String, Object> filterCriteria = new Map<String, Object>();
    public static void clearFilterCriteria(){
        filterCriteria.clear();
    }

    public static Map<ID, IncomeVerification__c> getIncomeVerificationMap(){
        Map<ID, IncomeVerification__c> incomeVerificationMap = new Map<ID, IncomeVerification__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Id != null';
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        incomeVerificationMap = new Map<ID, IncomeVerification__c>((List<IncomeVerification__c>)db.query(query));
        return incomeVerificationMap;       
    }

    public static Map<ID, IncomeVerification__c> getIncomeVerificationMapWithIncomeVerificationId(Set<Id> incomeVerificationIds){
        Map<ID, IncomeVerification__c> incomeVerificationMap = new Map<ID, IncomeVerification__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(incomeVerificationIds);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        incomeVerificationMap = new Map<ID, IncomeVerification__c>((List<IncomeVerification__c>)db.query(query));
        return incomeVerificationMap;       
    }

    public static Map<ID, IncomeVerification__c> getIncomeVerificationMapWithStudentId(Set<Id> studentIds){
        Map<ID, IncomeVerification__c> incomeVerificationMap = new Map<ID, IncomeVerification__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Student__c IN ' + DatabaseUtil.inSetStringBuilder(studentIds);
        if(DatabaseUtil.filterByStudentID){
            ID studentID = DatabaseUtil.studentPersonAccountID;
            query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
        }
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        incomeVerificationMap = new Map<ID, IncomeVerification__c>((List<IncomeVerification__c>)db.query(query));
        return incomeVerificationMap;       
    }

    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }
    
    private static String buildFilterString(){
        String filterStr = '';
        if(filterCriteria.size()>0){
            for(String filter : filterCriteria.keyset()){
                filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) +  '\' ');
            }           
        }
        return filterStr;
    }

    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getIncomeVerificationFieldNames() + ' FROM IncomeVerification__c ';
        return soql;
    }

    private static String getIncomeVerificationFieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'IncomePerMonth__c, ';
        fieldNames += 'IncomePerYear__c, ';
        fieldNames += 'BeginDate__c , ';
        fieldNames += 'EmploymentHistory__c, ';
        fieldNames += 'DateVerified__c, ';
        fieldNames += 'DateReported__c, ';
        fieldNames += 'Student__c, ';
        fieldNames += 'Type__c, ';
        fieldNames += 'Verified__c, ';
        fieldNames += 'EndDate__c, ';
        fieldNames += 'Status__c ';
        return fieldNames;
    }
}