vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Employee, Contractor, or Internship.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <inlineHelpText>The name of the organization employing the student.</inlineHelpText>
        <label>Employer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmploymentEndDate__c</fullName>
        <inlineHelpText>The date the employment ended.</inlineHelpText>
        <label>Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentStartDate__c</fullName>
        <inlineHelpText>The date the employment started.</inlineHelpText>
        <label>Employment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>The Student related to this Employment History.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment History</relationshipLabel>
        <relationshipName>Employment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Full Time or Part Time</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The date the student&#39;s employment was verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/EmploymentCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <masterLabel>Employment Category</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/EmploymentType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <masterLabel>Employment Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/EmploymentHistoryQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: EmploymentHistoryQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-11   Jared Hagemann	Created 
/////////////////////////////////////////////////////////////////////////
public class EmploymentHistoryQueries {
	public static Map<String, Object> filterCriteria = new Map<String, Object>();
	public static void clearFilterCriteria(){
		filterCriteria.clear();
	}

	public static Map<ID, EmploymentHistory__c> getEmploymentHistoryMap(){
		Map<ID, EmploymentHistory__c> empHisMap = new Map<ID, EmploymentHistory__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Id != null';
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		empHisMap = new Map<ID, EmploymentHistory__c>((List<EmploymentHistory__c>)db.query(query));
		return empHisMap;		
	}

	public static Map<ID, EmploymentHistory__c> getEmploymentHistoryMapWithStudentId(Set<ID> studentIds){
		Map<ID, EmploymentHistory__c> empHisMap = new Map<ID, EmploymentHistory__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Student__c IN ' + DatabaseUtil.inSetStringBuilder(studentIds);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		empHisMap = new Map<ID, EmploymentHistory__c>((List<EmploymentHistory__c>)db.query(query));
		return empHisMap;
	}

	public static Map<ID, EmploymentHistory__c> getEmploymentHistoryMapWithEmploymentHistoryId(Set<ID> empHisIDs){
		Map<ID, EmploymentHistory__c> empHisMap = new Map<ID, EmploymentHistory__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(empHisIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		empHisMap = new Map<ID, EmploymentHistory__c>((List<EmploymentHistory__c>)db.query(query));
		return empHisMap;
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
	
	private static String buildFilterString(){
		String filterStr = '';
		if(filterCriteria.size()>0){
			for(String filter : filterCriteria.keyset()){
				filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) + 	'\' ');
			}			
		}
		return filterStr;
	}

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getEmploymentHistoryFieldNames() + ' FROM EmploymentHistory__c ';
		return soql;
	}

	private static String getEmploymentHistoryFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Category__c, ';
		fieldNames += 'Employer__c, ';
		fieldNames += 'EmploymentEndDate__c, ';
		fieldNames += 'EmploymentStartDate__c, ';
		fieldNames += 'Student__c, ';
		fieldNames += 'Type__c, ';
		fieldNames += 'Verified__c ';
		return fieldNames;
	}
}