vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/IncomeVerificationQueries_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: IncomeVerificationQueries_TEST
// 
// Description: 
//  Unit test for IncomeVerificationQueries
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-24   Jared Hagemann  Created 
/////////////////////////////////////////////////////////////////////////
@isTest
public class IncomeVerificationQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testGetIncomeVerificationMap(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<Id, EmploymentHistory__c> testEmpHisMap = TestDataFactory.createAndInsertEmploymentHistory(1, testStudentAccountMap);
    	Map<Id, IncomeVerification__c> testIncVerMap = TestDataFactory.createAndInsertIncomeVerification(1, testEmpHisMap);
    	Test.startTest();
    	Map<Id, IncomeVerification__c> resultIncVerMap = IncomeVerificationQueries.getIncomeVerificationMap();
    	System.assertEquals(testIncVerMap.keySet().size(), resultIncVerMap.keySet().size());
    	Test.stopTest();
    }

    static testMethod void testGetIncomeVerificationMapWithIncomeVerificationId(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<Id, EmploymentHistory__c> testEmpHisMap = TestDataFactory.createAndInsertEmploymentHistory(1, testStudentAccountMap);
    	Map<Id, IncomeVerification__c> testIncVerMap = TestDataFactory.createAndInsertIncomeVerification(1, testEmpHisMap);
    	Test.startTest();
    	Map<Id, IncomeVerification__c> resultIncVerMap = IncomeVerificationQueries.getIncomeVerificationMapWithIncomeVerificationId(testIncVerMap.keySet());
    	System.assertEquals(testIncVerMap.keySet().size(), resultIncVerMap.keySet().size());
    	Test.stopTest();
    }

    static testMethod void testGetIncomeVerificationMapWithStudentId(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<Id, EmploymentHistory__c> testEmpHisMap = TestDataFactory.createAndInsertEmploymentHistory(1, testStudentAccountMap);
    	Map<Id, IncomeVerification__c> testIncVerMap = TestDataFactory.createAndInsertIncomeVerification(1, testEmpHisMap);
    	Test.startTest();
    	Map<Id, IncomeVerification__c> resultIncVerMap = IncomeVerificationQueries.getIncomeVerificationMapWithStudentId(testStudentAccountMap.keySet());
    	System.assertEquals(testIncVerMap.keySet().size(), resultIncVerMap.keySet().size());
    	Test.stopTest();
    }
}