vemo-mdapi-qa/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{00000000}</displayFormat>
        <label>Employment History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/GenericDocument__c.object
<CustomObject>
    <label>Generic Document</label>
    <nameField>
        <displayFormat>GD-{0000000000}</displayFormat>
        <label>Generic Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ParentID__c</fullName>
        <label>ParentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/IncomeVerification__c.object
<CustomObject>
    <label>Income Verification</label>
    <nameField>
        <displayFormat>IV-{00000000}</displayFormat>
        <label>Income Verification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Verification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EmploymentHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Employment History record.</inlineHelpText>
        <label>Employment History</label>
        <referenceTo>EmploymentHistory__c</referenceTo>
        <relationshipLabel>Income Verification</relationshipLabel>
        <relationshipName>Income_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/GenericDocumentQueries_TEST.cls
@isTest
public with sharing class GenericDocumentQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
	@isTest public static void validateGetGenericDocumentMapByID() {
		Map<Id, GenericDocument__c> testDocMap = TestDataFactory.createAndInsertGenericDocument(TestUtil.TEST_THROTTLE);
		Test.startTest();
		Map<Id, GenericDocument__c> resultDocMap = GenericDocumentQueries.getGenericDocumentMapByID(testDocMap.keySet());
		System.assertEquals(testDocMap.keySet().size(), resultDocMap.keySet().size());
		Test.stopTest();
	}

	@isTest public static void validateGetGenericDocumentMapByParentID() {
		TestUtil.setStandardConfiguration();

    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<Id, EmploymentHistory__c> testEmpHisMap = TestDataFactory.createAndInsertEmploymentHistory(1, testStudentAccountMap);
    	Map<Id, IncomeVerification__c> testIncVerMap = TestDataFactory.createAndInsertIncomeVerification(1, testEmpHisMap);
		Map<Id, GenericDocument__c> testDocMap = TestDataFactory.createAndInsertGenericDocument(TestUtil.TEST_THROTTLE);
    	Set<String> incStrings = new Set<String>();		
		for(IncomeVerification__c inc : testIncVerMap.values()){
			incStrings.add(((String)inc.id).subString(0,15));
		}
		for(GenericDocument__c genDoc : testDocMap.values()){
			genDoc.ParentID__c = ((String)(testIncVerMap.values()[0].id)).substring(0,15);
		}
		update testDocMap.values();

		Test.startTest();
		Map<Id, GenericDocument__c> resultDocMap = GenericDocumentQueries.getGenericDocumentMapByParentID(incStrings);

		System.debug('1:'+[SELECT id, ParentID__c from GenericDocument__c]);
		System.debug('2:'+[SELECT id from IncomeVerification__c]);
		System.assertEquals(testDocMap.keySet().size(), resultDocMap.keySet().size());
		Test.stopTest();
	}

}