vemo-mdapi-qa/objects/Fee__c.object
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>FEE-{0000000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Late Fee or NSF Fee.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentAllocation__c.object
<CustomObject>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Fee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Fee related to this Payment Allocation.</inlineHelpText>
        <label>Fee</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <inlineHelpText>The Payment Instruction related to this Payment Allocation.</inlineHelpText>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/globalValueSets/DebitType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/FeeType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Late Fee</fullName>
    </customValue>
    <customValue>
        <fullName>NSF Fee</fullName>
    </customValue>
    <masterLabel>Fee Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/LedgerViewController_TEST.cls
@isTest
public class LedgerViewController_TEST{
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        //create students
        Map<Id,Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(1);
        //create Programs with school
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(1,TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        integer cnt = 0;
        for(Account acc:studentMap.values()){
            acc.PrimarySchool__pc = schoolMap.values()[0].id;
        }
        update studentMap.values();
        
                 
        //create an agreement for student
        Map<ID, StudentProgram__c> studProgramMap = TestDataFactory.createAndInsertStudentProgram(1,studentMap,programMap);
        Map<ID, StudentProgramMonthlyStatus__c> monthlyStatusMap = TestDataFactory.createAndInsertStudentProgramMonthlyStatus(2,studProgramMap);
        Map<ID, StudentProgramAmountDue__c> spAmtDueMap = TestDataFactory.createAndInsertStudentProgramAmountDue(studProgramMap, monthlyStatusMap);
        integer count=0;
        for(StudentProgramAmountDue__c ad:spAmtDueMap.values()){
            ad.AssessmentDateTime__c = Datetime.now();
            if(count == 0){
                ad.type__c = 'Reconciliation';
                count++;
            }
        }
        update spAmtDueMap.values();
        
        Map<ID, PaymentMethod__c> pmMap = TestDataFactory.createAndInsertPaymentMethod(1, studentMap);
        Map<ID, PaymentInstruction__c> piMap = TestDataFactory.createAndInsertPaymentInstruction(2, studentMap, pmMap);
        Map<ID, PaymentAllocation__c> paMap = TestDataFactory.createAndInsertPaymentAllocation(2, piMap, studProgramMap);   
        Map<Id, Fee__c> feeMap = TestDataFactory.createAndInsertFee(2, studentMap);            
    }
    
    @isTest
    public static void testGetStudent(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap(); 
        Test.StartTest();
        LedgerViewController.getStudent(studentMap.values()[0].id);    
        Test.StopTest();
    }
    
    @isTest
    public static void testGetJournalEntriesWithCustomerID(){
    Map<ID, Account> studentMap = AccountQueries.getStudentMap(); 
        Test.StartTest();
        LedgerViewController.getJournalEntriesWithCustomerID(studentMap.values()[0].id);  
        Test.StopTest();
    } 
}