vemo-mdapi-qa/objects/Fee__c.object
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>FEE-{0000000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount of the fee.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>DateAssessed__c</fullName>
        <inlineHelpText>The date the fee was assessed.</inlineHelpText>
        <label>Date Assessed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateCleared__c</fullName>
        <inlineHelpText>The date the fee&#39;s payment cleared.</inlineHelpText>
        <label>Date Cleared</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Unpaid, Paid, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Late Fee or NSF Fee.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/FeeStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Fee Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/FeeType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Late Fee</fullName>
    </customValue>
    <customValue>
        <fullName>NSF Fee</fullName>
    </customValue>
    <masterLabel>Fee Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/FeeService.cls
/////////////////////////////////////////////////////////////////////////
// Class: FeeService
// 
// Description: 
// 	Handles all FeeService DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-24   Jared Hagemann  Created              
/////////////////////////////////////////////////////////////////////////
public with sharing class FeeService {
	public static List<Fee> getFeeWithFeeID(Set<ID> feeIDs){
		Map<Id, Fee__c> feeMap = FeeQueries.getFeeMapWithFeeId(feeIDs);
		List<Fee> feeList = new List<Fee>();
		for(Fee__c fe : feeMap.values()){
			feeList.add(new Fee(fe));
		}
		return feeList;
	}

	public static List<Fee> getFeeWithCustomerID(Set<ID> customerIDs){
		Map<Id, Fee__c> feeMap = FeeQueries.getFeeMapWithCustomerId(customerIDs);
		List<Fee> feeList = new List<Fee>();
		for(Fee__c fe : feeMap.values()){
			feeList.add(new Fee(fe));
		}
		return feeList;
	}

	public class Fee{
		public String feeID {get;set;}
		public Decimal amount {get;set;}
		public String customer {get;set;}
		public Date dateAssessed {get;set;}
		public Date dateCleared {get;set;}
		public String status {get;set;}
		public String type {get;set;}

		public Fee(){

		}

		public Fee(Boolean testValues){
			if(testValues){
				this.amount = 1000; 
				this.dateAssessed = System.today(); 
				this.dateCleared = System.today();
				this.status = 'Unpaid'; //Paid, Cancelled
				this.type = 'Late Fee'; //NSF Fee
			}
		}

		public Fee(Fee__c fe){
			this.feeID = fe.ID;
			this.amount = fe.Amount__c;	
			this.customer = fe.Customer__c;
			this.dateAssessed = fe.DateAssessed__c;		
			this.dateCleared = fe.DateCleared__c;
			this.status = fe.Status__c;
			this.type = fe.Type__c;
		}
	}
}