vemo-mdapi-qa/objects/Fee__c.object
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>FEE-{0000000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount of the fee.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>DateAssessed__c</fullName>
        <inlineHelpText>The date the fee was assessed.</inlineHelpText>
        <label>Date Assessed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateCleared__c</fullName>
        <inlineHelpText>The date the fee&#39;s payment cleared.</inlineHelpText>
        <label>Date Cleared</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Unpaid, Paid, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Late Fee or NSF Fee.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FeeType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/FeeStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Fee Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/FeeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Late Fee</fullName>
    </customValue>
    <customValue>
        <fullName>NSF Fee</fullName>
    </customValue>
    <masterLabel>Fee Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/FeeQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: IncomeVerificationQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-11   Jared Hagemann	Created 
/////////////////////////////////////////////////////////////////////////
public class FeeQueries {
	public static Map<String, Object> filterCriteria = new Map<String, Object>();

	public static Map<ID, Fee__c> getFeeMap(){
		Map<ID, Fee__c> feeMap = new Map<ID, Fee__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Id != null';
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Customer__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		feeMap = new Map<ID, Fee__c>((List<Fee__c>)db.query(query));
		return feeMap;		
	}

	public static Map<ID, Fee__c> getFeeMapWithFeeId(Set<Id> feeIds){
		Map<ID, Fee__c> feeMap = new Map<ID, Fee__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(feeIds);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Customer__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		feeMap = new Map<ID, Fee__c>((List<Fee__c>)db.query(query));
		return feeMap;		
	}

	public static Map<ID, Fee__c> getFeeMapWithCustomerId(Set<Id> customerIds){
		Map<ID, Fee__c> feeMap = new Map<ID, Fee__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Customer__c IN ' + DatabaseUtil.inSetStringBuilder(customerIds);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Customer__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		feeMap = new Map<ID, Fee__c>((List<Fee__c>)db.query(query));
		return feeMap;		
	}

	public static void clearFilterCriteria(){
		filterCriteria.clear();
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
	
	private static String buildFilterString(){
		String filterStr = '';
		if(filterCriteria.size()>0){
			for(String filter : filterCriteria.keyset()){
				filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) + 	'\' ');
			}			
		}
		return filterStr;
	}

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getIncomeVerificationFieldNames() + ' FROM Fee__c ';
		return soql;
	}

	private static String getIncomeVerificationFieldNames(){
		String fieldNames;
		fieldNames = 'Id, ';
		fieldNames += 'Amount__c, ';
		fieldNames += 'Customer__c, ';
		fieldNames += 'DateAssessed__c , ';
		fieldNames += 'DateCleared__c, ';
		fieldNames += 'Status__c, ';
		fieldNames += 'Type__c ';
		return fieldNames;
	}
}