vemo-mdapi-qa/objects/GenericDocument__c.object
<CustomObject>
    <label>Generic Document</label>
    <nameField>
        <displayFormat>GD-{0000000000}</displayFormat>
        <label>Generic Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <label>AttachmentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentName__c</fullName>
        <label>Attachment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/OutboundEmail__c.object
<CustomObject>
    <label>Outbound Email</label>
    <nameField>
        <displayFormat>Email-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Outbound Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CurrentNumberofAttachments__c</fullName>
        <label>Current Number of Attachments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AdobeSignStatus__c</fullName>
        <inlineHelpText>The status of the AdobeSign process.</inlineHelpText>
        <label>Adobe Sign Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Begin Signing Process</fullName>
                </value>
                <value>
                    <fullName>Document Uploaded to Adobe</fullName>
                </value>
                <value>
                    <fullName>Document Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Signing Widget Created</fullName>
                </value>
                <value>
                    <fullName>Document Signed</fullName>
                </value>
                <value>
                    <fullName>Signed Document Attached</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AgreementSigned__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if student has signed the agreement.</inlineHelpText>
        <label>Agreement Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CongaFinalDisclosureStatus__c</fullName>
        <inlineHelpText>The status of the Final Disclosure (Generate, Generated).</inlineHelpText>
        <label>Conga Final Disclosure Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Generate</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CongaUnsignedAgreementID__c</fullName>
        <inlineHelpText>The ID of the Unsigned Agreement.</inlineHelpText>
        <label>Conga Unsigned AgreementID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalDisclosureID__c</fullName>
        <inlineHelpText>Used by the system to construct the above Final Disclosure Clean URL.</inlineHelpText>
        <label>FinalDisclosureID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenerateAgreement__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Manually check this box to re-generate the Agreement.</inlineHelpText>
        <label>Generate Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GenerateFinalDisclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Manually check this box to re-generate the Final Disclosure.</inlineHelpText>
        <label>Generate Final Disclosure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SignedAgreementID__c</fullName>
        <inlineHelpText>Used by the system to construct the above Signed Agreement Clean URL.</inlineHelpText>
        <label>Signed AgreementID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/AgreementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/GenericDocumentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Uploaded</fullName>
    </customValue>
    <masterLabel>Generic Document Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/AttachmentTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: AttachmentTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-2016   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class AttachmentTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State Control Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution Control - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.TriggerContext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'AttachmentTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.TriggerContext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'AttachmentTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'AttachmentTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'AttachmentTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onBeforeInsert()');
       //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> newAttachmentList = (List<Attachment>)tc.newList;
        //This is where you should call your business logic


    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onBeforeUpdate()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> newAttachmentList = (List<Attachment>)tc.newList;
        List<Attachment> oldAttachmentList = (List<Attachment>)tc.oldList;
        Map<ID, Attachment> newAttachmentMap = (Map<ID, Attachment>)tc.newMap;
        Map<ID, Attachment> oldAttachmentMap = (Map<ID, Attachment>)tc.oldMap;
        //This is where you should call your business logic
 
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onBeforeDelete()');
       //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> oldAttachmentList = (List<Attachment>)tc.oldList;
        Map<ID, Attachment> oldAttachmentMap = (Map<ID, Attachment>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onAfterInsert()');
         //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> newAttachmentList = (List<Attachment>)tc.newList;
        Map<ID, Attachment> newAttachmentMap = (Map<ID, Attachment>)tc.newMap;
        //This is where you should call your business logic
        setDefaultsOnInsert(newAttachmentList);
        Map<String, Map<ID, Attachment>> attachmentsByObjectType = determineObjectType(newAttachmentMap);

        for(String objectType : attachmentsByObjectType.keyset()){
            if(objectType == 'StudentProgram__c') handleStudentProgramAttachments(null, newAttachmentMap);
            else if(objectType == 'GenericDocument__c') handleGenericDocumentAttachments(null, newAttachmentMap);
            else if(objectType == 'OutboundEmail__c') handleOutbountEmailAttachments(null, newAttachmentMap);
            
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onAfterUpdate()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> newAttachmentList = (List<Attachment>)tc.newList;
        List<Attachment> oldAttachmentList = (List<Attachment>)tc.oldList;
        Map<ID, Attachment> newAttachmentMap = (Map<ID, Attachment>)tc.newMap;
        Map<ID, Attachment> oldAttachmentMap = (Map<ID, Attachment>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldAttachmentMap, newAttachmentMap);
        
        Map<String, Map<ID, Attachment>> attachmentsByObjectType = determineObjectType(newAttachmentMap);
        
        for(String objectType : attachmentsByObjectType.keyset()){
            if(objectType == 'StudentProgram__c') handleStudentProgramAttachments(oldAttachmentMap, newAttachmentMap);
            else if(objectType == 'GenericDocument__c') handleGenericDocumentAttachments(null, newAttachmentMap);
        }
   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onAfterDelete()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> oldAttachmentList = (List<Attachment>)tc.oldList;
        Map<ID, Attachment> oldAttachmentMap = (Map<ID, Attachment>)tc.oldMap;
        //This is where you should call your business logic
        
        Map<String, Map<ID, Attachment>> attachmentsByObjectType = determineObjectType(oldAttachmentMap);

        for(String objectType : attachmentsByObjectType.keyset()){
            if(objectType == 'OutboundEmail__c') handleOutbountEmailAttachments(oldAttachmentMap, null);
        }
     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.TriggerContext tc){
system.debug('AttachmentTriggerHandler.onAfterUndelete()');
        //Recast the trigger context variables into the appropriate shandlerect types
        List<Attachment> newAttachmentList = (List<Attachment>)tc.newList;
        Map<ID, Attachment> newAttachmentMap = (Map<ID, Attachment>)tc.newMap;
        //This is where you should call your business logic
        
        Map<String, Map<ID, Attachment>> attachmentsByObjectType = determineObjectType(newAttachmentMap);

        for(String objectType : attachmentsByObjectType.keyset()){
            if(objectType == 'OutboundEmail__c') handleOutbountEmailAttachments(null, newAttachmentMap);
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<Attachment> newAttachmentList){
system.debug('AttachmentTriggerHandler.setDefaultsOnInsert()');
        for(Attachment acct : newAttachmentList){

        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, Attachment> oldAttachmentMap, Map<ID, Attachment> newAttachmentMap){
system.debug('AttachmentTriggerHandler.setDefaultsOnUpdate()'); 
        for(Attachment acct : newAttachmentMap.values()){

        }
    }
    
    /////////////////////////////////////////////////////////////////////////
    //Method: handleStudentProgramAttachments
    /////////////////////////////////////////////////////////////////////////
    private void handleStudentProgramAttachments(Map<ID, Attachment> oldAttachmentMap, Map<ID, Attachment> newAttachmentMap){
        System.debug('AttachmentTriggerHandler.handleStudentProgramAttachments()'); 
        
        //to do - not bulkified
        List<StudentProgram__c> agreementsToUpdate = new List<StudentProgram__c>();
        Set<ID> attachParentIDs = new Set<ID>();
        for(Attachment attach: newAttachmentMap.values()){
            attachParentIDs.add(attach.ParentID);
        }

        Map<ID, StudentProgram__c> agreementMap = new Map<ID, StudentProgram__c>([SELECT id, AdobeSignStatus__c,
                                                                                            CongaUnsignedAgreementID__c, 
                                                                                            SignedAgreementID__c, 
                                                                                            FinalDisclosureID__c
                                                                                    FROM StudentProgram__c
                                                                                    WHERE id = :attachParentIDs limit 1]);
        Map<ID, List<StudentProgram__c>> agreementsByAttachID = new Map<ID, List<StudentProgram__c>>();
        for(Attachment attach : newAttachmentMap.values()){
            if(!agreementsByAttachID.containsKey(attach.id)){
                agreementsByAttachID.put(attach.id, new List<StudentProgram__c>());
            }
            agreementsByAttachID.get(attach.id).add(agreementMap.get(attach.ParentID));
        }
        system.debug(agreementsByAttachID);

        //This currently will only support one attachment per agreement - the algorithm will fail if there are multipel agreements for the same
        //agreement in the same trigger scope
        for(Attachment attach : newAttachmentMap.values()){
            system.debug(attach.Name);

//          String unsignedKey = 'unsigned-agreement-'+String.valueOf(attach.ParentID).subString(0,15)+'.pdf';
            String unsignedKey = AgreementService.unsignedAgreementFileName(attach.ParentID)+'.pdf';
            system.debug(unsignedKey);

//            String signedKey = 'signed-agreement-'+String.valueOf(attach.ParentID).subString(0,15)+'.pdf';
            String signedKey = AgreementService.signedAgreementFileName(attach.ParentID)+'.pdf';
            system.debug(signedKey);           

            //String finalDisKey = 'final-disclosure-'+String.valueOf(attach.ParentID).subString(0,15)+'.pdf';
            String finalDisKey = AgreementService.finalDisclosureFileName(attach.ParentID)+'.pdf';
            system.debug(finalDisKey);             

            if(attach.Name == unsignedKey){
                StudentProgram__c agreement = new StudentProgram__c();
                agreement.id = agreementsByAttachID.get(attach.id)[0].id;
//decoupleasync             agreement.AdobeSignStatus__c = 'Begin Signing Process';
//decoupleasync             agreement.CongaUnsignedAgreementID__c = attach.id;
                agreement.GenerateAgreement__c = false;
                //try asynch
                AgreementService.UpdateAgreementAsync job = new AgreementService.UpdateAgreementAsync();
                job.congaAgreementStatus = 'Generated';
                job.generateAgreement = 'false';
                job.Agreement = agreement;
                system.debug('enqueueJob: UpdateAgreementAsync:'+job);
                system.enqueueJob(job);
                //agreementsToUpdate.add(agreement);
            
            }
            if(attach.Name == signedKey){
                StudentProgram__c agreement = new StudentProgram__c();
                agreement.id = agreementsByAttachID.get(attach.id)[0].id;
                agreement.AdobeSignStatus__c = 'Signed Document Attached';
                agreement.SignedAgreementID__c = attach.id;
                agreement.AgreementSigned__c = true;
                agreement.Status__c = 'Application Complete';
                //try asynch

                AgreementService.UpdateAgreementAsync job = new AgreementService.UpdateAgreementAsync();
                job.Agreement = agreement;
                job.agreementStatus = agreement.Status__c;
                system.debug('enqueueJob: UpdateAgreementAsync'+job);
                system.enqueueJob(job);
                //agreementsToUpdate.add(agreement);
               
            }
            if(attach.Name == finalDisKey){

                StudentProgram__c agreement = new StudentProgram__c();
                agreement.id = agreementsByAttachID.get(attach.id)[0].id;
                agreement.FinalDisclosureID__c = attach.id;
                //agreement.GenerateFinalDisclosure__c = false;
                //agreement.CongaFinalDisclosureStatus__c = 'Generated';
                system.debug(agreement);
                //try asynch
                AgreementService.UpdateAgreementAsync job = new AgreementService.UpdateAgreementAsync();
                job.congaFinalDisclosureStatus = 'Generated';
                job.generateFinalDisclosure = 'false';
                job.Agreement = agreement;
                system.debug('enqueueJob: UpdateAgreementAsync'+job);
                system.enqueueJob(job);
                //agreementsToUpdate.add(agreement);
               
            }
        }
        if(agreementsToUpdate.size()>0){
            //try asynch
            //update agreementsToUpdate;
        }
    }  

    /////////////////////////////////////////////////////////////////////////
    //Method: handleGenericDocumentAttachments
    /////////////////////////////////////////////////////////////////////////
    private void handleGenericDocumentAttachments(Map<ID, Attachment> oldAttachmentMap, Map<ID, Attachment> newAttachmentMap){
        System.debug('AttachmentTriggerHandler.handleGenericDocumentAttachments()'); 
        
        List<GenericDocument__c> documentsToUpdate = new List<GenericDocument__c>();
        Set<ID> attachParentIDs = new Set<ID>();
        for(Attachment attach: newAttachmentMap.values()){
            attachParentIDs.add(attach.ParentID);
        }

        Map<ID, GenericDocument__c> agreementMap = new Map<ID, GenericDocument__c>([SELECT id, AttachmentID__c, AttachmentName__c, Status__c
                                                                                    FROM GenericDocument__c
                                                                                    WHERE id = :attachParentIDs limit 1]);
        Map<ID, List<GenericDocument__c>> docsByAttachID = new Map<ID, List<GenericDocument__c>>();
        for(Attachment attach : newAttachmentMap.values()){
            if(!docsByAttachID.containsKey(attach.id)){
                docsByAttachID.put(attach.id, new List<GenericDocument__c>());
            }
            docsByAttachID.get(attach.id).add(agreementMap.get(attach.ParentID));
        }
        system.debug(docsByAttachID);

        //This currently will only support one attachment per agreement - the algorithm will fail if there are multipel agreements for the same
        //agreement in the same trigger scope
        List<GenericDocument__c> docListToUpdate = new List<GenericDocument__c>();
        for(Attachment attach : newAttachmentMap.values()){
            system.debug(attach);
            GenericDocument__c document = new GenericDocument__c();
            document.AttachmentID__c = ((String)(attach.id)).subString(0,15);
            document.AttachmentName__c = attach.Name;
            document.id = docsByAttachID.get(attach.id)[0].id;
            document.Status__c = 'Uploaded';
            docListToUpdate.add(document);
        }
        if(docListToUpdate.size()>0){
            update docListToUpdate;
        }
    }
    
    private void handleOutbountEmailAttachments(Map<ID, Attachment> oldAttachmentMap, Map<ID, Attachment> newAttachmentMap){
        Set<ID> attachParentIDs = new Set<ID>();
        List<OutboundEmail__c> oEmailtoUpsert = new List<OutboundEmail__c>();
        
        Map<id,List<Attachment>> oEmailIdNAttachmentListMap = new Map<id,List<Attachment>>();
        Map<id,List<Attachment>> oEmailIdNDelAttachmentListMap = new Map<id,List<Attachment>>();
        
        if(newAttachmentMap != null){
            for(Attachment attach: newAttachmentMap.values()){
                
                if(!oEmailIdNAttachmentListMap.containsKey(attach.ParentID)){
                    oEmailIdNAttachmentListMap.put(attach.ParentID, new List<attachment>());
                }
                oEmailIdNAttachmentListMap.get(attach.ParentID).add(attach);     
                attachParentIDs.add(attach.ParentID);
            }
        }
        
        if(oldAttachmentMap != null){
            for(Attachment attach: oldAttachmentMap.values()){
                if(!oEmailIdNDelAttachmentListMap.containsKey(attach.ParentID)){
                    oEmailIdNDelAttachmentListMap.put(attach.ParentID, new List<attachment>());
                }
                oEmailIdNDelAttachmentListMap.get(attach.ParentID).add(attach);     
                attachParentIDs.add(attach.ParentID);
            }
        } 
        
        Integer noOfAtts = 0;
        for(OutboundEmail__c oEmail : [select id,CurrentNumberofAttachments__c  from OutboundEmail__c where id IN: attachParentIDs]){
            noOfAtts = 0;
            if(oEmailIdNAttachmentListMap.containsKey(oEmail.Id)) {
                noOfAtts += oEmailIdNAttachmentListMap.get(oEmail.Id).size();
            }
            if(oEmailIdNDelAttachmentListMap.containsKey(oEmail.Id)) {
                noOfAtts -= oEmailIdNDelAttachmentListMap.get(oEmail.Id).size();
            }
            oEmail.CurrentNumberofAttachments__c = oEmail.CurrentNumberofAttachments__c == null ? noOfAtts : (oEmail.CurrentNumberofAttachments__c + noOfAtts);
            
            oEmailtoUpsert.add(oEmail);
        } 
        
        if(oEmailtoUpsert != null && oEmailtoUpsert.size()>0)
            upsert oEmailtoUpsert;                                                                             
    }
    
    /////////////////////////////////////////////////////////////////////////
    //Method: determineObjectType
    /////////////////////////////////////////////////////////////////////////
    private Map<String, Map<ID, Attachment>> determineObjectType(Map<ID, Attachment> newAttachmentMap){
        Map<String, Map<ID, Attachment>> attachmentByObjectType = new Map<String, Map<ID, Attachment>>();
        for(Attachment attach : newAttachmentMap.values()){
            String objectType = String.valueOf(attach.ParentId.getSobjectType());
            if(!attachmentByObjectType.containsKey(objectType)) {
                attachmentByObjectType.put(objectType, new Map<ID, Attachment>());
            }
            attachmentByObjectType.get(objectType).put(attach.id, attach);
        }
        system.debug('attachmentByObjectType:'+attachmentByObjectType);
        return attachmentByObjectType;
    }
    public class AttachmentTriggerHandlerException extends Exception {}
}