vemo-mdapi-qa/objects/GenericDocument__c.object
<CustomObject>
    <label>Generic Document</label>
    <nameField>
        <displayFormat>GD-{0000000000}</displayFormat>
        <label>Generic Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ParentID__c</fullName>
        <label>ParentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/GenericDocumentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pending Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Uploaded</fullName>
    </customValue>
    <masterLabel>Generic Document Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/GenericDocumentTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: GenericDocumentTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2018-01-02   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class GenericDocumentTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State acctrol Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution acctrol - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.Triggercontext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            
 
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.Triggercontext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'GenericDocumentTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'GenericDocumentTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onBeforeInsert()');
       //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> newGenericDocumentList = (List<GenericDocument__c>)tc.newList;
        //This is where you should call your business logic
        setDefaultsOnInsert(newGenericDocumentList);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onBeforeUpdate()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> newGenericDocumentList = (List<GenericDocument__c>)tc.newList;
        List<GenericDocument__c> oldGenericDocumentList = (List<GenericDocument__c>)tc.oldList;
        Map<ID, GenericDocument__c> newGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.newMap;
        Map<ID, GenericDocument__c> oldGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldGenericDocumentMap, newGenericDocumentMap);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onBeforeDelete()');
       //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> oldGenericDocumentList = (List<GenericDocument__c>)tc.oldList;
        Map<ID, GenericDocument__c> oldGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onAfterInsert()');
         //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> newGenericDocumentList = (List<GenericDocument__c>)tc.newList;
        Map<ID, GenericDocument__c> newGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.newMap;
        //This is where you should call your business logic

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onAfterUpdate()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> newGenericDocumentList = (List<GenericDocument__c>)tc.newList;
        List<GenericDocument__c> oldGenericDocumentList = (List<GenericDocument__c>)tc.oldList;
        Map<ID, GenericDocument__c> newGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.newMap;
        Map<ID, GenericDocument__c> oldGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.oldMap;
        //This is where you should call your business logic

   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onAfterDelete()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> oldGenericDocumentList = (List<GenericDocument__c>)tc.oldList;
        Map<ID, GenericDocument__c> oldGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.Triggercontext tc){
system.debug('GenericDocumentTriggerHandler.onAfterUndelete()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<GenericDocument__c> newGenericDocumentList = (List<GenericDocument__c>)tc.newList;
        Map<ID, GenericDocument__c> newGenericDocumentMap = (Map<ID, GenericDocument__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<GenericDocument__c> newGenericDocumentList){
system.debug('GenericDocumentTriggerHandler.setDefaultsOnInsert()');

        for(GenericDocument__c gd : newGenericDocumentList){
        	gd.Status__c = 'Pending Upload';
            if(String.isNotBlank(gd.ParentID__c)) gd.ParentID__c = gd.ParentID__c.substring(0,15);
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, GenericDocument__c> oldGenericDocumentMap, Map<ID, GenericDocument__c> newGenericDocumentMap){
system.debug('GenericDocumentTriggerHandler.setDefaultsOnUpdate()'); 
        for(GenericDocument__c gd : newGenericDocumentMap.values()){
            if(String.isNotBlank(gd.ParentID__c)) gd.ParentID__c = gd.ParentID__c.substring(0,15);
        }
    }

    public class GenericDocumentTriggerHandlerException extends Exception {}
}