vemo-mdapi-qa/objects/GenericDocument__c.object
<CustomObject>
    <label>Generic Document</label>
    <nameField>
        <displayFormat>GD-{0000000000}</displayFormat>
        <label>Generic Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttachmentCleanURL__c</fullName>
        <formula>IF(!ISBLANK(AttachmentID__c), $Setup.GlobalSettings__c.AttachmentDownloadPrefix__c &amp; AttachmentID__c, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attachment Clean URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <label>AttachmentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentName__c</fullName>
        <label>Attachment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentID__c</fullName>
        <label>ParentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObjectType__c</fullName>
        <label>Parent Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SObjectTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/GenericDocumentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Uploaded</fullName>
    </customValue>
    <masterLabel>Generic Document Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/GenericDocumentType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pay stubs</fullName>
    </customValue>
    <customValue>
        <fullName>Letter from employer</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Other types of verifiable documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Signed 4506T authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Employment contract</fullName>
    </customValue>
    <customValue>
        <fullName>Type1</fullName>
        <isActive>false</isActive>
        <label>Type1</label>
    </customValue>
    <customValue>
        <fullName>Type2</fullName>
        <isActive>false</isActive>
        <label>Type2</label>
    </customValue>
    <masterLabel>Generic Document Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/SObjectTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IncomeVerification__c</fullName>
    </customValue>
    <customValue>
        <fullName>Reconciliation__c</fullName>
    </customValue>
    <masterLabel>SObject Types</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/GenericDocumentService.cls
public with sharing class GenericDocumentService {
	public static List<GenericDocument> getGenericDocumentWithGenericDocumentID(Set<ID> genDocIDs){
		System.debug('GenericDocumentService.getGenericDocumentWithGenericDocumentID');
		Map<Id, GenericDocument__c> genDocObjMap = GenericDocumentQueries.getGenericDocumentMapByID(genDocIDs);
		List<GenericDocument> genDocList = new List<GenericDocument>();
		for(GenericDocument__c genDocObj : genDocObjMap.values()){
			genDocList.add(new GenericDocument(genDocObj));
		}
		return genDocList;
	}

	public static List<GenericDocument> getGenericDocumentWithParentID(Set<String> parentIDs){
		System.debug('GenericDocumentService.getGenericDocumentWithParentID');
		System.debug('greg2:'+parentIDs);
		Map<Id, GenericDocument__c> genDocObjMap = GenericDocumentQueries.getGenericDocumentMapByParentID(parentIDs);
		List<GenericDocument> genDocList = new List<GenericDocument>();
		for(GenericDocument__c genDocObj : genDocObjMap.values()){
			genDocList.add(new GenericDocument(genDocObj));
		}
		return genDocList;
	}

	public static Set<Id> createGenericDocument(List<GenericDocument> genericDocuments){
		System.debug('GenericDocumentService.createGenericDocument');
		List<GenericDocument__c> genDocList = new List<GenericDocument__c>();
		for(GenericDocument genDoc : genericDocuments){
			GenericDocument__c genDocObj = genDocClassToGenDocObject(genDoc);
			genDocList.add(genDocObj);
		}
		insert genDocList;
		Set<Id> genDocIDs = new Set<Id>();
		for(GenericDocument__c genDoc : genDocList){
			genDocIDs.add(genDoc.ID);
		}
		return genDocIDs;
	}
	public static Set<Id> updateGenericDocument(List<GenericDocument> genericDocuments){
		System.debug('GenericDocumentService.updateGenericDocument');
		List<GenericDocument__c> genDocList = new List<GenericDocument__c>();
		for(GenericDocument genDoc : genericDocuments){
			GenericDocument__c genDocObj = genDocClassToGenDocObject(genDoc);
			genDocList.add(genDocObj);
		}
		update genDocList;
		Set<Id> genDocIDs = new Set<Id>();
		for(GenericDocument__c genDoc : genDocList){
			genDocIDs.add(genDoc.ID);
		}
		return genDocIDs;
	}

	public static Integer deleteGenericDocument(Set<ID> genDocIDs){
		System.debug('GenericDocumentService.deleteGenericDocument');
		Map<ID, GenericDocument__c> genDocMap = GenericDocumentQueries.getGenericDocumentMapByID(genDocIDs);
		Integer numToDelete = genDocMap.size();
		delete genDocMap.values();
		return numToDelete;
	}
	public static GenericDocument__c genDocClassToGenDocObject(GenericDocument docClass){
		GenericDocument__c docObj = new GenericDocument__c();
		if(docClass.genericDocumentID != null) docObj.ID = docClass.genericDocumentID;
		if(docClass.type != null) docObj.Type__c = docClass.type;
		if(docClass.status != null) docObj.Status__c = docClass.status;
		if(docClass.parentID != null) docObj.ParentID__c = docClass.parentID;
		if(docClass.parentObjectType != null) docObj.ParentObjectType__c = docClass.parentObjectType;
		if(docClass.comments != null) docObj.Comments__c = docClass.comments;
		return docObj;
	}	

	public class GenericDocument{
		public String genericDocumentID {get;set;}
		public String type {get;set;}
		public String status {get;set;}
		public String attachmentID {get;set;}
		public String attachmentName {get;set;}
		public String attachmentURL {get;set;}
		public String parentID {get;set;}
		public String parentObjectType {get;set;}
		public String comments {get;set;}


		public GenericDocument(){

		}

		public GenericDocument(Boolean testValues){
			if(testValues){
				

			}
		}

		public GenericDocument(GenericDocument__c doc){
			this.genericDocumentID = doc.ID;
			this.type = doc.Type__c;
			this.status = doc.Status__c;
			this.attachmentID = doc.AttachmentID__c;
			this.attachmentName = doc.AttachmentName__c;
			this.attachmentURL = doc.AttachmentCleanURL__c;
			this.parentID = doc.ParentID__c;
			this.parentObjectType = doc.ParentObjectType__c;
			this.comments = doc.Comments__c;
		}
	}
}