vemo-mdapi-qa/objects/GenericDocument__c.object
<CustomObject>
    <label>Generic Document</label>
    <nameField>
        <displayFormat>GD-{0000000000}</displayFormat>
        <label>Generic Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttachmentCleanURL__c</fullName>
        <formula>IF(!ISBLANK(AttachmentID__c), $Setup.GlobalSettings__c.AttachmentDownloadPrefix__c &amp; AttachmentID__c, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attachment Clean URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <label>AttachmentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentID__c</fullName>
        <label>ParentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Reconciliation__c.object
<CustomObject>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>REC-{00000}</displayFormat>
        <label>Reconciliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not started</fullName>
                </value>
                <value>
                    <fullName>Documents submitted</fullName>
                </value>
                <value>
                    <fullName>Follow-up required</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ReconciliationDetail__c.object
<CustomObject>
    <label>ReconciliationDetail</label>
    <nameField>
        <displayFormat>RD-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>ReconciliationDetail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReconciliationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Reconciliation__c</fullName>
        <label>Reconciliation</label>
        <referenceTo>Reconciliation__c</referenceTo>
        <relationshipLabel>ReconciliationDetail</relationshipLabel>
        <relationshipName>ReconciliationDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/GenericDocumentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Uploaded</fullName>
    </customValue>
    <masterLabel>Generic Document Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/GenericDocumentType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pay stubs</fullName>
    </customValue>
    <customValue>
        <fullName>Letter from employer</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Other types of verifiable documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Signed 4506T authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Employment contract</fullName>
    </customValue>
    <customValue>
        <fullName>Type1</fullName>
        <isActive>false</isActive>
        <label>Type1</label>
    </customValue>
    <customValue>
        <fullName>Type2</fullName>
        <isActive>false</isActive>
        <label>Type2</label>
    </customValue>
    <masterLabel>Generic Document Type</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/GenericDocumentViewApexCTRL.cls
public class GenericDocumentViewApexCTRL {
    public static String objectType;

    @AuraEnabled
    public static List<GenericDocument__c> getGenericDocumentList(string recordId){
        System.debug('GenericDocumentViewApexCTRL.getGenericDocuments()');
        System.debug('recordId:'+recordId);
        
        String query = '';
        
        if(Id.valueOf(recordId).getSObjectType().getDescribe().getName() == 'Reconciliation__c'){
            Map<Id, ReconciliationDetail__c> reconciliationDetailMap = ReconciliationQueries.getReconciliationDetailMapWithReconciliationID(new Set<ID>{recordID});
            Set<string> reconciliationDetailIDs = new Set<string>();
            
            for(string rDetailId : reconciliationDetailMap.keyset())
                reconciliationDetailIDs.add(rDetailId.substring(0, 15));    
            //query = 'SELECT id, Type__c, Status__c, AttachmentID__c, AttachmentCleanURL__c from GenericDocument__c where ParentID__c != null and (ParentID__c IN '+DatabaseUtil.inSetStringBuilder(reconciliationDetailIDs) + ' or ParentID__c = \''+recordId.substring(0, 15)+')\'';
              query = 'SELECT id, Type__c, Status__c, AttachmentID__c, AttachmentCleanURL__c from GenericDocument__c where ParentID__c != null and (ParentID__c IN '+DatabaseUtil.inSetStringBuilder(reconciliationDetailIDs) + ' or ParentID__c = \''+recordId.substring(0, 15)+'\')';

        }
        else{
            query = 'SELECT id, Type__c, Status__c, AttachmentID__c, AttachmentCleanURL__c from GenericDocument__c where ParentID__c != null and ParentID__c = \''+recordId.substring(0, 15)+'\'';
        }
        
        Map<ID, GenericDocument__c> docMap = new Map<ID, GenericDocument__c>((List<GenericDocument__c>)Database.query(query));
        System.debug('docMap:'+docMap);
        return docMap.values();
    }
}