vemo-mdapi-qa/objects/GenericDocument__c.object
<CustomObject>
    <label>Generic Document</label>
    <nameField>
        <displayFormat>GD-{0000000000}</displayFormat>
        <label>Generic Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttachmentCleanURL__c</fullName>
        <formula>IF(!ISBLANK(AttachmentID__c), $Setup.GlobalSettings__c.AttachmentDownloadPrefix__c &amp; AttachmentID__c, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attachment Clean URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <label>AttachmentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentName__c</fullName>
        <label>Attachment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentID__c</fullName>
        <label>ParentID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObjectType__c</fullName>
        <label>Parent Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SObjectTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GenericDocumentType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/GenericDocumentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pending Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Uploaded</fullName>
    </customValue>
    <masterLabel>Generic Document Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/GenericDocumentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pay stubs</fullName>
    </customValue>
    <customValue>
        <fullName>Letter from employer</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Other types of verifiable documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Signed 4506T authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Employment contract</fullName>
    </customValue>
    <customValue>
        <fullName>Type1</fullName>
        <isActive>false</isActive>
        <label>Type1</label>
    </customValue>
    <customValue>
        <fullName>Type2</fullName>
        <isActive>false</isActive>
        <label>Type2</label>
    </customValue>
    <masterLabel>Generic Document Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/SObjectTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IncomeVerification__c</fullName>
    </customValue>
    <customValue>
        <fullName>Reconciliation__c</fullName>
    </customValue>
    <masterLabel>SObject Types</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/GenericDocumentQueries.cls
public with sharing class GenericDocumentQueries {
    public static Map<String, Object> filterCriteria = new Map<String, Object>();
    public static void clearFilterCriteria(){
        filterCriteria.clear();
    }

    public static Map<ID, GenericDocument__c> getGenericDocumentMapByID(Set<ID> genericDocumentIDs){
        String query = generateSOQLSelect();
        query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(genericDocumentIDs);
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        Map<ID, GenericDocument__c> retMap = new Map<ID, GenericDocument__c>((List<GenericDocument__c>)db.query(query));


        return retMap;
    }

    public static Map<ID, GenericDocument__c> getGenericDocumentMapByParentID(Set<String> parentIDs){
        String query = generateSOQLSelect();
        query += ' WHERE ParentID__c IN ' + DatabaseUtil.inSetStringBuilder(parentIDs);
        query += buildFilterString();
        query += ' '+ generateLIMITStatement();
        system.debug('***query'+query);
        DatabaseUtil db = new DatabaseUtil();
        Map<ID, GenericDocument__c> retMap = new Map<ID, GenericDocument__c>((List<GenericDocument__c>)db.query(query));


        return retMap;
    }

    private static String generateSOQLSelect(){
        String soql;
		soql = 'SELECT ' + getFieldNames() + ' FROM GenericDocument__c';
        return soql;
    }

    private static String getFieldNames(){
        String fieldNames;
		fieldNames = 'id, ';
        fieldNames += 'Name, ';
        fieldNames += 'Type__c, ';
        fieldNames += 'ParentID__c, ';
        fieldNames += 'ParentObjectType__c, ';
        fieldNames += 'Status__c, ';
        fieldNames += 'AttachmentID__c, ';
        fieldNames += 'AttachmentName__c, ';
        fieldNames += 'Comments__c, ';
        fieldNames += 'AttachmentCleanURL__c ';

        return fieldNames;
    }
    
    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }

    //private static String generateRecordTypeStatement(String recordTypeLabel){
    //    ID recordTypeID = (String)GlobalUtil.getRecordTypeIDByLabelName('Account', recordTypeLabel);
    //    return 'RecordTypeID = \''+ String.valueOf(recordTypeID) + '\'';
    //}

    private static String buildFilterString(){
        String filterStr = '';
        if(filterCriteria.size()>0){
            for(String filter : filterCriteria.keyset()){
                filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) +  '\' ');
            }           
        }
        return filterStr;
    }
}