vemo-mdapi-qa/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>GlobalSettings</label>
    <fields>
        <fullName>AllowTestStudent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is checked, the api will allow login to bypass the decryption process of the VEMO_AUTH param</description>
        <inlineHelpText>If this field is checked, the api will allow login to bypass the decryption process of the VEMO_AUTH param</inlineHelpText>
        <label>Allow testStudent via API</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AttachmentDownloadPrefix__c</fullName>
        <defaultValue>&quot;https://vemo--dev1--c.cs2.content.force.com/servlet/servlet.FileDownload?file=&quot;</defaultValue>
        <label>Attachment Download Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClosedWonCaseQueue__c</fullName>
        <defaultValue>&quot;Origination&quot;</defaultValue>
        <description>This is the name of the queue for which cases will automatically be created when an opportunity goes to closed won</description>
        <inlineHelpText>This is the name of the queue for which cases will automatically be created when an opportunity goes to closed won</inlineHelpText>
        <label>ClosedWonCaseQueue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DebugLevel__c</fullName>
        <defaultValue>&quot;DEBUG&quot;</defaultValue>
        <inlineHelpText>Choose NONE, FINE, DEBUG, or CRITICAL</inlineHelpText>
        <label>Debug Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentDownloadPrefix__c</fullName>
        <defaultValue>&quot;https://vemo--dev2--c.cs44.content.force.com/servlet/servlet.ImageServer?id=&quot;</defaultValue>
        <label>Document Download Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailNotifications__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EmailNotifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OAuthUtilConsumerID__c</fullName>
        <label>OAuthUtilConsumerID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuthUtilConsumerSecret__c</fullName>
        <label>OAuthUtilConsumerSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuthUtilEndpoint__c</fullName>
        <inlineHelpText>&#39;test&#39; or &#39;prod&#39; (without quotes)</inlineHelpText>
        <label>OAuthUtilEndpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuthUtilPassword__c</fullName>
        <inlineHelpText>Include security token if applicable</inlineHelpText>
        <label>OAuthUtilPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuthUtilUserID__c</fullName>
        <label>OAuthUtilUserID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VemoAccountID__c</fullName>
        <label>VemoAccountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkflowRules__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WorkflowRules</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/GlobalSettings.cls
///////////////////////////////////////////////////////////////////////// test2
// Class: GlobalSettings
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-07-13   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class GlobalSettings {
    ////////////////////////////////////////////////////////////////////////
    //Static Block
    /////////////////////////////////////////////////////////////////////////
	static{
		if (Test.isRunningTest()){
            Profile sysAdmin = [SELECT Id from Profile where Name = 'System Administrator'];
			User thisUser = [Select Id
                             FROM User
                             WHERE ProfileId = :sysAdmin.id and isActive = true
                             LIMIT 1];
			System.runAs(thisUser) {
				try{
					createDefaultSettings(); //if a test is running - create the settings so the test classes dont have to
				} catch(DMLException e){
				//probably fine - just means it already exists
				}
				
			}
		}	
	}
    private static GlobalSettings__c globalSettingsObj = GlobalSettings__c.getInstance();
    private static GlobalSettings singletonInstance = null;
    public static GlobalSettings getSettings(){
        if(singletonInstance == null){
            singletonInstance = new GlobalSettings();
        }
        return singletonInstance;
    }
    public Boolean workflowRules {
        get{
            if (workflowRules == null){
                workflowRules = globalSettingsObj.WorkflowRules__c;
            }
            return workflowRules;
        }    
        set;
    }
    public Boolean validationRules {
        get{
            if (validationRules == null){
                validationRules = globalSettingsObj.ValidationRules__c;
            }
            return validationRules;
        }    
        set;
    }
    public String closedWonCaseQueue {
        get{
            if (closedWonCaseQueue == null){
                closedWonCaseQueue = globalSettingsObj.ClosedWonCaseQueue__c;
            }
            return closedWonCaseQueue;
        }    
        set;
    } 
    public Boolean emailNotifications {
        get{
            if (emailNotifications == null){
                emailNotifications = globalSettingsObj.EmailNotifications__c;
            }
            return emailNotifications;
        }    
        set;
    } 
    public String vemoAccountID {
        get{
            if (vemoAccountID == null){
                vemoAccountID = globalSettingsObj.VemoAccountID__c;
            }
            return vemoAccountID;
        }    
        set;
    }     
    public Boolean allowTestStudent {
        get{
            if (allowTestStudent == null){
                allowTestStudent = globalSettingsObj.AllowTestStudent__c;
            }
            return allowTestStudent;
        }    
        set;
    }
    public String oauthUtilUserID {
        get{
            if (oauthUtilUserID == null){
                oauthUtilUserID = globalSettingsObj.OAuthUtilUserID__c;
            }
            return oauthUtilUserID;
        }    
        set;
    }      

    public String oauthUtilPassword {
        get{
            if (oauthUtilPassword == null){
                oauthUtilPassword = globalSettingsObj.OAuthUtilPassword__c;
            }
            return oauthUtilPassword;
        }    
        set;
    }     
    public String oauthUtilConsumerID {
        get{
            if (oauthUtilConsumerID == null){
                oauthUtilConsumerID = globalSettingsObj.OAuthUtilConsumerID__c;
            }
            return oauthUtilConsumerID;
        }    
        set;
    } 
    public String oauthUtilConsumerSecret {
        get{
            if (oauthUtilConsumerSecret == null){
                oauthUtilConsumerSecret = globalSettingsObj.OAuthUtilConsumerSecret__c;
            }
            return oauthUtilConsumerSecret;
        }    
        set;
    }
    public String oauthUtilEndpoint {
        get{
            if (oauthUtilEndpoint == null){
                oauthUtilEndpoint = globalSettingsObj.OAuthUtilEndpoint__c;
            }
            return oauthUtilEndpoint;
        }    
        set;
    }    
    public String debugLevel {
        get{
            if (debugLevel == null){
                debugLevel = globalSettingsObj.DebugLevel__c;
            }
            return debugLevel;
        }    
        set;        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: createDefaultSettings
    /////////////////////////////////////////////////////////////////////////
	public static void createDefaultSettings(){
        if(globalSettingsObj == null){
            globalSettingsObj = new GlobalSettings__c();
        }
        List<GlobalSettings__c> settings = new List<GlobalSettings__c>();
        //Organizational Settings
        settings.add(new GlobalSettings__c(SetupOwnerID = UserInfo.getOrganizationID(),
                                             AllowTestStudent__c = false,
                                             AttachmentDownloadPrefix__c = 'https://vemo--dev1--c.cs2.content.force.com/servlet/servlet.FileDownload?file=',
                                             ClosedWonCaseQueue__c = 'Origination',
                                             DebugLevel__c = 'DEBUG',
                                             DocumentDownloadPrefix__c = 'https://vemo--dev2--c.cs44.content.force.com/servlet/servlet.ImageServer?id=',
                                             EmailNotifications__c = true,
                                             OAuthUtilConsumerID__c = '',
                                             OAuthUtilConsumerSecret__c = '',
                                             OAuthUtilEndpoint__c = '',
                                             OAuthUtilPassword__c = '',
                                             OAuthUtilUserID__c = '',
                                             ValidationRules__c = true,
                                             VemoAccountID__c = '',
                                             WorkflowRules__c = true));
        //User Settings
        settings.add(new GlobalSettings__c(SetupOwnerID = UserInfo.getUserID(),
                                             AllowTestStudent__c = true,
                                             AttachmentDownloadPrefix__c = 'https://vemo--dev1--c.cs2.content.force.com/servlet/servlet.FileDownload?file=',
                                             ClosedWonCaseQueue__c = 'Origination',
                                             DebugLevel__c = 'DEBUG',
                                             DocumentDownloadPrefix__c = 'https://vemo--dev2--c.cs44.content.force.com/servlet/servlet.ImageServer?id=',
                                             EmailNotifications__c = true,
                                             OAuthUtilConsumerID__c = '',
                                             OAuthUtilConsumerSecret__c = '',
                                             OAuthUtilEndpoint__c = '',
                                             OAuthUtilPassword__c = '',
                                             OAuthUtilUserID__c = '',
                                             ValidationRules__c = true,
                                             VemoAccountID__c = '',
                                             WorkflowRules__c = true));    


        Database.insert(settings, true);           
	}
    public class GlobalSettingsException extends Exception {}
}