vemo-mdapi-qa/objects/IncomeBand__c.object
<CustomObject>
    <label>Income Band</label>
    <nameField>
        <displayFormat>IB-{0000000}</displayFormat>
        <label>Income Band Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/IncomeBandQueries_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: IncomeBandQueries_TEST
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-04-25   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public with sharing class IncomeBandQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
	@isTest public static void validateGetIncomeBandMap() {
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
    	Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(TestUtil.TEST_THROTTLE);
    	Map<ID, SchoolProgramsOfStudy__c> testSPOSMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schools, posMap);
    	Map<ID, IncomeBand__c> testBands = TestDataFactory.createAndInsertIncomeBands(2, testSPOSMap);
		Test.startTest();
		Map<Id, IncomeBand__c> resultIncomeBandMap = IncomeBandQueries.getIncomeBandMap();
		System.assertEquals(testBands.keySet().size(), resultIncomeBandMap.keySet().size());
		Test.stopTest();
	}

}