vemo-mdapi-qa/objects/IncomeBand__c.object
<CustomObject>
    <label>Income Band</label>
    <nameField>
        <displayFormat>IB-{0000000}</displayFormat>
        <label>Income Band Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EarningsGroup__c</fullName>
        <label>Earnings Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EarningsGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Income Bands</relationshipLabel>
        <relationshipName>Income_Bands</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <formula>CIPTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <formula>if ( ISBLANK( Name ),  ProgramOfStudy__r.Description__c,  Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>School_Programs_of_Study</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/EarningsGroup.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Earnings Group</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/IncomeBandQueries.cls
public with sharing class IncomeBandQueries {

	public static Map<String, Object> filterCriteria = new Map<String, Object>();
	public static void clearFilterCriteria(){
		filterCriteria.clear();
	}

	public static Map<ID, IncomeBand__c> getIncomeBandMap(){
		Map<ID, IncomeBand__c> peMap = new Map<ID, IncomeBand__c>();
		String query = generateSOQLSelect();
		query += ' WHERE EarningsGroup__c != null';
		if(DatabaseUtil.filterBySchoolID){
			ID schoolID = DatabaseUtil.schoolID;
			query += ' AND SchoolProgramOfStudy__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		peMap = new Map<ID, IncomeBand__c>((List<IncomeBand__c>)db.query(query));
		return peMap;		
	}

	public static Map<ID, IncomeBand__c> getIncomeBandMapWithSchoolProgramOfStudyIDs(Set<ID> schoolProgramOfStudyIDs){
		Map<ID, IncomeBand__c> peMap = new Map<ID, IncomeBand__c>();
		String query = generateSOQLSelect();
		query += ' WHERE SchoolProgramOfStudy__c IN ' + DatabaseUtil.inSetStringBuilder(schoolProgramOfStudyIDs);

		if(DatabaseUtil.filterBySchoolID){
			ID schoolID = DatabaseUtil.schoolID;
			query += ' AND SchoolProgramOfStudy__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		peMap = new Map<ID, IncomeBand__c>((List<IncomeBand__c>)db.query(query));
		return peMap;		
	}

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getFieldNames() + ' FROM IncomeBand__c';
		return soql;
	}

	private static String getFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Name, ';
		fieldNames += 'EarningsGroup__c, ';
		fieldNames += 'SchoolProgramOfStudy__c, ';
		fieldNames += 'SchoolProgramOfStudy__r.Description__c, ';
		fieldNames += 'SchoolProgramOfStudy__r.ProgramOfStudy__c, ';
		fieldNames += 'SchoolProgramOfStudy__r.School__c ';

		return fieldNames;
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}

	private static String buildFilterString(){
		String filterStr = '';
		if(filterCriteria.size()>0){
			for(String filter : filterCriteria.keyset()){
				filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) + 	'\' ');
			}			
		}
		return filterStr;
	}
}