vemo-mdapi-qa/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Critical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Critical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateTimeLogged__c</fullName>
        <label>DateTime Logged</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MillisecondsLogged__c</fullName>
        <label>Milliseconds Logged</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RelatedTo__c</fullName>
        <label>RelatedTo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SecondsLogged__c</fullName>
        <label>Seconds Logged</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/LogService.cls
public with sharing class LogService {
	private static List<Log__c> logs = new List<Log__c>();
	public static void fine(String str, String relatedTo){
		logs.add(new Log__c(Log__c = str.left(2000),
							SecondsLogged__c = DateTime.now().second(),
							RelatedTo__c = relatedTo,			
							DateTimeLogged__c = DateTime.now(),
							MillisecondsLogged__c = DateTime.now().millisecond()));
	}	
	public static void debug(String str, String relatedTo){
		logs.add(new Log__c(Log__c = str.left(2000),
							SecondsLogged__c = DateTime.now().second(),
							RelatedTo__c = relatedTo,			
							DateTimeLogged__c = DateTime.now(),
							MillisecondsLogged__c = DateTime.now().millisecond()));
	}
	public static void critical(String str, String relatedTo){
		logs.add(new Log__c(Log__c = str.left(2000),
							RelatedTo__c = relatedTo,
							DateTimeLogged__c = DateTime.now(),
							SecondsLogged__c = DateTime.now().second(),
							MillisecondsLogged__c = DateTime.now().millisecond(),
							Critical__c = true));
	}
	public static void writeLogs(){
		if(logs.size()>0){
			if(GlobalSettings.getSettings().debugLevel != 'NONE' && String.isNotEmpty(GlobalSettings.getSettings().debugLevel)){
				insert logs;				
			}
			logs.clear();
		}
	}
	public static void purgeLogs(){
		delete [select id from Log__c];
	}
}