vemo-mdapi-qa/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Notification__c.object
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Notifications Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HtmlBody__c</fullName>
        <label>Html Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PlainText__c</fullName>
        <label>Plain Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToEmail__c</fullName>
        <label>To Email</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/ApexEmailServicesHandler.cls
global class ApexEmailServicesHandler implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        System.debug('ApexEmailServicesHandler.handleInboundEmail()');
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();

        String myErr;
//        List<Log__c> logs = new List<Log__c>();*/
        Set<String> toAddressesSet = new Set<String>();
        toAddressesSet.addAll(email.toAddresses);

        try{
        	
        	ApexEmailServicesHandler.captureNotification(email, envelope, toAddressesSet);
			//throw new ApexEmailServicesHandlerException('Inbound Email Had No Associated Service');                

        } catch (Exception e){
            if (email.plainTextBody != null){
                myErr = 'plainTextBody=' + email.plainTextBody;
            } else {
                myErr = 'htmlBody=' + email.htmlBody;
            }            
//            logs.add(new Log__c(Message__c=e.getTypeName() + '\n' + e.getCause() + '\n' + e.getMessage() + '\n\nmyErr=' + myErr));
//            insert logs;
            
            result.success = false;         
            result.message = e.getTypeName() + '\n' + e.getCause() + '\n' + e.getMessage() + '\n\nmyErr=' + myErr + '\n\nemail=' + String.valueOf(email);
            return result;
        }
        return result;
    }

    private static void captureNotification(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope, Set<String>toAddressesSet){
    	Notification__c notice = new Notification__c();
    	Contact cont = new Contact();

    	AccountQueries.clearFilterCriteria();
    	System.debug('toAddressesSet:'+toAddressesSet);
    	Map<ID, Account> acctMap = AccountQueries.getStudentMapWithPersonEmails(toAddressesSet);
    	System.debug('acctMap:'+acctMap);



    	if(acctMap.size()==1){
    		notice.Contact__c = acctMap.values()[0].PersonContactID;    		

    		Task newTask = new Task();
    		newTask.ActivityDate = Date.today();
    		newTask.Subject = 'Email Sent: '+ email.subject;
    		newTask.Status = 'Completed';
    		newTask.WhoId = acctMap.values()[0].PersonContactID;
    		newTask.WhatID = acctMap.values()[0].id;
    		newTask.Description = email.plainTextBody;
    		insert newTask;
    	}

    	notice.ToEmail__c = String.valueOf(toAddressesSet);
    	notice.HTMLBody__c = email.htmlBody;
    	notice.PlainText__c = email.plainTextBody;
    	notice.Subject__c = email.subject;

    	insert notice;



    }
    public class ApexEmailServicesHandlerException extends Exception {}
}