vemo-mdapi-qa/objects/Notification__c.object
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Notifications Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HtmlBody__c</fullName>
        <label>Html Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PlainText__c</fullName>
        <label>Plain Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToEmail__c</fullName>
        <label>To Email</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/NotificationService.cls
/////////////////////////////////////////////////////////////////////////
// Class: NotificationService
// 
// Description: 
// 	Handles all Notification DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-17   Jared Hagemann  Created              
/////////////////////////////////////////////////////////////////////////
public with sharing class NotificationService {
	
	public static List<Notification> getNotificationWithNotificationID(Set<ID> notificationIDs){
		System.debug('NotificationService.getNotificationWithNotificationID');
		Map<Id, Notification__c> notiMap = NotificationQueries.getNotificationByID(notificationIDs);
		List<Notification> notiList = new List<Notification>();
		for(Notification__c noti : notiMap.values()){
			notiList.add(new Notification(noti));
		}
		return notiList;
	}

	public static List<Notification> getNotificationWithStudentID(Set<ID> studentIDs){
		System.debug('NotificationService.getNotificationWithNotificationID');
		Map<Id, Notification__c> notiMap = NotificationQueries.getNotificationByStudentID(studentIDs);
		List<Notification> notiList = new List<Notification>();
		for(Notification__c noti : notiMap.values()){
			notiList.add(new Notification(noti));
		}
		return notiList;
	}
	

	public class Notification{
		public String notificationID {get;set;}
		public String contact {get;set;}
		public String htmlBody {get;set;}
		public String plainText {get;set;}
		public String subject {get;set;}
		public String toEmail {get;set;}

		public Notification(){

		}

		public Notification(Boolean testValues){
			if(testValues){
				this.htmlBody = 'Test htmlBody'; 
				this.plainText = 'Test Plain Text'; 
				this.subject = 'Test Subject'; 
			}
		}

		public Notification(Notification__c noti){
			this.notificationID = noti.ID;
			this.contact = noti.Contact__c;	
			this.htmlBody = noti.HtmlBody__c;		
			this.plainText = noti.PlainText__c;
			this.subject = noti.Subject__c;
			this.toEmail = noti.ToEmail__c;
		}
	}
}