vemo-mdapi-qa/objects/Notification__c.object
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Notifications Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HtmlBody__c</fullName>
        <label>Html Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PlainText__c</fullName>
        <label>Plain Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToEmail__c</fullName>
        <label>To Email</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/NotificationNActivityViewCls.cls
public without sharing class NotificationNActivityViewCls{
    
    public notification__c notification{get;set;}
    public activityHistory activity{get;set;}

    public NotificationNActivityViewCls(){
        Id id = apexpages.currentpage().getparameters().get('id');
        Id accountd = apexpages.currentpage().getparameters().get('accId');
        string objectName = apexpages.currentpage().getparameters().get('record');
        
        if(objectName == 'Notification'){
            notification = [select id,name,createddate,lastmodifiedDate,createdBy.name,lastModifiedBy.name,
                            owner.name,Contact__c,contact__r.name,HtmlBody__c,PlainText__c,Subject__c,ToEmail__c 
                            from notification__c where Id =: id];    
        }
        else if(objectName == 'Activity'){
            List<account> accList = [select (select id,calltype,subject,activityDate,owner.name,what.name,who.name,
                                             description,priority,status,lastModifiedDate,createddate from activityHistories  
                                             where id =: id) 
                                     from account where id=: accountd];
            if(accList != null && accList.size()>0 && accList[0].activityHistories !=null && accList[0].activityHistories.size()>0)
                activity = accList[0].activityHistories;
            //system.debug(accList);
        }
    }
}