vemo-mdapi-qa/objects/Notification__c.object
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Notifications Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HtmlBody__c</fullName>
        <label>Html Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PlainText__c</fullName>
        <label>Plain Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToEmail__c</fullName>
        <label>To Email</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/NotificationQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: NotificationQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-17   Jared Hagemann  Created 
/////////////////////////////////////////////////////////////////////////
public class NotificationQueries {
    public static Map<String, Object> filterCriteria = new Map<String, Object>();
    public static void clearFilterCriteria(){
        filterCriteria.clear();
    }

    public static Map<ID, Notification__c> getNotificationMap(){
        Map<ID, Notification__c> notificationMap = new Map<ID, Notification__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Id != null';
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        notificationMap = new Map<ID, Notification__c>((List<Notification__c>)db.query(query));
        return notificationMap;     
    }

    public static Map<ID, Notification__c> getNotificationByID(Set<Id> notificationIds){
        Map<ID, Notification__c> notificationMap = new Map<ID, Notification__c>();
        String query = generateSOQLSelect();
        query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(notificationIds);
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        notificationMap = new Map<ID, Notification__c>((List<Notification__c>)db.query(query));
        return notificationMap;     
    }

    public static Map<ID, Notification__c> getNotificationByStudentID(Set<Id> studentIds){
        Map<Id, Account> studentMap = AccountQueries.getStudentMapWithStudentID(studentIds);
        Set<Id> contactIds = new Set<Id>();
        for(Account stud : studentMap.values()){
            contactIds.add(stud.PersonContactID);
        }   
        Map<ID, Notification__c> notificationMap = new Map<ID, Notification__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Contact__c IN ' + DatabaseUtil.inSetStringBuilder(contactIds);
        query += buildFilterString();       
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        notificationMap = new Map<ID, Notification__c>((List<Notification__c>)db.query(query));
        return notificationMap;     
    }

    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }
    
    private static String buildFilterString(){
        String filterStr = '';
        if(filterCriteria.size()>0){
            for(String filter : filterCriteria.keyset()){
                filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) +  '\' ');
            }           
        }
        return filterStr;
    }

    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getNotificationFieldNames() + ' FROM Notification__c ';
        return soql;
    }

    private static String getNotificationFieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'Name, ';
        fieldNames += 'Contact__c, ';
        fieldNames += 'HtmlBody__c , ';
        fieldNames += 'PlainText__c, ';
        fieldNames += 'Subject__c, ';
        fieldNames += 'ToEmail__c, ';
        fieldNames += 'Contact__r.account.name, ';
        fieldNames += 'createdDate';
        return fieldNames;
    }
}