vemo-mdapi-qa/objects/OutboundEmail__c.object
<CustomObject>
    <label>Outbound Email</label>
    <nameField>
        <displayFormat>Email-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Outbound Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>PlainTextBody__c</fullName>
        <description>Optional. The text version of the email, specified by the sender. You must specify a value for setTemplateId, setHtmlBody, or setPlainTextBody. Or, you can define both setHtmlBody and setPlainTextBody.</description>
        <inlineHelpText>Optional. The text version of the email, specified by the sender. You must specify a value for setTemplateId, setHtmlBody, or setPlainTextBody. Or, you can define both setHtmlBody and setPlainTextBody.</inlineHelpText>
        <label>PlainTextBody</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SendviaSES__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send via SES</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Optional. The email subject line. If you are using an email template, the subject line of the template overrides this value.</description>
        <inlineHelpText>Optional. The email subject line. If you are using an email template, the subject line of the template overrides this value.</inlineHelpText>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <description>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</description>
        <inlineHelpText>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</inlineHelpText>
        <label>ToAddresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/OutboundEmailBatch_TEST.cls
@isTest
public class OutboundEmailBatch_TEST {
  @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testStart(){
      
      OutboundEmail__c oEmail = new OutboundEmail__c();
      oEmail.SendviaSES__c = true;
      oEmail.ToAddresses__c = 'test@testing.com';
      oEmail.PlainTextBody__c = 'test';
      oEmail.subject__c = 'subTest';
      insert oEmail;
      
      Test.startTest();
      OutboundEmailBatch oeb = new OutboundEmailBatch();
      Database.executeBatch(oeb, 200);
      Test.stopTest();
    }
}