vemo-mdapi-qa/objects/OutboundEmail__c.object
<CustomObject>
    <label>Outbound Email</label>
    <nameField>
        <displayFormat>Email-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Outbound Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SendviaSES__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send via SES</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TemplateID__c</fullName>
        <description>Required if using a template, optional otherwise. The ID of the template used to create the email.</description>
        <inlineHelpText>Required if using a template, optional otherwise. The ID of the template used to create the email.</inlineHelpText>
        <label>TemplateID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <description>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</description>
        <inlineHelpText>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</inlineHelpText>
        <label>ToAddresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WhatID__c</fullName>
        <description>If you specify a contact for the targetObjectId field, you can specify an optional whatId as well. This helps to further ensure that merge fields in the template contain the correct data.</description>
        <inlineHelpText>If you specify a contact for the targetObjectId field, you can specify an optional whatId as well. This helps to further ensure that merge fields in the template contain the correct data.</inlineHelpText>
        <label>WhatID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Reconciliation__c.object
<CustomObject>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>REC-{00000}</displayFormat>
        <label>Reconciliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AdobeSignStatus__c</fullName>
        <description>The status of the AdobeSign process.</description>
        <inlineHelpText>The status of the AdobeSign process.</inlineHelpText>
        <label>Adobe Sign Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Begin Signing Process</fullName>
                </value>
                <value>
                    <fullName>Document Uploaded to Adobe</fullName>
                </value>
                <value>
                    <fullName>Document Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Signing Widget Created</fullName>
                </value>
                <value>
                    <fullName>Document Signed</fullName>
                </value>
                <value>
                    <fullName>Signed Document Attached</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AgreementSigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When the associated Adobe Sign Agreement is SIgned, this box should be checked</description>
        <label>Agreement Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Student__r.PersonContact.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendKickOffEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Kick-Off Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendSubmissionConfirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Submission Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not started</fullName>
                </value>
                <value>
                    <fullName>Documents submitted</fullName>
                </value>
                <value>
                    <fullName>Follow-up required</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/ReconciliationBatch.cls
public with sharing class ReconciliationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
	public enum JobType {CREATE_AGREEMENTS, CREATE_ESIGN, RETRIEVE_SIGNED_AGREEMENTS, SEND_KICK_OFF, SEND_CONFIRMATION} 
	
	public String query {get;set;}
	public JobType job {get;set;}
	
	public ReconciliationBatch() {
		job = JobType.CREATE_AGREEMENTS;
	}
	public ReconciliationBatch(String query) {
		this.query = query;
		job = JobType.CREATE_AGREEMENTS;
	}	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('ReconciliationBatch.start()');
		if(job == JobType.CREATE_AGREEMENTS){
			if(String.isEmpty(this.query)){
				query = 'SELECT id from Reconciliation__c WHERE Status__c =  \'Eligible\' and AdobeSignStatus__c = \'None\'';
			}
		} else if (job == JobType.CREATE_ESIGN){
			if(String.isEmpty(this.query)){
				query = 'SELECT id from Reconciliation__c WHERE Status__c =  \'Eligible\' and AdobeSignStatus__c = \'Document Uploaded to Adobe\'';
			}
		} else if (job == JobType.RETRIEVE_SIGNED_AGREEMENTS){
			if(String.isEmpty(this.query)){
				query = 'SELECT id from Reconciliation__c WHERE AgreementSigned__c = true and AdobeSignStatus__c = \'Document Awaiting Signature\'';
			}
		} else if (job == JobType.SEND_KICK_OFF){
			if(String.isEmpty(this.query)){
				query = 'SELECT id from Reconciliation__c WHERE SendKickOffEmail__c = false and AdobeSignStatus__c = \'Document Awaiting Signature\'';
			}
		} else if (job == JobType.SEND_CONFIRMATION){
			if(String.isEmpty(this.query)){
				query = 'SELECT id from Reconciliation__c WHERE SendSubmissionConfirmation__c = false and Status__c = \'Documents Submitted\'';
			}
		}
		System.debug('job:'+job);
		System.debug('query:'+query);
		LogService.writeLogs();
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.debug('ReconciliationBatch.execute()');
		Set<ID> scopeIDs = new Set<ID>();
		for(sObject sobj : scope){
			scopeIDs.add(sobj.id);
		}

        Map<ID, Reconciliation__c> reconMap = new Map<ID, Reconciliation__c>([SELECT id, Email__c, Status__c
                                                                              FROM Reconciliation__c
                                                                              where id = :scopeIDs]);
        
        List<Reconciliation__c> reconsToUpdate = new List<Reconciliation__c>();
		List<OutboundEmail__c> emailsToSend = new List<OutboundEmail__c>();
		if(job == JobType.CREATE_AGREEMENTS){
            for(Reconciliation__c recon : reconMap.values()){
                try{
                    ReconciliationService.generateESignDocument(recon.id);                    
                } catch (Exception e){

                }                
            }
        } else if(job == JobType.CREATE_ESIGN){  
            for(Reconciliation__c recon : reconMap.values()){
                try{
                    ReconciliationService.getEsignUrl(recon.id);         
                } catch (Exception e){

                }                
            }
        } else if(job == JobType.RETRIEVE_SIGNED_AGREEMENTS){  
            for(Reconciliation__c recon : reconMap.values()){
                try{
                    ReconciliationService.getSignedDocument(recon.id);
                    reconsToUpdate.add(new Reconciliation__c (id = recon.id,
                                                              AdobeSignStatus__c = 'Signed Document Attached'));
                } catch (Exception e){

                }                
            }
        } else if(job == JobType.SEND_KICK_OFF){
			EmailTemplate template = [select Id from EmailTemplate where DeveloperName = 'Recon_Kick_Off' limit 1];
            for(Reconciliation__c recon : reconMap.values()){
                try{
					emailsToSend.add(new OutboundEmail__c(WhatID__c = recon.id,
														  TemplateID__c = template.id,
														  SendviaSES__c = true,
														  ToAddresses__c = recon.Email__c));
                    reconsToUpdate.add(new Reconciliation__c(id = recon.id,
															 Status__c = 'Not Started',
															 SendKickOffEmail__c = true));
                } catch (Exception e){

                }                
            }
        } else if(job == JobType.SEND_CONFIRMATION){
			EmailTemplate template = [select Id from EmailTemplate where DeveloperName = 'Recon_Submission_Confirmation'];			
            for(Reconciliation__c recon : reconMap.values()){
                try{
					emailsToSend.add(new OutboundEmail__c(WhatID__c = recon.id,
														  TemplateID__c = template.id,
														  SendviaSES__c = true,
														  ToAddresses__c = recon.Email__c));
                    reconsToUpdate.add(new Reconciliation__c(id = recon.id,
															 SendSubmissionConfirmation__c = true));
                } catch (Exception e){

                }                
            }
        }   
        if(emailsToSend.size()>0){
            insert emailsToSend;
        }
        if(reconsToUpdate.size()>0){
            update reconsToUpdate;
        }
		
		LogService.writeLogs();	
	}
	
	public void finish(Database.BatchableContext BC) {
		System.debug('ReconciliationBatch.finish()');
		if(job == JobType.CREATE_AGREEMENTS){  
            ReconciliationBatch job = new ReconciliationBatch();
            job.Job = ReconciliationBatch.JobType.CREATE_ESIGN;
            Database.executeBatch(job, 1);
        } else if(job == JobType.CREATE_ESIGN){  
            ReconciliationBatch job = new ReconciliationBatch();
            job.Job = ReconciliationBatch.JobType.RETRIEVE_SIGNED_AGREEMENTS;
            Database.executeBatch(job, 1);
        } else if(job == JobType.RETRIEVE_SIGNED_AGREEMENTS){  
            ReconciliationBatch job = new ReconciliationBatch();
            job.Job = ReconciliationBatch.JobType.SEND_KICK_OFF;
            Database.executeBatch(job, 200);
        } else if(job == JobType.SEND_KICK_OFF){  
            ReconciliationBatch job = new ReconciliationBatch();
            job.Job = ReconciliationBatch.JobType.SEND_CONFIRMATION;
            Database.executeBatch(job, 200);
        } else if(job == JobType.SEND_CONFIRMATION){  
			OutboundEmailBatch job = new OutboundEmailBatch();
			Database.executeBatch(job, 1);
        }         
		LogService.writeLogs();
	}


	public class StudentAccountBatchException extends Exception {}
}