vemo-mdapi-qa/objects/OutboundEmail__c.object
<CustomObject>
    <label>Outbound Email</label>
    <nameField>
        <displayFormat>Email-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Outbound Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>BccAddresses__c</fullName>
        <description>Optional. A list of blind carbon copy (BCC) addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum allowed is 25.</description>
        <inlineHelpText>Optional. A list of blind carbon copy (BCC) addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum allowed is 25.</inlineHelpText>
        <label>BccAddresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CcAddresses__c</fullName>
        <description>Optional. A list of carbon copy (CC) addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum allowed is 25.</description>
        <inlineHelpText>Optional. A list of carbon copy (CC) addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum allowed is 25.</inlineHelpText>
        <label>CcAddresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Charset__c</fullName>
        <description>Optional. The character set for the email. If this value is null, the user&#39;s default value is used.</description>
        <inlineHelpText>Optional. The character set for the email. If this value is null, the user&#39;s default value is used.</inlineHelpText>
        <label>Charset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentNumberofAttachments__c</fullName>
        <label>Current Number of Attachments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EntityAttachmentIDs__c</fullName>
        <description>Optional. Array of IDs of Document, ContentVersion, or Attachment items to attach to the email.</description>
        <inlineHelpText>Optional. Array of IDs of Document, ContentVersion, or Attachment items to attach to the email.</inlineHelpText>
        <label>EntityAttachmentIDs</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExpectedNumberofAttachements__c</fullName>
        <label>Expected Number of Attachements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FileAttachments__c</fullName>
        <description>Optional. A list containing the file names of the binary and text files you want to attach to the email.</description>
        <inlineHelpText>Optional. A list containing the file names of the binary and text files you want to attach to the email.</inlineHelpText>
        <label>FileAttachments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HtmlBody__c</fullName>
        <description>Optional. The HTML version of the email, specified by the sender. The value is encoded according to the specification associated with the organization. You must specify a value for setTemplateId, setHtmlBody, or setPlainTextBody. Or, you can define both setHtmlBody and setPlainTextBody.</description>
        <inlineHelpText>Optional. The HTML version of the email, specified by the sender. The value is encoded according to the specification associated with the organization. You must specify a value for setTemplateId, setHtmlBody, or setPlainTextBody. Or, you can define both</inlineHelpText>
        <label>HtmlBody</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>InReplyToParentMessageIDs__c</fullName>
        <description>Sets the optional In-Reply-To field of the outgoing email. This field identifies the email or emails to which this email is a reply (parent emails).</description>
        <inlineHelpText>Sets the optional In-Reply-To field of the outgoing email. This field identifies the email or emails to which this email is a reply (parent emails).</inlineHelpText>
        <label>InReplyToParentMessageIDs</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OptOutPolicy__c</fullName>
        <description>Optional. If you added recipients by ID instead of email address and the Email Opt Out option is set, this method determines the behavior of the sendEmail() call. If you add recipients by their email addresses, the opt-out settings for those recipients aren’t checked and those recipients always receive the email.</description>
        <inlineHelpText>Optional. If you added recipients by ID instead of email address and the Email Opt Out option is set, this method determines the behavior of the sendEmail() call.</inlineHelpText>
        <label>OptOutPolicy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SEND</fullName>
                    <default>true</default>
                    <label>SEND</label>
                </value>
                <value>
                    <fullName>FILTER</fullName>
                </value>
                <value>
                    <fullName>REJECT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrgWideEmailAddressId__c</fullName>
        <description>Optional. The ID of the organization-wide email address associated with the outgoing email. The object&#39;s DisplayName field cannot be set if the setSenderDisplayName field is already set.</description>
        <inlineHelpText>Optional. The ID of the organization-wide email address associated with the outgoing email. The object&#39;s DisplayName field cannot be set if the setSenderDisplayName field is already set.</inlineHelpText>
        <label>OrgWideEmailAddressId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlainTextBody__c</fullName>
        <description>Optional. The text version of the email, specified by the sender. You must specify a value for setTemplateId, setHtmlBody, or setPlainTextBody. Or, you can define both setHtmlBody and setPlainTextBody.</description>
        <inlineHelpText>Optional. The text version of the email, specified by the sender. You must specify a value for setTemplateId, setHtmlBody, or setPlainTextBody. Or, you can define both setHtmlBody and setPlainTextBody.</inlineHelpText>
        <label>PlainTextBody</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>References__c</fullName>
        <description>Optional. The References field of the outgoing email. Identifies an email thread. Contains the parent emails&#39; References and message IDs, and possibly the In-Reply-To fields.</description>
        <inlineHelpText>Optional. The References field of the outgoing email. Identifies an email thread. Contains the parent emails&#39; References and message IDs, and possibly the In-Reply-To fields.</inlineHelpText>
        <label>References</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendFromOrgWideEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked, the system will automatically send the message from the Org Wide Default Email address</description>
        <inlineHelpText>If this field is checked, the system will automatically send the message from the Org Wide Default Email address</inlineHelpText>
        <label>Send From Org Wide Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendviaSES__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send via SES</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendWhenAttachmentsExist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send When Attachments Exist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Optional. The email subject line. If you are using an email template, the subject line of the template overrides this value.</description>
        <inlineHelpText>Optional. The email subject line. If you are using an email template, the subject line of the template overrides this value.</inlineHelpText>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetObjectId__c</fullName>
        <description>Required if using a template, optional otherwise. The ID of the contact, lead, or user to which the email will be sent. The ID you specify sets the context and ensures that merge fields in the template contain the correct data.</description>
        <inlineHelpText>Required if using a template, optional otherwise. The ID of the contact, lead, or user to which the email will be sent. The ID you specify sets the context and ensures that merge fields in the template contain the correct data.</inlineHelpText>
        <label>TargetObjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TemplateID__c</fullName>
        <description>Required if using a template, optional otherwise. The ID of the template used to create the email.</description>
        <inlineHelpText>Required if using a template, optional otherwise. The ID of the template used to create the email.</inlineHelpText>
        <label>TemplateID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToAddresses__c</fullName>
        <description>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</description>
        <inlineHelpText>Optional. A list of email addresses or object IDs of the contacts, leads, and users you’re sending the email to. The maximum number of email addresses allowed is 100.</inlineHelpText>
        <label>ToAddresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TreatBodiesAsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Optional. If set to true, the subject, plain text, and HTML text bodies of the email are treated as template data.</description>
        <inlineHelpText>Optional. If set to true, the subject, plain text, and HTML text bodies of the email are treated as template data.</inlineHelpText>
        <label>TreatBodiesAsTemplate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TreatTargetObjectAsRecipient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Optional. If set to true, the targetObjectId (a contact, lead, or user) is the recipient of the email. If set to false, the targetObjectId is supplied as the WhoId field for template rendering but isn’t a recipient of the email. The default is true.</description>
        <inlineHelpText>Optional. If set to true, the targetObjectId (a contact, lead, or user) is the recipient of the email. If set to false, the targetObjectId is supplied as the WhoId field for template rendering but isn’t a recipient of the email. The default is true.</inlineHelpText>
        <label>TreatTargetObjectAsRecipient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WhatID__c</fullName>
        <description>If you specify a contact for the targetObjectId field, you can specify an optional whatId as well. This helps to further ensure that merge fields in the template contain the correct data.</description>
        <inlineHelpText>If you specify a contact for the targetObjectId field, you can specify an optional whatId as well. This helps to further ensure that merge fields in the template contain the correct data.</inlineHelpText>
        <label>WhatID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/OutboundEmailTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: OutboundEmailTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-07-06   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class OutboundEmailTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State acctrol Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution acctrol - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.Triggercontext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            
 
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.Triggercontext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'OutboundEmailTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'OutboundEmailTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onBeforeInsert()');
       //Recast the trigger acctext variables into the appropriate shandlerect types
        List<OutboundEmail__c> newOutboundEmailList = (List<OutboundEmail__c>)tc.newList;
        //This is where you should call your business logic
        setDefaultsOnInsert(newOutboundEmailList);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onBeforeUpdate()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<OutboundEmail__c> newOutboundEmailList = (List<OutboundEmail__c>)tc.newList;
        List<OutboundEmail__c> oldOutboundEmailList = (List<OutboundEmail__c>)tc.oldList;
        Map<ID, OutboundEmail__c> newOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.newMap;
        Map<ID, OutboundEmail__c> oldOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldOutboundEmailMap, newOutboundEmailMap);


    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onBeforeDelete()');
       //Recast the trigger acctext variables into the appropriate shandlerect types
        List<OutboundEmail__c> oldOutboundEmailList = (List<OutboundEmail__c>)tc.oldList;
        Map<ID, OutboundEmail__c> oldOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onAfterInsert()');
         //Recast the trigger acctext variables into the appropriate shandlerect types
        List<OutboundEmail__c> newOutboundEmailList = (List<OutboundEmail__c>)tc.newList;
        Map<ID, OutboundEmail__c> newOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.newMap;
        //This is where you should call your business logic
        manageSendEmail(null, newOutboundEmailMap);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onAfterUpdate()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<OutboundEmail__c> newOutboundEmailList = (List<OutboundEmail__c>)tc.newList;
        List<OutboundEmail__c> oldOutboundEmailList = (List<OutboundEmail__c>)tc.oldList;
        Map<ID, OutboundEmail__c> newOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.newMap;
        Map<ID, OutboundEmail__c> oldOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.oldMap;
        //This is where you should call your business logic
        manageSendEmail(oldOutboundEmailMap, newOutboundEmailMap);

   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onAfterDelete()');

        List<OutboundEmail__c> oldOutboundEmailList = (List<OutboundEmail__c>)tc.oldList;
        Map<ID, OutboundEmail__c> oldOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.Triggercontext tc){
        System.debug('OutboundEmailTriggerHandler.onAfterUndelete()');
        //Recast the trigger acctext variables into the appropriate shandlerect types
        List<OutboundEmail__c> newOutboundEmailList = (List<OutboundEmail__c>)tc.newList;
        Map<ID, OutboundEmail__c> newOutboundEmailMap = (Map<ID, OutboundEmail__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<OutboundEmail__c> newOutboundEmailList){
        System.debug('OutboundEmailTriggerHandler.setDefaultsOnInsert()');

        for(OutboundEmail__c email : newOutboundEmailList){
            if(email.SendWhenAttachmentsExist__c == true){
                if(email.ExpectedNumberofAttachements__c == email.CurrentNumberofAttachments__c)
                    email.SendviaSES__c = true;
                else 
                    email.SendviaSES__c = false;
            }
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, OutboundEmail__c> oldOutboundEmailMap, Map<ID, OutboundEmail__c> newOutboundEmailMap){
        System.debug('OutboundEmailTriggerHandler.setDefaultsOnUpdate()'); 
        for(OutboundEmail__c email : newOutboundEmailMap.values()){
            if(email.SendWhenAttachmentsExist__c == true){
                if(email.ExpectedNumberofAttachements__c == email.CurrentNumberofAttachments__c)
                    email.SendviaSES__c = true;
                else 
                    email.SendviaSES__c = false;
            }
        }
    }

    /////////////////////////////////////////////////////////////////////////
    //Method: manageStatements
    /////////////////////////////////////////////////////////////////////////
    private static void manageSendEmail(Map<ID, OutboundEmail__c> oldOutboundEmailMap, Map<ID, OutboundEmail__c> newOutboundEmailMap){
        Set<ID> emailsToSend = new Set<ID>();
        Integer emailCount = 0;
        OrgWideEmailAddress owa = [select id, DisplayName, Address from OrgWideEmailAddress limit 1];


        for(OutboundEmail__c email : newOutboundEmailMap.values()){
            if(oldOutboundEmailMap != null && email.Send__c == true && oldOutboundEmailMap.get(email.id).Send__c == false){
                emailsToSend.add(email.id);
            }
            if(oldOutboundEmailMap == null && email.Send__c == true){
                emailsToSend.add(email.id);
            }
        }
        List<Messaging.Email> emails = new List<Messaging.Email>();
        for(ID theID : emailsToSend){
            Messaging.SingleEmailMessage sem = new Messaging.SingleEmailMessage();
            
            if(String.isNotBlank(newOutboundEmailMap.get(theID).BccAddresses__c)){
                List<String> bcc = newOutboundEmailMap.get(theID).BccAddresses__c.split(',');
                sem.setBccAddresses(bcc);
                emailCount+=bcc.size();             
            }

            if(String.isNotBlank(newOutboundEmailMap.get(theID).CcAddresses__c)){
                List<String> cc = newOutboundEmailMap.get(theID).CcAddresses__c.split(',');         
                sem.setCCAddresses(cc);
                emailCount+=cc.size();              
            }           


            sem.setCharset(newOutboundEmailMap.get(theID).Charset__c);

            //if(String.isNotBlank(newOutboundEmailMap.get(theID).EntityAttachmentIDs__c)){
            //  List<String> attachments = newOutboundEmailMap.get(theID).EntityAttachmentIDs__c.split(',');
            //  sem.setEntityAttachments(attachments);
            //}

//List<Attachment> attachments = [SELECT Name, Body, ContentType, BodyLength from Attachment where id = '00P7A000003SHWD'];

            //if(String.isNotBlank(newOutboundEmailMap.get(theID).FileAttachments__c)){
            //  List<Messaging.EmailFileAttachment> fileAttachments = new List<Messaging.EmailFileAttachment>();
            //  Messaging.EmailFileAttachment efa = new MEssaging.EmailFileAttachment();
            //  efa.setFileName('test attachment');
            //  efa.setBody(attachments[0].Body);
            //  efa.setInline(false); //false = attachment, true = inline
            //  efa.setContentType(attachments[0].ContentType);
            //  fileAttachments.add(efa);
            //  sem.setFileAttachments(fileAttachments);
            //}


            sem.setHTMLBody(newOutboundEmailMap.get(theID).HTMLBody__c);
            sem.setInReplyTo(newOutboundEmailMap.get(theID).InReplyToParentMessageIDs__c);
            sem.setOptOutPolicy(newOutboundEmailMap.get(theID).OptOutPolicy__c);
            sem.setPlainTextBody(newOutboundEmailMap.get(theID).PlainTextBody__c);

            if(newOutboundEmailMap.get(theID).SendFromOrgWideEmail__c){
                sem.setOrgWideEmailAddressID(owa.id);               
            } else if(String.isNotBlank(newOutboundEmailMap.get(theID).OrgWideEmailAddressId__c)){
                sem.setOrgWideEmailAddressId(newOutboundEmailMap.get(theID).OrgWideEmailAddressId__c);              
            }

            sem.setReferences(newOutboundEmailMap.get(theID).References__c);
            sem.setSubject(newOutboundEmailMap.get(theID).Subject__c); //Don't send with template

            sem.setTargetObjectId(newOutboundEmailMap.get(theID).TargetObjectId__c); //send with templateID
            sem.setTemplateId(newOutboundEmailMap.get(theID).TemplateID__c);

            if(String.isNotBlank(newOutboundEmailMap.get(theID).ToAddresses__c)){
                List<String> to = newOutboundEmailMap.get(theID).ToAddresses__c.split(',');             
                sem.setToAddresses(to);
                emailCount+=to.size(); 
            }           

            sem.setTreatBodiesAsTemplate(newOutboundEmailMap.get(theID).TreatBodiesAsTemplate__c);
            sem.setTreatTargetObjectAsRecipient(newOutboundEmailMap.get(theID).TreatTargetObjectAsRecipient__c);
            sem.setWhatId(newOutboundEmailMap.get(theID).WhatID__c); //send with templateID


/////////////////////////////////////////////////////////
            //not in object yet

            //EmailTemplate templateId = [Select id from EmailTemplate where name = 'All Schools Adverse Action Credit Not Approved'];
            //sem.setTemplateId(templateId.id);


            sem.setBccSender(false);
            sem.setUseSignature(false);
            //sem.setReplyTo('info@vemo.com');
            //sem.setSenderDisplayName('Vemo Education');
            sem.setSaveAsActivity(false);

System.debug('sem:'+sem);
            emails.add(sem);
        }

        if(emails.size()>0){
            System.debug('emailCount:'+emailCount);
            Messaging.reserveSingleEmailCapacity(emailCount);

            Boolean opt_AllOrNone = true;
            Messaging.SendEmailResult[] semr = Messaging.sendEmail(emails, opt_AllOrNone);
        }
    }

    public class OutboundEmailTriggerHandlerException extends Exception {}
}