vemo-mdapi-qa/objects/PaymentAllocation__c.object
<CustomObject>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>The amount of this Payment Allocation.</inlineHelpText>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <inlineHelpText>The Payment Instruction related to this Payment Allocation.</inlineHelpText>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>Sum of the Payment Allocations for this Payment Instruction.</inlineHelpText>
        <label>Amount Allocated</label>
        <summarizedField>PaymentAllocation__c.AmountAllocated__c</summarizedField>
        <summaryForeignKey>PaymentAllocation__c.PaymentInstruction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaidToDate__c</fullName>
        <inlineHelpText>The total amount paid so far for this Student Program.</inlineHelpText>
        <label>Paid to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/classes/PaymentAllocationTriggerHandler_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentAllocationTriggerHandler_TEST
// 
// Description: 
// 		Test class for PaymentAllocationTriggerHandler
//
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-10   Jared Hagemann  Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public with sharing class PaymentAllocationTriggerHandler_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<Id, StudentProgram__c> studProgramMap = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, PaymentMethod__c> paymentMethods = TestDataFactory.createAndInsertPaymentMethod(1, students);
    	Map<ID, PaymentInstruction__c> paymentInstructionMap = TestDataFactory.createAndInsertPaymentInstruction(TestUtil.TEST_THROTTLE, students, paymentMethods);
    }
	//to do jared - this is just a dummy method to get past test levels
	@isTest
	public static void testManageAgreementsInsert(){
		TestUtil.setStandardConfiguration();
		Map<Id, StudentProgram__c> studProgramMap = StudentProgramQueries.getStudentProgramMap();
		Map<ID, PaymentInstruction__c> paymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMap();
    	Test.startTest();
    		Map<Id, PaymentAllocation__c> paymentAllocationMap = TestDataFactory.createAndInsertPaymentAllocation(5, paymentInstructionMap, studProgramMap);
    	Test.stopTest();
    	Map<Id, StudentProgram__c> studProgramResultMap = StudentProgramQueries.getStudentProgramMap();
    	for(StudentProgram__c sp : studProgramResultMap.values()){
    		System.assertEquals(5000, sp.PaidToDate__c);
    	} 		
	}

	@isTest
	public static void testManageAgreementsUpdate(){
		TestUtil.setStandardConfiguration();
		Map<Id, StudentProgram__c> studProgramMap = StudentProgramQueries.getStudentProgramMap();
		Map<ID, PaymentInstruction__c> paymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMap();
		Map<Id, PaymentAllocation__c> paymentAllocationMap = TestDataFactory.createAndInsertPaymentAllocation(5, paymentInstructionMap, studProgramMap);
		for(PaymentAllocation__c pa : paymentAllocationMap.values()){
			pa.AmountAllocated__c = 500;
		}
    	Test.startTest();
    		update paymentAllocationMap.values();
    	Test.stopTest();
    	Map<Id, StudentProgram__c> studProgramResultMap = StudentProgramQueries.getStudentProgramMap();
    	for(StudentProgram__c sp : studProgramResultMap.values()){
    		System.assertEquals(2500, sp.PaidToDate__c);
    	} 		
	}

	@isTest
	public static void testManageAgreementsDelete(){
		TestUtil.setStandardConfiguration();
		Map<Id, StudentProgram__c> studProgramMap = StudentProgramQueries.getStudentProgramMap();
		Map<ID, PaymentInstruction__c> paymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMap();
		Map<Id, PaymentAllocation__c> paymentAllocationMap = TestDataFactory.createAndInsertPaymentAllocation(5, paymentInstructionMap, studProgramMap);
    	Test.startTest();
    		delete paymentAllocationMap.values();
    	Test.stopTest();
    	Map<Id, StudentProgram__c> studProgramResultMap = StudentProgramQueries.getStudentProgramMap();
    	for(StudentProgram__c sp : studProgramResultMap.values()){
    		System.assertEquals(0, sp.PaidToDate__c);
    	} 	
	}
}