vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountPosted__c</fullName>
        <inlineHelpText>The Posted amount of the Payment Instruction.</inlineHelpText>
        <label>Amount Posted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DatePosted__c</fullName>
        <inlineHelpText>The date the Payment Instruction posted.</inlineHelpText>
        <label>Date Posted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date of the Payment Instruction.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StewardshipACHBatchDetail__c.object
<CustomObject>
    <label>Stewardship ACH Batch Detail</label>
    <nameField>
        <displayFormat>SACHBD-{000000000}</displayFormat>
        <label>Stewardship ACH Batch Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AccountGUID__c</fullName>
        <label>AccountGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountScheduleGUID__c</fullName>
        <externalId>true</externalId>
        <label>AccountScheduleGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AmountFormula__c</fullName>
        <formula>PaymentInstruction__r.Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AmountFormula</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BankAccount__c</fullName>
        <formula>Text(StewardshipACHBatch__r.BankAccount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bank Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchGUIDFormula__c</fullName>
        <formula>StewardshipACHBatch__r.BatchGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BatchGUIDFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchGUID__c</fullName>
        <label>BatchGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchType__c</fullName>
        <formula>TEXT(StewardshipACHBatch__r.BatchType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Batch Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyEntryDescription__c</fullName>
        <label>CompanyEntryDescription</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisbursementAccountGUIDFormula__c</fullName>
        <formula>PaymentMethod__r.StewardshipDisbursementAccountGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DisbursementAccountGUIDFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisbursementDonorGUIDFormula__c</fullName>
        <formula>Account__r.StewardshipDisbursementDonorGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DisbursementDonorGUIDFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DonorGUID__c</fullName>
        <label>DonorGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentAccountGUIDFormula__c</fullName>
        <formula>PaymentMethod__r.StewardshipPaymentAccountGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PaymentAccountGUIDFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentDonorGUIDFormula__c</fullName>
        <formula>Account__r.StewardshipPaymentDonorGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PaymentDonorGUIDFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentInstruction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Instruction</label>
        <referenceTo>PaymentInstruction__c</referenceTo>
        <relationshipLabel>Stewardship ACH Batch Details</relationshipLabel>
        <relationshipName>Stewardship_ACH_Batch_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurringType__c</fullName>
        <label>Recurring Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - One Time Non Recurring</fullName>
                    <default>true</default>
                    <label>1 - One Time Non Recurring</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>QC&#39;d</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Transmitting</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Batch Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StewardshipProcess__c</fullName>
        <label>Stewardship Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTransaction</fullName>
                </value>
                <value>
                    <fullName>CreateCreditTransaction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransactionAmount__c</fullName>
        <description>TransactionAmount returned from Stewardship</description>
        <inlineHelpText>TransactionAmount returned from Stewardship</inlineHelpText>
        <label>TransactionAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TransactionStatus__c</fullName>
        <inlineHelpText>C – Cleared
B - Bounced or returned
P – Processing</inlineHelpText>
        <label>TransactionStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payment (Incoming Money)</fullName>
                </value>
                <value>
                    <fullName>Credit (Outgoing Money)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/PaymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/StewardshipACHBatchDtlTriggerHndlr.cls
/////////////////////////////////////////////////////////////////////////
// Class: StewardshipACHBatchDtlTriggerHndlr
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-07-06   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class StewardshipACHBatchDtlTriggerHndlr implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State batchDetailrol Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
//    public static Boolean manageCasesHasRun = false;
//    public static Boolean manageStewardshipACHBatchDetailSharesHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution batchDetailrol - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.Triggercontext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            
 
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.Triggercontext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'StewardshipACHBatchDtlTriggerHndlr' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'StewardshipACHBatchDtlTriggerHndlr'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onBeforeInsert()');
       //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.newList;
        //This is where you should call your business logic
        setDefaultsOnInsert(newStewardshipACHBatchDetailList);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onBeforeUpdate()');
        //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.newList;
        List<StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.oldList;
        Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.newMap;
        Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldStewardshipACHBatchDetailMap, newStewardshipACHBatchDetailMap);
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onBeforeDelete()');
       //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.oldList;
        Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onAfterInsert()');
         //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.newList;
        Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.newMap;
        //This is where you should call your business logic

        manageStewardship(null, newStewardshipACHBatchDetailMap);
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onAfterUpdate()');
        //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.newList;
        List<StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.oldList;
        Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.newMap;
        Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.oldMap;
        //This is where you should call your business logic

        manageStewardship(oldStewardshipACHBatchDetailMap, newStewardshipACHBatchDetailMap);
        managePayments(oldStewardshipACHBatchDetailMap, newStewardshipACHBatchDetailMap);
   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onAfterDelete()');
        //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.oldList;
        Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.Triggercontext tc){
system.debug('StewardshipACHBatchDtlTriggerHndlr.onAfterUndelete()');
        //Recast the trigger batchDetailext variables into the appropriate shandlerect types
        List<StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailList = (List<StewardshipACHBatchDetail__c>)tc.newList;
        Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap = (Map<ID, StewardshipACHBatchDetail__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailList){
system.debug('StewardshipACHBatchDtlTriggerHndlr.setDefaultsOnInsert()');

        for(StewardshipACHBatchDetail__c batchDetail : newStewardshipACHBatchDetailList){
            if(batchDetail.Amount__c == null || batchDetail.Amount__c == 0) batchDetail.Amount__c = batchDetail.AmountFormula__c;
            
          //temp  if(String.isEmpty(batchDetail.BatchGUID__c)) batchDetail.BatchGUID__c = batchDetail.BatchGUIDFormula__c;

            if(batchDetail.BankAccount__c == 'Payments'){
                if(String.isEmpty(batchDetail.DonorGUID__c)) batchDetail.DonorGUID__c = batchDetail.PaymentDonorGUIDFormula__c;
                if(String.isEmpty(batchDetail.AccountGUID__c)) batchDetail.AccountGUID__c = batchDetail.PaymentAccountGUIDFormula__c;                
            }
            if(batchDetail.BankAccount__c == 'Disbursement'){
                if(String.isEmpty(batchDetail.DonorGUID__c)) batchDetail.DonorGUID__c = batchDetail.DisbursementDonorGUIDFormula__c;
                if(String.isEmpty(batchDetail.AccountGUID__c)) batchDetail.AccountGUID__c = batchDetail.DisbursementAccountGUIDFormula__c;                
            }
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap, Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap){
system.debug('StewardshipACHBatchDtlTriggerHndlr.setDefaultsOnUpdate()'); 
        for(StewardshipACHBatchDetail__c batchDetail : newStewardshipACHBatchDetailMap.values()){
            if(batchDetail.Amount__c == null || batchDetail.Amount__c == 0) batchDetail.Amount__c = batchDetail.AmountFormula__c;
            if(batchDetail.Status__c == 'Cancelled' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).Status__c != 'Cancelled'){
                batchDetail.StewardshipProcess__c = 'CancelTransaction';
            }

            if(batchDetail.BankAccount__c == 'Payments'){
                if(String.isEmpty(batchDetail.DonorGUID__c)) batchDetail.DonorGUID__c = batchDetail.PaymentDonorGUIDFormula__c;
                if(String.isEmpty(batchDetail.AccountGUID__c)) batchDetail.AccountGUID__c = batchDetail.PaymentAccountGUIDFormula__c;                
            }
            if(batchDetail.BankAccount__c == 'Disbursement'){
                if(String.isEmpty(batchDetail.DonorGUID__c)) batchDetail.DonorGUID__c = batchDetail.DisbursementDonorGUIDFormula__c;
                if(String.isEmpty(batchDetail.AccountGUID__c)) batchDetail.AccountGUID__c = batchDetail.DisbursementAccountGUIDFormula__c;                
            }
        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: managePayments
    /////////////////////////////////////////////////////////////////////////
    private void managePayments(Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap, Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap){
        System.debug('StewardshipACHBatchDtlTriggerHndlr.managePayments()'); 

        Set<ID> paymentIDs = new Set<ID>();
        for(StewardshipACHBatchDetail__c batchDetail : newStewardshipACHBatchDetailMap.values()){
            if(String.isNotEmpty(batchDetail.PaymentInstruction__c)){
                paymentIDs.add(batchDetail.PaymentInstruction__c);
            }
        }        
        Map<ID, PaymentInstruction__c> paymentsToUpdate = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentInstructionID(paymentIDs);//new Map<ID, PaymentInstruction__c>([Select id, Date__c from PaymentInstruction__c where ID in: paymentIDs]);
        for(StewardshipACHBatchDetail__c batchDetail : newStewardshipACHBatchDetailMap.values()){
            if(String.isNotEmpty(batchDetail.PaymentInstruction__c)){
                PaymentInstruction__c payment = paymentsToUpdate.get(batchDetail.PaymentInstruction__c);
                System.debug('payment:'+payment);
                Date postedDate;
                Date createdDate = Date.newInstance(payment.CreatedDate.year(), payment.CreatedDate.month(), payment.CreatedDate.day());
                System.debug('payment.Date__c:'+payment.Date__c);
                System.debug('createdDate:'+createdDate);
                if(payment.Date__c < createdDate){
                    postedDate = createdDate;
                } else {
                    postedDate = payment.Date__c;
                }
                System.debug('postedDate:'+postedDate);
                if(batchDetail.TransactionStatus__c == 'C' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).TransactionStatus__c != 'C'){
                    paymentsToUpdate.put(batchDetail.PaymentInstruction__c, new PaymentInstruction__c(id = batchDetail.PaymentInstruction__c,
                                                                    DatePosted__c = postedDate,//paymentsToUpdate.get(batchDetail.PaymentInstruction__c).Date__c,
                                                                    AmountPosted__c = batchDetail.TransactionAmount__c,
                                                                   Status__c = 'Cleared'));
                }
                if(batchDetail.TransactionStatus__c == 'B' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).TransactionStatus__c != 'B'){
                    paymentsToUpdate.put(batchDetail.PaymentInstruction__c, new PaymentInstruction__c(id = batchDetail.PaymentInstruction__c,
                                                                   Status__c = 'Bounced'));
                }
                if(batchDetail.TransactionStatus__c == 'P' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).TransactionStatus__c != 'P'){
                    paymentsToUpdate.put(batchDetail.PaymentInstruction__c, new PaymentInstruction__c(id = batchDetail.PaymentInstruction__c,
                                                                   Status__c = 'Processing'));
                }
                if(batchDetail.Status__c == 'Cancelled' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).Status__c != 'Cancelled'){
                    paymentsToUpdate.put(batchDetail.PaymentInstruction__c, new PaymentInstruction__c(id = batchDetail.PaymentInstruction__c,
                                                                   Status__c = 'Cancelled'));
                }
                if(batchDetail.Status__c == 'Batch Cancelled' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).Status__c != 'Batch Cancelled'){
                    paymentsToUpdate.put(batchDetail.PaymentInstruction__c, new PaymentInstruction__c(id = batchDetail.PaymentInstruction__c,
                                                                   Status__c = 'Cancelled'));
                }
                if(batchDetail.Status__c == 'Approved' && oldStewardshipACHBatchDetailMap.get(batchDetail.id).Status__c != 'Approved'){
                    paymentsToUpdate.put(batchDetail.PaymentInstruction__c, new PaymentInstruction__c(id = batchDetail.PaymentInstruction__c,
                                                                   Status__c = 'Processing'));
                }
            }
        }
        if(paymentsToUpdate.size()>0){
            update paymentsToUpdate.values();
        }
    }


    /////////////////////////////////////////////////////////////////////////
    //Method: manageStewardship
    /////////////////////////////////////////////////////////////////////////
    private void manageStewardship(Map<ID, StewardshipACHBatchDetail__c> oldStewardshipACHBatchDetailMap, Map<ID, StewardshipACHBatchDetail__c> newStewardshipACHBatchDetailMap){
system.debug('StewardshipACHBatchDtlTriggerHndlr.manageStewardship()'); 
        Set<Id> paymentDetailIds = new Set<Id>();
        Set<Id> creditDetailIds = new Set<ID>();
        Set<ID> cancelTxIDs = new Set<ID>();
        for(StewardshipACHBatchDetail__c batchDetail : newStewardshipACHBatchDetailMap.values()){
            if((oldStewardshipACHBatchDetailMap == null && batchDetail.StewardshipProcess__c == 'CreateTransaction') ||
               (batchDetail.StewardshipProcess__c == 'CreateTransaction' && batchDetail.StewardshipProcess__c != oldStewardshipACHBatchDetailMap.get(batchDetail.id).StewardshipProcess__c)){
                if(batchDetail.ScheduledDate__c == null) batchDetail.addError('Scheduled Date is required for Payment transactions');
                if(batchDetail.TransactionType__c != 'Payment (Incoming Money)') batchDetail.addError('Not a payment');
                if(batchDetail.BatchType__c != 'Payment (Incoming Money)') batchDetail.addError('Not a payment batch');
                 if(String.isEmpty(batchDetail.Memo__c)) batchDetail.addError('Requires Memo');
                paymentDetailIds.add(batchDetail.Id);
            }

            if((oldStewardshipACHBatchDetailMap == null && batchDetail.StewardshipProcess__c == 'CreateCreditTransaction') ||
               (batchDetail.StewardshipProcess__c == 'CreateCreditTransaction' && batchDetail.StewardshipProcess__c != oldStewardshipACHBatchDetailMap.get(batchDetail.id).StewardshipProcess__c)){
                if(batchDetail.TransactionType__c != 'Credit (Outgoing Money)') batchDetail.addError('Not a credit');
                if(batchDetail.BatchType__c != 'Credit (Outgoing Money)') batchDetail.addError('Not a credit batch');
                if(String.isEmpty(batchDetail.CompanyEntryDescription__c)) batchDetail.addError('Requires CompanyEntryDescription');
                if(String.isEmpty(batchDetail.Memo__c)) batchDetail.addError('Requires Memo');
                creditDetailIds.add(batchDetail.Id);
            }

            if((oldStewardshipACHBatchDetailMap == null && batchDetail.StewardshipProcess__c == 'CancelTransaction') ||
               (batchDetail.StewardshipProcess__c == 'CancelTransaction' && batchDetail.StewardshipProcess__c != oldStewardshipACHBatchDetailMap.get(batchDetail.id).StewardshipProcess__c)){
                if(String.isEmpty(batchDetail.AccountScheduleGUID__c)) batchDetail.addError('Requires AccountScheduleGUID');
                cancelTxIds.add(batchDetail.Id);
            }
        }


        for(ID theID : paymentDetailIds){
            StewardshipTechService.CreateTransactionRequest input = new StewardshipTechService.CreateTransactionRequest();
            //input.DonorGUID = '117FDE89-F3DD-47AC-806A-C19185F11AB6';
            //input.AccountGUID = '5A8811D0-65DD-48EA-817C-D0799B70485D';
            input.DonorGUID = newStewardshipACHBatchDetailMap.get(theID).DonorGUID__c;
            input.AccountGUID = newStewardshipACHBatchDetailMap.get(theID).AccountGUID__c;
            input.Amount1 = newStewardshipACHBatchDetailMap.get(theID).Amount__c;
            input.Memo1 = newStewardshipACHBatchDetailMap.get(theID).Memo__c;

            input.RecurringType = String.valueOf(newStewardshipACHBatchDetailMap.get(theID).RecurringType__c).left(1);
            input.ScheduledDate = newStewardshipACHBatchDetailMap.get(theID).ScheduledDate__c;
//            input.BatchGUID = newStewardshipACHBatchDetailMap.get(theID).BatchGUID__c;
            
            StewardshipTechService.CreateTransactionQueueable job = new StewardshipTechService.CreateTransactionQueueable();
            job.input = input;
            job.stewardshipBatchDetailID = theID;
            job.acctType = StewardshipTechService.AccountType.PAYMENT;
            System.enqueueJob(job);

        }

        for(ID theID : creditDetailIds){
            StewardshipTechService.CreateCreditTransactionRequest input = new StewardshipTechService.CreateCreditTransactionRequest();
            //input.DonorGUID = '117FDE89-F3DD-47AC-806A-C19185F11AB6';
            //input.AccountGUID = '5A8811D0-65DD-48EA-817C-D0799B70485D';
            input.DonorGUID = newStewardshipACHBatchDetailMap.get(theID).DonorGUID__c;
            input.AccountGUID = newStewardshipACHBatchDetailMap.get(theID).AccountGUID__c;
            input.Amount = newStewardshipACHBatchDetailMap.get(theID).Amount__c;
            input.Memo = newStewardshipACHBatchDetailMap.get(theID).Memo__c;
            input.CompanyEntryDescription = newStewardshipACHBatchDetailMap.get(theID).CompanyEntryDescription__c;


//            input.BatchGUID = newStewardshipACHBatchDetailMap.get(theID).BatchGUID__c;
            
            StewardshipTechService.CreateCreditTransactionQueueable job = new StewardshipTechService.CreateCreditTransactionQueueable();
            job.input = input;
            job.stewardshipBatchDetailID = theID;
            job.acctType = StewardshipTechService.AccountType.DISBURSEMENT;
            System.enqueueJob(job);

        }

        for(ID theID : cancelTxIds){
            StewardshipTechService.CancelTransactionRequest input = new StewardshipTechService.CancelTransactionRequest();

            input.DonorGUID = newStewardshipACHBatchDetailMap.get(theID).DonorGUID__c;
            input.AccountScheduleGUID = newStewardshipACHBatchDetailMap.get(theID).AccountScheduleGUID__c;
            
            StewardshipTechService.CancelTransactionQueueable job = new StewardshipTechService.CancelTransactionQueueable();
            job.input = input;
            job.stewardshipBatchDetailID = theID;
            job.acctType = StewardshipTechService.AccountType.PAYMENT;
            System.enqueueJob(job);

        }

    }

    public class StewardshipACHBatchDtlTriggerHndlrException extends Exception {}
}