vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <inlineHelpText>Sum of the Payment Allocations for this Payment Instruction.</inlineHelpText>
        <label>Amount Allocated</label>
        <summarizedField>PaymentAllocation__c.AmountAllocated__c</summarizedField>
        <summaryForeignKey>PaymentAllocation__c.PaymentInstruction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AmountPosted__c</fullName>
        <inlineHelpText>The Posted amount of the Payment Instruction.</inlineHelpText>
        <label>Amount Posted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DatePosted__c</fullName>
        <inlineHelpText>The date the Payment Instruction posted.</inlineHelpText>
        <label>Date Posted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date of the Payment Instruction.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RemainingAllocation__c</fullName>
        <formula>Amount__c -  AmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount minus Amount Allocated.</inlineHelpText>
        <label>Remaining Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Scheduled_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransactionDirection__c</fullName>
        <inlineHelpText>Inbound (from Student to Vemo) or Outbound (from Vemo to Student).</inlineHelpText>
        <label>Transaction Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionDirection</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Optional description - helpful in case Customer has multiple accounts at one bank.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/PaymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/globalValueSets/TransactionDirection.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <masterLabel>Transaction Direction</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/PaymentInstructionService.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentInstructionService
// 
// Description: 
//  Handles all PaymentInstruction DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-13   Jared Hagemann  Created              
/////////////////////////////////////////////////////////////////////////
public with sharing class PaymentInstructionService {
    
    public static List<PaymentInstruction> getPaymentInstructionWithPaymentInstructionID(Set<ID> paymentInstructionIDs){
        System.debug('PaymentInstructionService.getPaymentInstructionWithPaymentInstructionID');
        Map<Id, PaymentInstruction__c> pymntInsMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentInstructionID(paymentInstructionIDs);
        List<PaymentInstruction> pymntInsList = new List<PaymentInstruction>();
        for(PaymentInstruction__c pymntIns : pymntInsMap.values()){
            pymntInsList.add(new PaymentInstruction(pymntIns));
        }
        return pymntInsList;
    }
    
    public static List<PaymentInstruction> getPaymentInstructionWithStudentID(Set<ID> studentIDs){
        System.debug('PaymentInstructionService.getPaymentInstructionWithStudentID');
        Map<Id, PaymentInstruction__c> pymntInsMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentStudentID(studentIDs);
        List<PaymentInstruction> pymntInsList = new List<PaymentInstruction>();
        for(PaymentInstruction__c pymntIns : pymntInsMap.values()){
            pymntInsList.add(new PaymentInstruction(pymntIns));
        }
        return pymntInsList;
    }

    public static Set<Id> createPaymentInstruction(List<PaymentInstruction> paymentInstructions){
        System.debug('PaymentInstructionService.createPaymentInstruction');
        List<PaymentInstruction__c> pymntInsList = new List<PaymentInstruction__c>();
        for(PaymentInstruction pymntIns : paymentInstructions){
            PaymentInstruction__c pymntInsObj = paymentMethodClsToPaymentmMethodObj(pymntIns);
            pymntInsList.add(pymntInsObj);
        }
        insert pymntInsList;
        Set<Id> pymntInsIDs = new Set<Id>();
        for(PaymentInstruction__c pymntIns : pymntInsList){
            pymntInsIDs.add(pymntIns.ID);
        }
        return pymntInsIDs;
    }

    public static Set<Id> updatePaymentInstruction(List<PaymentInstruction> paymentInstructions){
        System.debug('PaymentInstructionService.createPaymentInstruction');
        List<PaymentInstruction__c> pymntInsList = new List<PaymentInstruction__c>();
        for(PaymentInstruction pymntIns : paymentInstructions){
            PaymentInstruction__c pymntInsObj = paymentMethodClsToPaymentmMethodObj(pymntIns);
            pymntInsList.add(pymntInsObj);
        }
        update pymntInsList;
        Set<Id> pymntInsIDs = new Set<Id>();
        for(PaymentInstruction__c pymntIns : pymntInsList){
            pymntInsIDs.add(pymntIns.ID);
        }
        return pymntInsIDs;
    }

    public static Integer deletePaymentInstruction(Set<ID> paymentInstructionIds){
        System.debug('PaymentInstructionService.deletePaymentInstruction');
        Map<ID, PaymentInstruction__c> pymntIns = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentInstructionID(paymentInstructionIds);
        Integer numToDelete = pymntIns.size();
        delete pymntIns.values();
        return numToDelete;
    }

    public static PaymentInstruction__c paymentMethodClsToPaymentmMethodObj(PaymentInstruction input){
        System.debug('PaymentMethodService.paymentMethodClsToPaymentmMethodObj');       
        PaymentInstruction__c result = new PaymentInstruction__c();
        if(input.paymentInstructionID != null) result.ID = input.paymentInstructionID;
        if(input.amount != null) result.Amount__c = input.amount;
        if(input.paymentDate != null) result.Date__c = input.paymentDate;
        if(input.paymentMethodID != null) result.PaymentMethod__c = input.paymentMethodID;
        if(input.studentID != null) result.Student__c = input.studentID;
        if(input.datePosted != null) result.DatePosted__c = input.datePosted;
        if(input.amountPosted != null) result.AmountPosted__c = input.amountPosted;
        if(input.transactionDirection != null) result.TransactionDirection__c = input.transactionDirection;
        if(input.status != null) result.Status__c = input.status;
        if(input.description != null) result.Description__c = input.description;
        return result;
    }



    public class PaymentInstruction{
        public String paymentInstructionID {get;set;}
        public Decimal amount {get;set;}
        public Decimal amountAllocated {get;set;}
        public Decimal remainingAllocation {get;set;}
        public Date paymentDate {get;set;}
        public String paymentMethodID {get;set;}
        public String studentID {get;set;}
        public Date datePosted {get;set;}
        public Decimal amountPosted {get; set;}
        public String transactionDirection {get;set;}
        public String status {get;set;}
        public String description {get;set;}

        public PaymentInstruction(){
        }

        public PaymentInstruction(Boolean testValues){
            if(testValues){
                this.amount = 1000;
                this.paymentDate = System.today();
                this.status = 'None';
            }
        }

        public PaymentInstruction(PaymentInstruction__c pymntIns){
            this.paymentInstructionID = pymntIns.ID;    
            this.amount = pymntIns.Amount__c;
            this.amountAllocated = pymntIns.AmountAllocated__c;
            this.remainingAllocation = pymntIns.RemainingAllocation__c;
            this.paymentDate = pymntIns.Date__c;
            this.paymentMethodID = pymntIns.PaymentMethod__c;
            this.studentID = pymntIns.Student__c;
            this.datePosted = pymntIns.DatePosted__c;
            this.amountPosted = pymntIns.AmountPosted__c;
            this.transactionDirection = pymntIns.TransactionDirection__c;
            this.status = pymntIns.Status__c;
            this.description = pymntIns.Description__c;
        }
    }
}