vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The Amount of the Payment Instruction.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date of the Payment Instruction.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Scheduled_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AutomaticallyConfirmTransactions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatically Confirm Transactions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DisbursementConfRequiredNotification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is checked, the SchoolEmailNotification2__c will be sent a notification email when there is one or more disbursement confirmations awaiting the program.</description>
        <inlineHelpText>If this field is checked, the SchoolEmailNotification2__c will be sent a notification email when there is one or more disbursement confirmations awaiting the program.</inlineHelpText>
        <label>Disbursement Conf Required Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchoolEmailNotification2__c</fullName>
        <label>School Email Notification 2</label>
        <type>Email</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Disbursement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount to be disbursed or refunded.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if Disbursement has been confirmed.</inlineHelpText>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionDate__c</fullName>
        <inlineHelpText>The date the funds were disbursed.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/PaymentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/ProgramBatch.cls
public class ProgramBatch implements Database.Batchable<sObject>, Database.ALlowsCallouts {
	public enum JobType {DISB_CONF_NOTIFICATION} 
	
	public String query {get;set;}
	public JobType job {get;set;}
	
	public ProgramBatch() {
		job = JobType.DISB_CONF_NOTIFICATION;
	}
	public ProgramBatch(String query) {
		this.query = query;
		job = JobType.DISB_CONF_NOTIFICATION;
	}	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('ProgramBatch.start()');
		if(job == JobType.DISB_CONF_NOTIFICATION){
			if(String.isEmpty(this.query)){
				String dateToday = String.valueOf(Date.today());
				query = 'SELECT id from Program__c where DisbursementConfRequiredNotification__c = true and AutomaticallyConfirmTransactions__c = false';
				//query = 'SELECT id, Date__c, Amount__c, Status__c from PaymentInstruction__c WHERE Status__c = \'None\' and Date__c <='+dateToday + ' ORDER BY Date__c ASC';
			}
		}
		System.debug('job:'+job);
		System.debug('query:'+query);
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.debug('ProgramBatch.execute()');
		Set<ID> scopeIDs = new Set<ID>();
		for(sObject sobj : scope){
			scopeIDs.add(sobj.id);
		}

		if(job == JobType.DISB_CONF_NOTIFICATION){
			Map<ID, Program__c> programMap = ProgramQueries.getProgramMapWithProgramID(scopeIDs);
			//Look for any disbursements waiting for confirmation
			Map<ID, Transaction__c> disbursementMap = new Map<ID, Transaction__c>([SELECT id,
																						  Agreement__c,
																						  Agreement__r.Program__c,
																						  Agreement__r.Student__c,
																						  Agreement__r.Student__r.PersonContactID,
																						  Agreement__r.Status__c
																				   FROM Transaction__c
																				   WHERE Agreement__r.Program__c = :programMap.keySet()
																				    and TransactionDate__c <= :Date.today()
																				    and (Status__c = 'Scheduled'
																				    	or (Status__c = 'Complete' and Confirmed__c = false))]);
			Map<ID, List<Transaction__c>> validDisbursementsByProgramID = new Map<ID, List<Transaction__c>>();
			for(Transaction__c tx : disbursementMap.values()){
				Set<String> validStatus = new Set<String>{'Certified', 'Partially Funded'};
				if(validStatus.contains(tx.Agreement__r.Status__c)){
					if(!validDisbursementsByProgramID.containsKey(tx.Agreement__r.Program__c)){
						validDisbursementsByProgramID.put(tx.Agreement__r.Program__c, new List<Transaction__c>());
					}
					validDisbursementsByProgramID.get(tx.Agreement__r.Program__c).add(tx);					
				}
			}
			System.debug('validDisbursementsByProgramID:'+validDisbursementsByProgramID);
			List<OutboundEmailService.OutboundEmail> outboundEmails = new List<OutboundEmailService.OutboundEmail>();
			for(ID theID : validDisbursementsByProgramID.keySet()){
				OutboundEmailService.OutboundEmail email = new OutboundEmailService.OutboundEmail();

                email.toAddresses = programMap.get(theID).SchoolEmailNotification2__c;
                //email.templateID = '00X7A000000EJ98';
                email.templateDevName = 'AllSchoolsAwaitingDisbursementConfirmation';
                email.whatID = theID;//validDisbursementsByProgramID.get(theID)[0].id;
                email.targetObjectId = validDisbursementsByProgramID.get(theID)[0].Agreement__r.Student__r.PersonContactID;
                email.sendImmediate = true;

				outboundEmails.add(email);


			}
			OutboundEmailService.createOutboundEmailV1(outboundEmails);			
		}
	}
	
	public void finish(Database.BatchableContext BC) {
		System.debug('ProgramBatch.finish()');		
	}
}