vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/classes/PaymentInstructionQueries_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentInstructionQueries_TEST
// 
// Description: 
//  Unit test for PaymentInstructionQueries
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-18   Jared Hagemann  Created 
/////////////////////////////////////////////////////////////////////////
@isTest
public class PaymentInstructionQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testGetPaymentInstructionMap(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInsturctionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    	Test.startTest();
        Map<Id, PaymentInstruction__c> resultPaymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMap();
    	System.assertEquals(testPaymentInsturctionMap.size(), resultPaymentInstructionMap.keySet().size());
    	Test.stopTest();
    }

    static testMethod void testGetPaymentInstructionMapWithPaymentInstructionID(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInsturctionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    	Test.startTest();
        Map<Id, PaymentInstruction__c> resultPaymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentInstructionID(testPaymentInsturctionMap.keySet());
    	System.assertEquals(testPaymentInsturctionMap.size(), resultPaymentInstructionMap.keySet().size());
    	Test.stopTest();
    }

    static testMethod void testGetPaymentInstructionMapWithPaymentStudentID(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInsturctionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    	Test.startTest();
        Map<Id, PaymentInstruction__c> resultPaymentInstructionMap = PaymentInstructionQueries.getPaymentInstructionMapWithPaymentStudentID(testStudentAccountMap.keySet());
    	System.assertEquals(testPaymentInsturctionMap.size(), resultPaymentInstructionMap.keySet().size());
    	Test.stopTest();
    }
}