vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>FullyAllocated__c</fullName>
        <formula>IF( AmountAllocated__c =  Amount__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Checked if Amount Allocated is equal to Amount.</inlineHelpText>
        <label>Fully Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled or Complete</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/PaymentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Created By Student</fullName>
    </customValue>
    <customValue>
        <fullName>Automatically Created</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Processed by Vemo</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Bounced</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Payment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/PaymentAllocationScheduled.cls
/*
PaymentAllocationScheduled job1 = new PaymentAllocationScheduled();
String cronStr = '0 0 * * * ? *';
System.schedule('PaymentAllocation', cronStr, job1);
*/
public class PaymentAllocationScheduled implements Schedulable {
	public void execute(SchedulableContext sc) {
//		String query = 'Select id from PaymentInstruction__c where FullyAllocated__c = false and (Status__c = \'Scheduled\' or Status__c = \'Complete\')';
		String query = 'Select id from PaymentInstruction__c where FullyAllocated__c = false and (Status__c = \'Cleared\')';
		Boolean proofMode = false;
		PaymentAllocationBatch job = new PaymentAllocationBatch(query, proofMode);
		Database.executeBatch(job, 1);
	}
}