vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BankAccountCategory__c</fullName>
        <inlineHelpText>Personal or Business</inlineHelpText>
        <label>Bank Account Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BankAccountCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BankAccountNumber__c</fullName>
        <label>Bank Account Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>BankAccountType__c</fullName>
        <inlineHelpText>Checking or Savings</inlineHelpText>
        <label>Bank Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BankAccountType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BankName__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankRoutingNumber__c</fullName>
        <label>Bank Routing Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CreditCardNumber__c</fullName>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Optional description - helpful in case Customer has multiple accounts at one bank.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this payment method inactive?</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this the Customer&#39;s primary payment method?</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UseForDisbursements__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Can this payment method be used for disbursements?</inlineHelpText>
        <label>Use For Disbursements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UseForRecurring__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Can this payment method be used for recurring payments?</inlineHelpText>
        <label>Use For Recurring</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/BankAccountCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <masterLabel>Bank Account Category</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/BankAccountType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checking</fullName>
    </customValue>
    <customValue>
        <fullName>Savings</fullName>
    </customValue>
    <masterLabel>Bank Account Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/PaymentMethodQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentMethodQueries
// 
// Description: 
// 	
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-13   Jared Hagemann  Created      
// 2017-05-18	Greg Cook 		Changed Student__c to Customer__c                           
/////////////////////////////////////////////////////////////////////////
public class PaymentMethodQueries {
	
	public static Map<String, Object> filterCriteria = new Map<String, Object>();
	public static void clearFilterCriteria(){
		filterCriteria.clear();
	}

	public static Map<ID, PaymentMethod__c> getPaymentMethodMap(){
		Map<ID, PaymentMethod__c> paymentMethodMap = new Map<ID, PaymentMethod__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Inactive__c = false';
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Customer__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		paymentMethodMap = new Map<ID, PaymentMethod__c>((List<PaymentMethod__c>)db.query(query));
		return paymentMethodMap;		
	}

	public static Map<ID, PaymentMethod__c> getPaymentMethodMapWithPaymentMethodID(Set<Id> paymentMethodIds){
		Map<ID, PaymentMethod__c> paymentMethodMap = new Map<ID, PaymentMethod__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(paymentMethodIds);
		query += ' and Inactive__c = false';
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Customer__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		paymentMethodMap = new Map<ID, PaymentMethod__c>((List<PaymentMethod__c>)db.query(query));
		return paymentMethodMap;		
	}

	public static Map<ID, PaymentMethod__c> getPaymentMethodMapWithCustomerID(Set<Id> customerIDs){
		Map<ID, PaymentMethod__c> paymentMethodMap = new Map<ID, PaymentMethod__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Customer__c IN ' + DatabaseUtil.inSetStringBuilder(customerIDs);
		query += ' and Inactive__c = false';
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Customer__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
		}
		query += buildFilterString();		
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		paymentMethodMap = new Map<ID, PaymentMethod__c>((List<PaymentMethod__c>)db.query(query));
		return paymentMethodMap;		
	}


	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
	
	private static String buildFilterString(){
		String filterStr = '';
		if(filterCriteria.size()>0){
			for(String filter : filterCriteria.keyset()){
				filterStr += ' and ' +filter+'=\''+String.valueOf(filterCriteria.get(filter) + 	'\' ');
			}			
		}
		return filterStr;
	}

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getFieldNames() + ' FROM PaymentMethod__c';
		return soql;
	}

	private static String getFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Name, ';
		fieldNames += 'BankAccountCategory__c, ';
		fieldNames += 'BankAccountNumber__c, ';
		fieldNames += 'BankAccountType__c, ';
		fieldNames += 'BankName__c, ';
		fieldNames += 'BankRoutingNumber__c, ';
		fieldNames += 'CreditCardNumber__c, ';
		fieldNames += 'Customer__c, ';
		fieldNames += 'Description__c, ';
		fieldNames += 'Primary__c, ';
		fieldNames += 'UseForDisbursements__c, ';
		fieldNames += 'UseForRecurring__c, ';
		fieldNames += 'Inactive__c ';		
		return fieldNames;
	}
	
}