vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/PaymentMethod__c.object
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/classes/PaymentInstructionService_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: PaymentInstructionService_TEST
// 
// Description: 
//  Unit test for PaymentInstructionService
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-18   Jared Hagemann  Created 
/////////////////////////////////////////////////////////////////////////
@isTest
public class PaymentInstructionService_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testGetPaymentInstructionWithPaymentInstructionID(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInsturctionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    	Test.startTest();
        List<PaymentInstructionService.PaymentInstruction> resultPaymentInstructionMap = PaymentInstructionService.getPaymentInstructionWithPaymentInstructionID(testPaymentInsturctionMap.keySet());
    	System.assertEquals(testPaymentInsturctionMap.size(), resultPaymentInstructionMap.size());
    	Test.stopTest();
    }

    static testMethod void testGetPaymentInstructionWithStudentID(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInsturctionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    	Test.startTest();
        List<PaymentInstructionService.PaymentInstruction> resultPaymentInstructionMap = PaymentInstructionService.getPaymentInstructionWithStudentID(testStudentAccountMap.keySet());
    	System.assertEquals(testPaymentInsturctionMap.size(), resultPaymentInstructionMap.size());
    	Test.stopTest();
    }

    static testMethod void testCreatePaymentInstruction(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	List<PaymentInstructionService.PaymentInstruction> pymntInstructions = new List<PaymentInstructionService.PaymentInstruction>();
    	for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
    		PaymentInstructionService.PaymentInstruction pymntIns = new PaymentInstructionService.PaymentInstruction(true);
    		pymntIns.studentID = testStudentAccountMap.values().get(i).Id;
    		pymntIns.paymentMethodID = testPaymentMethodMap.values().get(i).Id;
    		pymntInstructions.add(pymntIns);
    	}
    	Test.startTest();
    	Set<ID> pymntInsIDs = PaymentInstructionService.createPaymentInstruction(pymntInstructions);
    	System.assertEquals(pymntInstructions.size(), PaymentInstructionQueries.getPaymentInstructionMap().size());
    	Test.stopTest();
    }

    static testMethod void testUpdatePaymentInstruction(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInstructionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);
    	List<PaymentInstructionService.PaymentInstruction> pymntInstructions = new List<PaymentInstructionService.PaymentInstruction>();
    	for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
    		PaymentInstructionService.PaymentInstruction pymntIns = new PaymentInstructionService.PaymentInstruction(true);
    		pymntIns.paymentInstructionID = testPaymentInstructionMap.values().get(i).Id;
    		//pymntIns.student = testStudentAccountMap.values().get(i).Id;
    		pymntIns.paymentMethodID = testPaymentMethodMap.values().get(i).Id;
    		pymntInstructions.add(pymntIns);
    	}
    	Test.startTest();
    	Set<ID> pymntInsIDs = PaymentInstructionService.updatePaymentInstruction(pymntInstructions);
    	System.assertEquals(pymntInstructions.size(), PaymentInstructionQueries.getPaymentInstructionMap().size());
    	Test.stopTest();
    }

    static testMethod void testDeletePaymentInstruction(){
    	Map<Id, Account> testStudentAccountMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, PaymentMethod__c> testPaymentMethodMap = TestDataFactory.createAndInsertPaymentMethod(1, testStudentAccountMap);
    	Map<ID, PaymentInstruction__c> testPaymentInstructionMap = TestDataFactory.createAndInsertPaymentInstruction(1, testStudentAccountMap, testPaymentMethodMap);

    	Test.startTest();
    	Integer del = PaymentInstructionService.deletePaymentInstruction(testPaymentInstructionMap.keySet());
    	Test.stopTest();
    	System.assertEquals(testPaymentInstructionMap.size(), del);
    	System.assertEquals(0, PaymentInstructionQueries.getPaymentInstructionMap().size());
    }
}