vemo-mdapi-qa/objects/PaymentInstruction__c.object
<CustomObject>
    <label>Payment Instruction</label>
    <nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Payment Instruction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Payment Method related to this Payment Instruction.</inlineHelpText>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Payment Method selected must match the Student of the Scheduled Payment</errorMessage>
            <filterItems>
                <field>PaymentMethod__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Student__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Instructions (Payment Method)</relationshipLabel>
        <relationshipName>Scheduled_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Refund__c.object
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000000000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StewardshipACHBatchDetail__c.object
<CustomObject>
    <label>Stewardship ACH Batch Detail</label>
    <nameField>
        <displayFormat>SACHBD-{000000000}</displayFormat>
        <label>Stewardship ACH Batch Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Stewardship_ACH_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>PaymentMethod__c</referenceTo>
        <relationshipName>Stewardship_ACH_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credit Check object used to determine credit at the time Student applied for this Student Program.</inlineHelpText>
        <label>Credit Check</label>
        <referenceTo>CreditCheck__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TransactionBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Disbursement Batch.</inlineHelpText>
        <label>Transaction Batch</label>
        <referenceTo>TransactionBatch__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/TransactionBatch__c.object
<CustomObject>
    <label>Disbursement Batch</label>
    <nameField>
        <displayFormat>DB-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Disbursement Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>TransactionBatches</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerSettings</label>
    <fields>
        <fullName>Account__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this box is checked the Account trigger will fire</description>
        <inlineHelpText>If this box is checked the Account trigger will fire</inlineHelpText>
        <label>Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attachment__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Attachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreditCheck__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CreditCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PaymentMethod</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentProgram__c</fullName>
        <defaultValue>true</defaultValue>
        <label>StudentProgram</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TransactionBatch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>TransactionBatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Transaction</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/TriggerSettings.cls
/////////////////////////////////////////////////////////////////////////
// Class: TriggerSettings
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-07-06   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class TriggerSettings {
    ////////////////////////////////////////////////////////////////////////
    //Static Block
    /////////////////////////////////////////////////////////////////////////
	static{
		if (Test.isRunningTest()){
            Profile sysAdmin = [SELECT Id from Profile where Name = 'System Administrator'];
			User thisUser = [Select Id
                             FROM User
                             WHERE ProfileId = :sysAdmin.id and isActive = true
                             LIMIT 1];
			System.runAs(thisUser) {
				try{
					createDefaultSettings(); //if a test is running - create the settings so the test classes dont have to
				} catch(DMLException e){
				//probably fine - just means it already exists
				}
				
			}
		}	
	}
    private static TriggerSettings__c triggerSettingsObj = TriggerSettings__c.getInstance();
    private static TriggerSettings singletonInstance = null;
    public static TriggerSettings getSettings(){
        if(singletonInstance == null){
            singletonInstance = new TriggerSettings();
        }
        return singletonInstance;
    }
    public Boolean accountTrigger {
        get{
            if (accountTrigger == null){
                accountTrigger = triggerSettingsObj.Account__c;
            }
            return accountTrigger;
        }    
        set;
    }
    public Boolean opportunityTrigger {
        get{
            if (opportunityTrigger == null){
                opportunityTrigger = triggerSettingsObj.Opportunity__c;
            }
            return opportunityTrigger;
        }    
        set;
    }
    public Boolean contactTrigger {
        get{
            if (contactTrigger == null){
                contactTrigger = triggerSettingsObj.Contact__c;
            }
            return contactTrigger;
        }    
        set;
    }
    public Boolean studentProgramTrigger {
        get{
            if (studentProgramTrigger == null){
                studentProgramTrigger = triggerSettingsObj.StudentProgram__c;
            }
            return studentProgramTrigger;
        }    
        set;
    }
    public Boolean attachmentTrigger {
        get{
            if (attachmentTrigger == null){
                attachmentTrigger = triggerSettingsObj.Attachment__c;
            }
            return attachmentTrigger;
        }    
        set;
    }
    public Boolean creditCheckTrigger {
        get{
            if (creditCheckTrigger == null){
                creditCheckTrigger = triggerSettingsObj.CreditCheck__c;
            }
            return creditCheckTrigger;
        }    
        set;
    }
    public Boolean caseTrigger {
        get{
            if (caseTrigger == null){
                caseTrigger = triggerSettingsObj.Case__c;
            }
            return caseTrigger;
        }    
        set;
    }
    public Boolean transactionTrigger {
        get{
            if (transactionTrigger == null){
                transactionTrigger = triggerSettingsObj.Transaction__c;
            }
            return transactionTrigger;
        }    
        set;
    }  
    public Boolean transactionBatchTrigger {
        get{
            if (transactionBatchTrigger == null){
                transactionBatchTrigger = triggerSettingsObj.TransactionBatch__c;
            }
            return transactionBatchTrigger;
        }    
        set;
    }    
    public Boolean programTrigger {
        get{
            if (programTrigger == null){
                programTrigger = triggerSettingsObj.Program__c;
            }
            return programTrigger;
        }    
        set;
    }  
    public Boolean paymentMethodTrigger {
        get{
            if (paymentMethodTrigger == null){
                paymentMethodTrigger = triggerSettingsObj.PaymentMethod__c;
            }
            return paymentMethodTrigger;
        }    
        set;
    }
    public Boolean studentProgramMonthlyStatusTrigger {
        get{
            if (studentProgramMonthlyStatusTrigger == null){
                studentProgramMonthlyStatusTrigger = triggerSettingsObj.StudentProgramMonthlyStatus__c;
            }
            return studentProgramMonthlyStatusTrigger;
        }    
        set;
    }
    public Boolean feeTrigger {
        get{
            if (feeTrigger == null){
                feeTrigger = triggerSettingsObj.Fee__c;
            }
            return feeTrigger;
        }    
        set;
    }
    public Boolean paymentAllocationTrigger {
        get{
            if (paymentAllocationTrigger == null){
                paymentAllocationTrigger = triggerSettingsObj.PaymentAllocation__c;
            }
            return paymentAllocationTrigger;
        }    
        set;
    }
    public Boolean studentProgramAmountDueTrigger {
        get{
            if (studentProgramAmountDueTrigger == null){
                studentProgramAmountDueTrigger = triggerSettingsObj.StudentProgramAmountDue__c;
            }
            return studentProgramAmountDueTrigger;
        }    
        set;
    }
    public Boolean incomeVerificationTrigger {
        get{
            if (incomeVerificationTrigger == null){
                incomeVerificationTrigger = triggerSettingsObj.IncomeVerification__c;
            }
            return incomeVerificationTrigger;
        }    
        set;
    }
    public Boolean paymentInstructionTrigger {
        get{
            if (paymentInstructionTrigger == null){
                paymentInstructionTrigger = triggerSettingsObj.PaymentInstruction__c;
            }
            return paymentInstructionTrigger;
        }    
        set;        
    }
    public Boolean stewardshipACHBatchTrigger {
        get{
            if (stewardshipACHBatchTrigger == null){
                stewardshipACHBatchTrigger = triggerSettingsObj.StewardshipACHBatch__c;
            }
            return stewardshipACHBatchTrigger;
        }    
        set;        
    }
    public Boolean stewardshipACHBatchDetailTrigger {
        get{
            if (stewardshipACHBatchDetailTrigger == null){
                stewardshipACHBatchDetailTrigger = triggerSettingsObj.StewardshipACHBatchDetail__c;
            }
            return stewardshipACHBatchDetailTrigger;
        }    
        set;        
    }
    public Boolean outboundEmailTrigger {
        get{
            if (outboundEmailTrigger == null){
                outboundEmailTrigger = triggerSettingsObj.OutboundEmail__c;
            }
            return outboundEmailTrigger;
        }    
        set;        
    }
    public Boolean secureSettingTrigger {
        get{
            if (secureSettingTrigger == null){
                secureSettingTrigger = triggerSettingsObj.SecureSetting__c;
            }
            return secureSettingTrigger;
        }    
        set;        
    }
    public Boolean genericDocumentTrigger {
        get{
            if (genericDocumentTrigger == null){
                genericDocumentTrigger = triggerSettingsObj.GenericDocument__c;
            }
            return genericDocumentTrigger;
        }    
        set;        
    }
    public Boolean refundTrigger {
        get{
            if (refundTrigger == null){
                refundTrigger = triggerSettingsObj.Refund__c;
            }
            return refundTrigger;
        }    
        set;        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: createDefaultSettings
    /////////////////////////////////////////////////////////////////////////
	public static void createDefaultSettings(){
        if(triggerSettingsObj == null){
            triggerSettingsObj = new TriggerSettings__c();
        }
        Database.insert(triggerSettingsObj, true);           
	}
    public class TriggerSettingsException extends Exception {}
}