vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Represents a funding event in a contract. This is typically a transaction from an investor or school to the school (for tuition) or directly to the student (ex. stipend)</description>
        <label>Disbursement</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/TransactionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/DisbursementService_TEST.cls
@isTest
public class DisbursementService_TEST {
/*	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    @isTest public static void validateGetDisbursementWithDisbursementID(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__C> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, Transaction__c> testDisbursement = TestDataFactory.createAndInsertDisbursements(1, agreements);
    	Test.startTest();
    	List<DisbursementService.Disbursement> dists = DisbursementService.getDisbursementWithDisbursementID(testDisbursement.keySet());
    	System.assertEquals(testDisbursement.size(), dists.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetDisbursementWithAgreementID(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__C> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, Transaction__c> testDisbursement = TestDataFactory.createAndInsertDisbursements(1, agreements);
    	Test.startTest();
    	List<DisbursementService.Disbursement> dists = DisbursementService.getDisbursementWithAgreementID(agreements.keySet());
    	System.assertEquals(testDisbursement.size(), dists.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetDisbursementWithStudentID(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__C> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, Transaction__c> testDisbursement = TestDataFactory.createAndInsertDisbursements(1, agreements);
    	Test.startTest();
    	List<DisbursementService.Disbursement> dists = DisbursementService.getDisbursementWithStudentID(students.keySet());
    	System.assertEquals(testDisbursement.size(), dists.size());
    	Test.stopTest();
    }

    @isTest public static void validateCreateDisbursement(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__c> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	List<DisbursementService.Disbursement> dists = new List<DisbursementService.Disbursement>();
    	for(StudentProgram__c agree : agreements.values()){
    		DisbursementService.Disbursement dis = new DisbursementService.Disbursement(true);
    		dis.studentID = agree.Student__c;
    		dis.agreementID = agree.Id;
    		dists.add(dis);
    	}
    	Test.startTest();
    	Set<ID> disbursementIDs = DisbursementService.createDisbursements(dists);
    	System.assertEquals(dists.size(), disbursementIDs.size());
    	Test.stopTest();
    }

    @isTest public static void validateUpdateDisbursement(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__c> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	List<DisbursementService.Disbursement> dists = new List<DisbursementService.Disbursement>();
    	for(StudentProgram__c agree : agreements.values()){
    		DisbursementService.Disbursement dis = new DisbursementService.Disbursement(true);
    		dis.studentID = agree.Student__c;
    		dis.agreementID = agree.Id;
    		dists.add(dis);
    	}
    	Set<ID> disbursementIDs = DisbursementService.createDisbursements(dists);
    	List<DisbursementService.Disbursement> distsToUpdate = DisbursementService.getDisbursementWithDisbursementID(disbursementIDs);
    	for(DisbursementService.Disbursement dis : distsToUpdate){
    		dis.status = 'Scheduled';
    	}
    	Test.startTest();
    	Set<ID> updatedDists = DisbursementService.updateDisbursements(distsToUpdate);
    	Test.stopTest();
    	Map<ID, Transaction__c> trans = TransactionQueries.getDisbursementMapWithDisbursementID(updatedDists);
    	for(Transaction__c tran : trans.values()){
    		System.assertEquals(tran.Status__c, 'Scheduled');
    	}
    }

    @isTest public static void validateDeleteDisbursements(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__c> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, Transaction__c> testDisbursement = TestDataFactory.createAndInsertDisbursements(1, agreements);
    	Test.startTest();
    	Integer numDis = testDisbursement.size();
    	Integer numDisDeleted = DisbursementService.deleteDisbursements(testDisbursement.keySet());
    	Test.stopTest();
    	System.assertEquals(numDis, numDisDeleted);
    	System.assertEquals(0, TransactionQueries.getDisbursementMap().size());
    }
*/
}