vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/AgreementService_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: AgreementService_TEST
// 
// Description: 
// 	Test class for AgreementService
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-18   Greg Cook       Created                          
/////////////////////////////////////////////////////////////////////////
@isTest
public class AgreementService_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, 
                                                                                    TestDataFactory.createAndInsertSchoolCustomerAccounts(1));
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        for(Account stud : studentMap.values()){
            stud.PrimarySchool__pc = schoolMap.values()[0].id;
        }
        update studentMap.values(); 
    }

    @isTest public static void validateGetAgreementWithAgreementID(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMap();


    	Map<Id, StudentProgram__c> testStudPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE,
                                                                                                  studentMap,
                                                                                                  programMap);
    	Test.startTest();
    	List<AgreementService.Agreement> agreements = AgreementService.getAgreementWithAgreementID(testStudPrgMap.keySet());
    	System.assertEquals(testStudPrgMap.keySet().size(), agreements.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetAgreementWithStudentID(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMap();


        Map<Id, StudentProgram__c> testStudPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE,
                                                                                                  studentMap,
                                                                                                  programMap);
    	Set<ID> studentIDs = new Set<ID>();
    	for(StudentProgram__c studPrg : testStudPrgMap.values()){
    		studentIDs.add(studPrg.Student__c);
    	}
    	Test.startTest();
    	List<AgreementService.Agreement> agreements = AgreementService.getAgreementWithStudentID(studentIDs);
    	System.assertEquals(testStudPrgMap.keySet().size(), agreements.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetAgreementWithSchoolID(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMap();


        Map<Id, StudentProgram__c> testStudPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE,
                                                                                                  studentMap,
                                                                                                  programMap);
    	Set<ID> schoolIDs = new Set<ID>();
    	for(StudentProgram__c studPrg : testStudPrgMap.values()){
    		schoolIDs.add(studPrg.Program__r.School__c);
    	}
    	Test.startTest();
    	List<AgreementService.Agreement> agreements = AgreementService.getAgreementWithSchoolID(schoolIDs);
    	System.assertEquals(testStudPrgMap.keySet().size(), agreements.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetAgreementWithProgramID(){
        Map<ID, Account> studentMap = AccountQueries.getStudentMap();
        Map<ID, Account> schoolMap = AccountQueries.getSchoolMap();
        Map<Id, Program__c> programMap = ProgramQueries.getProgramMap();


        Map<Id, StudentProgram__c> testStudPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE,
                                                                                                  studentMap,
                                                                                                  programMap);
        Set<ID> programIDs = new Set<ID>();
        for(StudentProgram__c studPrg : testStudPrgMap.values()){
            programIDs.add(studPrg.Program__c);
        }
        Test.startTest();
        List<AgreementService.Agreement> agreements = AgreementService.getAgreementWithProgramID(programIDs);
        System.assertEquals(testStudPrgMap.keySet().size(), agreements.size());
        Test.stopTest();
    }

    @isTest public static void validateCreateAgreement(){
    	List<AgreementService.Agreement> agreements = new List<AgreementService.Agreement>();
        Map<ID, Account> students = AccountQueries.getStudentMap();
        Map<ID, Program__c> programs = ProgramQueries.getProgramMap();
        for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
            AgreementService.Agreement agr = new AgreementService.Agreement(true);
            agr.studentID = students.values().get(i).ID;
            agr.programID = programs.values().get(i).ID;
            agreements.add(agr);
        }
        Test.startTest();
        Set<ID> agreementIDs = AgreementService.createAgreement(agreements);
        System.assertEquals(agreements.size(), StudentProgramQueries.getStudentProgramMap().size());
        Test.stopTest();
    }

    @isTest public static void validateUpdateAgreement(){
    	List<AgreementService.Agreement> agreements = new List<AgreementService.Agreement>();
        Map<ID, Account> students = AccountQueries.getStudentMap();
        Map<ID, Program__c> programs = ProgramQueries.getProgramMap();
        for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
            AgreementService.Agreement agr = new AgreementService.Agreement(true);
            agr.studentID = students.values().get(i).ID;
            agr.programID = programs.values().get(i).ID;
            agreements.add(agr);
        }        
        Set<ID> agreementIDs = AgreementService.createAgreement(agreements);
        List<AgreementService.Agreement> agreementAfter = AgreementService.getAgreementWithAgreementID(agreementIDs);
        for(AgreementService.Agreement agr : agreementAfter){
            agr.agreementStatus = 'Application Complete';
        }
        Test.startTest();
        Set<ID> updatedIDs = AgreementService.updateAgreement(agreementAfter);
        Test.stopTest();
        Map<ID, StudentProgram__c> updatedStudProgs = StudentProgramQueries.getStudentProgramMap();
        for(StudentProgram__c studProg : updatedStudProgs.values()){
            System.assertEquals('Application Complete', studProg.Status__c);
        }
    }

    @isTest public static void validateDeleteAgreement(){
    	List<AgreementService.Agreement> agreements = new List<AgreementService.Agreement>();
        Map<ID, Account> students = AccountQueries.getStudentMap();
        Map<ID, Program__c> programs = ProgramQueries.getProgramMap();
        for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
            AgreementService.Agreement agr = new AgreementService.Agreement(true);
            agr.studentID = students.values().get(i).ID;
            agr.programID = programs.values().get(i).ID;
            agreements.add(agr);
        }        
        Set<ID> agreementIDs = AgreementService.createAgreement(agreements);
        System.assertEquals(agreements.size(), StudentProgramQueries.getStudentProgramMap().size());

        Test.startTest();
        Integer deletedNum = AgreementService.deleteAgreement(agreementIDs);
        Test.stopTest();
        System.assertEquals(deletedNum, agreementIDs.size());
        System.assertEquals(0, StudentProgramQueries.getStudentProgramMap().size());
    }
}