vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AgeOfMajorityRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age of Majority Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnrollmentBeginDate__c</fullName>
        <label>Enrollment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentEndDate__c</fullName>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentStatusRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GradeLevelRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegistrationBeginDate__c</fullName>
        <label>Registration Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegistrationEndDate__c</fullName>
        <label>Registration End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ResidencyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residency Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>School Program of Study Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramEligibility__c.object
<CustomObject>
    <label>Program Eligibility</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Program Eligibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Eligibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of Program related to this Student Program.</inlineHelpText>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status in the life-cycle of the Student Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AgreementStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/AgreementStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Application Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Application Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Funded</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>Deferment</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Application Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>School</fullName>
    </customValue>
    <customValue>
        <fullName>Leave of Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Internship</fullName>
    </customValue>
    <customValue>
        <fullName>Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pause</fullName>
    </customValue>
    <customValue>
        <fullName>Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>Application Declined or Ineligible</fullName>
        <isActive>false</isActive>
        <label>Application Declined or Ineligible</label>
    </customValue>
    <customValue>
        <fullName>Cancelled By Student</fullName>
        <isActive>false</isActive>
        <label>Cancelled By Student</label>
    </customValue>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/EnrollmentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Three Quarter Time</fullName>
    </customValue>
    <customValue>
        <fullName>Half Time</fullName>
    </customValue>
    <customValue>
        <fullName>Less than Half Time</fullName>
    </customValue>
    <masterLabel>Enrollment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/GradeLevel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/ProgramStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/Residency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US Citizen/Non-Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Naturalized Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Work Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Student Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Refugee/Asylee</fullName>
    </customValue>
    <masterLabel>Residency</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/OfferService.cls
/////////////////////////////////////////////////////////////////////////
// Class: OfferService
// 
// Description: 
//  Handles all Offer virtual functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-25   Greg Cook       Created                     
/////////////////////////////////////////////////////////////////////////
public with sharing class OfferService {
    public static Map<ID, List<OfferService.Offer>> getOffersByStudentIDWithStudentMap(Map<ID, Account> studentMap){
        System.debug('OfferService.getOffersByStudentIDWithStudentMap');
        Map<ID, List<OfferService.Offer>> offersByStudentID = new Map<ID, List<OfferService.Offer>>();

        //Get the schools for these students
        Set<ID> schoolIDs = new Set<ID>();
        for(Account stud : studentMap.values()){
            schoolIDs.add(stud.PrimarySchool__pc);
        }
        system.debug('schoolIDs:'+schoolIDs);
        system.debug('studentMap:'+studentMap);
        Map<Id, Program__c> programMap = ProgramQueries.getOpenProgramMapWithSchoolID(schoolIDs);
        system.debug('1');
        Map<ID, StudentProgram__c> invitationMap = StudentProgramQueries.getInvitedStudentProgramMapWithStudentID(studentMap.keyset());
        system.debug('2');
        Map<ID, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMapWithStudentID(studentMap.keySet());
        system.debug('3');
        system.debug('programMap:'+programMap);
        system.debug('invitationMap:'+invitationMap);
        system.debug('agreementMap:'+agreementMap);
        
        //Sort the programs by school
        Map<ID, List<Program__c>> programsBySchoolID = new Map<ID, List<Program__c>>();
        if(programMap.size()>0){
            for(Program__c prog : programMap.values()){
                if(!programsBySchoolID.containsKey(prog.School__c)){
                    programsBySchoolID.put(prog.School__c, new List<Program__c>());
                }
                programsBySchoolID.get(prog.School__c).add(prog);
            }
        }
        system.debug('programsBySchoolID:'+programsBySchoolID);
        
        //Sort the invitations by studentID
        Map<ID, List<StudentProgram__c>> invitationsByStudentID = new Map<ID, List<StudentProgram__c>>();
        if(invitationMap.size()>0){
            for(StudentProgram__c agreement : invitationMap.values()){
                if(!invitationsByStudentID.containsKey(agreement.Student__c)){
                    invitationsByStudentID.put(agreement.Student__c, new List<StudentProgram__c>());
                }
                invitationsByStudentID.get(agreement.Student__c).add(agreement);
            }
        }
        system.debug('invitationsByStudentID:'+invitationsByStudentID);

        //Sort the agreements by studentID
        Map<ID, List<StudentProgram__c>> agreementsByStudentID = new Map<ID, List<StudentProgram__c>>();
        if(agreementMap.size()>0){
            for(StudentProgram__c agreement : agreementMap.values()){
                if(!agreementsByStudentID.containsKey(agreement.Student__c)){
                    agreementsByStudentID.put(agreement.Student__c, new List<StudentProgram__c>());
                }
                agreementsByStudentID.get(agreement.Student__c).add(agreement);
            }
        }
        system.debug('agreementsByStudentID:'+agreementsByStudentID);       

        //loop back through students
        for(Account acct : studentMap.values()){
            system.debug('acct:'+acct);
            if(programsBySchoolID.containsKey(acct.PrimarySchool__pc)){
                //return the appropriate list of offers for that students school
                for(Program__c prog : programsBySchoolID.get(acct.PrimarySchool__pc)){
                    //filter out legacy programs
                    //changing to registration date range
//                  if(prog.EnrollmentEndDate__c >= Date.today()){
                    if(prog.RegistrationBeginDate__c <= Date.today() && prog.RegistrationEndDate__c >= Date.today()){
                            

                        system.debug('prog:'+prog);
                        Boolean foundExistingProgram = false;
                        //Loop through the student's existing agreements and make sure they don't already have one for this programID
                        /*as per Jira 886 Don't Assume and Don't filter out
                        if(agreementsByStudentID.containsKey(acct.id)){
                            system.debug('1');
                            for(StudentProgram__c agreement : agreementsByStudentID.get(acct.id)){
                                system.debug('agreement:'+agreement);
                                if(agreement.Program__c == prog.id){
                                    foundExistingProgram = true;
                                    continue; //break out of the for loop
                                }
                            }                   
                        }
                        */

                        if(!foundExistingProgram){
                            if(!offersByStudentID.containsKey(acct.id)){
                                offersByStudentID.put(acct.id, new List<Offer>());
                            }

                            Offer off = new Offer(prog, null);
                            off.studentID = acct.id;
                            offersByStudentID.get(acct.id).add(off);                        
                        }
                    }
                }
            }
            if(invitationsByStudentID.containsKey(acct.id)){
                //return the appropriate list of invitations for that student
                for(StudentProgram__c agreement : invitationsByStudentID.get(acct.id)){
                    //filter out legacy enrollments
                    if(agreement.Program__r.EnrollmentEndDate__c >= Date.today()){
                        if(!offersByStudentID.containsKey(acct.id)){
                            offersByStudentID.put(acct.id, new List<Offer>());
                        }
                        Offer off = new Offer(null, agreement);
                        offersByStudentID.get(acct.id).add(off);
                    }
                }               
            }
        }
        system.debug('offersByStudentID:'+offersByStudentID);

        return offersByStudentID;
    }
    
    //method to get offers after checking the eligibilty for the school initited flow for a particular school
    public static Map<ID,Offer> getEligibleOffersByProgramIDWithCriteria(ID schoolID,String residency,
                         String enrollmentStatus, String gradeLevel,
                         ID schoolProgramOfStudyID, String state, Date birthdate){
        
        Map<ID,Offer> output = new Map<ID,Offer>();
        
        /* Was using this while getting for a existing student
        
        List<StudentService.Student> students = StudentService.getStudentsWithStudentID(new Set<ID>{studentID});
        StudentService.Student student = null;
        
        if(students.size() == 1) student = students[0];
        else return null; //no student found. Cannot proceed!!! 
                
        if(student.primarySchoolID <> null) DatabaseUtil.schoolID = student.primarySchoolID;    
        else return null; // no school found on student. cannot proceed!!!
        */
        
        if(schoolID <> null){
            DatabaseUtil.schoolID = schoolID;
                    
            //get all programs for the required School whose enrollmentStatus = "invite only" and status = "open"
            Map<ID, Program__c> inviteOnlyPrgMap = ProgramQueries.getInviteOnlyProgramMapWithSchoolID(new Set<ID>{schoolID});
            
            //filter the inviteOnlyPrgMap after checking registration end date
            if(inviteOnlyPrgMap <> null && inviteOnlyPrgMap.size()>0){
                List<Program__c> tempList = inviteOnlyPrgMap.values(); 
                inviteOnlyPrgMap = new Map<ID, Program__c>();
                for(Program__c prg:tempList){
                    if(prg.RegistrationEndDate__c >= Date.today()) inviteOnlyPrgMap.put(prg.id,prg);
                }
            }
            
            //get all eligibilityRecords for the required school
            Map<ID, ProgramEligibility__c> prgprgEligibilityMap = ProgramEligibilityQueries.getProgramEligibilityMap();
            Program__c program = null;
             
            for(ProgramEligibility__c prgEligibility: prgprgEligibilityMap.values()){
                
                //check eligibilty only for programs contained in inviteOnlyPrgMap
                
                if(inviteOnlyPrgMap.containsKey(prgEligibility.program__c)){
                    program = inviteOnlyPrgMap.get(prgEligibility.program__c);
                    if(program.ResidencyRequired__c){
                        if(prgEligibility.Residency__c == null || residency == null) continue;
                        if(!prgEligibility.Residency__c.contains(residency)) continue; 
                    }
                    if(program.EnrollmentStatusRequired__c){
                        if(prgEligibility.EnrollmentStatus__c == null || enrollmentStatus == null) continue;
                        if(!prgEligibility.EnrollmentStatus__c.contains(enrollmentStatus)) continue;
                    }
                    if(program.GradeLevelRequired__c){
                        if(prgEligibility.GradeLevel__c == null || gradeLevel == null) continue;
                        if(!prgEligibility.GradeLevel__c.contains(gradeLevel)) continue;
                    }
                    if(program.SchoolProgramOfStudyRequired__c){
                        if(prgEligibility.SchoolProgramOfStudy__c == null || schoolProgramOfStudyID == null) continue;
                        if(prgEligibility.SchoolProgramOfStudy__c <> schoolProgramOfStudyID) continue;
                    }
                    if(program.AgeOfMajorityRequired__c){
                        if(birthdate == null || state == null) continue;
                        
                        // Calc age from birthdate
                        Integer ageTotalDays = birthdate.daysBetween(system.today());
                        Integer studentAge = (Integer)(math.Floor(ageTotalDays / 365.2425));
                        
                        if(ProgramEligibilityQueries.determineAgeOfMajority(state) > studentAge) {
                          continue;
                        }      
                    } 
                    
                    if(!output.containsKey(prgEligibility.program__c)){
                        output.put(prgEligibility.program__c,new Offer(inviteOnlyPrgMap.get(prgEligibility.program__c),null));        
                    }
                }
            }
        }
        return output;                                                                            
    } 

    public class Offer{
        public String programID {get;set;}
        public String programName {get;set;}
        public String schoolID {get;set;}
        public String programStatus {get;set;}
        public String agreementStatus {get;set;}
        public String agreementID {get;set;}
        public String studentID {get;set;}
        public Date enrollmentBeginDate {get;set;}
        public Date enrollmentEndDate {get;set;}
        public Date registrationBeginDate {get;set;}
        public Date registrationEndDate {get;set;}

        public Offer(){

        }

        public Offer(Boolean testValues){
            if(testValues){
                //to do
                //this.programName = 'testProgramName';
                //this.programStatus = 'Open'; //Planned, Closed, Cancelled
            }
        }

        public Offer(Program__c prog, StudentProgram__c agreement){
            //system.debug('OfferService.Offer(prog, agreement)');
            //system.debug('prog:'+prog);
            //system.debug('agreement:'+agreement);
            if(prog != null){
                this.programID = prog.Id;   
                this.programName = prog.ProgramName__c;     
                this.schoolID = prog.School__c;
                this.programStatus = prog.ProgramStatus__c;
                this.enrollmentEndDate = prog.EnrollmentEndDate__c;
                this.enrollmentBeginDate = prog.EnrollmentBeginDate__c;
                this.registrationBeginDate = prog.RegistrationBeginDate__c;
                this.registrationEndDate = prog.RegistrationEndDate__c;
            } else if (agreement != null){
                this.agreementStatus = agreement.Status__c;
                this.studentID = agreement.Student__c;
                this.programID = agreement.Program__c;
                this.programName = agreement.Program__r.ProgramName__c;
                this.programStatus = agreement.Program__r.ProgramStatus__c;
                this.schoolID = agreement.Program__r.School__c;
                this.agreementID = agreement.ID;
                this.enrollmentEndDate = agreement.Program__r.EnrollmentEndDate__c;
                this.enrollmentBeginDate = agreement.Program__r.EnrollmentBeginDate__c;
                this.registrationBeginDate = agreement.Program__r.RegistrationBeginDate__c;
                this.registrationEndDate = agreement.Program__r.RegistrationEndDate__c;
            }
        }
    }
}