vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentType__c</fullName>
        <description>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</description>
        <inlineHelpText>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</inlineHelpText>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Invite Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/ProgramStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/ProgramQueries_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: ProgramQueries_TEST
// 
// Description: 
//      Test class for ProgramQueries
//
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-18   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class ProgramQueries_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
    @isTest public static void validateGetProgram(){
        Map<Id, Account> schools = TestDAtaFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Program__c> prgMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schools);
        Test.startTest();
        Map<Id, Program__c> resultPrgMap = ProgramQueries.getProgramMapWithProgramID(prgMap.keySet());
        System.assertEquals(prgMap.keySet().size(), resultPrgMap.keySet().size());
        Test.stopTest();
    }
    
    @isTest public static void validateGetProgramMapForSchool(){
        Map<Id, Account> schools = TestDAtaFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Program__c> prgMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schools);
        Test.startTest();
        Set<Id> schoolIDs  = new Set<ID>();
        for(Program__c prog : prgMap.values()){
            schoolIDs.add(prog.School__c);
        }
        Map<Id,Program__c> prgMapResult = ProgramQueries.getProgramMapWithSchoolID(schoolIDs);
        System.assertEquals(prgMap.keySet().size(), prgMapResult.keySet().size());
        Test.stopTest();
    }

    @isTest public static void validateGetProgramMapById(){
        Map<Id, Account> schools = TestDAtaFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Program__c> prgMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schools);
        Test.startTest();
        Map<Id,Program__c> prgMapResult = ProgramQueries.getProgramMap();
        System.assertEquals(prgMap.keySet().size(), prgMapResult.keySet().size());
        Test.stopTest();
    }
    
    @isTest public static void validateGetInviteOnlyAndOpenProgramMap(){
        Map<Id, Account> schools = TestDAtaFactory.createAndInsertSchoolCustomerAccounts(2);
        Map<Id, Program__c> prgMap = TestDataFactory.createAndInsertPrograms(5, schools);
        Test.startTest();
            integer cnt = 0;
            for(Program__c prg:prgMap.values()){
                prg.ProgramStatus__c = 'Open';
                prg.EnrollmentType__c = 'Open';
                if(cnt < 5){
                    prg.EnrollmentType__c = 'Invite Only';
                    prg.ProgramStatus__c = 'Open';
                    cnt++;
                }                        
            }
            update prgMap.values();
            Map<ID, Program__c> inviteOnlyResultMap = ProgramQueries.getInviteOnlyProgramMapWithSchoolID(schools.keySet());
            Map<ID, Program__c> openResultMap = ProgramQueries.getOpenProgramMapWithSchoolID(schools.keySet());
            System.assertEquals(5,inviteOnlyResultMap.size());
            System.assertEquals(5,openResultMap.size());
        Test.StopTest();     
    }
    
    
}