vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Fee</fullName>
        <active>false</active>
        <description>Represents a payment from school or investor to Vemo</description>
        <label>Fee</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/classes/VemoAPILedgerResource_TEST.cls
@isTest
public class VemoAPILedgerResource_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testHandleGetV1(){
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<Id, StudentProgram__c> studProgramMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, students, programs);
        Map<Id, Transaction__c> transactions = TestDataFactory.createAndInsertTransactions(TestUtil.TEST_THROTTLE,studProgramMap, TransactionService.disbursementRecType);
        //Map<Id, Transaction__c> transactions1 = TestDataFactory.createAndInsertTransactions(TestUtil.TEST_THROTTLE,studProgramMap, 'FEE');
      
        Map<String, String> ledgerParams = new Map<String, String>();
        
        ledgerParams.put('customerID', (String)schools.values().get(0).id);
        VemoAPI.APIInfo ledgerApiInfo = TestUtil.initializeAPI('v1', 'GET', ledgerParams, null);
        
        Test.startTest();
        
        VemoAPI.ResultResponse ledgerResult = (VemoAPI.ResultResponse)VemoAPILedgerResource.handleAPI(ledgerApiInfo);
        //System.assertEquals(1, ledgerResult.numberOfResults);
        
        Test.stopTest();
    }
}