vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>AmountDueToDate__c</fullName>
        <inlineHelpText>The total amount billed so far for this Student Program.</inlineHelpText>
        <label>Amount Due To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyAmountDueToDate__c</fullName>
        <inlineHelpText>This field contains the total sum of any monthly amount ever created against this Student Program.</inlineHelpText>
        <label>Monthly Amount Due to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ReconciliationDueToDate__c</fullName>
        <inlineHelpText>This field contains the total sum of any reconciliation ever created against this Student Program.</inlineHelpText>
        <label>Reconciliation Due to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Monthly Status.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Monthly Status</relationshipLabel>
        <relationshipName>Student_Program_Monthly_Status</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/StudProgAmountDueTriggerHandler_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: StudProgAmountDueTriggerHandler_TEST
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-04   Jared Hagemann  Created                              
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class StudProgAmountDueTriggerHandler_TEST {

	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<Id, StudentProgram__c> agreementMap = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<Id, StudentProgramMonthlyStatus__c> agreementMonthStats = TestDataFactory.createAndInsertStudentProgramMonthlyStatus(5, agreementMap);
    }


	static testMethod void testManageAgreementsInsert(){
		TestUtil.setStandardConfiguration();
		Map<Id, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
		Map<Id, StudentProgramMonthlyStatus__c> agreementMonthStats =new Map<Id, StudentProgramMonthlyStatus__c>([select Id, Agreement__c from StudentProgramMonthlyStatus__c]);
    	Test.startTest();
    	Map<Id, StudentProgramAmountDue__c> agreementAmountDue = TestDataFactory.createAndInsertStudentProgramAmountDue(agreementMap, agreementMonthStats);
    	Test.stopTest();

    	List<StudentProgram__c> resultAgreements = [select Id, AmountDueToDate__c, ReconciliationDueToDate__c, MonthlyAmountDueToDate__c from StudentProgram__c where Id in: agreementMap.keySet() and AmountDueToDate__c > 0];
    	System.assert(!resultAgreements.isEmpty());
    	
    	for(StudentProgram__c agreement : resultAgreements){
    		System.assertEquals(5000 ,agreement.AmountDueToDate__c);
    	}   
    	
	}

	static testMethod void testManageAgreementsUpdate(){
		TestUtil.setStandardConfiguration();
		Map<Id, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
		Map<Id, StudentProgramMonthlyStatus__c> agreementMonthStats =new Map<Id, StudentProgramMonthlyStatus__c>([select Id, Agreement__c from StudentProgramMonthlyStatus__c]);
    	Map<Id, StudentProgramAmountDue__c> agreementAmountDue = TestDataFactory.createAndInsertStudentProgramAmountDue(agreementMap, agreementMonthStats);
    	for(StudentProgramAmountDue__c spad : agreementAmountDue.values()){
    		spad.Amount__c = 500;
    	}
    	Test.startTest();
    		update agreementAmountDue.values();
    	Test.stopTest();

    	List<StudentProgram__c> resultAgreements = [select Id, AmountDueToDate__c, ReconciliationDueToDate__c, MonthlyAmountDueToDate__c from StudentProgram__c where Id in: agreementMap.keySet() and AmountDueToDate__c > 0];
    	System.assert(!resultAgreements.isEmpty());
    	
    	for(StudentProgram__c agreement : resultAgreements){
    		System.assertEquals(2500 ,agreement.AmountDueToDate__c);
    	}   
    	
	}

	static testMethod void testManageAgreementsDelete(){
		TestUtil.setStandardConfiguration();
		Map<Id, StudentProgram__c> agreementMap = StudentProgramQueries.getStudentProgramMap();
		Map<Id, StudentProgramMonthlyStatus__c> agreementMonthStats =new Map<Id, StudentProgramMonthlyStatus__c>([select Id, Agreement__c from StudentProgramMonthlyStatus__c]);
    	Map<Id, StudentProgramAmountDue__c> agreementAmountDue = TestDataFactory.createAndInsertStudentProgramAmountDue(agreementMap, agreementMonthStats);
    	
    	Test.startTest();
    		delete agreementAmountDue.values();
    	Test.stopTest();

    	List<StudentProgram__c> resultAgreements = [select Id, AmountDueToDate__c, ReconciliationDueToDate__c, MonthlyAmountDueToDate__c from StudentProgram__c where Id in: agreementMap.keySet() and AmountDueToDate__c > 0];
    	System.assert(resultAgreements.isEmpty());     	
	}
}