vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/VemoAPIStatementResource_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: VemoAPIStatementResource_TEST
// 
// Description: 
// 	Test class for VemoAPIStatementResource
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-06-10   Jared Hagemann  Created                              
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class VemoAPIStatementResource_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testHandleGetV1(){
		Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<Id, StudentProgram__c> studProgramMap = TestDataFactory.createAndInsertStudentProgram(1, students, programs);

		Map<String, String> studIDParams = new Map<String, String>();
		studIDParams.put('VEMO_AUTH', 'ABC');
		studIDParams.put('studentID', TestUtil.createStringFromIDSet(students.keySet()));
		VemoAPI.APIInfo studIDApiInfo = TestUtil.initializeAPI('v1', 'GET', studIDParams, null);
		
		Test.startTest();
		VemoAPI.ResultResponse idResult = (VemoAPI.ResultResponse)VemoAPIStatementResource.handleAPI(studIDApiInfo);
		System.assertEquals(TestUtil.TEST_THROTTLE, idResult.numberOfResults);
		Test.stopTest();
	}
}