vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/TransactionSchedule__c.object
<CustomObject>
    <label>Disbursement Schedule</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FundingAmount__c</fullName>
        <label>Funding Amount %</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Transaction_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SpecialDisbursementType__c</fullName>
        <label>Special Disbursement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/DisbursementSpecialTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/TransactionScheduleService.cls
public with sharing class TransactionScheduleService{
    
    public static List<transactionSchedule> gettransactionScheduleswithProgramID(set<ID> programIDs){
         System.debug('TransactionScheduleService.gettransactionScheduleswithProgramID');
         Map<Id, transactionSchedule__c> transactionScheduleMap = TransactionScheduleQueries.getTransactionScheduleMapWithProgramID(programIDs);
         List<transactionSchedule> transactionSchedules = new List<transactionSchedule>();
         for(transactionSchedule__c txSch : transactionScheduleMap.values()){
             transactionSchedules.add(new transactionSchedule(txSch));
         }
         return transactionSchedules;
    }
    
     public static Map<ID,List<transactionSchedule>> gettransactionSchedulesByProgramIDWithProgramID(Set<ID> programIDs){
        System.debug('TransactionScheduleService.gettransactionSchedulesByProgramIDWithProgramID');
        List<transactionSchedule> transactionSchedules = TransactionScheduleService.gettransactionScheduleswithProgramID(programIDs); 
        Map<Id, List<transactionSchedule>> transactionScheduleMap = new Map<Id, List<transactionSchedule>>();
        for(transactionSchedule txsch:transactionSchedules){
             if(!transactionScheduleMap.containsKey(txsch.ProgramId)){
                transactionScheduleMap.put(txsch.ProgramId, new List<transactionSchedule>());  
             } 
             transactionScheduleMap.get(txsch.ProgramId).add(txsch);  
        }
        return transactionScheduleMap;
     }
    
    public class TransactionSchedule{
        public String transactionScheduleID {get;set;}
        public Decimal Amount {get;set;}
        public Decimal FundingAmount {get;set;} 
        public String ProgramID {get;set;}
        public Date ScheduledDate {get;set;}
        public String SpecialDisbursementType {get;set;}
        
        public transactionSchedule(){}
        
        public transactionSchedule(TransactionSchedule__c transSch){
            this.transactionScheduleID = transSch.id;
            this.Amount = transSch.Amount__c;
            this.FundingAmount = transSch.FundingAmount__c;
            this.ProgramID = transSch.Program__c;
            this.ScheduledDate =  transSch.ScheduledDate__c;
            this.SpecialDisbursementType = transSch.SpecialDisbursementType__c;
        }
    }
}