vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>GenerateFinalDisclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Manually check this box to re-generate the Final Disclosure.</inlineHelpText>
        <label>Generate Final Disclosure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/GenerateFinalDisclosureBatch_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: GenerateFinalDisclosureBatch_TEST
// 
// Description: 
//  Unit test for GenerateFinalDisclosureBatch
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-25   Jared Hagemann  Created 
/////////////////////////////////////////////////////////////////////////
@isTest
public class GenerateFinalDisclosureBatch_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testStart(){
    	Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<Id, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<Id, StudentProgram__c> studentPrograms = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	for(StudentProgram__c sp : studentPrograms.values()){
    		sp.GenerateFinalDisclosure__c = true;
    	}
    	update studentPrograms.values();
    	Test.startTest();
    	GenerateFinalDisclosureBatch gfdb = new GenerateFinalDisclosureBatch();
    	Database.executeBatch(gfdb, 200);
    	Test.stopTest();
    }
}