vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/SchoolProgramsOfStudyQueries_TEST.cls
@isTest
public with sharing class SchoolProgramsOfStudyQueries_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    @isTest public static void validateGetSchoolProgramOfStudyMap(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
    	Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(TestUtil.TEST_THROTTLE);
    	Map<ID, SchoolProgramsOfStudy__c> testSPOSMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schools, posMap);
    	Test.startTest();
    	Map<ID, SchoolProgramsOfStudy__c> resultSPOSMap = SchoolProgramsOfStudyQueries.getSchoolProgramOfStudyMap();
    	System.assertEquals(testSPOSMap.size(), resultSPOSMap.size());
    	Test.stopTest();
    }

    @isTest public static void getSchoolProgramOfStudyMapWithSPOSID(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
    	Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(TestUtil.TEST_THROTTLE);
    	Map<ID, SchoolProgramsOfStudy__c> testSPOSMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schools, posMap);
    	Test.startTest();
    	Map<ID, SchoolProgramsOfStudy__c> resultSPOSMap = SchoolProgramsOfStudyQueries.getSchoolProgramOfStudyMapWithSPOSID(testSPOSMap.keySet());
    	System.assertEquals(testSPOSMap.size(), resultSPOSMap.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetSchoolProgramOfStudyMapWithPOSID(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
    	Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(TestUtil.TEST_THROTTLE);
    	Map<ID, SchoolProgramsOfStudy__c> testSPOSMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schools, posMap);
    	Test.startTest();
    	Map<ID, SchoolProgramsOfStudy__c> resultSPOSMap = SchoolProgramsOfStudyQueries.getSchoolProgramOfStudyMapWithPOSID(posMap.keySet());
    	System.assertEquals(testSPOSMap.size(), resultSPOSMap.size());
    	Test.stopTest();
    }

    @isTest public static void validateGetSchoolProgramOfStudyMapWithSchoolID(){
    	Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
    	Map<ID, ProgramOfStudy__c> posMap = TestDataFactory.createAndInsertProgramOfStudy(TestUtil.TEST_THROTTLE);
    	Map<ID, SchoolProgramsOfStudy__c> testSPOSMap = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schools, posMap);
    	Test.startTest();
    	Map<ID, SchoolProgramsOfStudy__c> resultSPOSMap = SchoolProgramsOfStudyQueries.getSchoolProgramOfStudyMapWithSchoolID(schools.keySet());
    	System.assertEquals(testSPOSMap.size(), resultSPOSMap.size());
    	Test.stopTest();
    }
}