vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/classes/StudentProgramQueries_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: StudentProgramQueries_TEST
// 
// Description: 
//      Test class for StudentProgramQueries
//
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-24   Greg Cook       Created                                 
// 
/////////////////////////////////////////////////////////////////////////
@isTest
public class StudentProgramQueries_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, students, programs);
    }
    @isTest public static void validateGetStudentProgramMap(){
        /*
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, students, programs);
        */
        Test.startTest();
        Map<Id, StudentProgram__c> resultStudentPrgMap = StudentProgramQueries.getStudentProgramMap();
        //System.assertEquals(studentPrgMap.keySet().size(), resultStudentPrgMap.keySet().size());
        Test.stopTest();
    }

    @isTest public static void validateGetStudentProgramMapWithAgreementID(){
        /*
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, students, programs);
        */
        Map<Id, StudentProgram__c> studentPrgMap = StudentProgramQueries.getStudentProgramMap();
        Set<ID> agreementIDs = new Set<ID>();
        for(StudentProgram__c studPrg : studentPrgMap.values()){
            agreementIDs.add(studPrg.ID);
        }
        Test.startTest();
        Map<Id, StudentProgram__c> resultStudentPrgMap = StudentProgramQueries.getStudentProgramMapWithAgreementID(agreementIDs);
        System.assertEquals(studentPrgMap.keySet().size(), resultStudentPrgMap.keySet().size());
        Test.stopTest();
    }

    @isTest public static void validateGetStudentProgramMapWithStudentID(){
        /*
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, students, programs);
        */
        Map<Id, StudentProgram__c> studentPrgMap = StudentProgramQueries.getStudentProgramMap();
        Set<ID> studentIDs = new Set<ID>();
        for(StudentProgram__c studPrg : studentPrgMap.values()){
            studentIDs.add(studPrg.Student__c);
        }
        Test.startTest();
        Map<Id, StudentProgram__c> resultStudentPrgMap = StudentProgramQueries.getStudentProgramMapWithStudentID(studentIDs);
        System.assertEquals(studentPrgMap.keySet().size(), resultStudentPrgMap.keySet().size());
        Test.stopTest();
    }

    @isTest public static void validateGetStudentProgramMapWithSchoolID(){
        /*
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(TestUtil.TEST_THROTTLE, students, programs);
        */
        Map<Id, StudentProgram__c> studentPrgMap = StudentProgramQueries.getStudentProgramMap();
        Set<ID> schoolIDs = new Set<ID>();
        for(StudentProgram__c studPrg : studentPrgMap.values()){
            schoolIDs.add(studPrg.Program__r.School__c);
        }
        Test.startTest();
        Map<Id, StudentProgram__c> resultStudentPrgMap = StudentProgramQueries.getStudentProgramMapWithSchoolID(schoolIDs);
        System.assertEquals(studentPrgMap.keySet().size(), resultStudentPrgMap.keySet().size());
        Test.stopTest();
    }
}