vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/TransactionSchedule__c.object
<CustomObject>
    <label>Disbursement Schedule</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FundingAmount__c</fullName>
        <label>Funding Amount %</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Transaction_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SpecialDisbursementType__c</fullName>
        <label>Special Disbursement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DisbursementSpecialTypes</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/DisbursementSpecialTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <masterLabel>Disbursement Special Types</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/TransactionScheduleQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: TransactionScheduleQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION----------------------------- 
// 2016-12-23   Greg Cook       Created   
/////////////////////////////////////////////////////////////////////////
public class TransactionScheduleQueries {
    public static Map<ID, TransactionSchedule__c> getTransactionScheduleMap(){
        Map<ID, TransactionSchedule__c> txSchMap = new Map<ID, TransactionSchedule__c>();
        String query = generateSOQLSelect();

        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' Where Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' Order By ScheduledDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        txSchMap = new Map<ID, TransactionSchedule__c>((List<TransactionSchedule__c>)db.query(query));
        return txSchMap;    
    }

    public static Map<ID, TransactionSchedule__c> getTransactionScheduleMapWithProgramID(Set<ID> programIDs){
        Map<ID, TransactionSchedule__c> txSchMap = new Map<ID, TransactionSchedule__c>();
        String query = generateSOQLSelect();
        query += ' WHERE Program__c IN ' + DatabaseUtil.inSetStringBuilder(programIDs);

        if(DatabaseUtil.filterBySchoolID){
            ID schoolID = DatabaseUtil.schoolID;
            query += ' and Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
        }
        query += ' Order By ScheduledDate__c asc';
        query += ' '+ generateLIMITStatement();
        DatabaseUtil db = new DatabaseUtil();
        txSchMap = new Map<ID, TransactionSchedule__c>((List<TransactionSchedule__c>)db.query(query));
        return txSchMap;
    }

    public static Map<ID, List<TransactionSchedule__c>> getTransactionSchedulesByProgramIDWithProgramID(Set<ID> programIDs){
        Map<ID, TransactionSchedule__c> txSchMap = getTransactionScheduleMapWithProgramID(programIDs);
        Map<ID, List<TransactionSchedule__c>> txSchByProgramID = new Map<ID, List<TransactionSchedule__c>>();

        for(TransactionSchedule__c txSch : txSchMap.values()){
            if(!txSchByProgramID.containsKey(txSch.Program__c)){
                txSchByProgramID.put(txSch.Program__c, new List<TransactionSchedule__c>());
            }
            txSchByProgramID.get(txSch.Program__c).add(txSch);
        }

        return txSchByProgramID;
    }

    private static String generateSOQLSelect(){
        String soql;
        soql = 'SELECT ' + getfieldNames() + ' FROM TransactionSchedule__c';
        system.debug(soql);
        return soql;
    }

    private static String getfieldNames(){
        String fieldNames;
        fieldNames = 'id, ';
        fieldNames += 'Name, ';
        fieldNames += 'Amount__c, ';
        fieldNames += 'FundingAmount__c, ';
        fieldNames += 'Program__c, ';
        fieldNames += 'ScheduledDate__c, ';
        fieldNames += 'SpecialDisbursementType__c ';

        return fieldNames;
    }
    
    private static String generateLIMITStatement(){
        String lim = 'LIMIT 50000';
        return lim;
    }
}