vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentStatusRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment Status Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GradeLevelRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Level Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResidencyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residency Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudyRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>School Program of Study Required</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramEligibility__c.object
<CustomObject>
    <label>Program Eligibility</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Program Eligibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Eligibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentStatus__c</fullName>
        <label>Enrollment Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GradeLevel__c</fullName>
        <label>Grade Level</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GradeLevel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SchoolProgramOfStudy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Program of Study</label>
        <referenceTo>SchoolProgramsOfStudy__c</referenceTo>
        <relationshipLabel>Program Eligibility</relationshipLabel>
        <relationshipName>Program_Eligibility</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/EnrollmentStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Three Quarter Time</fullName>
    </customValue>
    <customValue>
        <fullName>Half Time</fullName>
    </customValue>
    <customValue>
        <fullName>Less than Half Time</fullName>
    </customValue>
    <masterLabel>Enrollment Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/GradeLevel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Sophomore</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Year Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Grade Level</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/globalValueSets/Residency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US Citizen/Non-Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Naturalized Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Work Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Immigrant with a US Student Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Refugee/Asylee</fullName>
    </customValue>
    <masterLabel>Residency</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/VemoAPIProgramEligibilityResource_TEST.cls
////////////////////////////////////////////////////////////////////////
// Class: VemoAPIProgramEligibilityResource_TEST
// 
// Description: 
//  Unit test for VemoAPIProgramEligibilityResource
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-05-12   Jared Hagemann  Created
/////////////////////////////////////////////////////////////////////////
@isTest
public class VemoAPIProgramEligibilityResource_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    @isTest static void testHandleGetV1(){
        Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<Id, Account> schools = TestDAtaFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, ProgramOfStudy__c> prgOfStudyMap = TestDataFactory.createAndInsertProgramOfStudy(TestUtil.TEST_THROTTLE);
        Map<Id, Program__c> testProgMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schools);
        Map<ID, ProgramEligibility__c> testProgEligMap = TestDataFactory.createAndInsertProgramEligibility(1, testProgMap);
        Map<ID, SchoolProgramsOfStudy__c> schlPrgOfStudy = TestDataFactory.createAndInsertSchoolProgramsOfStudy(schools, prgOfStudyMap);

        for(Program__c prg : testProgMap.values()){
            prg.ResidencyRequired__c = true;
            prg.EnrollmentStatusRequired__c = true;
            prg.GradeLevelRequired__c = true;
            prg.SchoolProgramOfStudyRequired__c = true;
        }
        for(ProgramEligibility__c prgEli : testProgEligMap.values()){
            prgEli.Residency__c = 'US Citizen';//Permanent Resident, Non-US Citizen
            prgEli.EnrollmentStatus__c = 'Full Time';//Three Quarter Time,  Half Time, Less than Half Time
            prgEli.GradeLevel__c = 'Freshman';//Sophomore, Junior, Senior, Fifth Year Senior, Other
            prgEli.SchoolProgramOfStudy__c = schlPrgOfStudy.values().get(0).Id;
        }
        for(Account stud : studentMap.values()){
            stud.Residency__pc = 'US Citizen';//Permanent Resident, Non-US Citizen
            stud.PrimarySchoolEnrollmentStatus__pc = 'Full Time';//Three Quarter Time,  Half Time, Less than Half Time
            stud.PrimarySchoolGradeLevel__pc = 'Freshman';//Sophomore, Junior, Senior, Fifth Year Senior, Other
            stud.SchoolProgramOfStudy__pc = schlPrgOfStudy.values().get(0).Id;
        }

        Map<String, String> params = new Map<String, String>();
        params.put('programID', (String)testProgMap.values().get(0).Id);
        params.put('VEMO_AUTH', 'testStudent_'+studentMap.values()[0].AuthSystemUserID__pc);
        VemoAPI.APIInfo apiInfo = TestUtil.initializeAPI('v1', 'GET', params, null);
        apiInfo.studentPersonAccountID = studentMap.values()[0].Id;
        
        Map<String, String> paramsWithAge = new Map<String, String>();
        paramsWithAge.put('programID', (String)testProgMap.values().get(0).Id);
        paramsWithAge.put('VEMO_AUTH', 'testStudent_'+studentMap.values()[0].AuthSystemUserID__pc);
        paramsWithAge.put('age', '24');
        VemoAPI.APIInfo apiInfoWithAge = TestUtil.initializeAPI('v1', 'GET', paramsWithAge, null);
        apiInfoWithAge.studentPersonAccountID = studentMap.values()[0].Id;

        Test.startTest();
        VemoAPI.ResultResponse results = (VemoAPI.ResultResponse)VemoAPIProgramEligibilityResource.handleAPI(apiInfo);
        VemoAPI.ResultResponse results1 = (VemoAPI.ResultResponse)VemoAPIProgramEligibilityResource.handleAPI(apiInfoWithAge );
        System.assertEquals(1, results.numberOfResults);
        Test.stopTest();
    }
}