vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated to a school</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Refund__c.object
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000000000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Student related to this Student Program.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be associated with a student</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExcludeFromBalance__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates that an amount due should not be included in the account statement summaries. Used primarily for reconciliation amounts that are pre-assessed for future months, but which should not actually show up on the statement/bill until that month arrives</inlineHelpText>
        <label>Exclude from Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Amount_Due</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RemainingAllocation__c</fullName>
        <formula>Amount__c - AmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Monthly Status.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Monthly Status</relationshipLabel>
        <relationshipName>Student_Program_Monthly_Status</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/DebitType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/StudProgAmountDueQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: StudProgAmountDueQueries
// 
// Description: 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION----------------------------- 
// 2016-12-23	Greg Cook 		Created
/////////////////////////////////////////////////////////////////////////
public class StudProgAmountDueQueries {
	public static Map<ID, StudentProgramAmountDue__c> getAmountDueMap(){
		Map<ID, StudentProgramAmountDue__c> studPrgMap = new Map<ID, StudentProgramAmountDue__c>();
		String query = generateSOQLSelect();
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' WHERE Agreement__r.Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
			if(DatabaseUtil.filterBySchoolID){
				ID schoolID = DatabaseUtil.schoolID;
				query += ' and Agreement__r.Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
			}
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		studPrgMap = new Map<ID, StudentProgramAmountDue__c>((List<StudentProgramAmountDue__c>)db.query(query));
		return studPrgMap;	
	}

	public static Map<ID, StudentProgramAmountDue__c> getAmountDueMapWithAgreementID(Set<ID> agreementIDs){
		Map<ID, StudentProgramAmountDue__c> studPrgMap = new Map<ID, StudentProgramAmountDue__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Agreement__c IN ' + DatabaseUtil.inSetStringBuilder(agreementIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Agreement__r.Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
			if(DatabaseUtil.filterBySchoolID){
				ID schoolID = DatabaseUtil.schoolID;
				query += ' and Agreement__r.Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
			}
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		studPrgMap = new Map<ID, StudentProgramAmountDue__c>((List<StudentProgramAmountDue__c>)db.query(query));
		return studPrgMap;	
	}

	public static Map<ID, StudentProgramAmountDue__c> getAmountDueMapWithStudentID(Set<ID> studentIDs){
		Map<ID, StudentProgramAmountDue__c> studPrgMap = new Map<ID, StudentProgramAmountDue__c>();
		String query = generateSOQLSelect();
		query += ' WHERE Agreement__r.Student__c IN ' + DatabaseUtil.inSetStringBuilder(studentIDs);
		if(DatabaseUtil.filterByStudentID){
			ID studentID = DatabaseUtil.studentPersonAccountID;
			query += ' and Agreement__r.Student__c = ' + DatabaseUtil.inStringBuilder(studentID)+ ' ';
			if(DatabaseUtil.filterBySchoolID){
				ID schoolID = DatabaseUtil.schoolID;
				query += ' and Agreement__r.Program__r.School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
			}
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		studPrgMap = new Map<ID, StudentProgramAmountDue__c>((List<StudentProgramAmountDue__c>)db.query(query));
		return studPrgMap;
	}


	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getfieldNames() + ' FROM StudentProgramAmountDue__c';
		system.debug(soql);
		return soql;
	}

	private static String getfieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
//		fieldNames += 'CreatedBy, ';
		fieldNames += 'Name, ';
		fieldNames += 'Agreement__c, ';
		fieldNames += 'Agreement__r.Student__c, ';
		fieldNames += 'Agreement__r.Program__c, ';
		
		fieldNames += 'Amount__c, ';
		fieldNames += 'RemainingAllocation__c, ';
		fieldNames += 'AssessmentDateTime__c, ';
		fieldNames += 'ExcludeFromBalance__c, ';
		fieldNames += 'Refund__c, ';
		fieldNames += 'StudentProgramMonthlyStatus__c, ';
		fieldNames += 'Type__c ';
		return fieldNames;
	}
	
	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
}