vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CIPCode__c</fullName>
        <label>CIPCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIPDefinition__c</fullName>
        <label>CIPDefinition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIPFamily__c</fullName>
        <label>CIPFamily</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIPTitle__c</fullName>
        <label>CIPTitle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CrossReferences__c</fullName>
        <label>CrossReferences</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <formula>CIPTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Examples__c</fullName>
        <label>Examples</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/ProgramOfStudyQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: ProgramOfStudyQueries
// 
// Description: 
// 	
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-01-01   Greg Cook       Created                                 
/////////////////////////////////////////////////////////////////////////
public class ProgramOfStudyQueries {
	public static Map<ID, ProgramOfStudy__c> getProgramOfStudyMap(){
		return new Map<ID, ProgramOfStudy__c> ([SELECT ID,
													CIPCode__c, 
													CIPDefinition__c,
													CIPFamily__c,
													CIPTitle__c,
													CrossReferences__c,
													Examples__c,
													GUID__c,
													Description__c
												FROM ProgramOfStudy__c
												LIMIT 50000]);
	}

	public static Map<ID, ProgramOfStudy__c> getProgramOfStudyMapWithPOSID(Set<ID> programOfStudyID){
		return new Map<ID, ProgramOfStudy__c> ([SELECT ID,
													CIPCode__c, 
													CIPDefinition__c,
													CIPFamily__c,
													CIPTitle__c,
													CrossReferences__c,
													Examples__c,
													GUID__c,
													Description__c
												FROM ProgramOfStudy__c
												WHERE ID IN: programOfStudyID
												LIMIT 50000]);
	}
}