vemo-mdapi-qa/objects/ProgramOfStudy__c.object
<CustomObject>
    <label>Program of Study</label>
    <nameField>
        <displayFormat>POS-{0000}</displayFormat>
        <label>Program of Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs of Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CIPCode__c</fullName>
        <label>CIPCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIPDefinition__c</fullName>
        <label>CIPDefinition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIPFamily__c</fullName>
        <label>CIPFamily</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIPTitle__c</fullName>
        <label>CIPTitle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CrossReferences__c</fullName>
        <label>CrossReferences</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <formula>CIPTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Examples__c</fullName>
        <label>Examples</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/SchoolProgramsOfStudy__c.object
<CustomObject>
    <label>School Program of Study</label>
    <nameField>
        <label>School Programs of Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Programs of Study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <formula>if ( ISBLANK( Name ),  ProgramOfStudy__r.Description__c,  Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramOfStudy__c</fullName>
        <label>Program Of Study</label>
        <referenceTo>ProgramOfStudy__c</referenceTo>
        <relationshipLabel>School Programs of Study</relationshipLabel>
        <relationshipName>SchoolProgramsOfStudy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SchoolDescription__c</fullName>
        <label>DEPRECATESchool Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>School_Programs_of_Study</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/SchoolProgramsOfStudyQueries.cls
/////////////////////////////////////////////////////////////////////////
// Class: SchoolProgramsOfStudyQueries
// 
// Description: 
// 	
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-01-01   Greg Cook       Created                                 
/////////////////////////////////////////////////////////////////////////
public class SchoolProgramsOfStudyQueries {
	public static Map<Id, SchoolProgramsOfStudy__c> getSchoolProgramOfStudyMap(){
		Map<ID, SchoolProgramsOfStudy__c> sposMap = new Map<ID, SchoolProgramsOfStudy__c>();
		String query = generateSOQLSelect();
		if(DatabaseUtil.filterBySchoolID){
			ID schoolID = DatabaseUtil.schoolID;
			query += ' WHERE School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		sposMap = new Map<ID, SchoolProgramsOfStudy__c>((List<SchoolProgramsOfStudy__c>)db.query(query));
		return sposMap;
	}

	public static Map<Id, SchoolProgramsOfStudy__c> getSchoolProgramOfStudyMapWithSPOSID(Set<ID> studentProgramsOfStudyIDs){
		Map<ID, SchoolProgramsOfStudy__c> sposMap = new Map<ID, SchoolProgramsOfStudy__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ID IN ' + DatabaseUtil.inSetStringBuilder(studentProgramsOfStudyIDs);
		if(DatabaseUtil.filterBySchoolID){
			ID schoolID = DatabaseUtil.schoolID;
			query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		sposMap = new Map<ID, SchoolProgramsOfStudy__c>((List<SchoolProgramsOfStudy__c>)db.query(query));
		return sposMap;
	}

	public static Map<Id, SchoolProgramsOfStudy__c> getSchoolProgramOfStudyMapWithPOSID(Set<ID> programOfStudyIDs){
		Map<ID, SchoolProgramsOfStudy__c> sposMap = new Map<ID, SchoolProgramsOfStudy__c>();
		String query = generateSOQLSelect();
		query += ' WHERE ProgramOfStudy__c IN ' + DatabaseUtil.inSetStringBuilder(programOfStudyIDs);
		if(DatabaseUtil.filterBySchoolID){
			ID schoolID = DatabaseUtil.schoolID;
			query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		sposMap = new Map<ID, SchoolProgramsOfStudy__c>((List<SchoolProgramsOfStudy__c>)db.query(query));
		return sposMap;
	}

	public static Map<Id, SchoolProgramsOfStudy__c> getSchoolProgramOfStudyMapWithSchoolID(Set<ID> schoolIDs){
		Map<ID, SchoolProgramsOfStudy__c> sposMap = new Map<ID, SchoolProgramsOfStudy__c>();
		String query = generateSOQLSelect();
		query += ' WHERE School__c IN ' + DatabaseUtil.inSetStringBuilder(schoolIDs);
		if(DatabaseUtil.filterBySchoolID){
			ID schoolID = DatabaseUtil.schoolID;
			query += ' and School__c = ' + DatabaseUtil.inStringBuilder(schoolID)+ ' ';
		}
		query += ' '+ generateLIMITStatement();
		DatabaseUtil db = new DatabaseUtil();
		sposMap = new Map<ID, SchoolProgramsOfStudy__c>((List<SchoolProgramsOfStudy__c>)db.query(query));
		return sposMap;
	}

	private static String generateSOQLSelect(){
		String soql;
		soql = 'SELECT ' + getFieldNames() + ' FROM SchoolProgramsOfStudy__c';
		return soql;
	}

	private static String getFieldNames(){
		String fieldNames;
		fieldNames = 'id, ';
		fieldNames += 'Name, ';
		fieldNames += 'ProgramOfStudy__c, ';
		fieldNames += 'ProgramOfStudy__r.CIPCode__c, ';	
		fieldNames += 'ProgramOfStudy__r.CIPDefinition__c, ';				
		fieldNames += 'ProgramOfStudy__r.CIPFamily__c, ';	
		fieldNames += 'ProgramOfStudy__r.CIPTitle__c, ';	
		fieldNames += 'ProgramOfStudy__r.CrossReferences__c, ';
		fieldNames += 'ProgramOfStudy__r.Examples__c, ';
		//fieldNames += 'ProgramOfStudy__r.GUID__c, ';
		fieldNames += 'ProgramOfStudy__r.Description__c, ';
		fieldNames += 'Description__c, ';
		fieldNames += 'SchoolDescription__c, ';
		fieldNames += 'School__c';
		return fieldNames;
	}

	private static String generateLIMITStatement(){
		String lim = 'LIMIT 50000';
		return lim;
	}
}