vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>StudentProgramMonthlyStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Student Program Monthly Status related to this Student Program Amount Due.</inlineHelpText>
        <label>Student Program Monthly Status</label>
        <referenceTo>StudentProgramMonthlyStatus__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramMonthlyStatus__c.object
<CustomObject>
    <label>Student Program Monthly Status</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Student Program Monthly Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Monthly Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-app/main/default/classes/AnnualStatementCTRL_TEST.cls
@isTest
public with sharing class AnnualStatementCTRL_TEST {

    @isTest static void getAccount_Test(){
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(1);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(2, students, programs);
        System.assertEquals(1, studentPrgMap.size());
        AnnualStatementCTRL controllerClass = new AnnualStatementCTRL();
        controllerClass.studentId = students.values()[0].Id;
        controllerClass.getAccount();
    }

    @isTest static void getAccount_TestWithNonStudentAccountId(){
        Map<Id, Account> accountMap = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
        System.assertEquals(1, accountMap.size());
        AnnualStatementCTRL controllerClass = new AnnualStatementCTRL();
        controllerClass.studentId = accountMap.values()[0].Id;
        controllerClass.getAccount();
    }


    @isTest static void getStudentProgramsWithAmountDueList_Test(){
        Map<Id, Account> students = TestDataFactory.createAndInsertStudentAccounts(1);
        Map<Id, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<Id, StudentProgram__c> studentPrgMap = TestDataFactory.createAndInsertStudentProgram(2, students, programs);
        Map<ID, StudentProgramMonthlyStatus__c> studProgMonthlyStatusMap = TestDataFactory.createAndInsertStudentProgramMonthlyStatus(
                12, studentPrgMap
        );
        Map<ID, StudentProgramAmountDue__c> studProgAmountDueMap = TestDataFactory.createAndInsertStudentProgramAmountDue(
                studentPrgMap,
                studProgMonthlyStatusMap
        );
        System.assertEquals(1, studentPrgMap.size());
        AnnualStatementCTRL controllerClass = new AnnualStatementCTRL();
        controllerClass.studentId = students.values()[0].Id;
        controllerClass.getstudentprograms();
        //controllerClass.getStudentProgramsWithAmountDueList();
    }

}