vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/Program_Config__c.object
<CustomObject>
    <label>Program Config</label>
    <nameField>
        <displayFormat>CONFIG{0}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Configs</relationshipLabel>
        <relationshipName>Calculation_Facors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>FundingAmountPostCertification__c</fullName>
        <inlineHelpText>(Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Funding Amount (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IncomeSharePostCertification__c</fullName>
        <inlineHelpText>The percent of student&#39;s total earned income that they will share each month. (Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Income Share (Post-Certification)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PaymentCapPostCertification__c</fullName>
        <inlineHelpText>The maximum amount student will pay over the payment term. (Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Payment Cap (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentCap__c</fullName>
        <label>Payment Cap</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentTermPostCertification__c</fullName>
        <inlineHelpText>The maximum number of months during which student will share their income. (Post-Certification) fields store the final values entered by the School Admin during certification.</inlineHelpText>
        <label>Payment Term (Post-Certification)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RequestedAmount__c</fullName>
        <label>Requested Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/Disclosure_TEST.cls
/////////////////////////////////////////////////////////////////////////
// Class: DisclosureTest
// 
// Description: 
// 	Test class for DisclosureService
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2017-03-13   Greg Cook       Created                          
/////////////////////////////////////////////////////////////////////////
@isTest
private class Disclosure_TEST {
	@TestSetup static void setupData(){
		Map<ID, Account> testAccounts = TestDataFactory.createAndInsertSchoolCustomerAccounts(1);
		Map<ID, Program__c> testPrograms = TestDataFactory.createAndInsertPrograms(1, testAccounts);
		Map<ID, Program_Config__c> testProgramConfigs = TestDataFactory.createAndInsertProgramConfig(1, testPrograms);
		TestDataFactory.createAndInsertProgramConfigIncomes(testProgramConfigs);
		TestDataFactory.createAndInsertProgramConfigLoans(testProgramConfigs);
		
		Map<ID, Account> testStudents = TestDataFactory.createAndInsertStudentAccounts(1);
		Map<ID, StudentProgram__c> testStudentPrograms = TestDataFactory.createAndInsertStudentProgram(1, testStudents, testPrograms);
	}
	
	@isTest private static void myUnitTest() {
/*		List<StudentProgram__c> testStudentPrograms = [Select ID From StudentProgram__c];
		Test.startTest();
			//test StudentProgramTriggerHandler trigger
			for(StudentProgram__c studentProgram : testStudentPrograms){
	            studentProgram.FundingAmountPostCertification__c = 20000;
	            //studentProgram.RequestedAmount__c = 10000;
	            studentProgram.IncomeSharePostCertification__c = 3;
	            studentProgram.PaymentTermPostCertification__c = 92;
	            studentProgram.PaymentCapPostCertification__c = 25000;
	        }
	        update testStudentPrograms;
	        
	        testStudentPrograms = [Select ID, Program__c, FundingAmountPostCertification__c, IncomeSharePostCertification__c, PaymentTermPostCertification__c, PaymentCapPostCertification__c From StudentProgram__c];
	        
	        //test DisclosureService.Calculation
	        testStudentPrograms[0].PaymentCap__c = null;
	        DisclosureService.Calculation(testStudentPrograms);
			
	        //test no Funding Amount, line 78;
	        testStudentPrograms[0].FundingAmountPostCertification__c = null;
//	        testStudentPrograms[0].RequestedAmount__c = null;
	        DisclosureService.Calculation(testStudentPrograms);
	        
			//test PMT
	        DisclosureService.PMT(null, null, null);
		Test.stopTest();*/
	}
}