vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>EnrollmentType__c</fullName>
        <description>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</description>
        <inlineHelpText>If this field is set to &quot;Open&quot; then any student can apply for the program.  If this field is set to &quot;Invite Only&quot; then students must be invited to the program for enrollment first (via &quot;Inivted&quot; StudentProgram__c record)</inlineHelpText>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Invite Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramStatus__c</fullName>
        <label>Program Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProgramStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegistrationBeginDate__c</fullName>
        <label>Registration Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegistrationEndDate__c</fullName>
        <label>Registration End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/ProgramStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <masterLabel>Program Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/VemoAPIOfferResource_TEST.cls
@isTest
public class VemoAPIOfferResource_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    static testMethod void testHandleGetV1(){
    	Map<ID, Account> studentMap = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Account> schoolMap = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	for(Integer i = 0; i < TestUtil.TEST_THROTTLE; i++){
    		studentMap.values().get(i).PrimarySchool__pc = schoolMap.values().get(i).Id;
    	}
    	update studentMap.values();
    	Map<ID, Program__c> programMap = TestDataFactory.createAndInsertPrograms(TestUtil.TEST_THROTTLE, schoolMap);
    	for(Program__c prg : programMap.values()){
    		prg.EnrollmentType__c = 'Open';
    		prg.ProgramStatus__c = 'Open';
    		prg.RegistrationBeginDate__c = Date.today().addMonths(-1);
    		prg.RegistrationEndDate__c = Date.today().addMonths(1);
    	}
    	update programMap.values();
    	Map<ID, StudentProgram__c> studentProgramMap = TestDataFactory.createAndInsertStudentProgram(1, studentMap, programMap);

    	Map<String, String> params = new Map<String, String>();
		params.put('studentID', (String)studentMap.values().get(0).Id);
		params.put('VEMO_AUTH', 'testStudent_'+studentMap.values()[0].AuthSystemUserID__pc);
		VemoAPI.APIInfo apiInfo = TestUtil.initializeAPI('v1', 'GET', params, null);
		//apiInfo.studentPersonAccountID = studentMap.values()[0].Id;

		Test.startTest();
		VemoAPI.ResultResponse stdResult = (VemoAPI.ResultResponse)VemoAPIOfferResource.handleAPI(apiInfo);
		System.assertEquals(TestUtil.TEST_THROTTLE, stdResult.numberOfResults);
		Test.stopTest();
    }

    static testMethod void testOfferResourceV1toOffer(){
    	VemoAPIOfferResource.OfferResourceInputV1 offerInput = new VemoAPIOfferResource.OfferResourceInputV1();
    	offerInput.programID = '1';
    	offerInput.programName = '2';
    	offerInput.schoolID = '3';
    	offerInput.programStatus = 'Open';
    	offerInput.agreementStatus = 'Pending';
    	offerInput.studentID = '4';
    	offerInput.agreementID = '5';
    	offerInput.enrollmentEndDate = Date.today();
    	Test.startTest();
    	OfferService.Offer offer = VemoAPIOfferResource.offerResourceV1toOffer(offerInput);
    	System.assertEquals(offerInput.programID, offer.programID);
    	Test.stopTest();
    }


}