vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/TransactionSchedule__c.object
<CustomObject>
    <label>Disbursement Schedule</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Transaction_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/TransactionScheduleService_TEST.cls
@isTest
public class TransactionScheduleService_TEST {
  @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    @isTest public static void validateGettransactionScheduleswithProgramID(){

      Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
      Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);


      Map<ID, TransactionSchedule__c> testSchedule = TestDataFactory.createAndInsertTransactionSchedule(2, programs);
      Test.startTest();
      Set<Id> programIDs = new Set<ID>();
      for(TransactionSchedule__c trsch : testSchedule.values()){
           programIDs.add(trsch.Program__c);
      }
      List<TransactionScheduleService.transactionSchedule> trschList = TransactionScheduleService.gettransactionScheduleswithProgramID(programIDs);
      Test.stopTest();
      System.assertEquals(testSchedule.keySet().size(), trschList.size());
    }

    @isTest public static void validateGettransactionSchedulesByProgramIDWithProgramID(){

      Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
      Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(2, schools);

      Map<ID, TransactionSchedule__c> testSchedule = TestDataFactory.createAndInsertTransactionSchedule(2, programs);
      Test.startTest();
      Set<Id> programIDs = new Set<ID>();
      for(TransactionSchedule__c trsch : testSchedule.values()){
           programIDs.add(trsch.Program__c);
      }
      Map<Id,List<TransactionScheduleService.transactionSchedule>> trschMap = TransactionScheduleService.gettransactionSchedulesByProgramIDWithProgramID(programIDs);
      
      Test.stopTest();

      System.assertEquals(programIDs.size(), trschMap.keyset().size());
    }
}