vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TransactionBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Disbursement Batch.</inlineHelpText>
        <label>Transaction Batch</label>
        <referenceTo>TransactionBatch__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/TransactionBatch__c.object
<CustomObject>
    <label>Disbursement Batch</label>
    <nameField>
        <displayFormat>DB-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Disbursement Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>TransactionBatches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionBatchStatus__c</fullName>
        <label>Transaction Batch Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Select Transactions</fullName>
                </value>
                <value>
                    <fullName>Freeze Transactions</fullName>
                </value>
                <value>
                    <fullName>Release Transactions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransactionsFrom__c</fullName>
        <label>Transactions From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TransactionsThrough__c</fullName>
        <label>Transactions Through</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UpdateConfirmed__c</fullName>
        <label>Update Confirmed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Not Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpdateTransactionDateTime__c</fullName>
        <label>DEPRECATEUpdate Transaction DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UpdateTransactionStatus__c</fullName>
        <label>Update Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-app/main/default/globalValueSets/TransactionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-app/main/default/classes/TransactionBatchTriggerHandler_TEST.cls
@isTest
public with sharing class TransactionBatchTriggerHandler_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

	@isTest public static void validateDML(){
		TestUtil.setStandardConfiguration();
		Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Program__c> otherPrograms = TestDataFactory.createAndInsertPrograms(1, schools);
    	Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
    	Map<ID, StudentProgram__C> agreements = TestDataFactory.createAndInsertStudentProgram(1, students, programs);
    	Map<ID, Transaction__c> txMap = TestDataFactory.createAndInsertTransactions(2, agreements,
    																				TransactionService.disbursementRecType);
    	List<TransactionBatch__c> txBatchList = new List<TransactionBatch__c>();
    	txBatchList.add(new TransactionBatch__c(Program__c = programs.values()[0].id,
	    									   TransactionsFrom__c = Date.Today().addDays(-1),
	    									   TransactionsThrough__c = Date.Today().addDays(1),
	    									   TransactionBatchStatus__c = 'Created'));

    	Test.startTest();
    	insert(txBatchList);

    	txBatchList[0].TransactionBatchStatus__c = 'Select Transactions';
    	update txBatchList;
    	
    	txBatchList[0].UpdateTransactionDateTime__c = Datetime.now().addMinutes(1);
    	txBatchList[0].UpdateTransactionStatus__c = 'Cancelled';
    	txBatchList[0].UpdateConfirmed__c = 'Confirmed';
    	update txBatchList; 

    	txBatchList[0].TransactionBatchStatus__c = 'Release Transactions';
    	update txBatchList;

    	delete txBatchList;
    	undelete txBatchList;
    	Test.stopTest();
	}


}