vemo-mdapi-qa/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Program related to this Student Program.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student Programs</relationshipLabel>
        <relationshipName>StudentPrograms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TransactionDate__c</fullName>
        <inlineHelpText>The date the funds were disbursed.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Represents a funding event in a contract. This is typically a transaction from an investor or school to the school (for tuition) or directly to the student (ex. stipend)</description>
        <label>Disbursement</label>
    </recordTypes>
</CustomObject>

vemo-app/main/default/classes/ReportPeriodicClientsController_TEST.cls
@isTest
public class ReportPeriodicClientsController_TEST{
    @TestSetup static void setupData(){
        Map<ID, Account> schools = TestDataFactory.createAndInsertSchoolCustomerAccounts(4);
        Map<ID, Program__c> programs = TestDataFactory.createAndInsertPrograms(1, schools);
        Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);
        Map<ID, StudentProgram__C> agreements;
        
        //create 1 studentProgram for each student, so that each school has 4 students under them 
        Integer count = 1;
        List<Account> studentList = students.values();
        for(Program__c program:programs.values()){
            Map<ID, Program__c> programForAgreement = new Map<ID,Program__c>();
            Map<ID, Account> studentsForAgreement = new Map<ID,Account>();
            programForAgreement.put(program.ID,program);
            for(integer i=0 ;i<studentList.size();i++){
                studentsForAgreement.put(studentList[i].id,studentList[i]);
                if(Math.mod(count,4) == 0) break;    
                count += 1;
            }
            
            agreements = TestDataFactory.createAndInsertStudentProgram(1, studentsForAgreement , programForAgreement);    
        }
        
        Map<ID,Transaction__c> disbursements = TestDataFactory.createAndInsertTransactions(3,agreements, TransactionService.disbursementRecType);
                    
    }
    
    @isTest public static void validateSchoolFilter(){
        
        Test.StartTest(); 

            ReportPeriodicClientsController  cntrl = new ReportPeriodicClientsController();
            cntrl.getSchools();
            cntrl.schools[0].selected = true;
            cntrl.runReport();
            System.assertEquals(4,cntrl.reportData.size(),'Number of rows in report should be 4');
        
        Test.StopTest();    
    }
    
    @isTest public static void validateDateFilter(){
        Test.StartTest();
            
            Date newTxDate = Date.Today().addYears(-1);
            
            Map<ID,Transaction__c> disbursements = TransactionQueries.getTransactionMap(TransactionService.disbursementRecType);
            for(Transaction__c disb: disbursements.values()){
                disb.transactionDate__c = newTxDate;
                break;
            }
            update disbursements.values();
            
            ReportPeriodicClientsController  cntrl = new ReportPeriodicClientsController();
            cntrl.startDate.transactionDate__c = newTxDate.adddays(-1);
            cntrl.endDate.transactionDate__c = newTxDate.adddays(1);
            cntrl.runReport();
            System.assertEquals(1,cntrl.reportData.size(),'Number of rows in report should be 1');
            
        Test.StopTest();    
    }
    
    @isTest public static void testExport(){
        Test.StartTest(); 

            ReportPeriodicClientsController  cntrl = new ReportPeriodicClientsController();
            cntrl.exportToCSV();
            cntrl.buildCsvString(); 
            
        Test.StopTest();   
    }
    
    @isTest public static void testSortDirectionToggling(){
        PageReference pageRef = Page.ReportPeriodicClients;
        Test.setCurrentPage(pageRef);
        
        Test.StartTest();
            
            ReportPeriodicClientsController  cntrl = new ReportPeriodicClientsController();
            ApexPages.currentPage().getParameters().put('sortByParam','School');
            System.assertEquals('ASCENDING',ReportPeriodicClientsController.sortDirection,'Should be ASCENDING');
            cntrl.sort();
            System.assertEquals('ASCENDING',ReportPeriodicClientsController.sortDirection,'Should be ASCENDING');
            cntrl.sort();
            System.assertEquals('DESCENDING',ReportPeriodicClientsController.sortDirection,'Should be DESCENDING');
            cntrl.sort();
            System.assertEquals('ASCENDING',ReportPeriodicClientsController.sortDirection,'Should be ASCENDING');
            
        Test.StopTest();
    }
    
    @isTest public static void testSortBy(){
            Test.StartTest();
                ReportPeriodicClientsController  cntrl = new ReportPeriodicClientsController();
                ApexPages.currentPage().getParameters().put('sortByParam','firstTxDate');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','firstTxAmount');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','School');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','Program');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','Student');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','StudentProgram');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','Disbursement');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','FundingAmountPostCertification');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','IncomeSharePostCertification');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','DefermentMonthsAllowed');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','GraceMonthsAllowed');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','MinimumIncomePerMonth');
                cntrl.sort();
                cntrl.sort();
                ApexPages.currentPage().getParameters().put('sortByParam','PaymentCapPostCertification');
                cntrl.sort();
                cntrl.sort();
            Test.StopTest();
    }
}