vemo-mdapi-qa/objects/Reconciliation__c.object
<CustomObject>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>REC-{00000}</displayFormat>
        <label>Reconciliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliation</relationshipLabel>
        <relationshipName>Reconciliation</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ReconciliationDetail__c.object
<CustomObject>
    <label>ReconciliationDetail</label>
    <nameField>
        <displayFormat>RD-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>ReconciliationDetail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReconciliationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Reconciliation__c</fullName>
        <label>Reconciliation</label>
        <referenceTo>Reconciliation__c</referenceTo>
        <relationshipLabel>ReconciliationDetail</relationshipLabel>
        <relationshipName>ReconciliationDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/ReconciliationQueries_TEST.cls
@isTest
public with sharing class ReconciliationQueries_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }

    @isTest public static void validateGetReconciliationMapWithStudentID() {
        Map<ID, Reconciliation__c> testReconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Map<ID, Account> testStudents = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);     
        for(Integer i=0; i<TestUtil.TEST_THROTTLE; i++){
            testReconciliationMap.values().get(i).student__c = testStudents.values().get(i).ID;
        }
        update testReconciliationMap.values();
        Test.startTest();
        Map<ID, Reconciliation__c> reconciliationMap = ReconciliationQueries.getReconciliationMapWithStudentID(testStudents.keySet());
        system.assertEquals(testReconciliationMap.size(), reconciliationMap.size());
        Test.stopTest();
    }
    @isTest public static void validateGetReconciliationMapWithReconciliationID() {
        Map<ID, Reconciliation__c> testReconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Test.startTest();
        Map<ID, Reconciliation__c> reconciliationMap = ReconciliationQueries.getReconciliationMapWithReconciliationID(testReconciliationMap.keySet());
        system.assertEquals(testReconciliationMap.size(), reconciliationMap.size());
        Test.stopTest();
    }

    @isTest public static void validateGetReconciliationDetailMapWithReconciliationID() {
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Map<ID, ReconciliationDetail__c> testReconciliationDetailMap = TestDataFactory.createAndInsertReconciliationDetail(TestUtil.TEST_THROTTLE,reconciliationMap );     
        Test.startTest();
        Map<ID, ReconciliationDetail__c> reconciliationDetailMap = ReconciliationQueries.getReconciliationDetailMapWithReconciliationID(reconciliationMap.keyset());
        system.assertEquals(testReconciliationDetailMap.size(), reconciliationDetailMap.size());
        Test.stopTest();
    }
    
    @isTest public static void validateGetRDetailMapWithRDetailID() {
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Map<ID, ReconciliationDetail__c> testReconciliationDetailMap = TestDataFactory.createAndInsertReconciliationDetail(TestUtil.TEST_THROTTLE,reconciliationMap );     
        Test.startTest();
        Map<ID, ReconciliationDetail__c> reconciliationDetailMap = ReconciliationQueries.getRDetailMapWithRDetailID(testReconciliationDetailMap.keyset());
        system.assertEquals(testReconciliationDetailMap.size(), reconciliationDetailMap.size());
        Test.stopTest();
    }
}