vemo-mdapi-qa/objects/Reconciliation__c.object
<CustomObject>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>REC-{00000}</displayFormat>
        <label>Reconciliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliation</relationshipLabel>
        <relationshipName>Reconciliation</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/ReconciliationDetail__c.object
<CustomObject>
    <label>ReconciliationDetail</label>
    <nameField>
        <displayFormat>RD-{YYYY}{MM}{DD}{0}</displayFormat>
        <label>ReconciliationDetail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReconciliationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Reconciliation__c</fullName>
        <label>Reconciliation</label>
        <referenceTo>Reconciliation__c</referenceTo>
        <relationshipLabel>ReconciliationDetail</relationshipLabel>
        <relationshipName>ReconciliationDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/ReconciliationService_TEST.cls
@isTest
public class ReconciliationService_TEST {
    @TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();
    }
    
    @isTest public static void validateGetReconciliationMapWithStudentID(){
        Map<ID, Reconciliation__c> testReconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Map<ID, Account> testStudents = TestDataFactory.createAndInsertStudentAccounts(TestUtil.TEST_THROTTLE);     
        for(Integer i=0; i<TestUtil.TEST_THROTTLE; i++){
            testReconciliationMap.values().get(i).student__c = testStudents.values().get(i).ID;
        }
        update testReconciliationMap.values();
        Test.startTest();
        List<ReconciliationService.Reconciliation> reconciliations = ReconciliationService.getReconciliationMapWithStudentID(testStudents.keySet());
        System.assertEquals(testReconciliationMap.size(), reconciliations.size());
        Test.stopTest();
    }
    
    @isTest public static void validateGetReconciliationDetailMapWithReconciliationID(){
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Map<ID, ReconciliationDetail__c> testReconciliationDetailMap = TestDataFactory.createAndInsertReconciliationDetail(TestUtil.TEST_THROTTLE,reconciliationMap );  
        Test.startTest();
        List<ReconciliationService.ReconciliationDetail> reconciliationDetails = ReconciliationService.getReconciliationDetailMapWithReconciliationID(reconciliationMap.keySet());
        System.assertEquals(testReconciliationDetailMap.size(), reconciliationDetails.size());
        Test.stopTest();
    }
    
    @isTest public static void validateGetRDetailMapWithRDetailID(){
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        Map<ID, ReconciliationDetail__c> testReconciliationDetailMap = TestDataFactory.createAndInsertReconciliationDetail(TestUtil.TEST_THROTTLE,reconciliationMap );  
        Test.startTest();
        List<ReconciliationService.ReconciliationDetail> reconciliationDetails = ReconciliationService.getRDetailMapWithRDetailID(testReconciliationDetailMap.keySet());
        System.assertEquals(testReconciliationDetailMap.size(), reconciliationDetails.size());
        Test.stopTest();
    }
    
    @isTest public static void validateCreateRDetails(){
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        List<ReconciliationService.ReconciliationDetail> reconciliationDetails = new List<ReconciliationService.ReconciliationDetail>();
        
        for(Reconciliation__c rc : reconciliationMap.values()){
            for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
                ReconciliationService.ReconciliationDetail rd = new ReconciliationService.ReconciliationDetail(true);
                rd.reconciliationID = rc.id;
                reconciliationDetails.add(rd);
            }
        }
        Test.startTest();
        Set<ID> rDetailIDs = ReconciliationService.createRDetails(reconciliationDetails);
        Test.stopTest();
    }
    
    @isTest public static void validateUpdateRDetails(){
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        List<ReconciliationService.ReconciliationDetail> reconciliationDetails = new List<ReconciliationService.ReconciliationDetail>();
        
        for(Reconciliation__c rc : reconciliationMap.values()){
            for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
                ReconciliationService.ReconciliationDetail rd = new ReconciliationService.ReconciliationDetail(true);
                rd.reconciliationID = rc.id;
                reconciliationDetails.add(rd);
            }
        }
        Set<ID> rDetailIDs = ReconciliationService.createRDetails(reconciliationDetails);
        Map<ID, ReconciliationDetail__c> reconciliationDetailMap = ReconciliationQueries.getRDetailMapWithRDetailID(rDetailIDs );
        List<ReconciliationService.ReconciliationDetail> updateReconciliations = ReconciliationService.getRDetailMapWithRDetailID(rDetailIDs);
        for(ReconciliationService.ReconciliationDetail rd : updateReconciliations){
            rd.employerStartDate = date.today().adddays(1);
        }
        Test.startTest();
        Set<ID> updatedIDs = ReconciliationService.updateRDetails(updateReconciliations);
        Test.stopTest();
    }
    
    @isTest public static void validateDeleteRDetails(){
        Map<ID, Reconciliation__c> reconciliationMap = TestDataFactory.createAndInsertReconciliation(TestUtil.TEST_THROTTLE);
        List<ReconciliationService.ReconciliationDetail> reconciliationDetails = new List<ReconciliationService.ReconciliationDetail>();
        
        for(Reconciliation__c rc : reconciliationMap.values()){
            for(Integer i = 0; i<TestUtil.TEST_THROTTLE; i++){
                ReconciliationService.ReconciliationDetail rd = new ReconciliationService.ReconciliationDetail(true);
                rd.reconciliationID = rc.id;
                reconciliationDetails.add(rd);
            }
        }
        Set<ID> rDetailIDs = ReconciliationService.createRDetails(reconciliationDetails);
        Test.startTest();
        Integer deletedNum = ReconciliationService.deleteRDetails(rDetailIDs);
        Test.stopTest();
        System.assertEquals(deletedNum, rDetailIDs.size());
    }
}