vemo-mdapi-qa/objects/Refund__c.object
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000000000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GenerateAmountDue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If and when this field is checked, an Amount Due Record will be created for this Refund</description>
        <inlineHelpText>If and when this field is checked, an Amount Due Record will be created for this Refund</inlineHelpText>
        <label>Generate Amount Due</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/objects/StudentProgramAmountDue__c.object
<CustomObject>
    <label>Student Program Amount Due</label>
    <nameField>
        <displayFormat>AD-{00000000}</displayFormat>
        <label>Student Program Amount Due</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Program Amount Due</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Agreement related to this Student Program Amount Due.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Debits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount due.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AssessmentDateTime__c</fullName>
        <inlineHelpText>The date/time stamp of when the amount due was calculated/assessed.</inlineHelpText>
        <label>Assessment DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExcludeFromBalance__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates that an amount due should not be included in the account statement summaries. Used primarily for reconciliation amounts that are pre-assessed for future months, but which should not actually show up on the statement/bill until that month arrives</inlineHelpText>
        <label>Exclude from Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Student Program Amount Due</relationshipLabel>
        <relationshipName>Student_Program_Amount_Due</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reconciliation, Monthly Amount, or Fee.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DebitType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/globalValueSets/DebitType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Reconciliation</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <masterLabel>Debit Type</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/RefundTriggerHandler.cls
/////////////////////////////////////////////////////////////////////////
// Class: RefundTriggerHandler
// 
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2018-03-19   Greg Cook       Created                              
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class RefundTriggerHandler implements TriggerDispatch.ITriggerHandlerClass {

    /**************************Static Variables***********************************/

    /**************************State refundrol Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution refundrol - Entry Points**********************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: mainEntry
    /////////////////////////////////////////////////////////////////////////
    public void mainEntry(TriggerDispatch.Triggercontext tc){       
        mainHasRun = true;
            
        if(tc.handler == 'RefundTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            
 
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: inProgressEntry
    /////////////////////////////////////////////////////////////////////////
    public void inProgressEntry(TriggerDispatch.Triggercontext tc){
        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'RefundTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'RefundTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'RefundTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeInsert
    /////////////////////////////////////////////////////////////////////////    
    public void onBeforeInsert(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onBeforeInsert()');
       //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> newRefundList = (List<Refund__c>)tc.newList;
        //This is where you should call your business logic
        setDefaultsOnInsert(newRefundList);

    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeUpdate(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onBeforeUpdate()');
        //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> newRefundList = (List<Refund__c>)tc.newList;
        List<Refund__c> oldRefundList = (List<Refund__c>)tc.oldList;
        Map<ID, Refund__c> newRefundMap = (Map<ID, Refund__c>)tc.newMap;
        Map<ID, Refund__c> oldRefundMap = (Map<ID, Refund__c>)tc.oldMap;
        //This is where you should call your business logic
        setDefaultsOnUpdate(oldRefundMap, newRefundMap);    
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onBeforeDelete
    /////////////////////////////////////////////////////////////////////////
    public void onBeforeDelete(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onBeforeDelete()');
       //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> oldRefundList = (List<Refund__c>)tc.oldList;
        Map<ID, Refund__c> oldRefundMap = (Map<ID, Refund__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    /****************************After logic****************************************/
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterInsert
    /////////////////////////////////////////////////////////////////////////
    public void onAfterInsert(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onAfterInsert()');
         //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> newRefundList = (List<Refund__c>)tc.newList;
        Map<ID, Refund__c> newRefundMap = (Map<ID, Refund__c>)tc.newMap;
        //This is where you should call your business logic
        manageAmountDue(null, newRefundMap);
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUpdate
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUpdate(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onAfterUpdate()');
        //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> newRefundList = (List<Refund__c>)tc.newList;
        List<Refund__c> oldRefundList = (List<Refund__c>)tc.oldList;
        Map<ID, Refund__c> newRefundMap = (Map<ID, Refund__c>)tc.newMap;
        Map<ID, Refund__c> oldRefundMap = (Map<ID, Refund__c>)tc.oldMap;
        //This is where you should call your business logic
        manageAmountDue(oldRefundMap, newRefundMap);
   }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterDelete
    /////////////////////////////////////////////////////////////////////////    
    public void onAfterDelete(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onAfterDelete()');
        //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> oldRefundList = (List<Refund__c>)tc.oldList;
        Map<ID, Refund__c> oldRefundMap = (Map<ID, Refund__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    /////////////////////////////////////////////////////////////////////////
    //Method: onAfterUndelete
    /////////////////////////////////////////////////////////////////////////
    public void onAfterUndelete(TriggerDispatch.Triggercontext tc){
system.debug('RefundTriggerHandler.onAfterUndelete()');
        //Recast the trigger refundext variables into the appropriate shandlerect types
        List<Refund__c> newRefundList = (List<Refund__c>)tc.newList;
        Map<ID, Refund__c> newRefundMap = (Map<ID, Refund__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnInsert
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnInsert(List<Refund__c> newRefundList){
system.debug('RefundTriggerHandler.setDefaultsOnInsert()');

        for(Refund__c refund : newRefundList){

        }
    }
    /////////////////////////////////////////////////////////////////////////
    //Method: setDefaultsOnUpdate
    /////////////////////////////////////////////////////////////////////////
    private void setDefaultsOnUpdate(Map<ID, Refund__c> oldRefundMap, Map<ID, Refund__c> newRefundMap){
system.debug('RefundTriggerHandler.setDefaultsOnUpdate()'); 
        for(Refund__c refund : newRefundMap.values()){

        }
    }


    /////////////////////////////////////////////////////////////////////////
    //Method: manageAmountDue
    /////////////////////////////////////////////////////////////////////////
    private void manageAmountDue(Map<ID, Refund__c> oldRefundMap, Map<ID, Refund__c> newRefundMap){
        Set<Id> refundIds = new Set<Id>();
        for(Refund__c refund : newRefundMap.values()){
        	if(String.isNotEmpty(refund.Agreement__c) && (refund.GenerateAmountDue__c == true && (oldRefundMap == null || oldRefundMap.get(refund.id).GenerateAmountDue__c != true))){
        		refundIDs.add(refund.id);
        	}
        }
        List<StudentProgramAmountDue__c> amountDueToAdd = new List<StudentProgramAmountDue__c>();
        for(ID theID : refundIDs){
        	Refund__c ref = newRefundMap.get(theID);
        	StudentProgramAmountDue__c amountDue = new StudentProgramAmountDue__c(Agreement__c = ref.Agreement__c,
        																		  Amount__c = ref.Amount__c,
        																		  AssessmentDateTime__c = DateTime.now(),
        																		  ExcludeFromBalance__c = false,
        																		  Refund__c = theID,
        																		  Type__c = 'Monthly Amount');
        	amountDueToAdd.add(amountDue);
        }

        if(amountDueToAdd.size()>0){
        	insert amountDueToAdd;
        }
    }

    public class RefundTriggerHandlerException extends Exception {}
}