vemo-mdapi-qa/objects/Refund__c.object
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000000000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

vemo-app/main/default/classes/RefundTriggerHandler_TEST.cls
@isTest
public with sharing class RefundTriggerHandler_TEST {
	@isTest
	public static void testDML() {
        Map<ID, Account> students = TestDataFactory.createAndInsertStudentAccounts(1);		
		List<Refund__c> refundsToAdd = new List<Refund__c>();
		refundsToAdd.add(new Refund__c(Account__c = students.values()[0].id));
		insert refundsToAdd;
		update refundsToAdd;
		delete refundsToAdd;
		undelete refundsToAdd;
		
	}
}