vemo-mdapi-qa/objects/SecureSetting__c.object
<CustomObject>
    <label>Secure Setting</label>
    <nameField>
        <label>Secure Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Encrypt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Encrypt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/SecureSettingTriggerHandler_TEST.cls
@isTest
public class SecureSettingTriggerHandler_TEST {
	@TestSetup static void setupData(){
        TestUtil.createStandardTestConditions();

    }

	@isTest	public static void test1() {
		TestUtil.setStandardConfiguration();
		List<SecureSetting__c> secureSettingsList = new List<SecureSetting__c>();
		secureSettingsList.add(new SecureSetting__c(Name = 'test1', Value__c = 'value1', Encrypt__c = false));
		secureSettingsList.add(new SecureSetting__c(Name = 'test2', Value__c = 'value2', Encrypt__c = true));
		insert secureSettingsList;

		Test.startTest();
		System.assertEquals(SecureSettings.getValue('test1'), 'value1');
		System.assertEquals(SecureSettings.getValue('test2'), 'value2');
		Test.stopTest();
	}
}