vemo-mdapi-qa/objects/StewardshipACHBatch__c.object
<CustomObject>
    <label>Stewardship ACH Batch</label>
    <nameField>
        <displayFormat>STACHBAT-{0000000000}</displayFormat>
        <label>Stewardshp ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vemo-mdapi-qa/objects/StewardshipACHBatchDetail__c.object
<CustomObject>
    <label>Stewardship ACH Batch Detail</label>
    <nameField>
        <displayFormat>SACHBD-{000000000}</displayFormat>
        <label>Stewardship ACH Batch Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>StewardshipACHBatch__c</fullName>
        <label>Stewardship ACH Batch</label>
        <referenceTo>StewardshipACHBatch__c</referenceTo>
        <relationshipLabel>Stewardship ACH Batch Details</relationshipLabel>
        <relationshipName>Stewardship_ACH_Batch_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/StewardshipACHBatchDtlTriggerHndlr_TEST.cls
@isTest
public with sharing class StewardshipACHBatchDtlTriggerHndlr_TEST {
	@TestSetup
	public static void testSetup(){
        TestUtil.createStandardTestConditions();
    }

	@isTest
	public static void testDML(){
		StewardshipACHBatch__c batchToCreate = new StewardshipACHBatch__c();
		insert batchToCreate;
		StewardshipACHBatchDetail__c batchDtlToCreate = new StewardshipACHBatchDetail__c(StewardshipACHBatch__c = batchToCreate.id);
		insert batchDtlToCreate;
		update batchDtlToCreate;
		delete batchDtlToCreate;
		undelete batchDtlToCreate;
		
	}
}