vemo-mdapi-qa/objects/StewardshipACHBatch__c.object
<CustomObject>
    <label>Stewardship ACH Batch</label>
    <nameField>
        <displayFormat>STACHBAT-{0000000000}</displayFormat>
        <label>Stewardshp ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>BankAccount__c</fullName>
        <label>Bank Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Disbursements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BatchGUID__c</fullName>
        <externalId>true</externalId>
        <label>BatchGUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchSelectResponse__c</fullName>
        <label>Batch Select Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BatchType__c</fullName>
        <label>Batch Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payment (Incoming Money)</fullName>
                </value>
                <value>
                    <fullName>Credit (Outgoing Money)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastSelectedDateTime__c</fullName>
        <label>Last Selected DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OpenBatchDetails__c</fullName>
        <label>Open Batch Details</label>
        <summaryFilterItems>
            <field>StewardshipACHBatchDetail__c.TransactionStatus__c</field>
            <operation>notEqual</operation>
            <value>C, B</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>StewardshipACHBatchDetail__c.StewardshipStatus__c</field>
            <operation>notContain</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>StewardshipACHBatchDetail__c.StewardshipACHBatch__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>QC&#39;d</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StewardshipProcess__c</fullName>
        <label>Stewardship Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PaymentBatchOpen</fullName>
                </value>
                <value>
                    <fullName>PaymentBatchSelect</fullName>
                </value>
                <value>
                    <fullName>PaymentBatchApprove</fullName>
                </value>
                <value>
                    <fullName>PaymentBatchCancel</fullName>
                </value>
                <value>
                    <fullName>CreditBatchOpen</fullName>
                </value>
                <value>
                    <fullName>PaymentBatch Created</fullName>
                </value>
                <value>
                    <fullName>CreditBatch Created</fullName>
                </value>
                <value>
                    <fullName>Batch Selected</fullName>
                </value>
                <value>
                    <fullName>Batch Approved</fullName>
                </value>
                <value>
                    <fullName>Batch Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StewardshipStatus__c</fullName>
        <label>Stewardship Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PaymentBatch Created</fullName>
                </value>
                <value>
                    <fullName>CreditBatch Created</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/StewardshipACHBatchBatch.cls
public with sharing class StewardshipACHBatchBatch implements Database.Batchable<sObject>, Database.ALlowsCallouts{
	public enum JobType {QUERY_APPROVED_OPEN} 
	
	public String query {get;set;}
	public JobType job {get;set;}
	
	public StewardshipACHBatchBatch() {
		job = JobType.QUERY_APPROVED_OPEN;
	}
	public StewardshipACHBatchBatch(String query) {
		this.query = query;
		job = JobType.QUERY_APPROVED_OPEN;
	}	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('StewardshipACHBatchBatch.start()');
		if(job == JobType.QUERY_APPROVED_OPEN){
			if(String.isEmpty(this.query)){
				String dateWindow = String.valueOf(Date.today().addDays(-7));
				query = 'SELECT id from StewardshipACHBatch__c WHERE Status__c = \'Approved\'' + ' and (OpenBatchDetails__c > 0 or ScheduledDate__c > '+dateWindow+')';
			}
		} 
		System.debug('job:'+job);
		System.debug('query:'+query);
		LogService.writeLogs();
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.debug('StewardshipACHBatchBatch.execute()');
		Set<ID> scopeIDs = new Set<ID>();
		for(sObject sobj : scope){
			scopeIDs.add(sobj.id);
		}

		if(job == JobType.QUERY_APPROVED_OPEN){
			Map<ID, StewardshipACHBatch__c> batchMap = new Map<ID, StewardshipACHBatch__c>([SELECT id,
																								   BankAccount__c,
																								   BatchGUID__c,
																								   BatchSelectResponse__c,
																								   BatchType__c,
																								   LastSelectedDateTime__c,
																								   OpenBatchDetails__c,
																								   ScheduledDate__c,
																								   Status__c,
																								   StewardshipProcess__c,
																								   StewardshipStatus__c
																	FROM StewardshipACHBatch__c
																	WHERE id = :scopeIDs
																	FOR UPDATE]);
			System.debug('batchMap:'+batchMap);
			queryApprovedOpen(batchMap);
			LogService.writeLogs();
		}
		
		LogService.writeLogs();	
	}
	
	public void finish(Database.BatchableContext BC) {
		System.debug('StewardshipACHBatchBatch.finish()');		
		LogService.writeLogs();
	}
	
	private static void queryApprovedOpen(Map<ID, StewardshipACHBatch__c> batchMap){
		System.debug('StewardshipACHBatchBatch.queryApprovedOpen()');
		for(StewardshipACHBatch__c batchRecord : batchMap.values()){
			batchRecord.StewardshipProcess__c = '';
		}
		update batchMap.values();
		for(StewardshipACHBatch__c batchRecord : batchMap.values()){
			batchRecord.StewardshipProcess__c = 'PaymentBatchSelect';
		}
		update batchMap.values();
		LogService.writeLogs();
	}
}