vemo-mdapi-qa/objects/StudentProgram__c.object
<CustomObject>
    <label>Student Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CongaFinalDisclosureID__c</fullName>
        <inlineHelpText>The ID of the Final Disclosure.</inlineHelpText>
        <label>Conga Final DisclosureID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CongaFinalDisclosureStatus__c</fullName>
        <inlineHelpText>The status of the Final Disclosure (Generate, Generated).</inlineHelpText>
        <label>Conga Final Disclosure Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Generate</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinalDisclosureID__c</fullName>
        <inlineHelpText>Used by the system to construct the above Final Disclosure Clean URL.</inlineHelpText>
        <label>FinalDisclosureID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenerateFinalDisclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Manually check this box to re-generate the Final Disclosure.</inlineHelpText>
        <label>Generate Final Disclosure</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-app/main/default/classes/GenerateFinalDisclosureBatch.cls
global class GenerateFinalDisclosureBatch implements Database.Batchable<sObject> {
	
	String query;
	
	global GenerateFinalDisclosureBatch() {
		query = 'SELECT id, CongaFinalDisclosureStatus__c, FinalDisclosureID__c, CongaFinalDisclosureID__c from StudentProgram__c where GenerateFinalDisclosure__c = true';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('GenerateFinalDisclosureBatch.start()');
		System.debug('session:'+UserInfo.getSessionId());
        System.debug('query:'+query);
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.debug('GenerateFinalDisclosureBatch.execute()');
		System.debug('session:'+UserInfo.getSessionId());
        system.debug('scope before:'+scope);
		for(StudentProgram__c agreement : (List<StudentProgram__c>) scope){
			agreement.CongaFinalDisclosureStatus__c = 'Generate';
			agreement.FinalDisclosureID__c = '';
			agreement.CongaFinalDisclosureID__c = '';
		}
        system.debug('scope after:'+scope);
		Database.update(scope, false);
	}
	
	global void finish(Database.BatchableContext BC) {
		System.debug('GenerateFinalDisclosureBatch.finish()');
	}
	
}