vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this disbursement is deleted and will be purged by an hourly job.  Necessary for school admins to be able to delete records</description>
        <inlineHelpText>If this flag is checked, this disbursement is deleted and will be purged by an hourly job</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

vemo-mdapi-qa/classes/PurgeDeletedDisbursementsBatch.cls
public with sharing class PurgeDeletedDisbursementsBatch implements Database.Batchable<sObject> {
        
    String query = 'SELECT id from Transaction__c where Deleted__c = true';

    public PurgeDeletedDisbursementsBatch() {
        
    }

    public PurgeDeletedDisbursementsBatch(String query){
    	if(String.isNotEmpty(query)) this.query = query;
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('PurgeDeletedDisbursementsBatch.start()');
        System.debug('query:'+query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('PurgeDeletedDisbursementsBatch.execute()');
        delete scope;
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('PurgeDeletedDisbursementsBatch.finish()');        
    }
    
}