vemo-mdapi-qa/objects/Transaction__c.object
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Disbursement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Agreement related to this Disbursement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>StudentProgram__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The amount to be disbursed or refunded.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RelatedSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Disbursement was created by a Disbursement Schedule, indicates the related Disbursement Schedule.</inlineHelpText>
        <label>Related Schedule</label>
        <referenceTo>TransactionSchedule__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>RelatedTransactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled, Pending, Complete, or Cancelled.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TransactionStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Student related to this Disbursement.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionDateTime__c</fullName>
        <label>DEPRECATETransaction DateTime</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Represents a funding event in a contract. This is typically a transaction from an investor or school to the school (for tuition) or directly to the student (ex. stipend)</description>
        <label>Disbursement</label>
    </recordTypes>
</CustomObject>

vemo-mdapi-qa/globalValueSets/TransactionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

vemo-mdapi-qa/classes/DisbursementService.cls
/////////////////////////////////////////////////////////////////////////
// Class: DisbursementService
// 
// Description: 
// 	Handles all Distribution DML functionality
// 
// Version Log
// DATE---------AUTHOR----------DESCRIPTION-----------------------------
// 2016-12-28   Greg Cook       Created                         
// 
/////////////////////////////////////////////////////////////////////////
public with sharing class DisbursementService {
/*
	public static List<Disbursement> getDisbursementWithDisbursementID(Set<ID> distributionIDs){
		System.debug('DisbursementService.getDisbursementWithDisbursementID');
		Map<ID, Transaction__c> trans = TransactionQueries.getDisbursementMapWithDisbursementID(distributionIDs);
		List<Disbursement> dists = new List<Disbursement>();
		for(Transaction__c tran : trans.values()){
			Disbursement dist = new Disbursement(tran);
			dists.add(dist);
		}
		return dists;
	}

	public static List<Disbursement> getDisbursementWithAgreementID(Set<ID> studentProgramIDs){
		System.debug('DisbursementService.getDisbursementWithAgreementID');
        system.debug(studentProgramIDs);
		Map<ID, Transaction__c> trans = TransactionQueries.getDisbursementMapWithAgreementID(studentProgramIDs);
		List<Disbursement> dists = new List<Disbursement>();
		for(Transaction__c tran : trans.values()){
			Disbursement dist = new Disbursement(tran);
			dists.add(dist);
		}
		return dists;
	}

	public static List<Disbursement> getDisbursementWithStudentID(Set<ID> accountIDs){
		System.debug('DisbursementService.getDisbursementWithStudentID');
		Map<ID, Transaction__c> trans = TransactionQueries.getDisbursementMapWithStudentID(accountIDs);
		List<Disbursement> dists = new List<Disbursement>();
		for(Transaction__c tran : trans.values()){
			Disbursement dist = new Disbursement(tran);
			dists.add(dist);
		}
		return dists;
	}

	public static Set<Id> createDisbursements(List<Disbursement> disbursement){
		System.debug('DisbursementService.createDisbursement');
		List<Transaction__c> trans = new List<Transaction__c>();
		for(Disbursement dis : disbursement){
			Transaction__c tran = disbursementToTransaction(dis);
			trans.add(tran);
		}
		insert trans;
		Set<ID> disIDs = new Set<ID>();
		for(Transaction__c tran : trans){
			disIDs.add(tran.ID);
		}
		return disIDs;
	}

	public static Set<Id> updateDisbursements(List<Disbursement> disbursements){
		System.debug('DisbursementnService.updateDisbursement');
		List<Transaction__c> trans = new List<Transaction__c>();
		for(Disbursement dis : disbursements){
			Transaction__c tran = disbursementToTransaction(dis);
			trans.add(tran);
		}
		update trans;
		Set<ID> disIDs = new Set<ID>();
		for(Transaction__c tran : trans){
			disIDs.add(tran.ID);
		}
		return disIDs;
	}

	public static Integer deleteDisbursements(Set<ID> disbursementIDs){
		System.debug('DisbursementService.deleteDisbursements');
		Map<ID, Transaction__c> trans = TransactionQueries.getDisbursementMapWithDisbursementID(disbursementIDs);
		Integer numToDelete = trans.size();
		delete trans.values();
		return numToDelete;
	}
	
	public static Transaction__c disbursementToTransaction(Disbursement dist){
		System.debug('DisbursementService.disbursementToTransaction');
		Transaction__c trans = new Transaction__c();
		
		if(dist.disbursementID != null) trans.ID = dist.disbursementID;
		if(dist.studentID != null) trans.Student__c = dist.studentID;
		if(dist.agreementID != null) trans.Agreement__c = dist.agreementID;
		if(dist.relatedScheduleID != null) trans.RelatedSchedule__c = dist.relatedScheduleID;
		if(dist.amount != null) trans.Amount__c = dist.amount;
		if(dist.transactionDate != null) trans.TransactionDateTime__c = dist.transactionDate;
		if(dist.status != null) trans.Status__C = dist.status;
		return trans;
	}

	public class Disbursement{
		public String disbursementID {get;set;}
		public String studentID {get;set;}
		public String agreementID {get;set;}
		public String relatedScheduleID {get;set;}
		public Decimal amount {get;set;}
		public DateTime transactionDate {get;set;}
		public String status {get;set;}

		public Disbursement(){

		}

		public Disbursement(Boolean testValues){
			if(testValues){
				this.transactionDate = System.now();
				this.amount = 1000;	
				this.status = 'Received'; //Pending, Scheduled		
			}
		}

		public Disbursement(Transaction__c trans){
			this.disbursementID = trans.ID;
			this.studentID = trans.Student__c;
			this.agreementID = trans.Agreement__c;
			this.relatedScheduleID = trans.RelatedSchedule__c;
			this.amount = trans.Amount__c;
			this.transactionDate = trans.TransactionDateTime__c;
			this.status = trans.Status__c;
		}
	}*/
}